CHANGES.md
Libplanet.Explorer.Executable/Program.cs
Libplanet.Explorer/Store/LiteDBRichStore.cs
Libplanet.Explorer/Store/MySQLRichStore.cs
Libplanet.Extensions.Cocona.Tests/Commands/StatsCommandTest.cs
Libplanet.Extensions.Cocona.Tests/Commands/StoreCommandTest.cs
Libplanet.Extensions.Cocona/Commands/StoreCommand.cs
Libplanet.RocksDBStore.Tests/MonoRocksDBStoreFixture.cs
Libplanet.RocksDBStore.Tests/RocksDBStoreFixture.cs
Libplanet.RocksDBStore/RocksDBKeyValueStore.cs
Libplanet.Tests/Store/DefaultStoreFixture.cs
Libplanet.Tests/Store/StateStoreTracker.cs
Libplanet.Tests/Store/StateStoreTrackerTest.cs
Libplanet.Tests/Store/StoreTest.cs
Libplanet.Tests/Store/StoreTracker.cs
Libplanet.Tests/Store/Trie/MemoryKeyValueStore.cs
Libplanet/Store/BaseStore.cs
Libplanet/Store/IStateStore.cs
Libplanet/Store/IStore.cs
Libplanet/Store/Trie/CacheableKeyValueStore.cs
Libplanet/Store/Trie/DefaultKeyValueStore.cs
Libplanet/Store/Trie/IKeyValueStore.cs
Libplanet/Store/TrieStateStore.cs

Closes #1448.
I don't think it is too far fetched to think `IStore`s (together with `IStateStore`s and `IKeyValueStore`s) in general might have unmanaged resources to be cleaned up from a user's perspective. I think it would be better to forgo type checking specific implementation whether a store is disposable or not and simply disposing an `IStore` as a general rule is better.
P.S. On a side note, I thought about also implementing finalizers, but there seem to be a general consensus to *avoid* using finalizers if possible. Any thoughts?

`IStore` is now `IDisposable`

---

CHANGES.md
Libplanet.Extensions.Cocona/Commands/Key/DerivationCommand.cs
Libplanet.Extensions.Cocona/Commands/KeyCommand.cs
Libplanet.Tests.ruleset
Libplanet.Tests/Action/ActionEvaluatorTest.cs
Libplanet.Tests/Crypto/PrivateKeyTest.cs
Libplanet.Tests/Net/SwarmTest.Broadcast.cs
Libplanet.Tests/Net/SwarmTest.cs
Libplanet.Tests/Tx/TransactionTest.cs
Libplanet/Crypto/PrivateKey.cs

`new PrivateKey(ByteUtil.FromHex(hex))` now can be shortened as `PrivateKey.FromString(hex)`.

`PrivateKey.FromString()` method

---

CHANGES.md
Libplanet.Explorer.Executable/Program.cs
Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
Libplanet.Tests/Blockchain/NullPolicy.cs
Libplanet/Blockchain/BlockChain.MineBlock.cs
Libplanet/Blockchain/BlockChain.cs
Libplanet/Blockchain/Policies/BlockPolicy.cs
Libplanet/Blockchain/Policies/IBlockPolicy.cs
Libplanet/Blocks/BlockExceedingTransactionsException.cs

`IBlockPolicy<T>.MaxTransactionsPerBlock` property is replaced by `IBlockPolicy<T>.GetMaxTransactionsPerBlock(long index)` method.

Let maximum transactions vary depending on block index

---

CHANGES.md
Libplanet.Explorer.Executable/Program.cs
Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
Libplanet.Tests/Blockchain/BlockChainTest.cs
Libplanet.Tests/Blockchain/NullPolicy.cs
Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs
Libplanet/Blockchain/BlockChain.MineBlock.cs
Libplanet/Blockchain/BlockChain.cs
Libplanet/Blockchain/Policies/BlockPolicy.cs
Libplanet/Blockchain/Policies/IBlockPolicy.cs
Libplanet/Blocks/BlockInsufficientTxsException.cs
Libplanet/Blocks/InvalidBlockMinTxException.cs

Put in place an option for MinTransactionsPerBlock to keep energy and cpu time to a minimum if a block policy (such as implemented by 9c) requires that blocks contain at least 1 or more transactions.  This code will stop the miner from trying to get the hash if there are less than the MinTrasactionsPerBlock as defined in the policy.
Currently the miner will continue mining an invalid block, and 9c has implemented a custom setting to force at least 1 transaction.  This will allow that to be configurable in the future.

Put in place an option for MinTransactionsPerBlock

---

CHANGES.md
Libplanet.Tests.ruleset
Libplanet.Tests/Blockchain/BlockChainTest.Internals.cs
Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
Libplanet.Tests/RandomExtensions.cs
Libplanet/Blockchain/BlockChain.MineBlock.cs
Libplanet/Blockchain/BlockChain.cs

This patch adds a new option `txPriority` to `BlockChain<T>.MineBlock()` method (and its internal parts, `GatherTransactionsToMine()` & `ListStagedTransactions()`).  The parameter takes an [`IComparer<Transaction<T>>`][1] to determine the priority of staged transactions.  Here's a very simple example:
```csharp
// Prioritize a certain signer's transactions over others':
Address prioritySigner = new Address("…");
IComparer<Transaction<T>> txPriority = Comparer<Transaction<T>>.Create(
(a, b) => a.Signer.Equal(prioritySigner) ? -1 : (b.Signer.Equal(prioritySigner) ? 1 : 0);
);
```
[1]: https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.icomparer-1?view=netstandard-2.0

`txPriority` option for `BlockChain<T>.MineBlock()` method

---

CHANGES.md
Libplanet.Explorer.Executable/Program.cs
Libplanet.Tests/Blockchain/NullPolicy.cs
Libplanet/Blockchain/BlockChain.MineBlock.cs
Libplanet/Blockchain/Policies/BlockPolicy.cs
Libplanet/Blockchain/Policies/IBlockPolicy.cs

Quick and dirty API change from `IBlockPolicy.MinTransactionsPerBlock` to `IBlockPolicy.GetMinTransactionsPerBlock()` for the surface level consistency. I'll do an internal cleanup after libplanet for [lib9c](https://github.com/planetarium/lib9c) and [headless](https://github.com/planetarium/NineChronicles.Headless) gets bumped.

Variable min txs per miner

---

CHANGES.md
Libplanet/Net/Transports/NetMQTransport.cs

This PR strips `TurnClient.CreatePermission()` calls in `NetMQTransport` due to below reasons.
-  TurnClient can't operate with TURN server that requires the permission of peers even with CreatePermission calls in certain environments because it requires public IP of nodes can be determined by TURN relay server.
- TURN servers in 9c mainnet are running with [`--server-relay` option](https://github.com/coturn/coturn/blob/553ce0216823904d4e52a9629c5bcbed4713f3d2/examples/etc/turnserver.conf#L746) to bypass this problem.
- In order to completely solve this, Connect must also go through TURN to be used.(#674)
- `CreatePermission` calls also occur when a specific node connects to another node, which has the side effect of losing the entire peer table if the connection to the TURN server is …

Remove CreatePermission in NetMQTransport

---

CHANGES.md
Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
Libplanet/Blockchain/BlockChain.cs

This PR forces `BlockChain<T>.MineBlock<T>` contain only one for transactions with two or more same nonces.
This symptom does not appear to occur after Libplanet 0.17.

Fix BlockChain<T>.MineBlock() for dupped nonce & Release 0.15.4

---

Libplanet/Net/Swarm.BlockSync.cs

Which is 150 seconds by default. This addresses issue #1490.
This PR does not contains neither changes of CHANGES.md nor new test cases. Please feel free to comment if you think any of those is required.

Set session timeout of block completion into SwarmOptions.MaxTimeout

---

CHANGES.md
Libplanet.Explorer.Executable/Program.cs
Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs
Libplanet/Blockchain/Policies/BlockPolicy.cs
Libplanet/Blockchain/Policies/DifficultyAdjustment.cs

Just some preparatory work to make difficulty adjustment algorithm more pluggable.
Other than separating out the chunk of default implementation inside `BlockPolicy<T>`, minor changes can be found in the changelog.
Making `minimumDifficulty` and `difficultyStability` parameters nullable is partly due to my OCD, but with an additional reason that these shouldn't really be easily configurable unless the user *really* knows what they are doing. I suspect the current default values used are rather inappropriate. 😶

Difficulty adjustment algorithm separated

---

CHANGES.md
Libplanet.Tests/Crypto/PrivateKeyTest.cs
Libplanet/Crypto/PrivateKey.cs
Libplanet/KeyStore/ProtectedPrivateKey.cs
Libplanet/Libplanet.csproj

Disallow shorter/longer private keys than 32 bytes & release 0.18.4

---

CHANGES.md
Libplanet.Tests/Blocks/HashAlgorithmTableTest.cs
Libplanet.Tests/HashAlgorithmTypeTest.cs
Libplanet/HashAlgorithmType.cs
Libplanet/Libplanet.csproj

This fixes the following error on Mono (including Unity) and .NET Framework:
```
Two byte arrays do not equal
Expected (C# array lit): new byte[32] { 0x78, 0x71, 0xe9, 0xcf, 0xd3, 0xf8, 0x22, 0x41, 0xd1, 0xd1, 0x70, 0x77, 0x27, 0x42, 0x12, 0xe5, 0xae, 0x20, 0xaa, 0xcd, 0x9c, 0xad, 0x04, 0xa4, 0x9d, 0x33, 0x69, 0x3b, 0xeb, 0xed, 0x0d, 0x8b }
Actual (C# array lit):   new byte[32] { 0x25, 0x81, 0xce, 0xcf, 0xeb, 0xf3, 0x95, 0x2f, 0xa9, 0xfc, 0x25, 0xfc, 0x38, 0x92, 0x9c, 0xa7, 0x5c, 0x7f, 0xd7, 0x83, 0x32, 0x84, 0x8b, 0x9f, 0x98, 0x7b, 0x38, 0x03, 0xa9, 0xbb, 0x4d, 0x8a }
Expected (hex): 7871e9cfd3f82241d1d17077274212e5ae20aacd9cad04a49d33693bebed0d8b
Actual (hex):   2581cecfebf3952fa9fc25fc38929ca75c7fd78332848b9f987b3803a9bb4d8a
at Libplanet.Tests.TestUtils.AssertBytesEqual (System.Byte[] …
```

Fix bug of streamed hash calculation & release 0.18.5

---

CHANGES.md
Libplanet.Tests/Blockchain/NullPolicy.cs
Libplanet.Tests/Net/SwarmTest.Broadcast.cs
Libplanet.Tests/Net/SwarmTest.cs
Libplanet/Blockchain/BlockChain.cs
Libplanet/Net/Swarm.BlockSync.cs
Libplanet/Net/Swarm.cs

This patch apparently stabilizes several flaky tests.
See also the changelog.

Broadcast new blocks immediately after they are appended

---

.circleci/config.yml
.circleci/xunit-junit.xslt
.github/workflows/check-build.yaml
.gitignore
CONTRIBUTING.md
Libplanet.Analyzers.Tests/ActionAnalyzerTest.cs
Libplanet.Analyzers.Tests/CSharpAnalysisFactAttribute.cs
Libplanet.Analyzers.Tests/Libplanet.Analyzers.Tests.csproj
Libplanet.Analyzers.Tests/Verifiers/CSharpAnalysisTheoryAttribute.cs
Libplanet.Explorer.UnitTests/Libplanet.Explorer.UnitTests.csproj
Libplanet.Explorer/Libplanet.Explorer.csproj
Libplanet.Extensions.Cocona.Tests/Libplanet.Extensions.Cocona.Tests.csproj
Libplanet.RocksDBStore.Tests/Libplanet.RocksDBStore.Tests.csproj
Libplanet.Stun.Tests/Libplanet.Stun.Tests.csproj
Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
Libplanet.Tests/Libplanet.Tests.csproj
Libplanet.Tests/Net/BlockCompletionTest.cs
Libplanet.Tests/Net/SwarmTest.Broadcast.cs
Libplanet.Tests/Net/SwarmTest.Preload.cs
Libplanet.Tests/Net/SwarmTest.cs
Libplanet/KeyStore/Web3KeyStore.cs
README.md

I've experimented with [CircleCI] for more than a week to evaluate it as a candidate for Azure Pipeline replacement.
The motivation was the deep-seated flakiness of our test suite and slow build time on CI (see also #1547), but an article on *Google Testing Blog* made me to try an alternative CI service: [*Where do our flaky tests come from?*][1] (by Jeff Listfield).  According to the article, memory consumption has the strong effect of flakiness on tests.  Although it's unsure which is the problem, a shortage of RAM or consuming memory in itself, I've supposed the former would be a cause of flakiness, at least in our test suite.
The problem with Azure Pipelines is the fact that [they give us only (?) 7 GB of RAM except for macOS runners which have 14 GB of RAM.][2][^1]  Unfortunately, …

Experiments with CircleCI as a replacement of Azure Pipelines

---

CHANGES.md
Libplanet.RocksDBStore/RocksDBKeyValueStore.cs
Libplanet.Tests/Store/StateStoreExtensionsTest.cs
Libplanet.Tests/Store/Trie/KeyValueStoreTest.cs
Libplanet.Tests/Store/TrieStateStoreTest.cs
Libplanet/Store/StateStoreExtensions.cs
Libplanet/Store/Trie/CacheableKeyValueStore.cs
Libplanet/Store/Trie/DefaultKeyValueStore.cs
Libplanet/Store/Trie/IKeyValueStore.cs
Libplanet/Store/Trie/ITrie.cs
Libplanet/Store/Trie/MemoryKeyValueStore.cs
Libplanet/Store/Trie/MerkleTrie.cs

This PR introduces #1554 by using a new `RocksDBKeyValueStore.Set(IDictionary<byte[], byte[]>)` method to increase write performance.
Additionally, it removes `rehearsal ` argument and feature from `ITrie` since there is no usage internally.

Tune `MerkleTrie`

---

.gitignore
CHANGES.md
Libplanet.Extensions.Cocona/Commands/ApvCommand.cs
Libplanet.Tests/Net/Protocols/ProtocolTest.cs
Libplanet.Tests/Net/Protocols/TestTransport.cs
Libplanet.Tests/Net/SwarmTest.Broadcast.cs
Libplanet.Tests/Net/SwarmTest.Fixtures.cs
Libplanet.Tests/Net/SwarmTest.cs
Libplanet.Tests/Net/Transports/BoundPeerExtensionsTest.cs
Libplanet.Tests/Net/Transports/NetMQTransportTest.cs
Libplanet.Tests/Net/Transports/TcpTransportTest.cs
Libplanet.Tests/Net/Transports/TransportTest.cs
Libplanet/Net/AsyncDelegate.cs
Libplanet/Net/Messages/MessageCodec.cs
Libplanet/Net/Protocols/KademliaProtocol.cs
Libplanet/Net/Swarm.MessageHandlers.cs
Libplanet/Net/Swarm.cs
Libplanet/Net/SwarmOptions.cs
Libplanet/Net/Transports/BoundPeerExtensions.cs
Libplanet/Net/Transports/ITransport.cs
Libplanet/Net/Transports/InvalidMagicCookieException.cs
Libplanet/Net/Transports/NetMQTransport.cs
Libplanet/Net/Transports/TcpTransport.cs

This PR adds TcpTransport which implements ITransport interface. NetMQTransport is still supported, but it is not a default option anymore. In order to use NetMQTransport, please set SwarmOptions.Type to SwarmOptions.TransportType.NetMQTransport.
Added `MessageCodec` class which inherits `IMessageCodec<T>` interface to encode a message into bytearray.

Introduce TCP transport

---

Libplanet/Blockchain/BlockChain.cs
Libplanet/Net/BlockCompletion.cs
Libplanet/Net/Messages/Message.cs
Libplanet/Net/Protocols/RoutingTable.cs
Libplanet/Net/Swarm.BlockSync.cs
Libplanet/Net/Swarm.MessageHandlers.cs
Libplanet/Net/Swarm.cs
Libplanet/Net/TxCompletion.cs

Aside from minor rephrasing here and there,
- `Source` property is added to `BlockChain<T>` and `RoutingTable` for easier `grep`ing.
- Once again, this is not a proper solution, but only for practicality. In my opinion, unless we want to pour a significant amount of resource in making a proper usage of structured logging, this should help with surveying console output at a glance (for now).
- Tried to scrub listings of transaction `Id`s, block `Hash`s, and locator `Hash`s from `BlockChain<T>` and `Swarm<T>`.
- Overly verbose logs related to `Message` seemed more detrimental than being helpful. If we really want to retain such information, level of logging for such messages should be lowered to `Verbose`, or handled at the `ITransport` layer.

Logging QoL improvements

---

CHANGES.md
Libplanet/Net/Swarm.BlockSync.cs

This pull request makes `Swarm<T>` sync recent blocks after forking the canonical chain to improve synchronism.
I got a report that he saw the canonical chain was locked often and it disturbs its performance, while developing Nine Chronicles RPC mode from @ipdae.
When the `Swarm<T>` was syncing blocks among other nodes, it has locked the canonical chain (write-lock) and has blocked reading something from the canonical chain.
In code, when to see `ProcessBlockDemand` in `Swarm.BlockSync`, it passes `BlockChain`, the canonical chain, directly. Currently, Nine Chronicles is in single miner mode so there may be no reorg and it appends new blocks directly without a fork and take a write lock.
https://github.com/planetarium/libplanet/blob/c8c056acdc3f2e52cd4973be93e2fb993bfed81d/Libplanet/Net/Sw …

Use forked chain while syncing blocks

---

CHANGES.md
Libplanet/Net/Swarm.BlockSync.cs
Libplanet/Net/SwarmOptions.cs

Inequality inside `Swarm<T>.PollBlocksAsync()` determining whether tip has become stale was set up to act oppositely to what was intended. This would've resulted in not polling properly once tip has actually gone stale unless tip is changed by a push from another node.
Also, changed the polling interval to `60` seconds.

Bad tip expiration for pulling blocks fix

---

CHANGES.md
Libplanet/Libplanet.csproj
Libplanet/Store/BlockSet.cs

Changed `BlockSet<T>`'s internal LRU cache from _Planetarium.LruCacheNet_ to _Caching.dll_.  Other uses (e.g., `RocksDBStore`) are unchanged.

Change LRU cache implementation for `BlockSet<T>`

---

CHANGES.md
Libplanet.Tests/Action/PolymorphicActionTest.cs
Libplanet/Action/PolymorphicAction.cs

This PR lets allow `PolymorphicAction<T>.InnerAction.PlainValue` to `IValue` instead of concrete `Dictionary`.

Allow IValue for PolymorphicAction<T>

---

CHANGES.md
Libplanet.Analyzers.Tests/Libplanet.Analyzers.Tests.csproj
Libplanet.Benchmarks/Libplanet.Benchmarks.csproj
Libplanet.Explorer.Executable/Libplanet.Explorer.Executable.csproj
Libplanet.Explorer.UnitTests/Libplanet.Explorer.UnitTests.csproj
Libplanet.Extensions.Cocona.Tests/Libplanet.Extensions.Cocona.Tests.csproj
Libplanet.RocksDBStore.Tests/Libplanet.RocksDBStore.Tests.csproj
Libplanet.RocksDBStore/Libplanet.RocksDBStore.csproj
Libplanet.Stun.Tests/Libplanet.Stun.Tests.csproj
Libplanet.Tests/Libplanet.Tests.csproj
Libplanet.Tools/Libplanet.Tools.csproj

This fixes MSBuild files so that the entire project can be built and tested on Apple Silicon (aarch64-apple-darwin), commonly known as M1 series.
As Apple Silicon is supported since .NET 6, on these M1 Macs executable/test projects target `net6.0` instead of `netcoreapp3.1`.
It also bums the version of *Planetarium.RocksDbSharp* package from 6.2.3 to [6.2.4-planetarium](https://www.nuget.org/packages/Planetarium.RocksDbSharp/6.2.4-planetarium) which contains prebuilt binaries for Apple Silicon (see also <https://github.com/planetarium/rocksdb-sharp/pull/6>).

Build on Apple Silicon (aarch64-apple-darwin)

---

CHANGES.md
Libplanet.Tests/Net/SwarmTest.Broadcast.cs
Libplanet.Tests/Net/SwarmTest.cs
Libplanet.Tests/Net/Transports/NetMQTransportTest.cs
Libplanet/Net/Transports/ITransport.cs
Libplanet/Net/Transports/NetMQTransport.cs
Libplanet/Net/Transports/TcpTransport.cs

We've found memory leak from `ITransport.MessageHistory`, so I removed as emergency measure.

Remove ITransport.MessageHistory & Release 0.21.3

---

CHANGES.md
Libplanet.Analyzers.Tests/ActionAnalyzerTest.cs
Libplanet.Analyzers/ActionAnalyzer.cs
Libplanet.Analyzers/rules/LAA1002.md
Libplanet.Tests/Misc/ArrayEqualityComparerTest.cs
Libplanet.Tests/Store/Trie/MerkleTrieTest.cs
Libplanet/Blocks/PreEvaluationBlock.cs
Libplanet/Libplanet.csproj
Libplanet/Misc/ArrayEqualityComparer.cs
Libplanet/Store/Trie/ITrieExtensions.cs
Libplanet/Store/Trie/MerkleTrie.cs
Libplanet/Store/Trie/Nodes/BaseNode.cs
Libplanet/Store/Trie/Nodes/INodeExtensions.cs
Libplanet/Store/Trie/Nodes/ValueNode.cs
Libplanet/Store/TrieStateStore.cs

This patches tries further fragmentation on states.  It addresses the following problems:
- States has been already fragmented on Merkle tree, but their atomic unit was an account.  Therefore, if an action changed only a tiny leaf in a tree, a new copy of the entire tree needed to be added.
- If an action needs only a tiny leaf in an account state tree, the entire tree had to be loaded including unused leafs.
By utilizing Bencodex offloading,[^1] states are now further fragmented into multiple subtrees, which can be offloaded and loaded when needed.  Such fragmentation is recursively applied to nested lists/dictionaries.  However, light values, encoded to 256 bytes[^2] or shorter, are embedded to their parent tree as offloading them is rather overkill.
To optimize shallow but broad …

Fragmented states on Merkle tree

---

CHANGES.md
Libplanet/Net/TxCompletion.cs

When demanding `Transaction<T>`s from a peer, `TxCompletion` also searches inside the storage and the staged pool to see if it needs to be downloaded.

Bugfix to remove unnecessary tx requests

---

CHANGES.md
Libplanet.Tests/Store/TrieStateStoreTest.cs
Libplanet/Store/TrieStateStore.cs

It's just a hotfix which is half-baked, but fixes <https://github.com/planetarium/NineChronicles.Snapshot/issues/78>.
The problem should be completely fixed through changing APIs.  See also <https://github.com/planetarium/libplanet/issues/1653> for my plan.

Release 0.23.1 & Fix `TrieStateStore.PruneStates()` throwing `ArgumentOutOfRangeException`

---

Libplanet/Blockchain/BlockChain.Swap.cs

Just a small chore.
Unless I'm missing something, I don't think tx shuffling for evaluation is necessary here. 😶

Remove `int` casting and clutter removal

---

CHANGES.md
Libplanet/Blockchain/BlockChain.cs

Adds a simple tagged metric to measure how long it takes to fetch stored hashes.
It might be a good idea to see how many chain ids there are but I'm not sure about the performance of `Store.ListChainIds()`. 😶

New metric for `BlockChain<T>.FindNextHashes()`

---

CHANGES.md
Libplanet/Net/TxCompletion.cs

Previously `TxCompletion` used to re-broadcast received all transactions even it is invalid so is not staged. It had lead to some unnecessary messages as follows:
```
TxIds            GetTxs
┌-------> SwarmB ---------┐
SwarmA ----------> SwarmC ------------> SwarmA (no request since the invalid transaction does not exists)
└-------> ...    ---------┘
```
Adding a regression test is skipped because there are no event handler such as `TxReceived` for the `TxId`s. But I've checked when receiving invalid transaction it broadcasts `TxId` and work as the diagram above.

Prevent broadcasting invalid transactions

---

CHANGES.md
Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
Libplanet.Tests/Blockchain/BlockChainTest.cs
Libplanet/Blockchain/BlockChain.cs

When working with a forked chain, `Append()` on a forked chain prematurely unstages transactions in the block being appended. This results in invalid nonce calculation when trying to create a new transaction while a forked chain is being worked on. Note unstaging and restaging of relevant transactions is dealt with in `Swap()` when syncing the canonical chain to a forked chain anyway.
This PR prevents premature unstaging of transactions by checking whether its calling instance is the canonical chain or not.

Prevent premature unstaging

---

CHANGES.md
Libplanet.RocksDBStore/RocksDBStore.cs
Libplanet/Blockchain/BlockChain.cs

This PR improves performance of `BlockChain<T>.FindNextHashes()` through two bellow adjustments.
1. Removed `_rwlock` from `BlockChain<T>.FindNextHashes()` because it has already protected by another lock on `BlockChain<T>.FindBranchpoint()`.
2. Added a memory cache for `RocksDBStore.IterateIndexes()` to speed up iterative lookups.

Improve performance of `BlockChain<T>.FindNextHashes()`

---

CHANGES.md
Libplanet.RocksDBStore/RocksDBKeyValueStore.cs
Libplanet.Tests/Store/Trie/KeyBytesTest.cs
Libplanet.Tests/Store/Trie/KeyValueStoreTest.cs
Libplanet.Tests/TestUtils.cs
Libplanet/HashDigest.cs
Libplanet/Store/Trie/CacheableKeyValueStore.cs
Libplanet/Store/Trie/DefaultKeyValueStore.cs
Libplanet/Store/Trie/IKeyValueStore.cs
Libplanet/Store/Trie/KeyBytes.cs
Libplanet/Store/Trie/MemoryKeyValueStore.cs
Libplanet/Store/Trie/MerkleTrie.cs
Libplanet/Store/TrieStateStore.cs

For later optimizations, this patch adds a new operation *multiget* to `IKeyValueStore`.  Further optimizations would be landed as separated patches later.
Plus, I addressed https://github.com/planetarium/libplanet/pull/1636#discussion_r764478088 that @greymistcube made in the previous pull request: now `IKeyValueStore` represents keys as `KeyBytes`, a thin wrapper around `ImmutableArray<byte>`, instead of `byte[]`.  `KeyBytes` is a readonly struct, and implements `IEquatable<KeyBytes>` & `GetHashCode()` method.  Human-readable `.ToString()` representation is a bonus.

Add multiget operation to `IKeyValueStore`

---

CHANGES.md
Libplanet.Tests/HashDigestTest.cs
Libplanet/Crypto/PrivateKey.cs
Libplanet/Crypto/PublicKey.cs
Libplanet/HashDigest.cs
Libplanet/Libplanet.csproj

This patch adds `HashDigest<T>.DeriveFrom()` overloads to remove redundant memcpy/malloc.
In order to move the pointer to the buffer (which is never changed) to `ImmutableArray<byte>` without memcpy, I used [`Unsafe.As<TFrom, TTo>()` method][1][^1] several times.[^2]  I would be able to implement it better if [there were `ImmutableArray.UnsafeFreeze<T>(T[])` method.][4]
[^1]: It parallels C++'s `std::reinterpret_cast<T>()`.
[^2]: Note that [`T[]` and `ImmutableArray<T>` share the same memory layout.][2]  See also [this article][3].
[1]: https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.unsafe.as?view=net-6.0#System_Runtime_CompilerServices_Unsafe_As__2___0__
[2]: https://github.com/dotnet/runtime/blob/v6.0.1/src/libraries/System.Threading.Tasks.Dataflow/src/Intern …

Remove redundant memcpy/malloc from `HashDigest<T>.DeriveFrom()`

---

CHANGES.md
Libplanet.Tests/Blockchain/Renderers/NonblockRendererTest.cs
Libplanet/Blockchain/Renderers/NonblockRenderer.cs

This patch fixes a bug that `NonblockRenderer<T>` & `NonblockActionRenderer<T>` are broken after they are once disposed.

Hotfix on non-blocking renderers & release 0.23.4

---

CHANGES.md
Libplanet.Tests/Net/Messages/NetMQMessageCodecTest.cs
Libplanet/Net/Messages/Message.cs
Libplanet/Net/Messages/TxIds.cs
Libplanet/Net/Swarm.cs

Seems like `Sender` property isn't used anywhere? 😶

Unused sender field removed from `Message.TxIds`

---

CHANGES.md
Libplanet.Extensions.Cocona/Commands/MptCommand.cs
Libplanet.Tests/Action/ActionContextTest.cs
Libplanet.Tests/Store/StateStoreExtensionsTest.cs
Libplanet.Tests/Store/Trie/KeyBytesTest.cs
Libplanet.Tests/Store/Trie/MerkleTrieExtensionsTest.cs
Libplanet.Tests/Store/Trie/MerkleTrieTest.cs
Libplanet.Tests/Store/Trie/TrieTest.cs
Libplanet.Tests/Store/TrieStateStoreTest.cs
Libplanet/Store/StateStoreExtensions.cs
Libplanet/Store/Trie/ITrie.cs
Libplanet/Store/Trie/ITrieExtensions.cs
Libplanet/Store/Trie/KeyBytes.cs
Libplanet/Store/Trie/MerkleTrie.cs
Libplanet/Store/Trie/MerkleTrieExtensions.cs

A small refactoring as a preparation for fixing #1653.  @moreal You should work on your job after this patch is merged.

Represent `ITrie` keys using `KeyBytes`

---

CHANGES.md
Libplanet.Tests/Net/Protocols/RoutingTableTest.cs
Libplanet/Net/Protocols/IProtocol.cs
Libplanet/Net/Protocols/Kademlia.cs
Libplanet/Net/Protocols/KademliaProtocol.cs
Libplanet/Net/Protocols/RoutingTable.cs

As a result of having new `nullable` contexts, nullability of arguments and properties have changed.
As a part of refactoring, although certain internal implementations have changed, other than a slight bugfix mentioned in the changelog, there should be no noticeable external behavior change. 😶

Nullable context on `Protocols` namespace

---

CHANGES.md
Libplanet/Net/TxCompletion.cs

Previously `TxCompletion<TPeer, TAction>.RequestTxsFromPeerAsync()` is maintained maximum 1 task for each peer to fetch transactions from. It caused a bug where fetching does not working even received a new `TxId`s from other peer.
This PR force to spawn `TxCompletion<TPeer, TAction>.RequestTxsFromPeerAsync()` task every time new `TxId`s are received.

Change the way how `TxCompletion<TPeer, TAction>` fetch transaction from other peers

---

Libplanet.Tests/Blockchain/BlockChainTest.cs
Libplanet.Tests/Blockchain/NullPolicy.cs
Libplanet/Blockchain/BlockChain.cs

This patch fixes the uncaught `ArgumentOutOfRangeException` thrown by `BlockChain<T>.GetStates()` or `GetState()` where the chain is uninitialized yet (i.e., has no genesis block yet).  This can be caused when `IBlockPolicy<T>` tries to use `GetStates()`/`GetState()` inside any of its `GetNextBlockDifficulty()`/`ValidateNextBlockTx()`/`ValidateNextBlock()` methods.
The following stack trace is from the exception I saw:
System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.
Stack Trace:
at Libplanet.Blockchain.BlockChain`1.get_Item(Int64 index) in ~/libplanet/Libplanet/Blockchain/BlockChain.cs:line 304
at Libplanet.Blockchain.BlockChain`1.get_Tip() in ~/libplanet/Libplanet/Blockchain/BlockChain.cs:line 246
at …

Fix `ArgumentOutOfRangeException` caused by uninitialized `BlockChain<T>`'s `GetStates()`

---

CHANGES.md
Libplanet/Net/Transports/NetMQTransport.cs

Do not throw error in `NetMQTransport.DoBroadcast()` method & release 0.25.3

---

CONTRIBUTING.md
Libplanet.Explorer/README.md
README.md

We recently moved our Discord server which is separated from the existing one, as it's virtually dedicated to Nine Chronicles nowadays.

Update Discord links

---

CHANGES.md
Libplanet.Tests/Net/SwarmTest.Consensus.cs
Libplanet.Tests/Net/SwarmTest.cs
Libplanet/Net/BlockCandidateTable.cs
Libplanet/Net/Swarm.BlockCandidate.cs
Libplanet/Net/Swarm.BlockSync.cs
Libplanet/Net/Swarm.cs

In order to solve the problem that it takes a long time to timeout when a node is disconnected while downloading a block from a node, it is a PR that implements a method of attaching downloaded blocks after receiving blocks in parallel.

Introduce `Swarm<T>.BlockCandidateConsumer`

---

CHANGES.md
Libplanet.RocksDBStore/RocksDBStore.cs

I found this when testing for https://github.com/planetarium/NineChronicles.Headless/issues/1004.
I found similar code in `PutBlock, DeleteBlock` and these methods were locking `_blockDbCache`, so i think `GetBlockDigest` is holding the wrong lock.

Fix `RocksDBStore`'s inaccurate lock handling

---

CHANGES.md
Libplanet.Tests/Store/TrieStateStoreTest.cs
Libplanet/Store/Trie/MerkleTrie.cs
Libplanet/Store/TrieStateStore.cs

Currently, `TrieStateStore.PruneStates` is too slow to use because its algorithm iterates all of the key-value pairs even if it was unnecessary. Its purpose was to make a state store consisting of only states of specific state root hashes. It tried to use another method which uses more disks but less CPU time and memory while maintaining the purpose. 
This pull request introduces the `TrieStateStore.CopyStates` method which copies only states of the given state root hashes. In the original plan, it planned to modify `TrieStateStore.PruneStates` but I became to think the `CopyStates` name seems to fit more during working. How do you think about it? 🤔  @dahlia

Introduce `TrieStateStore.CopyStates()` method

---

CHANGES.md
Libplanet.Tests/Store/Trie/MerkleTriePathCursorTest.cs
Libplanet.Tests/Store/Trie/Nodes/ShortNodeTest.cs
Libplanet/Store/Trie/MerkleTrie.Path.cs
Libplanet/Store/Trie/MerkleTrie.cs
Libplanet/Store/Trie/Nodes/ShortNode.cs

This allows multiple states to be loaded at a time through `IKeyValueStore.Get(IReadOnlyList<KeyBytes>)` method.  In order to parallelize path finding, I replaced recursion-based path finder with explicit loops.  See also `MerkleTrie.ResolvePath()` method and `MerkleTrie.Get()` method.

Parallelize MPT path finding

---

CHANGES.md
Libplanet.Tools/package.json

Upgrade node-fetch for @planetarium/cli package

---

CHANGES.md
Libplanet/Net/Transports/NetMQTransport.cs

Closes #1751. For the rationale, see #1751.

Retries removed from `NetMQTransport`

---

CHANGES.md
Libplanet/Net/Messages/DifferentVersion.cs
Libplanet/Net/Messages/FindNeighbors.cs
Libplanet/Net/Messages/Neighbors.cs
Libplanet/Net/Messages/Ping.cs
Libplanet/Net/Messages/Pong.cs

This implements #1754, but only protocol related messages were included because some of non-protocol messages use internal class (`BlockLocator`) as its constructor arguments. It would be great to make other messages as public in future.

Make some message classes public

---

CHANGES.md
Libplanet/Action/ActionEvaluator.cs

Closes #1755.
Very minimal implementation to address #1755. There are two issues with this:
- There is no way to identify which `Block<T>` the target `Transaction<T>` belongs to. This is partially due to `ActionEvaluator<T>` not assuming, albeit rightly so, that `Block<T>` is "complete" since `IPreEvaluationBlock<T>` is passed on for evaluation not a mined `Block<T>`. It is possible to associate with `IPreEvaluationBlock<T>`'s `PreEvaluationHash`, but that is a whole another issue.
- As mentioned in `FIXME`, due to lazy evaluation, the measurement depends on how `EvaluateTx()` is called.
It might be possible to resolve the issues above, but I didn't actually want to change the behavior too much just for the sake of better logging. 😶

Added metric log for transaction evaluation

---

Libplanet/Blockchain/BlockChain.Swap.cs

Not sure how much granularity is needed. This simply adds render duration log for an entire block.

Render duration log added

---

CHANGES.md
Libplanet.Net/Transports/NetMQTransport.cs

Closes #1753.
Partially addresses #1722 and #1734.
As `SendMultipartMessageAsync` seemed like an anti-pattern for using `NetMQ`, this PR attempts to mitigate the issue by using `TrySendMultipartMessage`. There are several reasons for this:
- There is no clear indication `SendMultipartMessageAsync` is actually working as intended, i.e. recovering or waiting when a `Message` can't be send immediately.
- Faster send and receive cycle by failing fast resulting in lower total `DealerSocket` usage.
- Reduces possible total wait time for `SendMessageWithReplyAsync`.
In my opinion, if we actually want an `async` functionality, it should be implemented at a higher level.
Although apocryphal, tested with this [docker image] on `9c-main` for more than a day without much issue, seemingly with better …

Use `TrySendMultipartMessage` instead of `SendMultipartMessageAsync` extension method

---

.circleci/config.yml
Libplanet.Net.Tests/AppProtocolVersionTest.cs
Libplanet.Net.Tests/BlockCompletionTest.cs
Libplanet.Net.Tests/BoundPeerTest.cs
Libplanet.Net.Tests/FactOnlyTurnAvailableAttribute.cs
Libplanet.Net.Tests/IceServerTest.cs
Libplanet.Net.Tests/InvalidMessageTimestampExceptionTest.cs
Libplanet.Net.Tests/Messages/BlockHashesTest.cs
Libplanet.Net.Tests/Messages/MessageTest.cs
Libplanet.Net.Tests/Messages/NetMQMessageCodecTest.cs
Libplanet.Net.Tests/PeerTest.cs
Libplanet.Net.Tests/Protocols/KBucketTest.cs
Libplanet.Net.Tests/Protocols/ProtocolTest.cs
Libplanet.Net.Tests/Protocols/RoutingTableTest.cs
Libplanet.Net.Tests/Protocols/TestMessage.cs
Libplanet.Net.Tests/Protocols/TestTransport.cs
Libplanet.Net.Tests/SwarmTest.AppProtocolVersion.cs
Libplanet.Net.Tests/SwarmTest.Broadcast.cs
Libplanet.Net.Tests/SwarmTest.Consensus.cs
Libplanet.Net.Tests/SwarmTest.Fixtures.cs
Libplanet.Net.Tests/SwarmTest.Preload.cs
Libplanet.Net.Tests/SwarmTest.cs
Libplanet.Net.Tests/Transports/BoundPeerExtensionsTest.cs
Libplanet.Net.Tests/Transports/InvalidMagicCookieExceptionTest.cs
Libplanet.Net.Tests/Transports/MessageSendFailedExceptionTest.cs
Libplanet.Net.Tests/Transports/NetMQTransportTest.cs
Libplanet.Net.Tests/Transports/TcpTransportTest.cs
Libplanet.Net.Tests/Transports/TransportExceptionTest.cs
Libplanet.Net.Tests/Transports/TransportTest.cs

XUnit does not supports parameterized runsettings, I've used environment variables to switch between "tcp" and "netmq" transport. This will resolve #1761.

Add transport type selection for `SwarmTest`s by environment variables

---

CHANGES.md
Libplanet.Net.Tests/SwarmTest.Broadcast.cs
Libplanet.Net/Swarm.BlockCandidate.cs
Libplanet.Net/Swarm.BlockSync.cs
Libplanet.Net/Swarm.cs

Since #1759, we had a problem with preload. So I was reverted.
If you look at the following code, there is a part where you made a mistake while deleting the parameter. 
https://github.com/planetarium/libplanet/pull/1792/files#diff-215bb45126357b0974dea14401f0213b497011890a129ae3a7df3e3468ea4911L524
If preload is always true, this `if` statement is meanless but I was left this code blocks.
In this PR. I'm re-implement #1759 and fixing those bugs.

Rollback #1759

---

CHANGES.md
Libplanet.RocksDBStore/Libplanet.RocksDBStore.csproj

This PR (back) ports #1791 to 0.26 due to support arm64 build. (sadly, we can't use 0.27 because there is a bug related tx transfer).

Porting #1791 (Bump RocksDbSharp for support arm64)

---

Libplanet/Libplanet.csproj

It was missed in <https://github.com/planetarium/libplanet/pull/1804>.

Fix `VersionPrefix` & release 0.26.4

---

CHANGES.md
Libplanet.Tests/Net/SwarmTest.Broadcast.cs
Libplanet.Tests/Net/SwarmTest.Preload.cs
Libplanet.Tests/Net/SwarmTest.cs
Libplanet.Tests/TestUtils.cs
Libplanet/Net/Swarm.cs

This PR fixes some flaky tests which are:
- `PreloadRetryWithNextPeers`
- `CreateNewChainWhenBranchPointNotExist`
- `BroadcastTxWhileMining`

Fix some flaky unit tests in `Libplanet.Net.Tests`

---

CHANGES.md
Libplanet.Tests/Blockchain/Renderers/NonblockRendererTest.cs
Libplanet/Blockchain/Renderers/NonblockRenderer.cs
Libplanet/Net/Swarm.BlockCandidate.cs

This addresses <https://github.com/planetarium/libplanet/issues/1772>.
There were multiple tries to prevent `NonblockRenderer<T>.Queue()` from calling `Thread.Start()`, and utilizing `Interlock` was indeed the most simple but robust way to achieve that.  A side story: `Thread.IsAlive` property can be more complex than you thought.  (Or it was to me at least.)
I tried to write a substantial regression test for this bug, but I couldn't find any way to make it clear without decreasing its reproducibility.  I concluded it's better to reproduce the situation well through less clear test logic, rather than clear one that does not reproduce it well.
Apart from the automated regression test, I tested _Nine Chronicles_[^1] with this patch for days, and I believe this is now quite stable.
[^1]: …

Fix `ThreadStateException` thrown by `NonblockRenderer<T>`

---

CHANGES.md
Libplanet/HashDigest.cs

This fixed <https://github.com/planetarium/libplanet/issues/1706>.

Fix `HashDigest<T>.DeriveFrom()` on .NET Standard 2.0 & release 0.25.5

---

.devcontainer/devcontainer.json
.vscode/extensions.json
CHANGES.md
Libplanet.Extensions.Cocona/Commands/ApvCommand.cs
Libplanet.Extensions.Cocona/Commands/KeyCommand.cs
Libplanet.Extensions.Cocona/Libplanet.Extensions.Cocona.csproj
Libplanet.Extensions.Cocona/PassphraseParameters.cs
Libplanet.Tools/Libplanet.Tools.csproj

This patch is the second take of @moreal's patch <https://github.com/planetarium/libplanet/pull/1593>.  In particular, this tried to address a [review suggestion on that made by myself][1]:
> As @riemannulus said, avoiding to get a passphrase through stdin was basically intended.
>
> IMHO the method to get a passphrase shouldn't be silently switched.  Instead, it'd better have an explicit option to turn on the such mode, e.g., `--passphrase-stdin`.  Of course, such option and the existing `-p`/`--passphrase` option should be mutually exclusive.
>
> On the other hand, however, exposing an uncaught exception to end-users is also a bug.  For the case `Console.IsInputRedirected` (i.e., `!isatty()`) without `--passphrase-stdin`, it should print an explicit error message instead of uncaught …

Allow `planet` command to take passphrase from stdin 

---

CHANGES.md
Libplanet.Tests/Action/ActionEvaluatorTest.cs
Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
Libplanet.Tests/Blocks/BlockMetadataTest.cs
Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
Libplanet/Action/ActionEvaluator.cs
Libplanet/Blocks/BlockMetadata.cs

Related to #1326.
Closes #1322.
Closes #1323.
This tries to readdress the issues mentioned in #1322 and #1323. While working on this PR, initial attempt was made to implement [Fisher-Yates] shuffling, but it turns out this is no trivial task.
First, some context on why [Fisher-Yates] is not used in this PR. The goal is to use `PreEvaluationHash` of a `Block<T>` to deterministically pseudo-randomly shuffle transactions by signer addresses. What [Fisher-Yates] algorithm provides is an unbiased sampling, but this requires higher entropy than that of `PreEvaluationHash` can provide by itself.<sup>[1](#footnote_01)</sup> Proper implementation would require increasing entropy by extending `PreEvaluationHash` with each transaction's signature, *not* signer address, on each step of selection …

OrderTxsForEvaluationV3 added

---

CHANGES.md
Libplanet/Action/ActionEvaluator.cs
Libplanet/Blockchain/BlockChain.cs

This PR moves logging from `BlockChain<T>.ExecuteActions()` to `ActionEvalutor<T>.Evaluate()` to enable logging of other methods that call it

Logging ActionEvaluator<T>.Evaluate() directly

---

CHANGES.md
Libplanet.Net/Transports/NetMQTransport.cs

Closes #1722.
This also effectively resolves #1819 since by eliminating an internal management of a collection of `DealerSocket`s inside `NetMQTransport`.
Unless the overhead for additional creations and teardowns of `DealerSocket` is substantial, which I don't think there is any reason to believe this is the case, this shouldn't cause an issue. As a result, overall socket usage should be further decreased by this patch.

Funnel broadcast to send

---

CHANGES.md
Libplanet.Net/Transports/NetMQTransport.cs

Partially addresses #1836.
Few things to note:
- This further relies on the reliability of `NetMQ`.
- There is no explicit check on whether a `Message` was actually sent.
- ~`DealerSocket` count is only an estimate as it can linger before actually getting disposed by `NetMQ` behind the scene.~
Tested with a local chain on 9c-internal [v100120 rc1] based client.
[v100120 rc1]: https://github.com/planetarium/NineChronicles/commit/cd871445c9fde4dcd0200a28516728f63f469032

DealerSocket linger added

---

CHANGES.md
Libplanet.RocksDBStore/RocksDBStore.cs
Libplanet/Store/BlockDigest.cs
Libplanet/Store/DefaultStore.cs

This addresses <https://github.com/planetarium/libplanet/issues/1500#issuecomment-1067793388> and releases this fix as 0.28.2.

Silence `RocksDBStore.GetBlockDigest()` for non-existent block hashes & release 0.28.2

---

CHANGES.md
Libplanet.Net.Tests/Protocols/TestTransport.cs
Libplanet.Net.Tests/SwarmTest.Broadcast.cs
Libplanet.Net.Tests/SwarmTest.cs
Libplanet.Net.Tests/Transports/TransportTest.cs
Libplanet.Net/Protocols/KademliaProtocol.cs
Libplanet.Net/Swarm.cs
Libplanet.Net/Transports/ITransport.cs
Libplanet.Net/Transports/NetMQTransport.cs
Libplanet.Net/Transports/TcpTransport.cs

See #1839 for the rationale.
To elaborate,
- With a proper pub/sub model, the responsibility of acknowledging a transportation of a `Message` that requires no reply is shifted from the sender to a receiver. In this model, the sender's application layer should not have a control to send a `Message` to a specific peer.
- With a req/rep model, 
- It is unintuitive to implicitly expect a reply for `SendMessageAsync()`.
- Every initiating `Message`s is a request, hence expects a reply.
In either case, there is no need for `SendMessageAsync()`.

Deprecate `ITransport.SendMessageAsync()`

---

.github/workflows/main.yml
CHANGES.md
Libplanet.RocksDBStore/RocksDBStore.cs
Libplanet/Store/BlockDigest.cs
Libplanet/Store/DefaultStore.cs

Note that I merged 66a1b9f41e7386e50e5976807f3bb3e2fc1afe48 instead of tag 0.28.2, because it does not refer to 66a1b9f41e7386e50e5976807f3bb3e2fc1afe48 the merge commit, but its parent commit instead.  It was my mistake, and it indeed didn't work with the release script on GitHub Actions.  (So I had to manually upload files to NuGet and GitHub releases).
In order to prevent such mistakes from now on, I added a small check to the main workflow.  It ensures if a new tag refers to a proper merge commit or a commit signed by GitHub @web-flow.[^1]
[^1]: As pull requests can be squashed when it's merged, sometimes tags may refer to a non-merge commit.  In such case, the commit is still signed by GitHub @web-flow.

Port 0.28.2 to main (0.29.x)

---

CHANGES.md
Libplanet.Net/Swarm.MessageHandlers.cs

Another follow up hotfix for #1839.
I honestly wanted to do a minor tweak on `ITransport` interface on `main` branch, but figured it'd be better to break up the work and do iterative interface update on `main` branch and have this dirty fix pushed to `0.28-maintenance` first. See #1846.
Although the behavior of `Swarm<T>` has changed, this is fully compatible with `0.28.1`.

Reply `Pong` to `TxIds` and `BlockHeaderMessage`

---

CHANGES.md
Libplanet.Extensions.Cocona/Commands/StoreCommand.cs
Libplanet.RocksDBStore.Tests/RocksDBStoreTest.cs
Libplanet.RocksDBStore/RocksDBStore.cs

This PR reverts following commits in order to release 0.29.
Revert "Merge pull request #1838 from longfin/feature/cf-remove"
This reverts commit 0e007e61359f45ff4884571d1fc1ee14f31dfec9, reversing
changes made to a25079609b6c70d076dc9a73ca57c36a5e8ee40f. (+1 squashed commits)
Revert "Merge pull request #1847 from limebell/bugfix/migration-indexes"
This reverts commit e3ff1aaaa85fbc3b48d255d33a6747f7b950c058, reversing
changes made to 0e007e61359f45ff4884571d1fc1ee14f31dfec9.

Revert IndexDB migration

---

CHANGES.md
Libplanet.Stun/Stun/TurnClient.cs

Temporarily resolves #1864. `16` is just some random number I chose. 😶
This might eventually run into a scaling issue again eventually.

Increase `Message` receive throughput

---

CHANGES.md
Libplanet.Explorer/Store/LiteDBRichStore.cs
Libplanet.Explorer/Store/MySQLRichStore.cs
Libplanet.RocksDBStore.Tests/RocksDBStoreTest.cs
Libplanet.RocksDBStore/RocksDBStore.cs
Libplanet.Tests/Store/ProxyStore.cs
Libplanet.Tests/Store/StoreTest.cs
Libplanet.Tests/Store/StoreTracker.cs
Libplanet/Store/BaseStore.cs
Libplanet/Store/DefaultStore.cs
Libplanet/Store/IStore.cs
Libplanet/Store/MemoryStore.cs

Adds `IStore.PruneOutdatedChains()` which deletes all non-canonical chains from the storage.
Closes #1874.

Add `IStore.PruneOutdatedChains()`

---

CHANGES.md
Libplanet.Net.Tests/Protocols/KBucketDictionaryTest.cs
Libplanet.Net.Tests/Protocols/KBucketTest.cs
Libplanet.Net.Tests/Protocols/ProtocolTest.cs
Libplanet.Net/Protocols/KBucket.cs
Libplanet.Net/Protocols/KBucketDictionary.cs
Libplanet.Net/Protocols/RoutingTable.cs

Partially addresses #1872. Note that only internal dictionaries are now concurrent, but `KBucket` itself is *not*. `KBucket` needs to orchestrate access to two internal dictionaries. Overall orchestration of the dictionaries will be handled in a different PR while also dealing with #1880.
Additionally, internal replacement cache size is limited to the size of a `KBucket`, i.e. the total number of `Address`es a `KBucket` can hold up to is twice its "bucket size". This results in a slight behavioral change of a `KBucket`. See `ProtocolTest.cs` in the code.

Enforce concurrency on `KBucket` internal dictionaries

---

CHANGES.md
Libplanet.Explorer.Executable/Program.cs
Libplanet.Net.Tests/Messages/BlockHashesTest.cs
Libplanet.Net.Tests/Messages/MessageTest.cs
Libplanet.Net.Tests/Messages/MessageValidatorTest.cs
Libplanet.Net.Tests/Messages/NetMQMessageCodecTest.cs
Libplanet.Net.Tests/SwarmTest.AppProtocolVersion.cs
Libplanet.Net.Tests/Transports/TcpTransportTest.cs
Libplanet.Net/DifferentAppProtocolVersionEncountered.cs
Libplanet.Net/Messages/IMessageCodec.cs
Libplanet.Net/Messages/MessageValidator.cs
Libplanet.Net/Messages/NetMQMessageCodec.cs
Libplanet.Net/Messages/TcpMessageCodec.cs
Libplanet.Net/Transports/BoundPeerExtensions.cs
Libplanet.Net/Transports/NetMQTransport.cs
Libplanet.Net/Transports/TcpTransport.cs

Closes #1885 for now.
Aside from generally dealing with #1885, `IMessageCodec` instances now have a fixed context for encoding and decoding in regards to `APV`s. We can also probably do away with `privatekey` and `timestamp` considering its lifecycle.

Separate `MessageValidator` for `IMessageCodec`s

---

CHANGES.md
Libplanet.Net.Tests/Messages/MessageValidatorTest.cs
Libplanet.Net/ActionExecutionState.cs
Libplanet.Net/BlockDownloadState.cs
Libplanet.Net/BlockHashDownloadState.cs
Libplanet.Net/BlockVerificationState.cs
Libplanet.Net/BoundPeer.cs
Libplanet.Net/FodyWeavers.xml
Libplanet.Net/Libplanet.Net.csproj
Libplanet.Net/Peer.cs
Libplanet.Net/PreloadState.cs
Libplanet.Tests/ByteUtilTest.cs
Libplanet.Tests/Store/StoreTrackLog.cs
Libplanet/Address.cs
Libplanet/Blocks/InvalidBlockPreEvaluationHashException.cs
Libplanet/Blocks/InvalidBlockTxHashException.cs
Libplanet/ByteUtil.cs
Libplanet/Crypto/PrivateKey.cs
Libplanet/Crypto/PublicKey.cs
Libplanet/Crypto/SymmetricKey.cs
Libplanet/FodyWeavers.xml
Libplanet/Libplanet.csproj
Libplanet/Nonce.cs
Libplanet/Store/Trie/MerkleTrie.cs
Libplanet/Store/Trie/Nodes/HashNode.cs
Libplanet/Store/Trie/Nodes/ValueNode.cs
Libplanet/Tx/RawTransaction.cs
Libplanet/Tx/Transaction.cs
Libplanet/Tx/TxId.cs

Remove `Fody.Equals` and classes using `[Equals]` attributed now implements `IEquatable<T>`.
Implementation `GetHashCode()` override method referenced:
https://github.com/Fody/Equals/blob/master/Equals.Fody/Injectors/GetHashCodeInjector.cs
due to compatibility.

Remove Fody dependency from Libplanet

---

.circleci/config.yml
Libplanet/Store/DefaultStore.cs

Fixed bug in `DefaultStore.PruneOutdatedChains()`.
Closes #1898 
Additionally it excludes `Libplanet.Explorer.Tests` from linux-unity-test because `Libplanet.Explorer` does not support net47 build because of `Microsoft.AspNetCore.Mvc.NewtonsoftJson 3.1.6` package.

Fix unit test bug in linux-unity-test

---

Libplanet/Action/ActionEvaluator.cs

This PR adds the `actionType` in the action evaluation log so that you can check how long it takes for specific actions to be evaluated at a glance without needing to look up the `TxId` each time. Also, this will be helpful in visualizing the evaluation time for each action type through log parsing.
**Note)** Blank txs are logged as `null`.
Before:
```
[16:37:47 DBG] 1 actions in transaction 9156218e694d63397df1cc8be0641a28e117742b60bff9c39403678b5529a0ec by 0x625D3aF1b2D9f6D13fc91b7AF6dde41A3c72B2AC with timestamp 2022-04-12T07:29:53.666732Z evaluated in 143ms.
[16:37:48 DBG] 1 actions in transaction 38889b212dd058635b5d8a953114f2595ee0a05ccaab0d8b52af18143aee3bad by 0x5b8da5757E3de0D07AA2BB8Eb04ed0c45f0BD625 with timestamp 2022-04-12T07:29:37.680461Z evaluated in 156ms.
[16:37:48 DBG] 1 …
```

update action evaluation log [skip changelog]

---

CHANGES.md
Libplanet.Net.Tests/DifferentAppProtocolVersionExceptionTest.cs
Libplanet.Net.Tests/InvalidMessageTimestampExceptionTest.cs
Libplanet.Net.Tests/Messages/BlockHashesTest.cs
Libplanet.Net.Tests/Messages/MessageTest.cs
Libplanet.Net.Tests/Messages/MessageValidatorTest.cs
Libplanet.Net.Tests/Messages/NetMQMessageCodecTest.cs
Libplanet.Net.Tests/Transports/TcpTransportTest.cs
Libplanet.Net/DifferentAppProtocolVersionException.cs
Libplanet.Net/InvalidMessageTimestampException.cs
Libplanet.Net/Messages/IMessageCodec.cs
Libplanet.Net/Messages/MessageValidator.cs
Libplanet.Net/Messages/NetMQMessageCodec.cs
Libplanet.Net/Messages/TcpMessageCodec.cs
Libplanet.Net/Protocols/KademliaProtocol.cs
Libplanet.Net/Transports/BoundPeerExtensions.cs
Libplanet.Net/Transports/NetMQTransport.cs
Libplanet.Net/Transports/TcpTransport.cs

More preparatory work for #1867.
Massive API overhaul is mainly to move `Message` validation logic from `IMessageCodec` to `ITransport` layer. Other than that, there is no noticeable behavioral change from `ITransport` and the layers above.

Context agnostic `IMessageCodec`s

---

Libplanet.Tests/Blockchain/BlockChainTest.cs

Rethrowing a caught exception causes an error on .NET 6, so I would like to remove this from the test code.
I guess the `catch` branch intended to give some textual demonstration of the test, thus intercepted the received exception `e`. It seems better to me that the demonstration be given elsewhere (maybe as a separate documentation).

Remove rethrowing of caught exception

---

CHANGES.md
Libplanet.Extensions.Cocona/Commands/KeyCommand.cs

This pull requests introduces `planet key sign` command through `KeyCommand` in `Libplanet.Extensions.Cocona`.
The command provides a feature to sign the given message encoded by base64 with the given private key, and prints the signature encoded by base64.
```
$ dotnet run --project Libplanet.Tools/Libplanet.Tools.csproj -- key sign b8b01397-eee7-4c03-9a8d-4beee26ca7b9 AA== --passphrase ""
MEUCIQCvyRlQMqtuowjNSoR+5FCvzr/hcRWeWYAsZCQpAjtq7gIgJJLwq5YPCHktTKExhsyiiQmWj+aMQFVP6ZVucf+g5Rg=
```

feat(cli): introduce `planet key sign` command

---

Libplanet.Tests/Consensus/VoteSetTest.cs
Libplanet.Tests/Consensus/VoteTest.cs
Libplanet/Consensus/Vote.cs
Libplanet/Consensus/VoteFlag.cs
Libplanet/Consensus/VoteSet.cs

For migration PoS, We need some struct for recording who participated in the block validation.
```mermaid
classDiagram
Block~T~ o-- Commit
Commit *-- Vote
VoteSet *-- Vote
class Block~T~ {
+Commit LastCommit
}
class Commit {
+Vote[] Votes
}
class Vote {
+ long Height
+ int Round
+ PublicKey Validator
+ TimeStmap timeStamp 
}
class VoteSet {
-Vote[] _prevote
-Vote[] _commit
}
```

Introduce `Vote` and `VoteSet`

---

Libplanet.Tests/Blocks/BlockCommitTest.cs
Libplanet/Blocks/Block.cs
Libplanet/Blocks/BlockCommit.cs
Libplanet/Blocks/BlockHeader.cs
Libplanet/Blocks/BlockMarshaler.cs
Libplanet/Blocks/BlockMetadata.cs
Libplanet/Blocks/IBlockMetadata.cs
Libplanet/Blocks/PreEvaluationBlockHeader.cs
Libplanet/Consensus/VoteSet.cs
Libplanet/Store/BlockDigest.cs

continue on the #1968 
For migration PoS, We need some struct for recording who participated in the block validation.
```mermaid
classDiagram
Block~T~ o-- Commit
Commit *-- Vote
VoteSet *-- Vote
class Block~T~ {
+Commit LastCommit
}
class Commit {
+Vote[] Votes
}
class Vote {
+ long Height
+ int Round
+ PublicKey Validator
+ TimeStmap timeStamp 
}
class VoteSet {
-Vote[] _votes
}
```

Introduce `BlockCommit`

---

Libplanet.Explorer.Executable/Program.cs
Libplanet.Net.Tests/Consensus/ConsensusContextTest.cs
Libplanet.Net.Tests/Consensus/ConsensusReactorTest.cs
Libplanet.Net.Tests/Consensus/ReactorTest.cs
Libplanet.Net.Tests/Consensus/RoundContextTest.cs
Libplanet.Net.Tests/Consensus/States/DefaultStateTest.cs
Libplanet.Net.Tests/Consensus/States/PreCommitStateTest.cs
Libplanet.Net.Tests/Consensus/States/PreVoteStateTest.cs
Libplanet.Net.Tests/TestUtils.cs
Libplanet.Net/Consensus/ConsensusContext.cs
Libplanet.Net/Consensus/ConsensusReactor.cs
Libplanet.Net/Consensus/DefaultState.cs
Libplanet.Net/Consensus/PreCommitState.cs
Libplanet.Net/Consensus/PreVoteState.cs
Libplanet.Net/Consensus/RoundContext.cs
Libplanet.Net/Messages/ConsensusCommit.cs
Libplanet.Net/Messages/ConsensusVote.cs
Libplanet/Blockchain/Policies/BlockPolicy.cs
Libplanet/Blockchain/Policies/IBlockPolicy.cs
Libplanet/Blockchain/Policies/NullBlockPolicy.cs

continue on the https://github.com/planetarium/libplanet/pull/1968
Previously, voting was conducted based on the peer's public key. However, this has the following problems:
1. It can be trusted that the message comes from the node that signed the message, but it cannot be verified that the message is a signed message with the validator's key.
2. In order to save the Vote to the Block, it was necessary to directly sign the Vote.
For the same reason as above, it has been implemented to ship and send `Vote` in the message.
```mermaid
classDiagram
ConsensusContext o-- RoundContext~T~
RoundContext~T~ o-- VoteSet
ConsensusVote *-- Vote
VoteSet *-- Vote
ConsensusCommit *-- Vote
class ConsensusContext {
-Dict~< long, RoundContext< T>>~ _roundContexts
}
class RoundContext~T~ {
-VoteSet _voteSet …
```

Using `Vote` and `VoteSet` on the PBFT

---

CHANGES.md
Libplanet.Net/TimeoutOptions.cs

Reference to a wrong constant fixed

---

CHANGES.md
Libplanet.Tests/Tx/TransactionTest.cs
Libplanet/Tx/Transaction.cs

This fixes <https://github.com/planetarium/NineChronicles.Headless/runs/6603180738>.

Fix `KeyNotFoundException` thrown by `Transaction<T>()`

---

Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
Libplanet.Tests/Blocks/BlockFixture.cs
Libplanet.Tests/Blocks/BlockMarshalerTest.cs
Libplanet.Tests/TestUtils.cs
Libplanet/Blockchain/BlockChain.MineBlock.cs

This adds `lastCommit` argument for `BlockChain<T>.MineBlock()`.
But there are still no validation for `BlockCommit` given in `BlockChain<T>.MineBlock()`, should add logic for it somewhere ASAP.

Add `BlockCommit` of last block when mine a new block

---

Libplanet.Net.Tests/Consensus/ConsensusContextTest.cs
Libplanet.Net.Tests/Consensus/ConsensusReactorTest.cs
Libplanet.Net.Tests/Consensus/RoundContextTest.cs
Libplanet.Net.Tests/Consensus/States/PreCommitStateTest.cs
Libplanet.Net.Tests/Consensus/States/PreVoteStateTest.cs
Libplanet.Net.Tests/TestUtils.cs
Libplanet.Net/Consensus/ConsensusContext.cs
Libplanet.Net/Consensus/ConsensusReactor.cs
Libplanet.Net/Consensus/DefaultState.cs
Libplanet.Net/Consensus/PreCommitState.cs
Libplanet.Net/Consensus/PreVoteState.cs
Libplanet.Net/Consensus/RoundContext.cs
Libplanet.Tests/Consensus/VoteSetTest.cs
Libplanet/Consensus/Vote.cs
Libplanet/Consensus/VoteSet.cs

Previously, each node did not validate the `Vote` message when they received it.
This vulnerability causes counterfeit of the `Vote` message from the attacker.
For the same reason as above, this PR is implemented to verify and sign about `Vote`.  
```mermaid
sequenceDiagram
State ->> RoundContext: call `Voting()`.
RoundContext ->> State: return `Vote` with unsigned.
State ->> ConsensusContext: call `SignVote()`.
ConsensusContext ->> State: return `Vote` with signed.
State ->> VoteSet: call `Add()`
VoteSet ->> VoteSet: verify and validate `Vote`
VoteSet ->> State: return bool which `Add()` is success
```

Verify signature when received PBFT vote message

---

Libplanet.Net.Tests/Consensus/ReactorTest.cs
Libplanet.Net.Tests/Consensus/RoundContextTest.cs
Libplanet.Net/Consensus/ConsensusContext.cs
Libplanet.Net/Consensus/ConsensusReactor.cs
Libplanet.Net/Consensus/IReactor.cs
Libplanet.Net/Consensus/PreCommitState.cs
Libplanet.Net/Consensus/PreVoteState.cs
Libplanet.Net/Consensus/RoundContext.cs

When commiting a new block, the votes for the block is stored in order to make next block. The votes collected will be included in `BlockHeader.LastCommit` field.
Additionally, fixed a bug where context committed block even commit count does not met the condition (2/3+).

Store voteset on memory when commit new block and access from reactor

---

CHANGES.md
Libplanet.Node/NodeUtils.cs

Serves two purposes:
- Removes the need to directly access "raw" class constructors as much as possible.
- Provide common basic functionality necessary to writing a boilerplate code.

✨ Introduce `NodeUtils` class

---

Libplanet.Net.Tests/Consensus/ReactorTest.cs
Libplanet.Net.Tests/Consensus/States/DefaultStateTest.cs
Libplanet.Net.Tests/Consensus/States/PreVoteStateTest.cs
Libplanet.Net/Consensus/ConsensusContext.cs
Libplanet.Net/Consensus/ConsensusReactor.cs
Libplanet.Net/Consensus/DefaultState.cs
Libplanet.Net/Consensus/PreVoteState.cs
Libplanet.Net/Consensus/RoundContext.cs
Libplanet.Net/Consensus/VoteBlockNotExistsException.cs

- `ConsensusPropose` will not broadcast 'ConsensusVote` if Block is not present in the store. (= Hold the vote)
- `PreVoteState<T>` will hold the node's vote until the proposed block is present in the store.
- When a node doesn't have a proposed block from `ConsensusMessage`, it will request the proposed block from the sender.
- Currently, `CommitBlock()` will be called even if the Block does not exist in the store.

Block Synchronization (refactored)

---

Libplanet.Node.Tests/Libplanet.Node.Tests.csproj
Libplanet.Node.Tests/NodeUtilsTest.cs
Libplanet.Node/NodeUtils.cs

Just some QoL methods. Eventually, those not requiring `<IAction>` should be separated out. 🙄

`NodeUtils` private key handling

---

CHANGES.md
Libplanet.Explorer.Executable/Program.cs
Libplanet.Net.Tests/SwarmTest.cs
Libplanet.Net/BootstrapOptions.cs
Libplanet.Net/Swarm.cs
Libplanet.Net/SwarmOptions.cs
Libplanet.Net/TimeoutOptions.cs

Mainly to reduce clutter on higher layers. 😶
This intermediary `SwarmOptions` seems quite untidy at the moment, but it'll get better soon after I add `PreloadOptions`. 😗

`BootstrapOptions` added to `SwarmOptions`

---

Libplanet.Benchmarks/SwarmBenchmark.cs
Libplanet.Explorer.Executable/Program.cs
Libplanet.Net.Tests/Consensus/ConsensusReactorTest.cs
Libplanet.Net.Tests/Consensus/ReactorTest.cs
Libplanet.Net.Tests/SwarmTest.Fixtures.cs
Libplanet.Net.Tests/SwarmTest.cs
Libplanet.Net.Tests/Transports/BoundPeerExtensionsTest.cs
Libplanet.Net/Consensus/CommitBlockNotExistsException.cs
Libplanet.Net/Consensus/ConsensusContext.cs
Libplanet.Net/Consensus/ConsensusReactor.cs
Libplanet.Net/Consensus/DefaultState.cs
Libplanet.Net/Consensus/IReactor.cs
Libplanet.Net/Consensus/PreVoteState.cs
Libplanet.Net/Swarm.cs

- Block synchronization has been replaced with Event. (`VoteHolding`, `RequestBlockInVoteHolding`)
- If committing was failed before, getting block and recommit will be retried in methodically. (`CommitFailed`, `RecommittingFailedRound`). This is not guaranteed in `IState` level yet.
- Answering `Blocks` is removed for letting Swarm answering (TODO: Swarm answers messages?). Above implementations should work without Swarm If response method with `Blocks` is added.
- Some Preparation for migration to Swarm.

Recomitting Failed Round / Preparing Swarm

---

CHANGES.md
Libplanet.Explorer.Executable/Options.cs
Libplanet.Net.Tests/FactOnlyTurnAvailableAttribute.cs
Libplanet.Net.Tests/IceServerTest.cs
Libplanet.Net.Tests/SwarmTest.cs
Libplanet.Net/IceServer.cs

Addresses https://github.com/planetarium/libplanet/issues/1995,
Also changed test conditions accordingly.
In my point of view, accepting multiple URI seems redundant, and may cause serious confusion. so I choose to accept only one URI. however, this might cause some side effects to the current codebase. I tested some use cases but cannot assure about that.

IceServer now accepts only one URI.

---

Libplanet.Benchmarks/SwarmBenchmark.cs
Libplanet.Explorer.Executable/Program.cs
Libplanet.Net.Tests/Consensus/ConsensusReactorTest.cs
Libplanet.Net.Tests/Consensus/ReactorTest.cs
Libplanet.Net.Tests/SwarmTest.Fixtures.cs
Libplanet.Net.Tests/SwarmTest.cs
Libplanet.Net.Tests/Transports/BoundPeerExtensionsTest.cs
Libplanet.Net/Consensus/ConsensusReactor.cs
Libplanet.Net/Swarm.cs

- This PR addresses remaining undone work in Block Synchronization PR, which is the `ConsensusReactor` and `Swarm` use separate `ITransport` for each.

Separate `ITransport`s (+ Prepare for PBFT Headless)

---

Libplanet.Net/Swarm.cs

`Swarm` needs to expose `VoteSetOf` and `Propose` for following method  : https://github.com/planetarium/NineChronicles.Headless/commit/7fd77a8518e66a22353978299d7ac7740fd8ff28

Expose `VoteSetOf` and `Propose`

---

Libplanet.Net/Consensus/ConsensusContext.cs
Libplanet.Net/Consensus/ConsensusReactor.cs
Libplanet.Net/Consensus/RoundContext.cs

- `RoundContext` is do not use `Serliog`.
- We want to filter only `Consensus` logs.
- Use `Serliog` in the `RoundContext`.
- Add some tagging to all `Consesnsus` logic.

Improve logging about consensus

---

Libplanet.Net/Swarm.cs

This patch also includes fix a bug where signing vote have used the swarm key, and it's now uses the consensus key.

Use swarm key for PBFT consensus node distinguish

---

CHANGES.md
Libplanet.Explorer.Executable/Options.cs
Libplanet.Net.Tests/FactOnlyTurnAvailableAttribute.cs
Libplanet.Net.Tests/IceServerTest.cs
Libplanet.Net.Tests/SwarmTest.cs
Libplanet.Net/IceServer.cs
Libplanet.Node.Tests/SwarmConfigTest.cs
Libplanet.Node/SwarmConfig.cs

Closes #2048.
I couldn't find a fully unambiguous specification for parsing `username:credential` for `UserInfo` field. In [RFC3986], it only specifies  such form is allowed but **not recommended**. So I took the liberty of equating `null` and `string.Empty` and interpreting most, if not all, edge cases as I fit to see as most intuitive. 🙄
[RFC3986]: https://datatracker.ietf.org/doc/html/rfc3986#section-3.2.1

Unnecessary parameters removed for `IceServer()`

---

.github/bin/constants.sh
CONTRIBUTING.md
Docs/docfx.json
Libplanet.Unity.Tests/Libplanet.Unity.csproj
Libplanet.Unity/Libplanet.Unity.csproj
Libplanet.sln

Import UnityEngine, UnityEngine.CoreModule dll
Current method is temporary...
1. Install Unity Version 2021.3.0f1
2. Copy `UnityEngine.dll` and `UnityEngine.CoreModule.dll` FYI https://docs.unity3d.com/Manual/UsingDLL.html
3. Paste in Libplanet.Unity/UnityReference/~

Import unity dll dependency

---

Libplanet.Unity/Miner/BaseMiner.cs
Libplanet.Unity/Miner/IMineListener.cs
Libplanet.Unity/Miner/SoloMiner.cs
Libplanet.Unity/Miner/SwarmMiner.cs

It can replace `planet-clicker` [CoMiner](https://github.com/planetarium/planet-clicker/blob/master/planet-clicker/Assets/LibplanetUnity/Agent.cs#L406)
It has been implemented as an abstract class so that the user can use specific mining code
below code is example
```csharp
...
public class MiningHandler<T> : IMineListener<T>
{
public void Success()
{
// Handle Success
}
public void Failure()
{
// Handle Failure
// ex) TxRetry, Logging
}
}
_miner = SoloMiner(_chain, _privateKey, MiningHandler)
StartCoroutine(_miner.CoStart())
...
```
If you want to use it with `Swarm`, you can use `SwarmMiner`

Miner Coroutine Object

---

Libplanet.Explorer/GraphTypes/ActionType.cs
Libplanet.Explorer/GraphTypes/BlockType.cs
Libplanet.Explorer/GraphTypes/TransactionType.cs

This PR resolves #1247, and "Tried but failed" to mediate #2065, but failed due to Generics of each queries in explorer.
Is there any good Idea to circumvent each IActions required by all queries?

Added GraphQL type descriptions

---

Libplanet.Net.Tests/SwarmTest.cs
Libplanet.Net/Consensus/ConsensusReactor.cs
Libplanet.Net/Swarm.cs
Libplanet.Net/SwarmOptions.cs

1. Recent `libplanet` development ecosystem, we don't use `StaticPeers` nowadays.
2. Instead, PBFT needs its own `PeerTable` and `ITransport` for consensus validator.
- Remove `StaticPeers` related logic. 
- Rename `StaticPeers` to `ConsensusPeers`

`StaticPeers` are now `ConsensusPeers`

---

Libplanet.Net.Tests/Consensus/ConsensusContextTest.cs
Libplanet.Net.Tests/TestUtils.cs
Libplanet.Net/Consensus/ConsensusContext.cs

- Consensus should go on when block is synced by non-consensus way.

Start consensus when new block is appended

---

Libplanet.Net.Tests/Consensus/ContextTest.cs
Libplanet.Net/Consensus/Context.cs
Libplanet.Net/Consensus/InvalidValidatorVoteMessageException.cs
Libplanet/Consensus/Vote.cs
Libplanet/Consensus/VoteSet.cs

Added `Vote.Verify(PublicKey)` method for signature validation, and use method to validate received voting messages (`ConsensusVote`, `ConsensusCommit`).

Validate vote message

---

Libplanet.Benchmarks/SwarmBenchmark.cs
Libplanet.Explorer.Executable/Program.cs
Libplanet.Net.Tests/Consensus/ConsensusReactorTest.cs
Libplanet.Net.Tests/SwarmTest.Fixtures.cs
Libplanet.Net.Tests/SwarmTest.cs
Libplanet.Net.Tests/Transports/BoundPeerExtensionsTest.cs
Libplanet.Net/Consensus/ConsensusReactor.cs
Libplanet.Net/Swarm.cs

- Remove argument, parameter `validators` from `Swarm<T>`
- Remove argument, parameter `validators` from `ConsensusReactor<T>`
- Remove checking between parameters `validators` and `validatorPeers`
- Subsitute `validators` paremeter with `PublicKey` obtained from`validatorPeers`
- Resolves https://github.com/planetarium/libplanet/issues/2093

refactor: Remove argument, parameter 'validators' from 'Swarm<T>' and 'ConsensusReactor<T>'

---

Libplanet.Net/Swarm.cs

- Remove unncessary field `ConsensusRoutingTable` in `Swarm<T>`
- https://github.com/planetarium/libplanet/issues/2094

refactor: Remove unnecessary field 'ConsensusRoutingTable' in 'Swarm<T>'

---

Libplanet.Net/Consensus/ConsensusReactor.cs
Libplanet.Net/Consensus/Context.cs

When bootstrapping a new network, nodes need minimum validator liveness for consensus. 
Waiting for nodes until +2/3 validator peers are checked.

Waiting for nodes to reach consensus

---

Libplanet.Net.Tests/Consensus/ConsensusContextTest.cs
Libplanet.Net.Tests/Consensus/ContextTest.cs
Libplanet.Net/Consensus/ConsensusContext.cs
Libplanet.Net/Consensus/Context.cs
Libplanet.Net/Consensus/Step.cs

All nodes in network may fail to receive `ConsensusPropose` message because of GST mismatch.
`ConsensusContext<T>` now have `Context<T>` for each height and remove it when consensus for higher height is started. It helps storing messages from higher height. Only messages from current consensus height will cause operation by limiting step in `Context<T>.DoHandleMessage()` to `Step.Propose`, `Step.PreVote` and `Step.PreCommit`.
A newly added test `ConsensusContextTest.HandleProposeMessageFromHigherHeight()` tests scenario that propose of higher height is received, and consensus completed in current height thus leads to next height's `Step.PreVote` fluently.

Store all messages for consensus regardless of it's height

---

CHANGES.md
Libplanet.Extensions.Cocona/Libplanet.Extensions.Cocona.csproj
Libplanet.Tools/Libplanet.Tools.csproj
Libplanet.Tools/Program.cs

This pull request bumps the` Cocona.Lite` package to `2.0.*`, the latest major version.

Bump `Cocona.Lite` to `2.0.*`

---

Libplanet.Net.Tests/Consensus/ConsensusContextTest.cs
Libplanet.Net/Consensus/ConsensusContext.cs
Libplanet.Net/Consensus/Context.cs

When more than two messages processed simultaneously, an if statement can be `true` but it actually should be false due to timing issue of the context change.

Context process messages in single task

---

Libplanet.Net.Tests/Consensus/ConsensusContextTest.cs
Libplanet.Net.Tests/Consensus/ConsensusReactorTest.cs
Libplanet.Net.Tests/Consensus/Context/ContextNonProposerTest.cs
Libplanet.Net.Tests/Consensus/Context/ContextProposerTest.cs
Libplanet.Net.Tests/Consensus/Context/ContextProposerValidRoundTest.cs
Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
Libplanet.Net.Tests/Consensus/Context/ContextTestBase.cs
Libplanet.Net.Tests/Consensus/ReactorTest.cs
Libplanet.Net.Tests/TestUtils.cs
Libplanet.Net/Consensus/ConsensusReactor.cs
Libplanet.Net/Consensus/Context.cs

This PR is refactoring `ConsensusReactorTest`, `ReactorTest` majorly.
+ Change `CreateReator` abstract to the concrete method.
+ `ReactorTest` defines and creates required objects to create `ConsensusReactor` in `ConsensusReactorTest`.
+ Some clean-up and bugfix created from https://github.com/planetarium/libplanet/pull/2100
+ Move `IncreaseRoundWhenTimeout` to `ConsensusContextTest`.
+ Testing timeout in `ConsensusReactor` is hard to imitates the situation.
---
+ Fix some of `Timeout` methods that does not multiply its multiplier.
+ Remove no longer needed TODO
+ Move responsibility `StopAsync()` in `ConsensusContextTest`, `ConsensusReactorTest`.
+  xUnit supports `IAsyncDispose` in v3 https://github.com/xunit/xunit/issues/2017

refactor: ReactorTest and ConsensusReactorTest

---

Libplanet.Benchmarks/SwarmBenchmark.cs
Libplanet.Explorer.Executable/Program.cs
Libplanet.Net.Tests/Consensus/ConsensusContextTest.cs
Libplanet.Net.Tests/Consensus/ConsensusReactorTest.cs
Libplanet.Net.Tests/Consensus/Context/ContextNonProposerTest.cs
Libplanet.Net.Tests/Consensus/Context/ContextProposerTest.cs
Libplanet.Net.Tests/Consensus/Context/ContextProposerValidRoundTest.cs
Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
Libplanet.Net.Tests/Consensus/Context/ContextTestBase.cs
Libplanet.Net.Tests/Consensus/ReactorTest.cs
Libplanet.Net.Tests/SwarmTest.Fixtures.cs
Libplanet.Net.Tests/SwarmTest.cs
Libplanet.Net.Tests/TestUtils.cs
Libplanet.Net.Tests/Transports/BoundPeerExtensionsTest.cs
Libplanet.Net/Consensus/ConsensusContext.cs
Libplanet.Net/Consensus/ConsensusReactor.cs
Libplanet.Net/Consensus/Context.cs
Libplanet.Net/Messages/ConsensusCommit.cs
Libplanet.Net/Messages/ConsensusMessage.cs
Libplanet.Net/Messages/ConsensusPropose.cs
Libplanet.Net/Messages/ConsensusVote.cs
Libplanet.Net/Swarm.cs
Libplanet.Tests/Blocks/BlockCommitTest.cs
Libplanet.Tests/Blocks/BlockFixture.cs
Libplanet.Tests/Consensus/VoteSetTest.cs
Libplanet.Tests/Consensus/VoteTest.cs
Libplanet/Consensus/Vote.cs
Libplanet/Consensus/VoteSet.cs

This resolves https://github.com/planetarium/libplanet/issues/2104
+ Remove `nodeId` from `Swarm<T>`, `ConsensusReactor`, `ConsensusContext`, `Context`
+ `VoteSet` stores votes in `Dictionary<PublicKey, Vote>` where key is vote of Validator's `PublicKey`.
+ `VoteSet.Votes` returns a new `IImutableList<Vote>` by indexing `Dictionary<PublicKey, Vote>` in order of `ValidatorSet`. `ToDictionary()` does not keep the order of list.

refactor: remove parameter `nodeId` from `Swarm<T>`

---

Libplanet.Net.Tests/Consensus/ConsensusContextTest.cs
Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
Libplanet.Net/Consensus/ConsensusContext.cs
Libplanet.Net/Consensus/Context.cs
Libplanet/Blocks/BlockCommit.cs
Libplanet/Consensus/VoteSet.cs

By storing `Vote`s from previous round, chain can be validated.

Fill `Block<T>.LastCommit` by getting voteset from last block's consensus context

---

CHANGES.md
Libplanet.Extensions.Cocona/Commands/KeyCommand.cs

this addresses #2017 and  #2107.
- `key derive [private key]` introduced.
- now most of key command accepts --path or --store-path flag to specify the KeyStore path.
- because of that, key export --path behaves differently now, not exporting file to that path, but use that path as keystore to import 'from'
- key export behavior changed 
- BEFORE : with --json and --path flag, JSON file has been exported to specified path.
- AFTER  : always outputs as stdout, regardless of json or raw hex key.

Add --path flag in `key` command, and implemented `key derive`

---

CHANGES.md
Libplanet.Net.Tests/IceServerTest.cs
Libplanet.Net/IceServer.cs

- Replace improper handling on invalid url with throwing exception
- Resolves https://github.com/planetarium/libplanet/issues/2058

fix: Prevent improper parsing on 'Uri.UserInfo' with exception

---

Libplanet.Net.Tests/SwarmTest.Broadcast.cs

- Enlarge time interval between blockchain tip check and `renderCount` assertion check
- `SwarmTest.BroadcastBlockWithSkip` sometimes fails, and it's due to early checking of `renderCount`
- `renderAction` occurs after blockchain tip change, and interval `100` between blockchain tip check and `renderCount` assertion could be so small that makes test flaky
- Enlarging time interval to `1000` between blockchain tip check and `renderCount` assertion check won't make this test 100% deterministic, but `almost` deterministic
- There are some ways to make this test deterministic, but those will contain some changes on functionality on `libplanet`, and those changes seems to not mendatory for main purpose of `libplanet`
- Before fix, almost every time, within 7 minutes, test failure has been …

fix: fix flaky test `SwarmTest.BroadcastBlockWithSkip`

---

Libplanet.Benchmarks/DataModel/DataModelBenchmark.LeafModel.cs
Libplanet.Benchmarks/DataModel/DataModelBenchmark.MidModel.cs
Libplanet.Benchmarks/DataModel/DataModelBenchmark.RootModel.cs
Libplanet.Benchmarks/DataModel/DataModelBenchmark.cs
Libplanet.Tests/Store/DataModelTest.cs
Libplanet/Store/DataModel.Decode.cs
Libplanet/Store/DataModel.Encode.cs

Closes #1956.
Revisiting #1980.
To make sure that there will be no substantial performance, for reference, I'm leaving a benchmark result here.
BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19044
11th Gen Intel Core i7-1185G7 3.00GHz, 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=3.1.413
[Host]     : .NET Core 3.1.19 (CoreCLR 4.700.21.41101, CoreFX 4.700.21.41603), X64 RyuJIT
DefaultJob : .NET Core 3.1.19 (CoreCLR 4.700.21.41101, CoreFX 4.700.21.41603), X64 RyuJIT
|             Method |       Mean |     Error |    StdDev |
|------------------- |-----------:|----------:|----------:|
|    EncodeRootModel | 5,661.5 us | 107.83 us | 110.74 us |
|    EncodeLeafModel | 1,645.6 us |  28.50 us |  25.26 us |
| EncodeRawLeafModel | 1,246.0 us |  22.13 us |  20.70 us |
|    DecodeRootModel | …

Refactor `DataModel`

---

Libplanet/Store/DataModel.Decode.cs

Closes #2143.
See #2137 for performance comparison.
Seems like we have slightly uglier code with slightly slower decoding. 🙄
Not as slow as I have originally worried.
Need to make sure this passes `linux-unity-test`.
BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19044
11th Gen Intel Core i7-1185G7 3.00GHz, 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=3.1.413
[Host]     : .NET Core 3.1.19 (CoreCLR 4.700.21.41101, CoreFX 4.700.21.41603), X64 RyuJIT
DefaultJob : .NET Core 3.1.19 (CoreCLR 4.700.21.41101, CoreFX 4.700.21.41603), X64 RyuJIT
|             Method |       Mean |     Error |    StdDev |     Median |
|------------------- |-----------:|----------:|----------:|-----------:|
|    EncodeRootModel | 5,556.3 us | 110.62 us | 122.96 us | 5,553.7 us |
|    EncodeLeafModel | 1,662.1 us | …

Use `object` instead of `dynamic` for Unity Mono compatibility.

---

.circleci/config.yml
.github/auto_assign.yml
.github/bin/dist-nuget.sh

- `dotnet nuget push` had been failed when we re-run a job triggered by a tag push (due to its flakiness).  Now such failure would not happen as it ignores NuGet packages of already uploaded versions.
- Test report XMLs hadn't been collected for tests without code coverage.  (I omitted it by mistake.)  It's now fixed.
- @colibrishin & @OnedgeLee are added to the auto-assign list.

Slightly improve CI/CD experience

---

CHANGES.md
Libplanet/Blockchain/BlockChain.cs
Libplanet/Blockchain/BlockLocator.cs

(Partially?) Implements #1762.
This PR does not completely decouple Libplanet.Net from Libplanet, but it exposes few APIs required to remove `[assembly: InternalsVisibleTo("Libplanet.Net")]` to the public. The exposed APIs are those of which does not seem to introduce severe side effects.

Expose BlockLocator and Libplanet.Net related functions in BlockChain<T>

---

.circleci/config.yml

Resolves #1598.
First we grep by four spaces (`    `) to find lines containing test cases, then replace with `\n    `. Then, we remove the consecutive multiple newlines, followed by another grep by four spaces to isolate only test cases.

Workaround for `dotnet test --list-tests` omitting newlines

---

CHANGES.md
Libplanet.RocksDBStore/RocksDBStore.cs
Libplanet.Tests/Blockchain/BlockChainTest.cs
Libplanet/Blockchain/BlockChain.cs

Resolves #2155.
The overflow was due to trying to cast `timestamp` to `int`, whereas `timestamp` can be anything in the range of `Int64`. Specifically, in `BlockChainTest`, the timestamp used for txs are set to Jan 1st 0, which is well outside `Int32`. `int` cast was removed.
`RocksDBStore` was using `DateTimeOffset.ToUnixMilliseconds` in `PutBlock`, which reduces the precision to at most miliseconds. As such, tests were failing for `PerceivedTime` since the default value for it was derived by `DateTimeOffset.UtcNow` which has more precision. Now, the default value for `PerceivedTime` has millisecond precision.

Fix timestamp-related problems in RocksDBStore

---

Libplanet.Tests/Blockchain/Renderers/DelayedActionRendererTest.cs

It's second attempt of #2167.  As `DelayedActionRendererTest.ClearRenderBufferWhenItsInterval()` is quite flaky for an unknown reason, I temporarily made it try up to 3 times when it fails.
Anyway, it should be properly resolved later: <https://github.com/planetarium/libplanet/issues/2166>.

Let `DelayedActionRendererTest.ClearRenderBufferWhenItsInterval()` try up to 3 times

---

CHANGES.md
Libplanet/Action/AccountStateDeltaImpl.cs
Libplanet/Action/IAccountStateDelta.cs
Libplanet/Action/IAccountStateView.cs

This pull request introduces a new interface named `IAccountStateDeltaView`, a part of `IAccountStateDelta` but read-only. For example, in nine-chronicles, it implements `IAccounStateDeltaExtensions`, utils to fetch typed many states over the raw API. In the case, it uses only read-only methods (e.g. `GetState`, `GetStates`, `GetBalance`). For cases like the extensions, its modification permission is too excessive so I hope it has a read-only view. (Of course, I think side-effects or mistakes will not occur though it has permission because it is immutable.)
If its labels are not fit this issue, please re-label for this issue 🙏🏻

Introduce `IAccountStateView`

---

Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextProposerTest.cs
Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTestBase.cs
Libplanet.Net.Tests/Consensus/Context/ContextNonProposerTest.cs
Libplanet.Net.Tests/Consensus/Context/ContextProposerTest.cs
Libplanet.Net.Tests/Consensus/Context/ContextProposerValidRoundTest.cs
Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
Libplanet.Net.Tests/Consensus/Context/ContextTestBase.cs
Libplanet.Net.Tests/TestUtils.cs
Libplanet.Net/Consensus/ConsensusContext.cs
Libplanet.Net/Consensus/Context.Async.cs
Libplanet.Net/Consensus/Context.Event.cs
Libplanet.Net/Consensus/Context.Mutate.cs
Libplanet.Net/Consensus/Context.cs
Libplanet/Blockchain/BlockChain.MineBlock.cs

Closes #2193.
Refactors `Context.cs`.
Largely tries to achieve the following two points:
- Better thread safety.
- Cover more cases.
While message consumption was single threaded, spawning side tasks for timeout events were problematic. As triggered timeout tasks needed to access the message log as a side task, race condition could happen as the main message consuming task could add messages to the message log while a timeout task was accessing the message log. Use of `Concurrency` type itself does not ensure concurrency, especially when conditional checks on the collection in question and `LINQ` expressions are involved.
The original intent was to additionally trigger processing tasks (i.e. apply upon rules) when timeout events occur, but as mentioned above, as timeout events are side …

Refactor `Context` for thread safety and covering additional edge cases

---

Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
Libplanet.Net/Consensus/Context.Async.cs
Libplanet.Net/Consensus/Context.Event.cs
Libplanet.Net/Consensus/Context.Mutate.cs

Closes #2196.
There is no real change to the behavior. To iron out the design consistency for `Context`, `AddMessage()` has been made `private`. See the note at the top of `Context.Mutate.cs`.
This only adds an event handler for thrown `Exception`s. If a need arises to react to these `Exception`s, other tasks should subscribe to `ExceptionOccurred` event handler and react accordingly. 😗

`ExceptionOccurred` `EventHandler<Exception>` added to `Context`

---

Libplanet.Node.Tests/Libplanet.Node.Tests.csproj
Libplanet.Tests/Libplanet.Tests.csproj

Analyzer was acting up under [VSCode]. Probably due to changes in #2173.
Seems like usage of [`System.Text.Json`] propagates the necessity to use [`Microsoft.Bcl.AsyncInterfaces`] regardless of targeted framework.
[VSCode]: https://code.visualstudio.com/
[`System.Text.Json`]: https://www.nuget.org/packages/System.Text.Json/5.0.2
[`Microsoft.Bcl.AsyncInterfaces`]: https://www.nuget.org/packages/Microsoft.Bcl.AsyncInterfaces/5.0.0

Package reference fix

---

.github/workflows/benchmarks.yml
.github/workflows/check-build.yaml
.github/workflows/main.yml

The GitHub Blog said, they will deprecate Ubuntu 18.04 runner image since 2022.12.01. So this pull request upgrades the runner image to the latest runner image.
See also https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/.

Upgrade Ubuntu 18.04 image to latest in GitHub Actions

---

CHANGES.md
Libplanet.Net.Tests/IceServerTest.cs
Libplanet.Net/IceServer.cs
Libplanet.Net/Transports/NetMQTransport.cs
Libplanet.Stun/IIceServer.cs
Libplanet.Stun/IceServerException.cs
Libplanet.Stun/Stun/TurnClient.cs

Related to #2218.
Two points:
- Not sure if `ProbeConnectableLength` is appropriate.
- ~Still wondering if there is a more elegant way of calling `async` from `sync`.~ 🙄
~P.S. I know forcefully calling `async` from `sync` is bad practice, but IMO this is still better than `async` code spreading uncontrollably without proper design support.~ 😐

Refactor `IceServer.CreateTurnClient()`

---

CHANGES.md
Libplanet.Net.Tests/Protocols/ProtocolTest.cs
Libplanet.Net.Tests/Protocols/TestTransport.cs
Libplanet.Net.Tests/SwarmTest.Broadcast.cs
Libplanet.Net.Tests/SwarmTest.Preload.cs
Libplanet.Net.Tests/SwarmTest.cs
Libplanet.Net.Tests/Transports/NetMQTransportTest.cs
Libplanet.Net.Tests/Transports/TransportTest.cs
Libplanet.Net/Swarm.cs
Libplanet.Net/Transports/ITransport.cs
Libplanet.Net/Transports/NetMQTransport.cs

Related to #1612, #1934.
Some preparatory work to streamline uses of `ITransport` and `Swarm<T>`.
This is mostly to move up `ITransport`'s binding phase more in line with the rest of the `Libplanet.Net`'s (seemingly) intended design. 🙄
There are some problematic uses of `async` and `CancellationToken` handling here and there, which should be dealt with shortly. 😐
Hopefully with this, we might be ready to combine `Peer` and `BoundPeer` into a single class.

♻️ Refactor `NetMQTransport`'s initialization

---

CHANGES.md
Libplanet.Net.Tests/BoundPeerTest.cs
Libplanet.Net/BoundPeer.cs

Add `PeerString` property to get a `BoundPeer`'s peer string.
resolved: #2187

Add `PeerString` property

---

Libplanet/Blockchain/BlockChain.MineBlock.cs
Libplanet/Blocks/BlockContent.cs

Follows #2252.
Keeping `PreEvaluationHash` as a separate entity from `PreviousHash` might be useful. Further discussion may be needed.

Use default `Nonce` for pbft `Block<T>`s

---

CHANGES.md
Libplanet.Tests/Tx/TransactionTest.cs
Libplanet/Tx/Transaction.cs

It's a hotfix of `Transaction<T>.Create()` and I'm going to release it as 0.40.1.
See also the changelog and the added regression test.

Fix `Transaction<T>.Create()` & release 0.40.1

---

CHANGES.md
Libplanet.Net.Tests/SwarmTest.Broadcast.cs
Libplanet.Tests/Blockchain/BlockChainTest.cs
Libplanet/Blockchain/BlockChain.cs

This method would've been implemented together in #2175, but I omitted it.

`BlockChain<T>.MakeTransaction()` for system actions

---

Libplanet.Net.Tests/Consensus/ConsensusReactorTestBase.cs
Libplanet.Net.Tests/SwarmTest.Broadcast.cs

Makes it overall less flaky. macos-netcore-test is still problematic.

Longer propagation delay for test

---

CHANGES.md
Libplanet.Explorer.Executable/Options.cs
Libplanet.Explorer.Executable/Program.cs
Libplanet.Tests/Action/ActionEvaluatorTest.cs
Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
Libplanet.Tests/Blockchain/BlockChainTest.cs
Libplanet/Blockchain/BlockChain.MineBlock.cs
Libplanet/Blockchain/Policies/BlockPolicy.cs
Libplanet/Blockchain/Policies/IBlockPolicy.cs
Libplanet/Blockchain/Policies/NullBlockPolicy.cs
Libplanet/Blocks/BlockMarshaler.cs
Libplanet/Blocks/InvalidBlockBytesLengthException.cs

Closes #2290.
To be frank, this is only tangentially related to what I'm supposed to be working on. 😗
~~It's a bit of a stretch, but the name `GetMaxBlockBytes()` is kept intact so the API doesn't have to change.~~
See the discussion below.

Check marshaled transactions size instead of entire block size

---

CHANGES.md
Libplanet.Net/Swarm.cs
Libplanet.Net/Transports/NetMQTransport.cs

Fixed a bug where NetMQTransport is not properly disposed of due to NetMQTransport._router being stopped before _router.Unbind() call. Will be released as 0.41.2.

Fix `NetMQTransport` disposal & Release 0.41.2

---

CHANGES.md
Libplanet/Blocks/Block.cs
Libplanet/Blocks/BlockHeader.cs
Libplanet/Blocks/BlockMetadata.cs
Libplanet/Store/BlockSet.cs

Migration is done by ignoring verification for `Hash` and `Signature` for PoW-based blocks.
Closes #2203.

Support chain migration from PoW-based blockchain to PBFT-based blockchain

---

CHANGES.md
Libplanet/Address.cs
Libplanet/Tx/TxId.cs

It's shocking that they haven't implemented `IEquatable<T>`.  Note that they've already had `Equals(T)` which could satisfy the interface anyway…

Let `Address` and `TxId` implement `IEquatable<T>`

---

.circleci/config.yml
CHANGES.md
Libplanet.Extensions.Cocona/Libplanet.Extensions.Cocona.csproj
Libplanet.Extensions.Cocona/Utils.cs
Libplanet.Node.Tests/Libplanet.Node.Tests.csproj
Libplanet.Node/SwarmConfig.cs
Libplanet.Tests/AddressTest.cs
Libplanet.Tests/Assets/CurrencyTest.cs
Libplanet.Tests/Assets/FungibleAssetValueTest.cs
Libplanet.Tests/Blocks/BlockHashTest.cs
Libplanet.Tests/HashDigestTest.cs
Libplanet.Tests/Libplanet.Tests.csproj
Libplanet.Tests/TestUtils.cs
Libplanet.Tests/Tx/TxIdTest.cs
Libplanet/Address.cs
Libplanet/Assets/Currency.cs
Libplanet/Assets/FungibleAssetValue.cs
Libplanet/Blocks/BlockHash.cs
Libplanet/HashDigest.cs
Libplanet/Libplanet.csproj
Libplanet/Tx/TxId.cs

I implemented several [custom JSON converters] for types so that they are serialized better with [`System.Text.Json.JsonSerializer`].
[custom JSON converters]: https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to
[`System.Text.Json.JsonSerializer`]: https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializer

Serialize/deserialize better with `System.Text.Json.JsonSerializer`

---

Libplanet/PoS/Misc/Asset.cs

To access from Lib9c, changed access modifier of `Libplnet.PoS.Asset` to public.

Change access modifier of `Libplnet.PoS.Asset`

---

CHANGES.md
Libplanet.Explorer.Executable/Program.cs
Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTestBase.cs
Libplanet.Net.Tests/Consensus/ConsensusReactorTestBase.cs
Libplanet.Net.Tests/Consensus/Context/ContextTestBase.cs
Libplanet.Net.Tests/TestUtils.cs
Libplanet.Net/Consensus/ConsensusContext.cs
Libplanet.Net/Consensus/ConsensusReactor.cs
Libplanet/Blockchain/BlockChain.MineBlock.cs
Libplanet/Blockchain/Policies/BlockPolicy.cs
Libplanet/Blockchain/Policies/IBlockPolicy.cs
Libplanet/Blockchain/Policies/NullBlockPolicy.cs

Adds `IBlockPolicy.GetValidators()` method to retrieve a set of validators tied to an index.

Added pluggable validators policy

---

CHANGES.md
Libplanet.Explorer.Tests/GraphQLTestUtils.cs
Libplanet.Explorer.Tests/TransactionQueryTest.cs
Libplanet.Explorer/Queries/TransactionQuery.cs

See also the changelog.
Note that I cherry-picked a part of 83f665e60949b59e0594003a5e7d77d8e8fe5bf7 (see also #2186).

Make `bindSignature()` can take tx w/ a system action & release 0.40.3

---

CHANGES.md
Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
Libplanet.Net.Tests/TestUtils.cs
Libplanet.Net/Consensus/Context.Mutate.cs
Libplanet.Net/Consensus/Context.cs
Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
Libplanet.Tests/Blocks/BlockCommitTest.cs
Libplanet.Tests/Blocks/BlockFixture.cs
Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
Libplanet.Tests/Consensus/VoteSetTest.cs
Libplanet.Tests/Consensus/VoteTest.cs
Libplanet/Blocks/PreEvaluationBlockHeader.cs
Libplanet/Consensus/IVoteMetadata.cs
Libplanet/Consensus/Vote.cs
Libplanet/Consensus/VoteMetadata.cs
Libplanet/Consensus/VoteSet.cs

Makes `Vote`'s design more in line with #2321.
In particular, it is not possible to "normally" generate a `Vote`, i.e. through `VoteMetadata.Sign()`, with one of the following properties:
- A `Vote` with its `Flag` set to `Null` or `Unknown` with a signature.
- A `Vote` with its `Flag` set to `Absent` or `Commit` without a signature.
However, unlike `Block<T>` and `Transaction<T>` in #2321, invalid votes **can** be created through deserialization, as this might be useful for collecting evidences in PoS.

`Vote` class overhauled

---

Libplanet.Explorer/GraphTypes/BencodexValueType.cs
Libplanet.Explorer/GraphTypes/ByteStringType.cs
Libplanet.Explorer/Libplanet.Explorer.csproj
Libplanet.Explorer/Queries/TransactionQuery.cs
Libplanet.Explorer/Store/IRichStore.cs
Libplanet.Explorer/Store/LiteDBRichStore.cs
Libplanet.Explorer/Store/MySQLRichStore.cs

This pull request bumps `StyleCop.Analyzer` to `1.2.0-beta.435`, the latest version.
I was working for #2353 and used `record` syntax but the current `StyleCop.Analyzer` doesn't support it. So I opened this pull request.
---
I don't know why this pull request cannot pass the `linux-unity-test` job 😭

Upgrade StyleCop analyzer to 1.2.0-beta.435

---

Libplanet/Assets/Currency.cs

This pull request resolves #2368. I don't have no idea to test this fallback automatically yet. 🤔 
When executing `Libplanet.Assets.Currency.GetHash()` method in WASM environment (Blazor), it throws `PlatformNotSupportedException`. This pull request makes the method use `SHA1Managed` when the exception was thrown.

Fallback with `SHA1Managed` if the platform doesn't support

---

CHANGES.md
Libplanet.Explorer.Tests/GraphTypes/TxResultTypeTest.cs
Libplanet.Explorer/GraphTypes/TxResult.cs
Libplanet.Explorer/GraphTypes/TxResultType.cs
Libplanet.Explorer/Queries/TransactionQuery.cs

Originally, `Libplanet.Tx.TxSuccess` stores `updatedStates`, `updatedFungibleAssets`, `fulgibleAssetsDelta` but GraphQL API doesn't support it. Maybe it was because `NineChronicles` do not store them and it didn't implement the parts. But `Libplanet.Explorer` is *generic* application, not specific for `NineChronicles`, so it should implement them. This pull request implements those.

Make TxResultType support TxSuccess fully

---

Libplanet.Tests/TestUtils.cs
Libplanet/Consensus/Vote.cs
Libplanet/Consensus/VoteMetadata.cs

Should be removed once we upgrade [Bencodex.Net] and use its new [JSON serialization] feature.
[Bencodex.Net]: https://github.com/planetarium/bencodex.net
[JSON serialization]: https://github.com/planetarium/bencodex.net/pull/69

🧹  Json serialization fix

---

CHANGES.md
Libplanet.Net.Tests/TestUtils.cs
Libplanet.Net/Consensus/ConsensusContext.cs
Libplanet.Net/Consensus/ConsensusReactor.cs
Libplanet.Net/Consensus/ConsensusReactorOption.cs
Libplanet.Net/Consensus/Context.cs
Libplanet.Net/Consensus/ContextTimeoutOption.cs
Libplanet.Net/Swarm.cs

This PR introduces a new class for the option of consensus timeout configuration.
- For each step (Propose, PreVote, PreCommit), there are base timeouts and multipliers. Base timeouts are the initial values for timeout, and multipliers are for multiplying factors when a new round is started.
- This class guards from unexpected values (where value <= 0) and lets the values can be configurable.

Option class for consensus timeout configuration

---

CHANGES.md
Libplanet.Tests/AddressTest.cs
Libplanet.Tests/Tx/TxIdTest.cs
Libplanet/Address.cs
Libplanet/Tx/TxId.cs

Also, `IComaparable.Compare()` is not supposed to throw `ArgumentNullException` according to its interface definition.

Expose `IComparable` and `IComparable<T>` interface methods for `Address`

---

CHANGES.md
Libplanet.Net.Tests/Messages/MessageValidatorTest.cs
Libplanet.Net/Messages/MessageValidator.cs

Solved https://github.com/planetarium/libplanet/issues/2377
I add `!message.Version.Version.Equals(appProtocolVersion.Version) || !trusted` condition above `DifferentAppProtocolVersionException`
it only checks apv version and accepts trusted signer

Implement different extra callbacks and ignore

---

Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs

Patching it since it's become quite a nuisance. 😑
Should fix flakiness for `HandleMessageFromHigherHeight()` test.

Temporary test fix

---

CHANGES.md
Libplanet.Explorer/GraphTypes/TxResultType.cs

This pull request makes `TxResultType`'s all internal classes public:
- `UpdatedStateType`
- `FungibleAssetBalancesType`
because it should be opened when other application wants to use `TxResultType`.

Make all `TxResultType`'s internal types public

---

Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
Libplanet.Net/Consensus/ConsensusContext.cs
Libplanet.Net/Consensus/Context.cs

There were cases where `ConsensusContext` did not dispose `Context` instances correctly, and this PR fixed it by iterating the dictionary and removing it correctly.
Skips the changelog because PBFT has not been released yet.

Remove old contexts

---

Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextProposerTest.cs
Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
Libplanet.Net/Consensus/ConsensusContext.Event.cs
Libplanet.Net/Consensus/ConsensusContext.cs
Libplanet.Net/Consensus/Context.Async.cs
Libplanet.Net/Consensus/Context.Event.cs
Libplanet.Net/Consensus/Context.Mutate.cs

This PR adds `EventHandler`s in `ConsensusContext<T>` which are listening to their designated `EventHandler` from multiple `Context<T>`.
Solves after-attaching (Subscribe method to `EventHandler` after the `Context<T>` has started) problem.
`ConsensusContext` has now its `EventHandler`s which are the same type as `Context<T>`'s. These will be attached to `Context<T>` when it is initialized (By `NewHeight()` or `HandleMessage`.)
This PR is one of fixing flakiness in the PBFT test, but the groundwork for subscribing `EventHandler` before the `Context` starts.
- `HandleMessageFromHigherHeight` fails due to time check. target time was 1 sec, actual time delta was ~= 0.99 sec, 1.5sec in the worst case.
- Some of the tests have a long duration. Most tests are timeout, so the shortened timeout …

Subscribing all `Context` EventHandler

---

Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
Libplanet.Tests/Blocks/BlockCommitTest.cs
Libplanet.Tests/Blocks/BlockMetadataTest.cs
Libplanet.Tests/Store/StoreTest.cs
Libplanet/Blocks/BlockCommit.cs
Libplanet/Blocks/BlockMetadata.cs

In addition to having to have same height and rounds, this also requires `BlockCommit`'s `Vote`s to have the same hash when not `null`.

Added `BlockCommit` hash consistency check

---

Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextProposerTest.cs
Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
Libplanet.Net.Tests/Consensus/ConsensusReactorTest.cs
Libplanet.Net.Tests/Consensus/Context/ContextNonProposerTest.cs
Libplanet.Net.Tests/Consensus/Context/ContextProposerTest.cs
Libplanet.Net.Tests/Consensus/Context/ContextProposerValidRoundTest.cs
Libplanet.Net.Tests/Consensus/Context/ContextTest.cs

This fixes the flakiness of the `ConsensusContext` test. 
- The flakiness occurred when the asynchronous `Context` starts and receives messages before any `EventHandler` is attached and catching.
- Some of the PBFT timeout tests run long.
- Expose timeout parameters from `Context` and `ConsensusContext` and set 1 second for every timeout test.
- Remove unnecessary `NetMQConfiguration` collection from the test.
- `HandleMessageFromHigherHeight` covers two cases. separated as `NewHeightDelay`.
- Removed two duplicated WaitHandle in `HandleMessageFromHigherHeight` which blocks the test.
- Simplified `UseLastCommitCacheIfHeightContextIsEmpty`.
- Shortened `StartAsync`'s PropagationDelay that triggers timeout in the CI test.
https://github.com/planetarium/libplanet/pull/2383 - This change …

Fix flakiness in PBFT `ConsensusContext` test

---

Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
Libplanet.Tests/Blocks/BlockCommitExtensionsTest.cs
Libplanet.Tests/Blocks/BlockCommitTest.cs
Libplanet.Tests/Consensus/VoteTest.cs
Libplanet.Tests/Store/StoreTest.cs
Libplanet/Consensus/Vote.cs

Prevents creating a `Vote` object with an invalid signature through "normal" operation.
Several tests are removed for now. As evidence collection is currently not under consideration, malformed messages are not allowed to be interpreted. Once structural validity of objects, all the way up to `Block<T>`, is enforced, we need a mechanism to handle "undecipherable" messages. This is currently not an issue at this testing phase as we are more concerned about correct behaviors among honest nodes.

Moved vote signature validity check to constructor

---

Libplanet.Net.Tests/Consensus/Context/ContextNonProposerTest.cs
Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
Libplanet.Net.Tests/Messages/MessageTest.cs
Libplanet.Net.Tests/TestUtils.cs
Libplanet.Net/Messages/ConsensusCommit.cs
Libplanet.Net/Messages/ConsensusVote.cs

There is a case in which a forged vote can be created with an arbitrary `VoteFlag` for `ConsensusVote/Commit` (e.g., `VoteFlag.PreVote` + `ConsensusCommit`.) These could lead to an unexpected state change of `Context<T>`.
The current `GetVotes()` and `GetCommits()` behaviour could count different `VoteFlag`. For example, If a `ConsensusVote` with a vote contains `VoteFlag.PreCommit` can be counted as a PreVote message.
https://github.com/planetarium/libplanet/blob/b580d379a2f092a9054504990e2b0812194144fc/Libplanet.Net/Consensus/MessageLog.cs#L52-L80
The methods are used in state change condition methods, `HasTwoThirdsPreVote()` and `HasTwoThirdsPreCommit()`, which do not also check `VoteFlag`.
https://github.com/planetarium/libplanet/blob/b580d379a2f092a9054504990e2b0812194144fc/Libplanet. …

Unexpected vote created with arbitrary `VoteFlag`

---

Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
Libplanet.Net/Consensus/Context.cs
Libplanet.Tests/Blocks/BlockCommitTest.cs
Libplanet.Tests/Consensus/VoteMetadataTest.cs
Libplanet.Tests/Consensus/VoteTest.cs
Libplanet/Consensus/VoteMetadata.cs
Libplanet/Consensus/VoteSet.cs

~~`Null` and `Unknown` type `Vote`s are no longer allowed to have `BlockHash`.~~
`Null` and `Unknown` type `Vote`s are no longer allowed to have `BlockHash` as `null`.

Added constraint on vote metadata

---

Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
Libplanet.Net.Tests/TestUtils.cs
Libplanet.Net/Consensus/ConsensusContext.cs

The `ConsensusReactor` initializes `ConsensusContext` with `BlockChain.Tip.Index`. This results in the initial height of `ConsensusContext` to same as the current Blockchain tip index (e.g., If the genesis block is the tip of Blockchain, then the initial height would be 0.) However, In the test fixture, the `ConsensusContext` is initialized with `BlockChain.Tip.Index + 1`, which is different from the actual implementation.
https://github.com/planetarium/libplanet/blob/c19e5f71195934fdefa5fee12903650c919bf868/Libplanet.Net/Consensus/ConsensusReactor.cs#L75-L83
https://github.com/planetarium/libplanet/blob/c19e5f71195934fdefa5fee12903650c919bf868/Libplanet.Net/Consensus/ConsensusReactor.cs#L112-L116
https://github.com/planetarium/libplanet/blob/c19e5f71195934fdefa5fee12903650c919bf868/Libpla …

Mismatch test fixture of `ConsensusContext` with actual implementation

---

Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
Libplanet.Net/Consensus/ConsensusContext.cs

The `ConsensusContext.NewHeight()` method was not thread-safe and could be invoked multiple times for the same height. No regression test for this because it's a timing problem and hard to reproduce.

Thread-safe NewHeight method in `ConsensusContext`

---

Libplanet.Explorer.Tests/Queries/TransactionQueryTest.cs
Libplanet.Explorer/Store/LiteDBRichStore.cs
Libplanet.Explorer/Store/MySQLRichStore.cs
Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
Libplanet.Net/Consensus/ConsensusContext.cs
Libplanet.Net/Consensus/Context.cs
Libplanet.RocksDBStore/RocksDBStore.cs
Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
Libplanet.Tests/Blocks/BlockCommitExtensionsTest.cs
Libplanet.Tests/Blocks/BlockCommitTest.cs
Libplanet.Tests/Blocks/BlockFixture.cs
Libplanet.Tests/Blocks/BlockMarshalerTest.cs
Libplanet.Tests/Blocks/BlockMetadataTest.cs
Libplanet.Tests/Consensus/VoteSetTest.cs
Libplanet.Tests/Store/ProxyStore.cs
Libplanet.Tests/Store/StoreTest.cs
Libplanet.Tests/Store/StoreTracker.cs
Libplanet.Tests/TestUtils.cs
Libplanet/Blockchain/BlockChain.MineBlock.cs
Libplanet/Blocks/BlockCommit.cs
Libplanet/Blocks/BlockCommitExtensions.cs
Libplanet/Consensus/VoteSet.cs
Libplanet/Store/BaseStore.cs
Libplanet/Store/DefaultStore.cs
Libplanet/Store/IStore.cs
Libplanet/Store/MemoryStore.cs

Notable changes:
- `Vote`'s in `BlockCommit` must be either `Null` or `PreCommit` votes.
- `BlockCommit` is now a `class`.

Added constraints to `BlockCommit`

---

Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
Libplanet.Net.Tests/TestUtils.cs
Libplanet.Net/Consensus/ConsensusContext.cs
Libplanet.Net/Consensus/ConsensusReactor.cs

This resolves #2423
Current `ConsensusContext` set `Height` value from parameter. This is hidden from a constructor, and set value -1 as default. The `Height` value changes only if `NewHeight()` is called or `OnBlockChainTipChanged()`.

Default `ConsensusContext.Height` value

---

Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
Libplanet.Net/Consensus/ConsensusContext.cs

`ClearOldLastCommitCache` removes every `LastCommit` caches if stored count is higher than `maxSize` (`lastCommitClearThreshold`.) This also removes the previous height `LastCommit`.
The problem is, for example, if a node goes down after the `NewHeight()` is called and then restarts, the `LastCommit` for the previous height does not exist in memory and even in the store.
- Removes `LastCommit` cache in FIFO manner and it does not remove all `LastCommit` cache now. It keeps the `maxSize` count of `lastCommit` cache.
- Some chores (Add documentation for method, simplifying test.)

Change removal `LastCommit` cache target

---

Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
Libplanet.Net/Consensus/Context.cs

This PR aligns `Context<T>.VoteSet()` return value with `BlockCommit` specification. `BlockCommit` specification has changed to take `Vote`s only if its `BlockHash` is the same as given `BlockHash`.
https://github.com/planetarium/libplanet/blob/253e997cbf34d3bb7231416826d3f778f477cec5/Libplanet/Blocks/BlockCommit.cs#L85-L96
- `Context<T>.VoteSet()` will now return `PreCommit` votes only if a vote has the same `BlockHash` with the known propose `BlockHash`.

`Context<T>.VoteSet` only returns same `BlockHash` with proposed block

---

Libplanet.RocksDBStore/RocksDBStore.cs
Libplanet.Tests/Store/StoreFixture.cs
Libplanet.Tests/Store/StoreTest.cs

This pull request tries to resolve #2338.
Since https://github.com/planetarium/libplanet/pull/1606, the blockchain node has been forking chain while syncing blocks. So there are too many forked chain ids. And they occur very deep recursion depth (stack overflow).
So this pull request makes `RocksDBStore.IterateIndexes` discover indexes sequentially without recursion. Fetch chain ids and store it as stack, iterate them.

Discover indexes sequentially

---

CHANGES.md
Libplanet.Explorer/GraphTypes/ActionType.cs
Libplanet.Explorer/Libplanet.Explorer.csproj

This pull request resolves #2416 
The execution result seems like below screenshot:
This pull request introduces `ActionType.json` field to represent action's json format.
----
I requested a review for SDK team but please adjust reviewers if it's other's part.

Add `json` field to `ActionType` GraphQL type

---

Libplanet.Net/Consensus/Context.Mutate.cs
Libplanet/Blockchain/BlockChain.cs
Libplanet/Blocks/BlockCommitExtensions.cs

🧹 As `Vote` instances are verified on instantiation, there is no need to double check from outside context.

🧹  Unnecessary code removed

---

CHANGES.md
Libplanet.Node.Tests/UntypedBlockTest.cs
Libplanet.Node.Tests/UntypedTransactionTest.cs
Libplanet.Node/UntypedTransaction.cs
Libplanet.Tests/Tx/TransactionTest.cs
Libplanet.Tests/Tx/TxMetadataTest.cs
Libplanet/Tx/Transaction.cs
Libplanet/Tx/TxMetadata.cs

Resolves #2456.
Removed `IAction` and signature serialization handling from `TxMetadata` to have the process more in line with `Block<T>`.

Streamline `Bencodex` serialization for `Transaction<T>`

---

CHANGES.md
Libplanet.Tests/Blocks/BlockMarshalerTest.cs
Libplanet/Blocks/BlockMarshaler.cs

Added new method `UnmarshalBlockHash()` which is unmarshaling the `BlockHash` from `Block<T>`, without unmarshaling the whole `Block<T>` or conversion. 
Note that this `BlockHash` should not be fully trusted and should validate `Block<T>` before being used in action.[^1]
[^1]: For instance, using `BlockHash` as a cross-reference with marshaled `Block<T>`, and later doing `Block<T>` unmarshaling 
lazy. If the `BlockHash` of `Block<T>` is different with actual `Block<T>` hash, then unmarshaling results fail. See `PreEvaluationBlockHeader`.

Add `BlockHash` unmarshaler from `Block`

---

Libplanet.Net.Tests/Consensus/Context/ContextNonProposerTest.cs
Libplanet.Net.Tests/Consensus/Context/ContextProposerTest.cs
Libplanet.Net.Tests/Consensus/Context/ContextProposerValidRoundTest.cs
Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
Libplanet.Net.Tests/TestUtils.cs
Libplanet.Net/Consensus/ConsensusContext.cs
Libplanet.Net/Consensus/Context.Mutate.cs
Libplanet.Net/Consensus/Context.cs

This mainly deals with removing custom `Context` initial state setup.
As `Context` is a rather complex structure in and of itself, it is **extremely hard** to know all the side-effects of simply setting its round and step to a desired value. Under normal operations, any state of a non-zero round and a step implies either that particular step has been reached by multiple iterations of timeouts and/or failure to form a consensus on a network where numerous messages have been received (even if the progression is made by purely timeouts, **there will be messages received** from the node itself, meaning it is never a clean slate).
This results in test codes not being clear as to whether tested methods are in fact being tested under right circumstances.

Test cleanup

---

Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
Libplanet.Net.Tests/TestUtils.cs
Libplanet.Net/Consensus/ConsensusContext.cs
Libplanet.Net/Consensus/Context.cs

Saving `LastCommit` while disposing `Context` should cover program termination case.
```mermaid
graph TD
A[Consensus Committed]
B[Consensus Valid]
C[Consensus Invalid]
D[Transit to EndCommit]
F[Program termination]
G[NewHeight called]
H[Context.Dispose]
I[Save LastCommit]
J[Propose]
K[PreVote]
L[PreCommit]
M[LockedValue is null]
N[LockedValue is available]
O[Do not save LastCommit]
P[Propose]
Q[PreVote]
R[PreCommit]
S{BlockCommit Ctor, +2/3?}
T[Exception]
U[Block Synchronization]
A --> D
D --> F
D --> G
F --> H
G --> H
H --> S
B --> J
B --> K
B --> L
J --> M
K --> M
K --> N
L --> N
M --> F
N --> F
S -->|Yes| I
S -->|No| T
T --> O
C --> P
C --> Q
C --> R
P --> M
Q --> M
R --> M
M --> U
N --> U
D --> U
U --> G
A --> U
```

Caching `LastCommit` in `Context` disposing

---

Libplanet.Net.Tests/Consensus/Context/ContextNonProposerTest.cs
Libplanet.Net/Consensus/Context.Mutate.cs
Libplanet.Net/Consensus/Context.cs
Libplanet.Net/Consensus/MessageLog.cs

Not the final spec, but implements few changes:
- As it stands, `MessageLog` is context agnostic (this might have to change later). Just as `GetPreVotes()` and `GetPreCommits()` return all stored prevotes and precommits for `Context` to parse, `GetPropose()` has been changed to `GetProposes()` to let `Context` decided on which one to use.
- One third vote counting logic has been changed.
- As `Round` is fixed for `Context.ProcessGenericUponRules()`, `GetPropose(Round)` is called only once at the beginning.

Fix `MessageLog.CountVotes(Round)` logic

---

.circleci/config.yml
Libplanet.Tests/Action/Sys/MintTest.cs
Libplanet.Tests/Action/Sys/TransferTest.cs

The original target was to exclude all test that makes tests flaky,
but i've narrowed down the target to excluding tests that generates distinguishable error messages.
Detailed history is like below comment ([link](https://github.com/planetarium/libplanet/pull/2386#issuecomment-1288424280))

Exclude problematic tests

---

CHANGES.md
Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
Libplanet.Net.Tests/Consensus/Context/ContextProposerValidRoundTest.cs
Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
Libplanet.Net.Tests/Consensus/GossipTest.cs
Libplanet.Net.Tests/Consensus/MessageCacheTest.cs
Libplanet.Net.Tests/Consensus/ProposalMetaDataTest.cs
Libplanet.Net.Tests/Consensus/ProposalTest.cs
Libplanet.Net.Tests/Messages/MessageTest.cs
Libplanet.Net.Tests/TestUtils.cs
Libplanet.Net/Consensus/Context.Mutate.cs
Libplanet.Net/Consensus/Context.cs
Libplanet.Net/Consensus/Proposal.cs
Libplanet.Net/Consensus/ProposalMetaData.cs
Libplanet.Net/Messages/ConsensusProposeMsg.cs

This PR introduces the new classes, `Proposal` and `ProposalMetaData`. These are for replacing sending raw `ConsensusProposeMsg` without a signature of its propose.
The `Proposal` is a signable class that contains the proposal information of consensus in a height and a round. The previous method, sending a raw proposal in `ConsensusProposeMsg`, can be manipulated easily by replacing the payload of its message. 
By adding a signature to the proposal, the attacker cannot manipulate the proposal until the attacker has no access to the target victim's private key.

Add signable consensus Proposal

---

Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
Libplanet.Net.Tests/Messages/MessageTest.cs
Libplanet.Net.Tests/TestUtils.cs
Libplanet.Net/Consensus/Context.Mutate.cs
Libplanet.Net/Messages/ConsensusProposeMsg.cs
Libplanet.Tests/Consensus/ProposalMetaDataTest.cs
Libplanet.Tests/Consensus/ProposalTest.cs
Libplanet/Consensus/Proposal.cs
Libplanet/Consensus/ProposalMetaData.cs

Changes:
- `Proposal` and `ProposalMetadata` moved from `Libplanet.Net.Consensus` to `Libplanet.Consensus`
- Removed `Timestamp` from `Proposal`.
- Fixed `GetHashCode()`

♻️ `Proposal` and `ProposalMetadata`

---

Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
Libplanet.Net.Tests/Messages/MessageTest.cs
Libplanet.Net.Tests/TestUtils.cs
Libplanet.Net/Consensus/Context.Async.cs
Libplanet.Net/Consensus/Context.Mutate.cs
Libplanet.Net/Messages/ConsensusPreCommitMsg.cs
Libplanet.Net/Messages/ConsensusPreVoteMsg.cs
Libplanet.Tests/Consensus/ProposalMetaDataTest.cs
Libplanet.Tests/Consensus/ProposalTest.cs
Libplanet/Consensus/ProposalMetaData.cs

Also removing `Timestamp` was a mistake in #2477. 😅
Otherwise, pushed `MarshaledBlock` further back in parameter ordering as it is a payload.

♻️ Minor fixes

---

Libplanet.Net/Consensus/ConsensusContext.cs
Libplanet.Net/Consensus/Context.cs

The `BlockCommit` has the validation of whether +2/3 votes exist. However, while in saving a `BlockCommit` in `Context.Dispose()`, it was trying to save `BlockCommit` even the `CommittedRound` does not exist.[^1]
not null `lockedValue` cases have no +2/3 commit cases.[^2] Due to this, `BlockCommit` constructor threw an exception which causes the `NewHeight` not to work properly.
[^1]: `CommittedRound` indicates the `PreCommit` has collected +2/3 commits.
[^2]: e.g., In step of `PreCommit` where round is not committed due to vote has not collected +2/3 yet.

Uncaught exception in `ConsensusContext.NewHeight()`

---

Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
Libplanet.Net.Tests/Consensus/ConsensusReactorTest.cs
Libplanet.Net/Consensus/ConsensusReactor.cs
Libplanet.Net/Consensus/Gossip.cs

There is a case where a `Gossip` can be initialized with an empty peer table if the peer is the first peer in the seed node.
The `Gossip` protocol starts with the `CheckValidatorsLiveness` task, which is for checking whether other nodes are alive. This task uses peer table `Gossip._table` to dial up and check liveness, however, this table was checked and updated only once before the task. 
If the task failed to check liveness due to an empty peer table, then the `CheckValidatorsLiveness` is trying to check liveness against the empty peer table indefinitely.
This PR tries to address the problem by:
- Updating a peer table in `CheckValidatorsLiveness()` for every retrying
- Add a new regular task for updating the peer table of `Gossip` from the seed node.
- Moved `CheckValidatorsLiveness()` …

Possible empty peer table of `Gossip`

---

CHANGES.md
Libplanet.RocksDBStore/RocksDBStore.cs
Libplanet.Tests/Store/StoreFixture.cs
Libplanet.Tests/Store/StoreTest.cs

This backports <https://github.com/planetarium/libplanet/pull/2379> and releases it as 0.43.2.
See also:
- https://github.com/planetarium/libplanet/issues/2338
- https://github.com/planetarium/libplanet/pull/2379

Backport #2379 & release 0.43.2

---

Docs/theme/styles/main.css

Presumably someone with more CSS knowledge can fix this more properly, but in any case, sloppy or not, this makes `<see langword>` tags render more like `<code>` tags in documentation. 😶

Changed `langword` tag rendering

---

Libplanet.Net.Tests/Consensus/Context/ContextNonProposerTest.cs
Libplanet.Net.Tests/Consensus/Context/ContextProposerTest.cs
Libplanet.Net.Tests/Consensus/Context/ContextProposerValidRoundTest.cs
Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
Libplanet.Net.Tests/TestUtils.cs

Generally to streamline testing. Whether a `Context` has sent a message is more of `Context`'s concern. It's responsibility stops at whether it has called the `BroadcastMessage()` method. We should try to minimize test's dependency on outside "fixture"'s behavior.

♻️ Use `Context.MessageBroadcasted` for tests

---

Libplanet.Net.Tests/Consensus/Context/MessageLogTest.cs
Libplanet.Net/Consensus/Context.Mutate.cs
Libplanet.Net/Consensus/Context.cs
Libplanet.Net/Consensus/MessageLog.cs
Libplanet/Consensus/ProposerSelector.cs

Related to #2473.
Migration of entire `MessageLog` related logic to `MessageLog` from `Context` complete. This should make `MessageLog` only to be in a "valid state" in relation to `Context` (unless there is some lapse in logic somewhere).
Didn't feel like `throw`ing `Exception`s only for the sake of debugging **with stack trace** as opposed to debugging with output logs was worth it, so I've made `MessageLog` exception free again with `bool` returns. 🙄
Also `ProposerSelector` `static` `class` has been added, kinda just stuck it in `Libplanet.Consensus` `namespace`, as I'm still not sure who or what should be responsible for proposer selection logic. 😐

Refactor `MessageLog`

---

Libplanet.Net/Consensus/ConsensusContext.cs

`ConsensusContext<T>.Dispose()` does not unsubscribe `BlockChain.TipChanged` event during the disposing. `NewHeight()` can be called without `ConsensusContext<T>`, this leads to an unexpected `Context<T>` that can be created by tip changes.

Unsubscribe tip event in `ConsensusContext.Dispose()`

---

Libplanet.Net/Consensus/ConsensusContext.cs
Libplanet.Net/Consensus/Context.cs

This PR adds the additional locks for preventing collision in `Dictionary<long, Context<T>>`.

Collision between indexing and creating in `Dictionary<long, Context<T>>`

---

CHANGES.md
Libplanet.Net.Tests/Transports/TransportTest.cs
Libplanet.Net/Transports/NetMQTransport.cs

This PR fixes freezing on `NetMQTransport.SendMessageAsync()`. (had been reported as #2424)

Fix hangs on .SendMessageAsync() & Release v0.43.3

---

Libplanet.Net.Tests/SwarmTest.Fixtures.cs
Libplanet.Net.Tests/SwarmTest.cs
Libplanet.Net/Consensus/ConsensusReactor.cs
Libplanet.Net/Swarm.cs

This PR resolves a possible problematic initialization path of `ConsensusReactor` that is `null` when the `consensusOption` is not given.
https://github.com/planetarium/libplanet/blob/845b423f35c477060227866f16eefd676997bf31/Libplanet.Net/Swarm.cs#L129-L157

Run `ConsensusReactor` if `consensusOption` is given

---

Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
Libplanet.Net.Tests/Consensus/Context/ContextProposerTest.cs
Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
Libplanet.Net/Consensus/ConsensusContext.cs
Libplanet.Net/Consensus/Context.Mutate.cs
Libplanet.Net/Consensus/Context.cs

Saving LastCommit in `Context<T>.Dispose()` was hard to debug. So the LastCommit saving point is moved from `Context<T>.Dispose()` to `Commit`.

Move `LastCommit` saving to `Commit`

---

CHANGES.md
Libplanet.Tests/Blockchain/BlockChainTest.cs
Libplanet/Blockchain/BlockChain.cs
Libplanet/Blockchain/BlockChainStates.cs

This PR aims to extract `ActionEvaluator<T>` creation, from `BlockChain<T>` constructor to outside. to achieve that, we need to solve the dependency chain as below.
1. `ActionEvaluator<T>` depends `BlockChain<T>` as `IBlockChainStates<T>`.
2. To perform as `IBlockChainStates<T>`, `BlockChain<T>` depends `IStore`, `IStateStore`, and itself. (due to state completion).
In other words, if we can implement `IBlockChainState<T>` without the whole `BlockChain<T>`, extracting `ActionEvaluator<T>` creation from `BlockChain<T>` constructor seems possible. 
* At first, I introduced a new `BlockChainStates<T>` implementing `IBlockChainStates<T>`, instead of `BlockChain<T>`.
* Moved `GetBlances()`, `GetStates()` and `GetTotalSupply()` from `BlockChain<T>` to `BlockChainStates<T>`.
* I think that we …

Inject ActionEvaluator and BlockChainStates explicitly

---

CHANGES.md
Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
Libplanet.Tests/Blockchain/BlockChainTest.cs
Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs
Libplanet/Blockchain/BlockChain.MineBlock.cs

Tried removing policy controlled parameters from `MineBlock()` as these aren't really being used. As far as I know, even [Lib9c] and [9c-headless] aren't affected by this.
[lib9c]: https://github.com/planetarium/lib9c
[9c-headless]: https://github.com/planetarium/NineChronicles.Headless

Removed policy controlled parameters from `MineBlock`

---

Libplanet.Tests/TestUtils.cs

`Zip` method has different overloads in .NET Framework and .NET Core.

chore: fix build failure in linux mono  [skip changelog]

---

Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextProposerTest.cs
Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
Libplanet.Net.Tests/Consensus/Context/ContextNonProposerTest.cs
Libplanet.Net.Tests/Consensus/Context/ContextProposerTest.cs
Libplanet.Net.Tests/Consensus/Context/ContextProposerValidRoundTest.cs
Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
Libplanet.Net.Tests/TestUtils.cs

Two points.
- Unless necessary, when testing `Context` and/or `ConsensusContext`, there should be no need to access underlying fixtures.
- `ValidatorSet` should be controlled by `BlockPolicy<T>`. Providing additional `ValidatorSet` creates an internally inconsistent structure.

Refactor test fixture

---

Libplanet.Net/Transports/NetMQTransport.cs

(I intended to limit the amount of #2521 since it's a hotfix. 😓 , so this PR would be merged into `main` after #2521 and 0.43.3 release)
This PR is the following work of #2521. it moves checks for timeout and firing codes, from `ProcessRequest()` to `SendMessageAsync()`.
Although the semantic has changed depending on whether or not to put the time to stay in the request queue(`_requests`) in the timeout, I was worried about whether it would actually be meaningful to put this semantic, so I omitted changelog now. but feel free to comment if you think it is necessary.

Move timeout related codes to `SendMessageAync()`

---

.circleci/config.yml
Libplanet.Net.Tests/Transports/TransportTest.cs
Libplanet.Node.Tests/SwarmConfigTest.cs
Libplanet.Tests/Action/ActionEvaluatorTest.cs
Libplanet.Tests/Action/Sys/MintTest.cs
Libplanet.Tests/Action/Sys/TransferTest.cs
Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
Libplanet.Tests/Blockchain/BlockChainTest.Internals.cs
Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
Libplanet.Tests/Blockchain/BlockChainTest.cs
Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs
Libplanet.Tests/Blockchain/Policies/StagePolicyTest.cs
Libplanet.Tests/Blockchain/Policies/VolatileStagePolicyTest.cs
Libplanet.Tests/Blockchain/Renderers/AnonymousActionRendererTest.cs
Libplanet.Tests/Blockchain/Renderers/AnonymousRendererTest.cs
Libplanet.Tests/Blockchain/Renderers/DelayedActionRendererTest.cs
Libplanet.Tests/Blockchain/Renderers/DelayedRendererTest.cs
Libplanet.Tests/Blockchain/Renderers/LoggedActionRendererTest.cs
Libplanet.Tests/Blockchain/Renderers/NonblockRendererTest.cs
Libplanet.Tests/Blocks/BlockContentTest.cs
Libplanet.Tests/Blocks/BlockMetadataTest.cs
Libplanet.Tests/Blocks/BlockTest.cs
Libplanet.Tests/Blocks/PreEvaluationBlockTest.cs
Libplanet.Tests/Store/BlockSetTest.cs
Libplanet.Tests/Store/DefaultStoreTest.cs
Libplanet.Tests/Store/StoreTest.cs
Libplanet.Tests/TestUtils.cs

- Flaky test methods for unity tests are isolated with `[SkippableFact]` and `[SkippableTheory]`.
- If flaky part is on test class constructor, the whole class is skipped by CI(since there are no fancy way to skip the whole test class on xunit).
- All isolated flaky tests are from signature validation error on block mining.
- Flaky tests that causes timeout are still exist, but they're not identified yet.
1. Find tests that causes timeout
2. Isolate tests that causes timeout
3. Figure out the reason that causes signature validation error and fix it
4. Figure out the reason that causes timeout and fix it

Isolate problematic tests

---

Libplanet.Net.Tests/Messages/NetMQMessageCodecTest.cs
Libplanet.Net.Tests/SwarmTest.cs
Libplanet.Net/Messages/BlocksMsg.cs
Libplanet.Net/Swarm.MessageHandlers.cs
Libplanet.Net/Swarm.cs

In preparation to requiring a `BlockCommit` when appending a PBFT `Block<T>`.

Changed `BlocksMsg` layout

---

Libplanet/Blockchain/BlockChain.cs

Putting `BlockCommit` into the store was out of the write lock of `BlockChain<T>.Append()`.

fix: Move putting `BlockCommit` to lock section

---

Libplanet.Tests/Blockchain/BlockChainTest.cs

This makes sure that the retrieved `BlockCommit` is not a stored `BlockCommit`.

Added test

---

CHANGES.md
Libplanet.Tests/Action/ActionEvaluatorTest.cs
Libplanet.Tests/Action/StaticActionTypeLoaderTest.cs
Libplanet/Action/ActionEvaluator.cs
Libplanet/Action/IActionTypeLoader.cs
Libplanet/Action/PolymorphicAction.cs
Libplanet/Action/StaticActionTypeLoader.cs
Libplanet/Blockchain/Renderers/Debug/ValidatingActionRenderer.cs
Libplanet/Blocks/Block.cs
Libplanet/Blocks/IBlockContent.cs
Libplanet/Blocks/IPreEvaluationBlock.cs
Libplanet/Blocks/PreEvaluationBlock.cs
Libplanet/Tx/ITransaction.cs
Libplanet/Tx/Transaction.cs

(I'll leaving content Korean during drafting, it will be translated later)
1. `Transaction<T>`, `Block<T>`에서 T제거 
2. `ActionEvaluator<T>`의 `EvaluateTxs()`, `EvaluateTxResult()` 등의 메소드를 정리
3. `IActionTypeLoader` & `StaticActionTypeLoader` 추가
4. `PolymorphicAction<T>`에 `StaticActionTypeLoader` 적용
- `Block<T>` 마샬링에서 T 제거
- `Transaction<T>.Create()` 등에서 `UpdatedAddresses` 자동 계산 해주는 부분 제거 후 직접 입력등으로 대체
- 정 안되면 `StaticActionTypeLoader()` 쓰게끔
- `ActionEvalutor<T>`에서 T제거
- Updated Addresses 관련
- `StateCompleter<T>` 제거 (이건 @planetarium/libplanet 에서 별도 진행 가능할 듯)
- non-`PolymorphicAction` 지원 여부 정하기
- 지원해야 한다면,  `IActionTypeLoader`에 단일 액션을 위한 인터페이스 추가 해야 함

Introduce IActionTypeLoader

---

CHANGES.md
Libplanet.Explorer/ExplorerStartup.cs

In our Planetarium Dev Discord Server, we decided to use the `/graphql/explorer` endpoint as its de-facto standard of `LibplanetExplorerSchema`'s endpoint.
This pull request makes `Libplanet.Explorer.Executable` also provide the `/graphql/explorer` endpoint, with `/graphql` endpoint for backward compatibility. I guess it should obsolete `/graphql` after applying it to [libplanet-explorer-frontend].
About the changelog, I'm not sure whether it should also be recorded or not.
[libplanet-explorer-frontend]: https://github.com/planetarium/libplanet-explorer-frontend
- https://github.com/planetarium/NineChronicles.Headless/pull/1706
- https://github.com/planetarium/NineChronicles.Headless/discussions/1690
- https://github.com/planetarium/planet-node/pull/42

Provide explorer in also `/graphql/explorer`

---

CHANGES.md
Libplanet.Explorer.Tests/Queries/TransactionQueryTest.cs
Libplanet.Net.Tests/SwarmTest.Preload.cs
Libplanet.Net.Tests/SwarmTest.cs
Libplanet.Tests/Action/ActionEvaluatorTest.cs
Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
Libplanet.Tests/Blockchain/BlockChainTest.cs
Libplanet.Tests/Blocks/PreEvaluationBlockTest.cs
Libplanet/Blockchain/BlockChain.cs

Resolves #2541
This PR adds validation of `BlockCommit` in `BlockChain<T>.Append()`.
There are some cases we should consider: 
- `PreloadAfterReorg` is failing but there will be no reorganization in PBFT, so skipped the test (Reorganization code should be removed.)
- When the validator set is dynamically changing, in my opinion, we should revisit this and think about how would block synchronization be done.

Validate `BlockCommit` while in `BlockChain<T>.Append()`

---

CHANGES.md
Libplanet.Explorer.Executable/Program.cs

This pull request introduces a new command, `schema`, on the `Libplanet.Explorer.Executable` project.
You can run it like the below:
```
$ dotnet run -- schema > schema.graphql
```
The `schema.graphql` file is on the gist link. ([link](https://gist.github.com/moreal/5ed64b5bcd1c1691bd1ad3ef3aa361fc)).
I expect this command can be used to get the explorer's GraphQL schema file of the specific Libplanet release.
Since this pull request, the root command (in C# code, `Program.Run()` method) became treated as a subcommand called `serve`. So you should run explorer like `dotnet run -- serve [OPTIONS]`. But it breaks backward compatibility. So it still supports root command by forwarding root command to `serve` subcommand.
Maybe this command will be introduced in *0.45.0* release, and I expect …

Provide `schema` command to get explorer schema

---

Libplanet.Net/Swarm.cs
Libplanet.Net/Transports/NetMQTransport.cs

Due to launching `NineChronicles`, we are logged all about things. But these days, it causes many problems like AWS price and delays in querying. And `TimeoutException`, which wrapped `CommunicationException`, is too noisy more than their impact.
So, I make this PR to ignore `TimeoutException` from `NetMQTransport.SendMessageAsync()`.

Ignore NetMQTransport's TimeoutException

---

CHANGES.md
Libplanet/Crypto/DefaultCryptoBackend.cs
Libplanet/Libplanet.csproj

As the title suggests, this PR bumps BouncyCastle to 2.0.0 (I think it's mainly a maintained version).

Bump BouncyCastle

---

CHANGES.md
Libplanet.Explorer.Executable/Program.cs
Libplanet.Explorer.Tests/GraphQLTestUtils.cs
Libplanet.Explorer.Tests/GraphTypes/ByteStringTypeTest.cs
Libplanet.Explorer.Tests/Queries/TransactionQueryTest.cs
Libplanet.Explorer/ExplorerStartup.cs
Libplanet.Explorer/GraphTypes/ActionType.cs
Libplanet.Explorer/GraphTypes/AddressType.cs
Libplanet.Explorer/GraphTypes/BencodexValueType.cs
Libplanet.Explorer/GraphTypes/BlockPolicyType.cs
Libplanet.Explorer/GraphTypes/BlockType.cs
Libplanet.Explorer/GraphTypes/ByteStringType.cs
Libplanet.Explorer/GraphTypes/CurrencyType.cs
Libplanet.Explorer/GraphTypes/FungibleAssetValueType.cs
Libplanet.Explorer/GraphTypes/NodeStateType.cs
Libplanet.Explorer/GraphTypes/PublicKeyType.cs
Libplanet.Explorer/GraphTypes/TransactionType.cs
Libplanet.Explorer/GraphTypes/TxResultType.cs
Libplanet.Explorer/Libplanet.Explorer.csproj
Libplanet.Explorer/Mutations/TransactionMutation.cs
Libplanet.Explorer/Queries/BlockQuery.cs
Libplanet.Explorer/Queries/ExplorerQuery.cs
Libplanet.Explorer/Queries/StateQuery.cs
Libplanet.Explorer/Queries/TransactionQuery.cs
Libplanet.Explorer/Schemas/ConfigureLibplanetExplorerSchema.cs
Libplanet.Explorer/Schemas/GraphQLBuilderExtensions.cs
Libplanet.Explorer/Schemas/LibplanetExplorerSchema.cs

Here's the set of changed dependencies:
-  *GraphQL*: 4.7.1 → 7.1.1
-  *GraphQL.Server.Authorization.AspNetCore*: 5.1.1 → 7.1.1
-  *GraphQL.Server.Transports.AspNetCore*: 5.1.1 → 7.1.1
-  *GraphQL.Server.Ui.Playground*: 5.1.1 → 7.1.1
-  *GraphQL.SystemTextJson*: 4.7.1 → 7.1.1
-  *GraphQL.Server.Transports.AspNetCore.SystemTextJson*: 5.1.1 → removed
Also check out the below official migration guide:
- 4.x → 5.x
- [Changes caused by GraphQL-Parser v8](https://graphql-dotnet.github.io/docs/migrations/migration5/#15-changes-caused-by-graphql-parser-v8)
- [`AddGraphQL` now accepts a configuration delegate instead of returning `IGraphQLBuilder`](https://graphql-dotnet.github.io/docs/migrations/migration5/#6-code-classlanguage-textaddgraphqlcode-now-accepts-a-configuration-delegate-instead-of-ret …

Upgrade GraphQL-related dependencies

---

CHANGES.md
Libplanet.Tools/Program.cs
Libplanet.Tools/README.md

This patch lets `planet` utilize [Cocona's command-line completion support][1] for bash and zsh.
[1]: https://github.com/mayuki/Cocona#shell-command-line-completion

Command-line completion support for planet CLI

---

CHANGES.md
Libplanet/Blockchain/Policies/VolatileStagePolicy.cs

As the title suggests, it enhances `VolatilePolicy`'s performance through two approaches.
1. Change `VolatilePolicy._ignored`'s implementation, from `ConcurrentBag<T>` to `HashSet<T>`.
- On my machine[^1], `ConcurrentBag<T>.Contains` was 20x slower than plain `HashSet<T>`'s.
- I've considered `ConccurentDictionary<K, V>` as an alternative, but `HashSet<T>` might be okay because `VolatilePolicy`already assumes rw lock hardly[^2].
2. Adjusts lock-scopes of `.Iterate()` to avoid unintended blocking.
Also, this PR doesn't suggest a long-term solution for `._ignored` at this moment, but we need to revisit it again in the near future because there is still no consideration about its expiration. 😢 
[^1]: i9-12900k, 32GB RAM, .NET 6.0.400, arch linux
[^2]: But also I believe that it can be the …

Improve performance of `VolatileStagePolicy.Iterate()` and `.GetNextTxNonce()` & Release 0.44.2

---

CHANGES.md
Libplanet/Blockchain/BlockChain.cs

Issues:
- We don't really have any concrete `class` that implements both `IStore` and `IStateStore`.
- In any case, if one wishes to use the same object for both storing blocks and states, it shouldn't be up to `BlockChain<T>` to decide. The caller of `BlockChain<T>` should be responsible by passing the same object as both `IStore` and `IStateStore`.
- If we want to support the current behavior (or something similar to it), then we should have a combined `interface` such as `ISuperStore : IStore, IStateStore` to make the intention more pronounced.

Removed automatic internal reassignment of `Store` to `StateStore`

---

.circleci/config.yml

Temporarily exclude `linux-unity-test` on workflow, due to the frequent error on `xunit-unity-runner`.
This change can be reverted on the condition the problem been solved.

Exclude linux-unity-test on workflow

---

Libplanet.Net.Tests/SwarmTest.cs
Libplanet.Net/Consensus/ConsensusContext.cs
Libplanet.Net/Consensus/ConsensusReactor.cs
Libplanet.Net/Consensus/Context.Async.cs
Libplanet.Net/Consensus/MessageLog.cs
Libplanet.Net/Swarm.cs

This PR allows network nodes to come online sequentially, at least under the assumption all nodes' `BlockChain<T>` are synced[^1].
[^1]: If not, there are cases where a previously committed `Block<T>` can be invalidated. Consider the following scenario. Let there be a single node with the highest tip index (for whatever reason, before shutting down the network, other nodes might have not been able to sync and/or commit the latest `Block<T>`). If such node does not come online before 2/3+ of the network and reach the consensus, effectively, the said node's tip will be ignored.

Context bootstrapping

---

CHANGES.md
Libplanet/Blockchain/BlockChain.Swap.cs

Either this or if we really want to use `Swap()` on any chain for whatever reason, then canonicity of the current chain should be checked before changing the canonical chain stored in `IStore`. 🙄

Made `Swap()` no longer allowed on non canonical chains

---

Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
Libplanet.Net/Consensus/ConsensusContext.cs

Several points:
- Ultimately, the `Exception` thrown is not logged anywhere, but swallowed.
- From the looks of it, and how it is implemented, `ConsensusContext<T>.HandleMessage()` is **expected** to **deal** with even `ConsensusMsg`es with lower heights, even if dealing means discarding the message. If that is the case, than simple logging would suffice.
- We could try to filter messages at a higher level by making `ConsensusReactor<T>.ProcessMessage()` compare the message height with `ConsensusContext<T>`'s height **and** throw an `Exception` from `ConsensusContext<T>.HandleMessage()` **and** catch and log the thrown exception at `ConsensusReactor<T>.ProcessMessage()`, I think this would be an overkill. 😑
- Throwing an `Exception` is costly. 🙄

`ConsensusContext<T>.HandleMessage()` return type as `bool`

---

.github/workflows/benchmarks-main.yml

I thought `./cache` already existed but not...

Fix benchmark script error

---

CHANGES.md
Libplanet.Net/Protocols/KademliaProtocol.cs
Libplanet.Net/Swarm.MessageHandlers.cs
Libplanet.Net/Swarm.cs
Libplanet.Net/Transports/NetMQTransport.cs
Libplanet.Net/TxCompletion.cs

This PR adjusts codes on `NetMQTransport`, `Swarm<T>`, and `TxCompletion<T>` to improve network throughput and latency.
- `TxCompletion<T>` now becomes to wait and buffer per node, for new requests.
- `NetMQTransport` now becomes to skip intermediates `Task` creations when not unnecessary.
- `NetMQTransport.ReplyMessageAsync()` now becomes to return `Task.CompletedTask` immediately after queuing.
- router socket in `NetMQTransport` now became to perform batch processing for `ReceiveMessage()` handler.
- `.ProcessRuntime()` now become to go ahead for each `.ProcessRequest()` instead of `await`.

Improve network performance & Release 0.44.4

---

Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
Libplanet.Net/Consensus/ConsensusContext.cs

Due to asynchronous nature between `BlockChain<T>` and `ConsensusContext`, `ConsensusContext.Height` cannot be guaranteed to be `BlockChain<T>.Tip.Index` + 1. Although seemingly a good practice for being defensive, this makes it harder to keep `ConsensusContext`'s state consistent as state transitions are generally triggered by an `event` while trying to rely on independently and continuously changing state of the `BlockChain<T>` that `ConsensusContext` relies on. In any case, `NewHeight()` is too dangerous of a method to be `public`.

Changed `NewHeight()` behavior

---

Libplanet.Net/Consensus/Context.Mutate.cs

This is a possible culprit for a node not being able to collect further votes.

Changed to allow commit failure due to desync between `Context<T>` and `BlockChain<T>`

---

Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
Libplanet.Net/Consensus/ConsensusContext.Event.cs
Libplanet.Net/Consensus/ConsensusContext.cs
Libplanet.Net/Consensus/ConsensusReactor.cs
Libplanet.Net/Consensus/ConsensusReactorOption.cs
Libplanet.Net/Consensus/Context.Async.cs
Libplanet.Net/Consensus/Context.Mutate.cs

♻️ Removed `ConsensusContext<T>.Commit()`

---

CHANGES.md
Libplanet.Tests/Action/ActionEvaluatorTest.cs
Libplanet.Tests/Blockchain/BlockChainTest.cs
Libplanet/Action/ActionEvaluator.cs
Libplanet/Action/IActionTypeLoader.cs
Libplanet/Action/PolicyBlockActionGetter.cs
Libplanet/Action/StaticActionTypeLoader.cs
Libplanet/Blockchain/BlockChain.cs
Libplanet/Blocks/PreEvaluationBlock.cs

This pull request makes `ActionEvaluator` receive `PolicyBlockActionGetter policyBlockActionGetter` instead of `IAction? policyBlockAction` and use loaded block action from the `policyBlockActionGetter`. Also, this pull request introduces `IActionTypeLoader.LoadAllActionTypes()`, a method to load all available action types by the block header. Its difference between itself and `IActionTypeLoader.Load()` method, is that it includes all actions even if it doesn't have `ActionTypeAttribute`. In other words, it includes non-polymorphic-actions too.
- @longfin : the proposer and designer of the `IActionTypeLoader` design. You can see the usage in https://github.com/planetarium/NineChronicles.Headless/pull/1774.

Load block action from delegator

---

CHANGES.md
Libplanet.Net/Swarm.BlockSync.cs
Libplanet.Tests/Blockchain/BlockChainTest.cs
Libplanet/Blockchain/BlockChain.cs

Closes #2650.
We probably need a better fix. 😥
The problem was during preloading, a large number of `BlockCommit`s are downloaded and stored in `IStore` temporarily. This was causing trouble as iterating over all stored `BlockCommit`s was taking way too long. This changes the behavior of `BlockChain<T>.Append()` so that only the `BlockCommit` that the `BlockChain<T>` **immediately knows** that is no longer required is removed instead of iterating over all `BlockCommit`s. However, this leaves a potential loophole where `IStore` can be populated with unnecessary `BlockCommit`s.

🔧 Faster `BlockCommit` cache management

---

CHANGES.md
Libplanet.Net/Protocols/KBucketDictionary.cs
Libplanet.Net/Protocols/KademliaProtocol.cs
Libplanet.Net/Swarm.MessageHandlers.cs
Libplanet.Net/Swarm.cs
Libplanet.Net/Transports/NetMQTransport.cs

This PR fixes internal codes using NetMQ in `NetMQTransport` to avoid blocking and improve latency (like #2631 ).
- Add `.CofigureAwait(false)` to `await`s, on NetMQ context-free methods. (e.g., `PingAsync()`).
- Increased I/O thread of NetMQ from 1 to 3.
- Increased `NetMQRuntime` itself (not its task), from 1 to `Environment.ProcessorCount`.
- I tried making this value follow `workers`, but it gave an error when there were 200+ runtimes.
- In a regular release it would be nice to remove `workers` and replace it with a constant or add it as another option. 
- `DealerSocket`s creating for `SendMessageAsync()` will have a `DisableTimeWait` option to avoid TCP TIME_WAIT.
Also, it tweaks `KBucketDictionary` a little bit too.
- Loosened the lock in `KBucketDictionary` by introducing …

Improve `NetMQTransport` again

---

.github/workflows/benchmarks-main.yml
.github/workflows/benchmarks-pr.yml
.github/workflows/build.yaml
.github/workflows/check-build.yaml
.github/workflows/main.yml
.github/workflows/push-docker-image.yml
.github/workflows/rebase.yml

While running GitHub Actions jobs, you can see alerts like the below screenshot.
Nodejs 12 became out of support in April 2022 and the GitHub Actions team is planning to migrate all actions to Nodejs 16 environment.
See also https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

ci(gh-actions): update actions used node12

---

CHANGES.md
Libplanet.Benchmarks/Store.cs
Libplanet.Explorer/Store/LiteDBRichStore.cs
Libplanet.Explorer/Store/MySQLRichStore.cs
Libplanet.Tests/Store/ProxyStore.cs
Libplanet.Tests/Store/StoreTest.cs
Libplanet.Tests/Store/StoreTracker.cs
Libplanet/Store/BaseStore.cs
Libplanet/Store/IStore.cs
Libplanet/Store/MemoryStore.cs

See [the discussion](https://github.com/planetarium/libplanet/discussions/2617) for more context.
The naming `GetCanonicalGenesisBlock<T>()` suggests there can be non-canonical genesis `Block<T>`s in `IStore`. This is problematic since this can be interpreted two different ways:
- There can be other genesis `Block<T>`s in `IStore`
- There can be some other chain id with a different genesis `Block<T>` in `IStore`
If it is the former, then there isn't much of a problem , but since the term "canonical" is closely tied to chain ids, I would say it is more likely than not to be interpreted as the latter. The rest of the API for `IStore` allowing there to be a chain id with a different genesis `Block<T>` also seem to suggest that the latter may be intended.
In any case, and thankfully, …

🧹 Removed `IStore.GetCanonicalGenesisBlock<T>()`

---

CHANGES.md
Libplanet.Net/Transports/NetMQTransport.cs
Libplanet/Blockchain/BlockChain.cs
Libplanet/Blockchain/BlockLocator.cs

This PR fixes two points as like below
- Fixed failures related to NetMQ, through `ForceDotNet.Force()` even upon Windows.
- Adjusted read-lock scope of `BlockChain<T>.GetBlockLocator()` method, to improve parallelism of block sync.

Fix NetMQ failures on Windows

---

Libplanet.Net/Swarm.BlockCandidate.cs
Libplanet.Net/Swarm.cs

This pull request just fixes a typo in `Swarm`'s logs, 'dail' → 'dial'.

Fix typo 'dail' → 'dial'

---

Libplanet/Action/ActionEvaluator.cs

While logging in `ActionEvaluator`, the `BlockHeader.PreEvaluationHash` was represented as `System.Collections.Immutable.ImmutableArray`1[System.Byte]`, not a hexadecimal string.
The log in my local environment was like the below text:
```
Evaluating policy block action for block #5674855 System.Collections.Immutable.ImmutableArray`1[System.Byte]
```

Correct logging in `ActionEvaluator`

---

.github/workflows/benchmarks-main.yml

windows didn't have an argument `-f` on `'rm'`

Fix CI - benchmark for windows

---

CHANGES.md
Libplanet/Action/ActionEvaluator.cs
Libplanet/Action/ActionTypeLoaderContext.cs
Libplanet/Action/IActionTypeLoader.cs
Libplanet/Action/IActionTypeLoaderContext.cs
Libplanet/Action/StaticActionTypeLoader.cs

> You can see the below content in `CHANGES.md` too.
-  Replaced `IPreEvaluationBlockHeader`-typed `blockHeader` parameter with
`IActionTypeLoaderContext`-typed `context` parameter in the below methods.
- `IActionTypeLoader.Load()`.
- `IActionTypeLoader.LoadAllActionTypes()`.
-  Added `IActionTypeLoaderContext` interface.

Introduce `IActionTypeLoaderContext`

---

.github/workflows/benchmarks-pr.yml

I think the current threshold of 130% might still be too tight. As it seems to still fluctuate quite a bit and the comparison is only made to the previous result, one lucky run might not give enough window for following PRs.
Some hypothetical napkin math:
- If benchmark time average is around 100 and fluctuates around this average by +-20%, this would give us the range of 80 to 120 to pass the test.
- If we get a lucky result around 80 for once, then based on this previous result, the next PR needs to run its benchmark below 80 * 1.3 = 104. Considering we are running multiple benchmarks, this is really easy to fail, that is, if the fluctuation is around 20%, which would require us to run multiple benchmark actions.
I suggest we relax the criteria for a while to gather more data before …

🔧 Relax benchmark alert threshold to 150%

---

.github/workflows/benchmarks-main.yml
.github/workflows/benchmarks-pr.yml

If any of the operating system fails, then all benchmarks have to be run again. I suppose this could be intended depending on our policy. 🙄

🔧 Try running benchmarks to completion on other os failure

---

CHANGES.md
Libplanet.Net.Tests/SwarmTest.Broadcast.cs
Libplanet.Net/AsyncDelegate.cs
Libplanet.Net/Libplanet.Net.csproj
Libplanet.Net/Protocols/KademliaProtocol.cs
Libplanet.Net/Transports/NetMQTransport.cs
Libplanet.Net/TxCompletion.cs

This PR fixes a bug causing instability in environments with limited available CPU resources (e.g., CI).
it also fixes that `NetMQTransport.ReplyMessageAsync()` hadn't worked properly. [^1]
[^1]: To be honest, I thought that the method would never wait, so I plan to fix the interface in the main, but I couldn't because Gossip, which is for PBFT, relies on that wait.

Fix bugs and stabilize unit test again

---

CHANGES.md
Libplanet.Explorer.Executable/Program.cs
Libplanet.Net.Tests/Messages/MessageValidatorTest.cs
Libplanet.Net.Tests/SwarmTest.AppProtocolVersion.cs
Libplanet.Net.Tests/SwarmTest.Fixtures.cs
Libplanet.Net.Tests/SwarmTest.cs
Libplanet.Net.Tests/Transports/BoundPeerExtensionsTest.cs
Libplanet.Net.Tests/Transports/NetMQTransportTest.cs
Libplanet.Net.Tests/Transports/TransportTest.cs
Libplanet.Net/AppProtocolVersionOptions.cs
Libplanet.Net/Messages/MessageValidator.cs
Libplanet.Net/Swarm.cs
Libplanet.Net/Transports/NetMQTransport.cs
Libplanet.Node/NetworkConfig.cs
Libplanet.Node/NodeConfig.cs

Preparatory work to enable extracting `ITransport` initialization from `Swarm<T>`'s constructor easier.

Introduce `AppProtocolVersionOptions`

---

CHANGES.md
Libplanet.Explorer.Executable/Options.cs
Libplanet.Explorer.Executable/Program.cs
Libplanet.Net.Tests/SwarmTest.Broadcast.cs
Libplanet.Net.Tests/SwarmTest.Fixtures.cs
Libplanet.Net.Tests/SwarmTest.cs
Libplanet.Net.Tests/Transports/NetMQTransportTest.cs
Libplanet.Net/AsyncDelegate.cs
Libplanet.Net/Libplanet.Net.csproj
Libplanet.Net/Protocols/KademliaProtocol.cs
Libplanet.Net/Swarm.cs
Libplanet.Net/Transports/NetMQTransport.cs
Libplanet.Net/TxCompletion.cs

This PR mainly aims to port the changes from #2684. also, it drops `workers` options no longer necessary, from `NetMQ Transport.CreateAsync()`,
And more, I tried a few test stabilizations but failed as a result. In particular, socket errors occur very often on macOS, which will be covered in another PR.

Port/0.45.4 & remove `workers` option for `NetMQTransport`

---

CHANGES.md
Libplanet.Explorer.Executable/Program.cs
Libplanet.Net.Tests/HostOptionsTest.cs
Libplanet.Net.Tests/SwarmTest.Fixtures.cs
Libplanet.Net.Tests/SwarmTest.cs
Libplanet.Net.Tests/Transports/BoundPeerExtensionsTest.cs
Libplanet.Net.Tests/Transports/NetMQTransportTest.cs
Libplanet.Net.Tests/Transports/TransportTest.cs
Libplanet.Net/HostOptions.cs
Libplanet.Net/Swarm.cs
Libplanet.Net/Transports/NetMQTransport.cs
Libplanet.Node.Tests/SwarmConfigTest.cs
Libplanet.Node/InitConfig.cs
Libplanet.Node/NodeConfig.cs

Continuation of #2693.
On a side note, I thought about making `HostOptions` as a plain collection of properties with `{ get; set; }` for each, like `AppProtocolVersionOptions` and `SwarmOptions`, but decided against it. This breaks overall consistency, but I think parsing options should be done at "options level". If anyone disagrees with the design, I can change it back. 🙄

Introduce `HostOptions`

---

CHANGES.md
Libplanet.Net/Transports/NetMQTransport.cs

This PR addresses a logging bug where the count of sockets is going negative value. Before the start, I couldn't find the current socket count-related property or field from NetMQ.
The socket count is incremented when the `GetRequestDealerSocket()` is called. If the `CancellationToken.ThrowIfCancellationRequested()` is thrown, then the socket is not allocated (i.e., `GetRequestDealerSocket()` is not called, the count is not incremented.)
The `DealerSocket` in `GetRequestDealerSocket()` throws `NetMQException` if allocating socket is failed. In this case, the socket is not allocated (socket count remains) and breaks out from `new DealerSocket` and `GetRequestDealerSocket()`.
The socket count is incremented by calling `GetRequestDealerSocket()`. `OperationCanceledException` also can be …

fix/transport: socket count

---

CHANGES.md
Libplanet/Blockchain/Policies/VolatileStagePolicy.cs

Do we really need the default to be 3 hours? 😶

🔧 Reduced tx lifespan from 3 hours to 10 minutes

---

Libplanet.Net.Tests/BoundPeerTest.cs
Libplanet.Net.Tests/Transports/TransportTest.cs
Libplanet.Net/BoundPeer.cs

This pull request makes `BoundPeer` not able to have an invalid hostname. (e.g., `.ninodes.com`, not `some.ninodes.com`).
I'm not sure but I'll request a review from members who looked network part usually according to my memory.

Validate hostname in `BoundPeer` type

---

CHANGES.md
Libplanet.Net.Tests/Transports/NetMQTransportTest.cs
Libplanet.Net/Transports/NetMQTransport.cs

This PR fixes a leakage of `NetMQSocket` on `NetMQTransport.SendMessageAsync()` when it has failed on connecting.
I splitted commits with intention because
- We should back-port this change to 0.45-maintenance after merging with #2708.
- I borrowed 2a194d7 from my other experimental PR(#2714) and perhaps I think the current way of handling is enough. however, there may be better implementations or implementations also need test cases for confirmation.

Fix NetMQSocket leak

---

CHANGES.md
Libplanet.Net.Tests/SwarmTest.Preload.cs
Libplanet.Net.Tests/SwarmTest.cs
Libplanet.Net/Swarm.cs
Libplanet.Tests/Blockchain/BlockChainTest.cs
Libplanet.Tests/Blockchain/BlockLocatorTest.cs
Libplanet/Blockchain/BlockChain.cs
Libplanet/Blockchain/BlockLocator.cs
Libplanet/Store/IStore.cs

Closes #2580, #2581, #2582, and #2583.
The implementation is still subject to change depending on what constraints we decide to impose on `BlockChain<T>` instances and how we want to handle variety of cases arising from constraints, or lack there of. The issue is rather far reaching and not obvious to resolve. See #2585.

♻️ Refactor `BlockLocator`

---

CHANGES.md
Libplanet/KeyStore/Web3KeyStore.cs

This PR adjusts internal codes of `Web3KeyStore`, to remove duplicated prefixes from return values of `.ListFiles()`. ([`Directory.EnumerateFiles()`](https://learn.microsoft.com/en-us/dotnet/api/system.io.directory.enumeratefiles?view=netstandard-2.0#system-io-directory-enumeratefiles(system-string)) returns full name so we don't need to combine return values and `Path`)
I couldn't prepare a regression test case since `System.IO.Path.Combine()` seems to elide duplicated parts automatically. but it didn't work so that on IL2CPP environment.
p.s. thanks for helping debug :) @sonohoshi

Elide duplicated prefix of paths in Web3KeyStore & Release 0.45.5

---

CHANGES.md
Libplanet.Extensions.Cocona.Tests/Commands/MptCommandTest.cs
Libplanet.Extensions.Cocona.Tests/Commands/StatsCommandTest.cs
Libplanet.Extensions.Cocona.Tests/Commands/StoreCommandTest.cs
Libplanet.Extensions.Cocona.Tests/Libplanet.Extensions.Cocona.Tests.csproj
Libplanet.Extensions.Cocona.Tests/Services/TestToolConfigurationService.cs
Libplanet.Extensions.Cocona.Tests/UtilsTest.cs
Libplanet.Extensions.Cocona/Commands/ApvCommand.cs
Libplanet.Extensions.Cocona/Commands/KeyCommand.cs
Libplanet.Extensions.Cocona/Commands/MptCommand.cs
Libplanet.Extensions.Cocona/Commands/StatsCommand.cs
Libplanet.Extensions.Cocona/Commands/StoreCommand.cs
Libplanet.Extensions.Cocona/Commands/TxCommand.cs
Libplanet.Extensions.Cocona/ConsolePasswordReader.cs
Libplanet.Extensions.Cocona/Extensions/ICoconaLiteServiceCollectionExtensions.cs
Libplanet.Extensions.Cocona/Libplanet.Extensions.Cocona.csproj
Libplanet.Extensions.Cocona/PassphraseParameters.cs
Libplanet.Extensions.Cocona/Services/IConfigurationService.cs
Libplanet.Extensions.Cocona/Services/JsonConfigurationService.cs
Libplanet.Extensions.Cocona/Utils.cs
Libplanet.Tools/Libplanet.Tools.csproj
Libplanet.Tools/Program.cs

Made changes on CLI-related projects (*Libplanet.Extensions.Cocona*, *Libplanet.Extensions.Cocona.Tests*, *Libplanet.Tools*):
-  Dropped .NET Standard 2.0 & .NET Core 3.1 targets, and added .NET 6.0 target instead.  (.NET Standard 2.1 remains.)
-  Use [file-scoped namespace declarations][1].
-  Upgraded *SonarAnalyzer.CSharp* to 8.51.0.59060 as [the existing version does not recognize file-scoped namespace declarations.][2]
[1]: https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-10#file-scoped-namespace-declaration
[2]: https://github.com/SonarSource/sonar-dotnet/issues/4731

Use .NET 6 & C# 10 on CLI tools

---

CHANGES.md
Libplanet.Tests/Action/ActionContextTest.cs
Libplanet/Action/AccountStateDeltaImpl.cs
Libplanet/Action/IAccountStateDelta.cs
Libplanet/Action/IAccountStateView.cs
Libplanet/Action/IValidatorSupportStateDelta.cs
Libplanet/Action/ValidatorStateExtensions.cs

`Validator`s dealt only in internal methods, so it had been removed from public interfaces.

Remove Validator related methods from interfaces

---

CHANGES.md
Libplanet.Explorer.Executable/Program.cs
Libplanet/Blockchain/Policies/BlockPolicy.cs
Libplanet/Blockchain/Policies/IBlockPolicy.cs
Libplanet/Blockchain/Policies/NullBlockPolicy.cs

During merging main, unnecessary policy property has been introduced to pbft branch.
So, this have to be removed.

Remove unnecessary policy for PBFT

---

CHANGES.md
Libplanet.Extensions.Cocona.Tests/BlockPolicyParamsTest.cs
Libplanet.Extensions.Cocona.Tests/Commands/MptCommandTest.cs
Libplanet.Extensions.Cocona.Tests/Commands/StoreCommandTest.cs
Libplanet.Extensions.Cocona.Tests/Libplanet.Extensions.Cocona.Tests.csproj
Libplanet.Extensions.Cocona.Tests/UtilsTest.cs
Libplanet.Extensions.Cocona/BlockPolicyParams.cs
Libplanet.Extensions.Cocona/Commands/ApvCommand.cs
Libplanet.Extensions.Cocona/Commands/BlockCommand.cs
Libplanet.Extensions.Cocona/Commands/KeyCommand.cs
Libplanet.Tools/Program.cs
Libplanet/Blockchain/BlockChain.cs

This patch introduces two subcommands to `planet` CLI.
This subcommands takes a Bencodex-serialized block file and then show its contents as a prettified JSON tree.  E.g.:
```bash
curl https://release.nine-chronicles.com/genesis-block-9c-main | planet block analyze -
```
This subcommands creates an empty genesis block and signs it in the specified key.  E.g.:
```bash
planet block generate-genesis KEY-ID ./genesis-block.bin
planet block analyze ./genesis-block.bin
```

New subcommands to CLI: `planet block analyze` & `planet block generate-genesis`

---

CHANGES.md
Libplanet/KeyStore/Web3KeyStore.cs

Actually, it ports only #2727. (#2719 was already fixed on 0.46.0  😅)

Port changes from 0.45.5 to 0.46-maintenance

---

CHANGES.md
Libplanet.Net.Tests/Messages/MessageValidatorTest.cs
Libplanet.Net.Tests/Protocols/TestTransport.cs
Libplanet.Net.Tests/SwarmTest.AppProtocolVersion.cs
Libplanet.Net/AppProtocolVersionOptions.cs
Libplanet.Net/Messages/MessageValidator.cs
Libplanet.Node/NetworkConfig.cs

Several points:
- I'm of the opinion that [`null`s are bad in general if they can be avoided](https://www.lucidchart.com/techblog/2015/08/31/the-worst-mistake-of-computer-science/).
- Currently, `null` option isn't really being used.
- Other than "it'd be nice to have trust any signer as an option", I still fail to see a concrete use case for this.
- Having both `null` and empty list as meaningful options are incompatible with current CLI.
If `null` is still that important, we should change the CLI to accept a formatted `string` to allow all possible cases. 🙄

♻️ Removed nullability from `TrustedAppProtocolVersionSigners`

---

CHANGES.md
Libplanet.Net/Messages/NetMQMessageCodec.cs
Libplanet.Net/Transports/NetMQTransport.cs

Closes #2762.
- Parse a `MessageType` from `NetMQMessage` for `ProcessRequest()` and `DoReply`.
- Due to the difference between `MessageType` and an actual class name of `Message`, the logger shows the message type in different ways (e.g., `Libplanet.Net.Message.Ping` from `Message`, `Ping` from `MessageType`)

log/transport: add message type in NetMQTransport logger

---

Libplanet.Net.Tests/Consensus/MessageCacheTest.cs
Libplanet.Net/Consensus/Gossip.cs
Libplanet.Net/Consensus/MessageCache.cs
Libplanet.Net/Messages/NetMQMessageCodec.cs
Libplanet.Net/Transports/NetMQTransport.cs

This PR resolves the modification of `Message` in `MessageCache` from outside by `Get()`. If the multiple `HandleWantAsync()` tasks are called, `Message ret` is modified because `Message ret` from `MessageCache.Get()` references the message in actual `Message` in the dictionary.
```Csharp
private async Task HandleWantAsync(WantMessage msg, CancellationToken ctx)
{
// FIXME: Message may have been discarded.
// TODO: Message instance in cache itself is modified.
// Should create new instance before modifying.
Message[] messages = msg.Ids.Select(id =>
{
Message ret = _cache.Get(id); // <= Where the bug is happened.
ret.Remote = _transport.AsPeer;
ret.Identity = msg.Identity;
return ret;
}).ToArray();
MessageId[] ids = messages.Select(m => m.Id).ToArray();
_logger.Debug(
"WantMessage: …
```

fix/gossip/messageCache: message in cache is being modified from outside

---

Libplanet.Net/BlockCandidateTable.cs
Libplanet.Net/Swarm.BlockCandidate.cs

There is some problem when 0 length candidate is in the table.
In this PR. We ignore if we try to add 0 length candidate in the CandidateTable.

Ignore too low length candidate

---

CHANGES.md
Libplanet.Net.Tests/BoundPeerTest.cs
Libplanet.Net/BoundPeer.cs
Libplanet.Net/Messages/NeighborsMsg.cs
Libplanet.Net/Messages/NetMQMessageCodec.cs
Libplanet.Net/Transports/CommunicationFailException.cs
Libplanet.Net/Transports/InvalidMessageSignatureException.cs
Libplanet.Net/Transports/SendMessageFailException.cs
Libplanet.Tests/Action/ActionEvaluatorTest.cs
Libplanet.Tests/AddressTest.cs
Libplanet.Tests/Common/Action/Attack.cs
Libplanet.Tests/Common/Action/DetectRehearsal.cs
Libplanet.Tests/Common/Action/DumbAction.cs
Libplanet.Tests/Common/Action/RandomAction.cs
Libplanet.Tests/Common/Action/SetStatesAtBlock.cs
Libplanet/Action/InsufficientBalanceException.cs
Libplanet/Action/Sys/Mint.cs
Libplanet/Action/Sys/Transfer.cs
Libplanet/Address.cs
Libplanet/Blocks/InvalidBlockTxCountPerSignerException.cs
Libplanet/Store/BaseStore.cs
Libplanet/Tx/TxMetadata.cs
Libplanet/Tx/TxSuccess.cs

Baby steps. 😶
- Allows to remove `[Serializable]` attribute on our own `class`es. `[Serializable]` was being used only for the sake of having objects to be serialized as a part of custom `Exception`s that we wanted to `throw`. This can reduce the exposure to the [warning] by Microsoft.
- `Address` now explicitly accepts `IValue` type not `Binary`. This is my own design decision to have overall consistency down the line.
- Before this PR, `Address(Binary)` is probably not even necessary as `Binary` would be implicitly casted to `Address(byte[])`. The same goes with `Address(Text)` where the parameter is implicitly casted to `Address(string)`. This makes it more error prone by allowing non-standard usage of `Address` encoding.
[warning]: …

♻️ Introduce `IBencodable`

---

CHANGES.md
Libplanet.Tests/Blockchain/Policies/VolatileStagePolicyTest.cs
Libplanet/Blockchain/Policies/VolatileStagePolicy.cs

Closes #2783 
Performing `+` operation on `TimeSpan.MaxValue` results in an `Exception`.

Fix `VolatileStagePolicy<T>`'s `Expired()`

---

Libplanet/ByteUtil.cs

Should be about 8 times faster. Tested with various lengths and sizes.
|   Method |      Mean |     Error |    StdDev |
|--------- |----------:|----------:|----------:|
| Original | 632.75 us | 12.454 us | 23.083 us |
|   Lookup |  78.23 us |  1.520 us |  2.029 us |

Optimized `ByteUtil.Hex()`

---

CHANGES.md
Libplanet.Tests/Action/ActionEvaluatorTest.cs
Libplanet.Tests/Blocks/BlockCommitTest.cs
Libplanet.Tests/TestUtils.cs
Libplanet/Blocks/BlockCommit.cs
Libplanet/Blocks/BlockMetadata.cs

(The document has originally written in Korean and translated into English.)
**(Correction: The `BlockHash` is being hashed with `StateRootHash`, however, the `LastCommit` is still not unique to a block.)**
https://github.com/planetarium/libplanet/blob/aa1d444f32ba468fb15186d7113078a52f164b84/Libplanet/Blocks/BlockHeader.cs#L65-L75
Afterward, when going to Proof-of-Stake and confirming that each `Validator` has participated in the consensus on the n-1th `Block`, it is confirmed using `LastCommit` of the nth `Block`, and this is used to confirm the validity of the `Validators` `Stake` is compensated when the corresponding `Block` is appended to the chain, and this information is stored in `State`.
*(Things to check: Is the value used for Power staking part of `Stake` by `Validator`, and …

pbft: Add `LastCommit` as `PreEvaluationHash` input

---

CHANGES.md
Libplanet.Net.Tests/BlockCandidateTableTest.cs
Libplanet.Net/BlockCandidateTable.cs
Libplanet.Net/Swarm.BlockCandidate.cs
Libplanet.Tests/Store/StoreFixture.cs

Preliminary refactoring to further specify the context in which a set of `Block<T>`s gets thrown around.
I'll probably be implementing a `Branch<T>` class shortly as the contractual guarantee from `GetCurrentRoundCandidate()` is pretty weak for the returned `List<T>` of `Block<T>`s when passing it around. For that reason, the usage of `SortedList<long, Block<T>>` has been removed as it does not sufficiently guarantee the desired properties. 😶
This adds two additional constraints to the previous implementation:
- `Block<T>`s have to have consecutive indices.
- `Block<T>`s should form a linked list in the sense that a "next" `Block<T>`'s `PreviousHash` should match that of the "previous" `Block<T>`s `Hash`.
As a side note, I think it'd be also a good idea to only allow `Block<T>`s that are …

♻️ Refactor `BlockCandidateTable`

---

Libplanet.Node/NodeUtils.cs
Libplanet.Tests/ByteUtilTest.cs
Libplanet/ByteUtil.cs

A sister PR to #2789.
Only about twice as fast than before. 😶
|   Method |     Mean |    Error |   StdDev |   Median |
|--------- |---------:|---------:|---------:|---------:|
| Original | 909.8 us | 18.03 us | 46.86 us | 934.0 us |
|    Parse | 454.6 us |  8.79 us | 23.16 us | 442.6 us |

Optimized `ParseHex()`

---

CHANGES.md
Libplanet.Net.Tests/BoundPeerTest.cs
Libplanet.Net/BoundPeer.cs
Libplanet.Net/Transports/CommunicationFailException.cs
Libplanet.Net/Transports/InvalidMessageSignatureException.cs
Libplanet.Net/Transports/SendMessageFailException.cs
Libplanet.Tests/AddressTest.cs
Libplanet/Action/InsufficientBalanceException.cs
Libplanet/Address.cs
Libplanet/Blocks/BlockPolicyViolationException.cs
Libplanet/Blocks/InvalidBlockTxCountPerSignerException.cs

♻️ Revert to add `Serializabe` attribute back into `Address` and `BoundPeer`

---

@planetarium/tx/README.md
@planetarium/tx/package.json
@planetarium/tx/src/action.ts
@planetarium/tx/src/index.ts
@planetarium/tx/src/tx/index.ts
@planetarium/tx/src/tx/unsigned.ts
@planetarium/tx/test/tx/unsigned.test.ts
CHANGES.md

This pull request makes the `@planetarium/tx` JavaScript package support building unsigned transactions with custom actions. Also, it specifies the node's version requirement through the `package.json` file's `engines` property because `globalThis.crypto` is available since Node.js `19.0.0`. You can check it by making a `.npmrc` file with `engine-strict=true` content.

feat(@planetarium/tx): Support building unsigned transactions with custom actions

---

Libplanet.Net/BlockCandidateTable.cs

🧹 Added contextual information to `BlockCandidate` logging

---

Libplanet.Net.Tests/Transports/NetMQTransportTest.cs
Libplanet.Tests/Action/ActionEvaluatorTest.cs
Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
Libplanet.Tests/Blockchain/BlockChainTest.Internals.cs
Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
Libplanet.Tests/Blockchain/BlockChainTest.cs
Libplanet.Tests/Blockchain/Policies/StagePolicyTest.cs
Libplanet.Tests/Blockchain/Renderers/AnonymousActionRendererTest.cs
Libplanet.Tests/Blockchain/Renderers/AnonymousRendererTest.cs
Libplanet.Tests/Blockchain/Renderers/DelayedActionRendererTest.cs
Libplanet.Tests/Blockchain/Renderers/DelayedRendererTest.cs
Libplanet.Tests/Blockchain/Renderers/LoggedActionRendererTest.cs
Libplanet.Tests/Blockchain/Renderers/NonblockRendererTest.cs
Libplanet.Tests/Blocks/BlockContentTest.cs
Libplanet.Tests/Blocks/BlockTest.cs
Libplanet.Tests/Blocks/PreEvaluationBlockTest.cs
Libplanet.Tests/Store/BlockSetTest.cs
Libplanet.Tests/Store/DefaultStoreTest.cs

On https://github.com/planetarium/libplanet/pull/2498, tests that failed has been excluded with skipping on unity test.
We knows that the problem is on the `xunit-unity-runner`, so most of them wasn't problematic.
So, revert to the original code.
This PR does not automatically revert #2498, since there were some fixes also. Only needless skipping will be reverted.

Revert temporal skippable tests

---

Libplanet.Benchmarks/AppendBlock.cs
Libplanet.Benchmarks/Commit.cs
Libplanet.Tests/Store/StoreFixture.cs

@limebell and @OnedgeLee have noticed that benchmark is failing due to the `SetValdiator` and `BlockCommit` changes. This PR finds out which tests have impact.
- The `ProposeBlock` is now proposing and appending. We might have to see `ProposeBlock()` and `Append()` separately.
- `TestUtils.GenesisBlock` have `TestUtils.ValidatorSet`. The time of benchmark related to `GenesisBlock` has been increased due to initial `SetValidator` transaction validation.
The general results increased due to the addition of `BlockCommit`, and the creation of a `LastCommit` and `Commit` for each block.
|                              Method |        Job | InvocationCount | UnrollFactor |      Mean |     Error |    StdDev |
|------------------------------------ |----------- |---------------- |------------- …

benchmark: Benchmark for `pbft`

---

Libplanet.Net/Swarm.BlockSync.cs

relative #2802
When finding preload branchpoint, find only `BlockHash` instead of `Block<T>`

Get preload blocks when its needed

---

CHANGES.md
Libplanet.Net.Tests/Transports/BoundPeerExtensionsTest.cs
Libplanet.Net/Transports/BoundPeerExtensions.cs
Libplanet.Net/Transports/NetMQTransport.cs

This PR introduces `BoundPeer.ResolveNetMQAddressAsync()` extension method, to address unintended blocking for hostname resolvings on `NetMQTransport. ProcessRequest()`.
I'm a little bit unsure that we might need to perform these resolvings on `.ProcessRequest()` instead of `.SendMessageAsync()`. afik `NetMQRuntime` keeps synchronization context for restricting thread, but `await` might be useful when there're other tasks.

Avoid unintended blocks on NetMQTransport

---

Libplanet.Net.Tests/SwarmTest.Preload.cs
Libplanet.Net/Protocols/KademliaProtocol.cs
Libplanet.Net/Swarm.BlockCandidate.cs
Libplanet.Net/Swarm.BlockSync.cs
Libplanet.Net/Swarm.cs
Libplanet.Net/Transports/NetMQTransport.cs
Libplanet.Net/TxCompletion.cs
Libplanet.RocksDBStore/RocksDBStore.cs
Libplanet.Stun/Stun/TurnClient.cs
Libplanet/Blockchain/BlockChain.Swap.cs
Libplanet/Store/TrieStateStore.cs

Although a case could be made whether method names should be handled as properties, I've decided to include method names as logged property. The reason is twofold:
- Cleaner codebase
- Easier parsing through property
Also, added `()` for missing cases. These are mainly for comprehension.
In the long run, a better solution would be to automatically generate the method name and line number as context at some point. 🙄

🧹 Changed method name logging for more consistency

---

Libplanet.Net/Transports/NetMQTransport.cs

🧹 Elevated `NetMQTransport` log levels

---

CHANGES.md
Libplanet.Tests/Blockchain/BlockChainTest.cs
Libplanet/Blockchain/BlockChain.cs
Libplanet/Blockchain/Policies/IBlockPolicy.cs

Just some preparatory work to tease out genesis block handling from `Append()`. The eventual goal is to change `Block<T>()` constructor to remove `IBlockPolicy` getting hold of a reference to an uninitialized `BlockChain<T>` "instance".
Notable changes:
- Introduces `ValidateGenesisBlock()` as a separate method. Although this violates DRY principle, I think this is better for comprehension as there are too many special `Block<T>` "fields" to consider.
- Reduced dependency for `IBlockPolicy` during genesis block validation.

Ignore policy checks for genesis block

---

.github/workflows/build.yaml

Fix CI regression introduced with #2847: https://github.com/planetarium/libplanet/actions/runs/4259681427/jobs/7412118146#step:7:18

CI: fix where obj/ directory is missing

---

Libplanet.Net/Swarm.BlockCandidate.cs
Libplanet/Blockchain/BlockChain.cs
Libplanet/Tx/InvalidTxNonceException.cs

This is a follow-up to #2845.
PR size is unnecessarily large due to indentation fix in `Swarm.BlockCandidate.cs`. 🙄
- Tx nonce validation has been extracted out as a separate method.
- There could be a slight performance degradation as we are iterating over `Block<T>.Transactions` twice.
- This is to mainly separate policy validation and structural validation more easily.
- Future plan is to re-use this method during genesis `Block<T>` validation.

♻️ Refactor validate nonces

---

@planetarium/account/.gitignore
@planetarium/account/README.md
@planetarium/account/global.d.ts
@planetarium/account/package.json
@planetarium/account/src/Account.ts
@planetarium/account/src/Address.ts
@planetarium/account/src/Message.ts
@planetarium/account/src/PublicKey.ts
@planetarium/account/src/RawPrivateKey.ts
@planetarium/account/src/Signature.ts
@planetarium/account/src/index.ts
@planetarium/account/test/Address.test.ts
@planetarium/account/test/Message.test.ts
@planetarium/account/test/PublicKey.test.ts
@planetarium/account/test/RawPrivateKey.test.ts
@planetarium/account/test/Signature.test.ts
@planetarium/account/test/setup.ts
@planetarium/account/test/utils.ts
@planetarium/account/tsconfig.json
@planetarium/account/vitest.config.ts
CHANGES.md
package.json
yarn.lock

Prerequisite: ~~#2847~~ satisfied
This PR introduces @planetarium/account typescript package into the typescript monorepo, which provides means to represent accounts for applications built with Libplanet.
Note that KeyStore interface is not yet ready and is not yet included in this PR. For now, RawPrivateKey constructor can be used with external code to access tx signing and account management features.
~~**Note for reviewers**: as this PR includes commits for #2847, you can examine only the latest commit for making a code review. This PR will be rebased on #2847 once it gets merged.~~ Not applicable

Introduce @planetarium/account

---

CHANGES.md
Libplanet/Action/PolymorphicAction.cs

This feature is temporary and it should be removed when removing the all `T` generic parameter.

Make `PolymorphicAction<T>._actionTypeLoader` configurable

---

Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextProposerTest.cs
Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
Libplanet.Net.Tests/Consensus/Context/ContextProposerTest.cs
Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
Libplanet.Net.Tests/TestUtils.cs
Libplanet.Tests/TestUtils.cs

- Make `CreateDummyConsensusContext` to fill returned `BlockChain`.
- Also, `CreateDummyContext` will fill returned `BlockChain`.
- Removed `validatorSet` parameter from `CreateDummyContext`
- Removed test : Remove `CannotProposeWithoutLastCommitWhenRequired`, since block proposal without required lastcommit will be prohibited by block appending, before proposal.
- #2730

Dummy context generation to fill blockchain on test

---

.github/workflows/main.yml

Previously, it had tested whether *@planetarium/cli* can be installed well with npm using the just released version if it's a tag push, and using the latest version otherwise.  However, testing against the just released version is fragile, so I changed it to test against the latest release consistently.
Note: this commit should be cherry-picked to the main branch as well.

Always test @planetarium/cli install with the latest version

---

Libplanet.Net/Consensus/Gossip.cs
Libplanet.Net/Protocols/KademliaProtocol.cs

Related to https://github.com/planetarium/libplanet/issues/2841
`Task.WhenAll()` invokes the task sequentially. If one of a task is neither yielding nor awaiting any task, then the other will wait for the completion of the task. 
`AsyncDelegate<T>` has `Task.WhenAll()`, which is used for `ProcessMessageHandler`, and it might block the next task until the first task is completed.
These are the comparison of the duration between a request replying to `ITransport` and the reply time that is actually sent. The replies are filtered only for consensus messages and categorized in RequestIds. Data is tracked for a hour.
N(Requests) : 4357
describe | replied (ms) | count | avg (ms)
-- | -- | -- | --
mean | 1.040046 | 2.086527 | 0.371145
std | 1.831166 | 1.546967 | 0.373520
min | 0.150000 | …

fix/pbft: parallel replying / task-switching between kademlia

---

CHANGES.md
Libplanet.Net.Tests/Consensus/ConsensusReactorTest.cs
Libplanet.Net.Tests/SwarmTest.Broadcast.cs
Libplanet.RocksDBStore.Tests/RocksDBStoreTest.cs
Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
Libplanet.Tests/Blockchain/BlockChainTest.cs
Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs
Libplanet.Tests/Blockchain/Policies/StagePolicyTest.cs
Libplanet.Tests/Blockchain/Renderers/DelayedActionRendererTest.cs
Libplanet.Tests/Blocks/PreEvaluationBlockTest.cs
Libplanet.Tests/Fixtures/IntegerSet.cs
Libplanet.Tests/Store/StoreTest.cs
Libplanet.Tests/TestUtils.cs
Libplanet/Blockchain/BlockChain.cs

Related to #1486 and #2585.
Added `BlockChain<T>.Create()` factory method to create a `BlockChain<T>` instance with an "empty" `IStore` from scratch. The reason is twofold:
- Reduce side effects of simply instantiating a `BlockChain<T>` instance.
- This can be further reduced by refactoring the `Fork()` method. In near future, we should be able to have `BlockChain<T>()` constructor without any side effects if all goes well. 🙃
- Reduce the usage of references to uninitialized `BlockChain<T>` instance.
- I have only prevented calling `Append()` with a genesis `Block<T>` for now. Further `BlockChain<T>()` refactoring is in order once this is merged.
Eventually, we should be able to assume `BlockChain<T>.Tip` to be non-`null` and `Count > 0` to be `true` on any `BlockChain<T>` object.
Notable …

Added `BlockChain<T>.Create()`

---

CHANGES.md
Libplanet/Blockchain/BlockChain.cs

Follow up on #2863 and resolves #1486 and #2585 more completely. 😋
PS.
We might want to expose a constructor that takes chain id as its argument to load a specific `BlockChain<T>` from an `IStore`. I'm not sure this functionality is necessary at the moment. 🙄

♻️ Remove side effects from `BlockChain<T>()`

---

.github/workflows/benchmarks-merged.yml

Follow-up PR of #2903 and #2902. Merged commits benchmark is not stored with branch name due to using `ref_name` in `on.push` actions.

ci/bench: use trigger branch/tag name as directory [skip changelog]

---

.github/workflows/benchmarks-merged.yml

I'm sorry for the mess 😓
(cherry picked from commit b4cbe99d9e0fdedd5545f939ea0c8d90fd220f3c)

ci/bench: missing cherry pick in 2908

---

CHANGES.md
Libplanet.Explorer/Store/LiteDBRichStore.cs
Libplanet.Explorer/Store/MySQLRichStore.cs
Libplanet.Net/Swarm.BlockSync.cs
Libplanet.RocksDBStore/RocksDBStore.cs
Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
Libplanet.Tests/Blockchain/BlockChainTest.cs
Libplanet.Tests/Store/ProxyStore.cs
Libplanet.Tests/Store/StoreTracker.cs
Libplanet/Blockchain/BlockChain.cs
Libplanet/Store/BaseStore.cs
Libplanet/Store/DefaultStore.cs
Libplanet/Store/IStore.cs
Libplanet/Store/MemoryStore.cs

Resolves #2878.
There are numerous issues pertaining to handling "globally" cached `BlockCommit`s, but this is more of a problem with how we handle `IStore` generally. In particular, having multiple chain instances with different chain ids with access to shared state (be it stored `Block<T>`s or `Transaction<T>`s, etc.) and **deletion** operations, the root of the problem is not having a scheme/spec/etc. for managing chain ids.
In any case, this PR only further specifies that any instance of `BlockChain<T>` should have `BlockCommit` for its `BlockChain<T>.Tip`, when applicable, i.e. when it is a non-genesis PBFT `Block<T>`.

♻️ Refactor block commit cache

---

CHANGES.md
Libplanet.Net.Tests/Messages/MessageTest.cs
Libplanet.Tests/Action/ActionEvaluatorTest.cs
Libplanet.Tests/Action/Sys/SetValidatorTest.cs
Libplanet.Tests/Blocks/BlockMetadataTest.cs
Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
Libplanet/Consensus/Validator.cs

🔀 Unlike #2927, #2929, #2931, #2933, #2935 this won't be immediately released. 😗
The plan is to release 0.51.2 with updated `BlockCommit` encoding similar to changes in #2927 for `Validator`.

🔀 Port 0.50.3 to 0.51.2

---

CHANGES.md
Libplanet.Tests/Blocks/BlockHashTest.cs
Libplanet/Blocks/BlockCommit.cs
Libplanet/Blocks/BlockHash.cs
Libplanet/Blocks/BlockMarshaler.cs
Libplanet/Consensus/VoteMetadata.cs
Libplanet/Tx/TxMetadata.cs

♻️ Of minor note: `TxMetadata` from `Dictionary` will now result in an error if there is malformed genesis hash (either by not being `Binary` or having `Null` as value) instead of ignoring it to be "null genesis hash".

♻️ `IBencodable` for `BlockHash`

---

CHANGES.md
Libplanet.Explorer.Executable/Program.cs
Libplanet.Tests/Action/ActionEvaluatorTest.cs
Libplanet/Action/ActionEvaluator.cs
Libplanet/Action/IFeeCalculator.cs
Libplanet/Blockchain/BlockChain.cs
Libplanet/Blockchain/Policies/BlockPolicy.cs
Libplanet/Blockchain/Policies/IBlockPolicy.cs
Libplanet/Blockchain/Policies/NullBlockPolicy.cs
Libplanet/Blocks/PreEvaluationBlock.cs

NineChronicles has a Tx spamming problem. And it is caused by the non-fee Transaction model. 
In this PR. introduce `IFeeCalculator`. It is an interface for calculating Transaction fees and collecting from signers.
Get `IFeeCalculator` as an `IBlockPolicy` and check the fee in `ActionEvaluator.EvaluateActions()`.

Introduce `IFeeCalculator`

---

Libplanet/Blockchain/BlockChain.cs
Libplanet/Blockchain/BlockChainStates.cs

This reverts commit 49a8555cfbbb28ac03f9b44e572fee87963625ab.
Set state cache didn't seem to help much with cache filling up too quickly and crashing a node. 🙄
Probably also need to reduce the cache size back down to 1,000.

⏪ Revert set state cache

---

Libplanet/Blockchain/BlockChain.cs
Libplanet/Blockchain/BlockChainStates.cs
Libplanet/Blockchain/StateCache.cs

Reintroduces "set-state-caching" removed by #2993. Uses a customized scheme to mange cache values. Probably could be tuned further. However, the underlying LRU cache scheme does not fit perfectly well as a solution to the problem we are having. Also needs more documentation as wrong calls to `StateCache.AddOrUpdate()` would result in improper execution of a `Block<T>`.

⚡ Introduce `StateCache`

---

CHANGES.md
Libplanet/Action/ValidatorStateExtensions.cs

fix: make `ValidatorStateExtensions` to public
(cherry picked from commit 84da0b42fe7f01833b1c9846eca09c2a45778b34)

Add missing commit

---

CHANGES.md
Libplanet/Blockchain/BlockChain.cs

`NineChronicles.Headless` is initialized `IBlockChainState` and `ActionEvaluator` from outside of libplanet.
https://github.com/planetarium/NineChronicles.Headless/blob/531436da407f665cdac1a4b79e7ef3ed6f136eea/Libplanet.Headless/Hosting/LibplanetNodeService.cs#L153-L177
From #2863, We deprecate `BlockChain<T>.ctor()` as a creation from scratch, but unlike `BlockChain<T>.ctor()`, `BlockChain<T>.Create()` does not allow parameter `IBlockChainState` and `ActionEvaluator`
In this PR, get a new parameter for `BlockChain<T>.Create()` for `IBlockChainState` and `ActionEvaluator`.

Get new parameter for `BlockChain<T>.Create()`

---

Libplanet/Blockchain/BlockChain.MineBlock.cs

After #2863, `BlockChain<T>` instances are guaranteed to have at least one `Block<T>`. 😗

🧹 Removed unnecessary logic

---

CHANGES.md
Libplanet.Net.Tests/Consensus/Context/ContextNonProposerTest.cs
Libplanet.Net.Tests/TestUtils.cs
Libplanet.Net/Consensus/Context.Mutate.cs
Libplanet.Net/Consensus/Context.cs
Libplanet/Blockchain/BlockChain.cs

Closes #2973 
Current block validation in PBFT consensus guarantees the sanity of a block header but the block content (e.g., Tx nonces, Policy defined validation rules or state root hash.) This could lead `Context<T>` to being locked in an invalid block and committed by consensus, even though the block is invalid.
- Rename `BlockChain<T>.ValidateNextBlock()` to `ValidateNextBlockHeader()`
- Refactor Tx nonce/policy validation and calculate and commit the state root hash to the `BlockChain<T>.ValidateNextBlockContent()` method.
- `Context<T>` validates the block with `ValidateNextBlockContext()` and if a node is a proposer, bypass the actions evaluation.
- Added `Context<T>.IsCurrentRoundProposer()` method due to SA1113.
This fix will resolve the problem, however, lengthen the consensus …

fix: validate block content in PreVote step

---

CHANGES.md
Libplanet.Net.Tests/Consensus/Context/MessageLogTest.cs
Libplanet.Net/Consensus/ConsensusContext.cs
Libplanet.Net/Consensus/Context.Async.cs
Libplanet.Net/Consensus/Context.Mutate.cs
Libplanet.Net/Consensus/Context.cs
Libplanet.Net/Consensus/Gossip.cs
Libplanet.Net/Consensus/MessageLog.cs

This changes MessageLog.Add()'s return type to void (which was bool), and throws error instead if failed. Since the method was internal, skip changelog.

Adjust consensus loggings

---

Libplanet.Net.Tests/Consensus/Context/ContextProposerTest.cs
Libplanet.Net/Consensus/Context.cs

Things to note:
- Now a node can propose an invalid `Block<T>`. `Context` does no validation on a proposed `Block<T>` at the time of proposal.
- A proposer is no longer treated as special during pre-vote step. All participating nodes must validate a proposed `Block<T>` during pre-vote step.

♻️ Refactor block validate

---

CHANGES.md
Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
Libplanet.Net.Tests/Consensus/ConsensusReactorTest.cs
Libplanet.Net.Tests/TestUtils.cs
Libplanet.Net/Consensus/ConsensusContext.cs
Libplanet.Net/Consensus/ConsensusReactor.cs
Libplanet.Net/Consensus/Context.Async.cs
Libplanet.Net/Consensus/Context.cs

Context interval is expected to be constant, but it varies.
`newHeightDelay`, that suspends `NewHeight()` with fixed time after `OnTipChanged` will be removed, and replaced with `contextMinInterval` that suspends `NewHeight()` with dynamic time, till interval between previous `NewHeight()` call and current `NewHeight()` call reaches to it.
Validator that doesn't have context of new tip appends block without delay, since it doesn't know the time that context has been made.

Replace newHeightDelay with contextMinInterval

---

CHANGES.md
Libplanet.Net.Tests/Consensus/GossipTest.cs
Libplanet.Net/Consensus/ConsensusReactor.cs
Libplanet.Net/Consensus/Gossip.cs

`Gossip` used to broadcast messages via `HeartbeatTask`, which is called every second. Message can be delayed at most 1 second and it may hurt consensus health.
This patch implements `Gossip.PublishMessage()` method that broadcasts message immediately, and gossips it after it sent.
closes #3054

Implement `Gossip.PublishMessage()`

---

@planetarium/account-aws-kms/package.json
@planetarium/account-aws-kms/src/AwsKmsAccount.ts
@planetarium/account-aws-kms/test/AwsKmsKeyStore.test.ts
@planetarium/account-web3-secret-storage/package.json
@planetarium/account-web3-secret-storage/src/Web3Account.ts
@planetarium/account-web3-secret-storage/src/Web3KeyStore.ts
@planetarium/account-web3-secret-storage/src/index.ts
@planetarium/account-web3-secret-storage/test/MockPassphraseEntry.ts
@planetarium/account-web3-secret-storage/test/Web3Account.test.ts
@planetarium/account-web3-secret-storage/test/Web3KeyStore.test.ts
@planetarium/account-web3-secret-storage/test/__snapshots__/Web3Account.test.ts.snap
@planetarium/account/src/Account.ts
@planetarium/account/src/Address.ts
@planetarium/account/src/RawPrivateKey.ts
@planetarium/account/test/Account.test.ts
@planetarium/account/test/Address.test.ts
@planetarium/account/test/RawPrivateKey.test.ts
@planetarium/tx/src/tx/signed.ts
@planetarium/tx/test/tx/fixtures.ts
CHANGES.md
yarn.lock

Now, *@planetarium/account-web3-secret-storage* uses `Web3Account` instead of `RawPrivateKey`. This change enables the users to interact with an instance of `Account` before unlocking the account, and defers the authentication (`PassphraseEntry.authenticate()`) to when the operation that requires unlocked account is requested.
Additionally, since some backends (web3) require accounts to be unlocked before publickey can be shown, Account.publicKey property is now changed to async Account.getPublicKey() method.

@planetarium/account-web3-secret-storage: `Web3Account` (deferred unlock) & asyncify `getPublicKey()`

---

CHANGES.md
Libplanet.Net/Consensus/Context.Mutate.cs
Libplanet.Net/Consensus/Context.cs

Following PR of #2996 and partially resolves #3045
Currently, block evaluation is done in proposing a block, which is required to get a final block from `PreEvaluationBlock`, `PreVote`, which is a stage of consensus for validating a given block, and `Commit`, which is a stage of consensus of finalizing the given block. This PR will cache an evaluated action from a block in the `PreVote` stage, and use it in the `Commit` stage.
With this, an evaluation count will be reduced from two to one, if a node is a non-proposer, or from three to two, if a node is a proposer. From a network perspective, the evaluation will be done two times, which are from the proposer in `Propose`, and from all nodes in `PreVote`.
A proposer could bypass the `PreVote` evaluation by caching an evaluation created from …

feat: cache evaluated actions in `Context<T>`

---

CHANGES.md
Libplanet.Benchmarks/AppendBlock.cs
Libplanet.Benchmarks/ProposeBlock.cs
Libplanet.Explorer.Tests/Indexing/BlockChainIndexTest.cs
Libplanet.Explorer.Tests/Queries/TransactionQueryTest.cs
Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
Libplanet.Net.Tests/Consensus/Context/ContextProposerTest.cs
Libplanet.Net.Tests/Consensus/Context/MessageLogTest.cs
Libplanet.Net.Tests/SwarmTest.Broadcast.cs
Libplanet.Net.Tests/SwarmTest.Fixtures.cs
Libplanet.Net.Tests/SwarmTest.Preload.cs
Libplanet.Net.Tests/SwarmTest.cs
Libplanet.Net/Consensus/Context.cs
Libplanet.Tests/Blockchain/BlockChainTest.ProposeBlock.cs
Libplanet.Tests/Blockchain/BlockChainTest.Stage.cs
Libplanet.Tests/Blockchain/BlockChainTest.cs
Libplanet.Tests/Blockchain/Renderers/DelayedActionRendererTest.cs
Libplanet.Tests/Fixtures/IntegerSet.cs
Libplanet.Tests/Store/StoreTest.cs
Libplanet/Blockchain/BlockChain.ProposeBlock.cs

Follow-up on #3072.
Notable changes:
- Removed `Timestamp` parameter from `ProposeBlock()`. It might be nice to have, but isn't being used anywhere. Besides, there is no easy path to assign custom timestamps for a running node.
- ~~Added `ProposeBlock()` that takes a list of `Transaction<T>`s to propose a somewhat custom `Block<T>`.~~
- On second thought, made such method `internal` only for testing.
Addendum:
We can also probably remove `BlockCommit` and `IComparer<Transaction<T>>`. 🙄

♻️ `BlockChain<T>.ProposeBlock()` overhaul

---

CHANGES.md
Libplanet.Tests/Tx/AddressSetTest.cs
Libplanet.Tests/Tx/TxMarshalerTest.cs
Libplanet.Tools/Libplanet.Tools.csproj
Libplanet.Tools/Program.cs
Libplanet/Tx/AddressSet.cs
Libplanet/Tx/TxInvoice.cs
Libplanet/Tx/TxMarshaler.cs

Previously, `Transaction<T>.UpdatedAddresses` in serialized form should have be ordered in a certain way, which depends on `ImmutableHashSet<T>`'s internals.  If a transaction payload had multiple updated addresses and they were ordered in another way, it failed to verify the signature.
This patch fixes it by letting `Transaction<T>.UpdatedAddresses` preserve the order regardless of the way to order it.  Note that it still does not allow duplicates though.  A new internal data structure named `AddressSet` is also introduced.

Preserve order of `Transaction<T>.UpdatedAddresses`

---

CHANGES.md
Libplanet.Explorer.Tests/Queries/StateQueryTest.cs
Libplanet.Explorer/Queries/StateQuery.cs

This pull request introduced the `states` query in the `StateQuery` GraphQL type.

Implement `query.stateQuery.states`

---

@planetarium/account-aws-kms/src/AwsKmsAccount.ts
@planetarium/account-aws-kms/test/AwsKmsKeyStore.test.ts
@planetarium/account-web3-secret-storage/src/Web3Account.ts
@planetarium/account-web3-secret-storage/src/Web3KeyStore.ts
@planetarium/account-web3-secret-storage/test/Web3Account.test.ts
@planetarium/account-web3-secret-storage/test/Web3KeyStore.test.ts
@planetarium/account/src/Account.ts
@planetarium/account/src/RawPrivateKey.ts
@planetarium/account/test/Account.test.ts
@planetarium/account/test/RawPrivateKey.test.ts
CHANGES.md

Now, `Account` has `getAddress()` async method that can get the address of the given account directly. Also, `Web3KeyStore` now uses `Web3KeyMetadata` which contains `address` field.

@planetarium/account: `Account.getAddress()`

---

CHANGES.md
Libplanet.Explorer.Tests/GraphTypes/BlockPolicyTypeTest.cs
Libplanet.Explorer.Tests/GraphTypes/CurrencyInputTypeTest.cs
Libplanet.Explorer.Tests/GraphTypes/CurrencyTypeTest.cs
Libplanet.Explorer.Tests/GraphTypes/TxResultTypeTest.cs
Libplanet.Explorer.Tests/Queries/StateQueryTest.cs
Libplanet.Explorer/GraphTypes/CurrencyInputType.cs
Libplanet.Explorer/GraphTypes/CurrencyType.cs
Libplanet.Explorer/Queries/StateQuery.cs

1. Replaced `ByteString`-typed `currencyHash` parameter with `CurrencyInput`-typed `currency` parameter in `query.stateQuery.balance`  and `query.stateQuery.totalSupply`.
2. Corrected the type of `Currency.decimalPlaces` to `byte` from `uint`.

Support `query.stateQuery.balance(...)` with custom currencies instead of `currencyHash`

---

CHANGES.md
Libplanet.Tests/Blockchain/BlockChainTest.cs
Libplanet.Tests/Blockchain/Renderers/AtomicActionRendererTest.cs
Libplanet/Blockchain/BlockChain.Swap.cs
Libplanet/Blockchain/Renderers/Debug/ValidatingActionRenderer.cs
Libplanet/Blockchain/Renderers/IActionRenderer.cs
Libplanet/Blockchain/Renderers/IRenderer.cs

As we've moved to PBFT, reorgs should not happen. In particular, calls to reorg related methods have been dead code for quite a while. This simply removes the unused part of the `RenderSwap()` method. 🙄
Notes:
- This only removes any invocation of reorg related renderer calls from `BlockChain<T>`. The interface is left intact. I'll be dealing with this piece by piece in follow-up PRs. 🙄
- I'm too scared to touch `ValidatingActionRenderer.Validate()`. I've made the condition very loose, but I'm not even sure if it is possible to "validate" renderer calls without explicitly invoking reorg related renderers as simply forward rendering lacks a branchpoint as its context. 😥

🧹 Remove reorg related render calls from `BlockChain<T>`

---

CHANGES.md
Libplanet.Tests/Tx/TxActionListTest.cs
Libplanet.Tests/Tx/TxCustomActionListTest.cs
Libplanet.Tests/Tx/TxSystemActionListTest.cs
Libplanet/Tx/TxActionList.cs
Libplanet/Tx/TxCustomActionList.cs
Libplanet/Tx/TxInvoice.cs
Libplanet/Tx/TxMarshaler.cs
Libplanet/Tx/TxSystemActionList.cs

My own general design opinions:
- Owning class generally should not care about *how* its member class is encoded.
- Similarly, a member class should not care about what its property name (dictionary key?) should be from the perspective of an owning class.
I have no idea whether `JsonConverters` still works with this change. 🙄

♻️ Refactor `TxActionList` encoding

---

CHANGES.md
Libplanet.Explorer/Libplanet.Explorer.csproj
Libplanet/Libplanet.csproj

- Bump bencodex to 0.9.0.
- `GetHashCode()` of `Bencodex.Types.Dictionary` and `Bencodex.Types.List` returns hash code derived from its content from now on.
- https://github.com/planetarium/libplanet/pull/2520

Bump `Bencodex` to `0.9.0`

---

CHANGES.md

In #3037, the `BlockChain<T>.ExecuteActions(Block<T>)` method was removed but it was not recorded well. This pull request just complements the part.

Complement missed deletion record in changelog

---

CHANGES.md
Libplanet.Net.Tests/SwarmTest.Broadcast.cs
Libplanet.Net.Tests/SwarmTest.Preload.cs
Libplanet.Net/Consensus/Context.Mutate.cs
Libplanet.Net/Swarm.BlockCandidate.cs
Libplanet.Net/Swarm.BlockSync.cs
Libplanet.Net/Swarm.cs
Libplanet.Tests/Action/ActionEvaluatorTest.cs
Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
Libplanet.Tests/Blockchain/BlockChainTest.Internals.cs
Libplanet.Tests/Blockchain/BlockChainTest.cs
Libplanet/Blockchain/BlockChain.cs

Resolves #3095.
Somewhat of a continuation of #3098.
Notable changes:
- Internal `Append()` has greatly reduced options
- Whether to evaluate a give `Block<T>` is solely determined by whether `actionEvaluations` is provided or not.
- There is no longer a split option for rendering `Renderer`s and `ActionRenderer`s.
- Rendering is disabled (possibly temporarily) for the preloading phase.

♻️ Streamlined rendering

---

Libplanet/Action/ActionEvaluator.cs
Libplanet/Action/IActionEvaluator.cs
Libplanet/Blockchain/BlockChain.Swap.cs

This pull request changes the return type of `IActionEvalutor.Evaluate()` to `IReadOnlyList<IActionEvaluation>`.
Skip changelog because `IActionEvaluator` is not released yet.

Update return type for `IActionEvaluator.Evaluate()` to `IReadOnlyList<IActionEvaluation>`

---

@planetarium/tx/test/tx/signed.test.ts
@planetarium/tx/test/tx/unsigned.test.ts

Currently, tests in `@planetarium/tx` are failing because the test data is not updated correctly. Since #3110 PR, the `type` property was removed but it was not applied to the `@planetarium/tx` package's test data yet.
https://github.com/planetarium/libplanet/pull/3110/files#diff-6bef7475a39e1cf3932feaac7dcb733711a27edde2e0f6a851ab8552b9087c48L188

test(@planetarium/tx): correct tx test data

---

Libplanet.Explorer/GraphTypes/BlockType.cs

This deprecates `Difficulty`, `TotalDifficulty` and `Nonce` field in block query, which was deleted in PBFT.

Deprecate pow block fields query

---

CHANGES.md
Libplanet.Explorer.Tests/GeneratedBlockChainFixture.cs
Libplanet.Net.Tests/Consensus/Context/ContextNonProposerTest.cs
Libplanet.Net.Tests/Consensus/Context/ContextProposerValidRoundTest.cs
Libplanet.Net.Tests/SwarmTest.Broadcast.cs
Libplanet.Net.Tests/SwarmTest.Preload.cs
Libplanet.Net.Tests/SwarmTest.cs
Libplanet.Tests/Action/AccountStateDeltaImplTest.cs
Libplanet.Tests/Action/AccountStateDeltaTest.cs
Libplanet.Tests/Action/ActionEvaluatorTest.cs
Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
Libplanet.Tests/Blockchain/BlockChainTest.Internals.cs
Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
Libplanet.Tests/Blockchain/BlockChainTest.cs
Libplanet.Tests/Blocks/PreEvaluationBlockTest.cs
Libplanet/Blockchain/BlockChain.Evaluate.cs
Libplanet/Blocks/PreEvaluationBlock.cs

- `PreEvaluationBlock.Evaluate<T>()` was only being used purely for convenience in test code.
- The name was misleading.

🧹 Remove `PreEvaluationBlock.Evaluate()`

---

CHANGES.md
Libplanet.RocksDBStore/RocksDBStore.cs

This PR fixes `KeyNotFoundException`, mentioned on #3126.
p.s. we need to revisit whether `_indexCache` on `RocksDBStore` is still needed.

Fix index cache in RocksDBStore

---

CHANGES.md
Libplanet.Tests/Blockchain/BlockChainTest.ProposeBlock.cs
Libplanet/Action/ActionEvaluator.cs
Libplanet/Action/IActionEvaluator.cs
Libplanet/Action/IActionLoader.cs
Libplanet/Action/StaticActionLoader.cs
Libplanet/Blockchain/BlockChain.ProposeBlock.cs

There should be an accompanying PR to filter malformed `Block`s containing malformed `Transaction`s received from the network.

🔧 Filter malformed `Transaction`s when proposing `Block`s

---

CHANGES.md
Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
Libplanet.Net/Consensus/Context.Async.cs
Libplanet.Tests/Common/Action/DelayAction.cs

- Mutation does not produce subsequent mutation any more.
- Instead, mutation will handle subsequent mutation with iteration.
- So, mutation produced from later messages will be consumed after every subsequent mutations has been consumed.
- This will secure `upon rules` to be performed as expected order.
- Resolves https://github.com/planetarium/libplanet/issues/3134
- `TimeoutPreVote` and `TimeoutPreCommit` can be called on inaccurate time, due to `IsValid` operation.
- But, I don't think it's so harmful, and negligible.
- According to PBFT spec, `upon rules` have to be executed `atomically`, so this seems to be a part of spec rather than restriction.
- This restriction exists from 1.0.0.

Fix mutation to be consumed sequentially

---

CHANGES.md
Libplanet.Net.Tests/Consensus/Context/ContextNonProposerTest.cs
Libplanet.Net/Consensus/Context.cs
Libplanet.Tests/Action/StaticActionTypeLoaderTest.cs
Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
Libplanet/Action/ActionEvaluator.cs
Libplanet/Action/IActionLoader.cs
Libplanet/Action/InvalidActionException.cs
Libplanet/Action/StaticActionLoader.cs
Libplanet/Blockchain/BlockChain.Evaluate.cs
Libplanet/Blockchain/BlockChain.cs

🔧 Filter malformed `Block`s from `BlockChain<T>.Append()` and `Context<T>.IsValid()`

---

CHANGES.md
Libplanet.Explorer.Tests/GraphTypes/CurrencyInputTypeTest.cs
Libplanet.Explorer/GraphTypes/CurrencyInputType.cs

This pull request suggests making `CurrencyInputType`'s `totalSupplyTrackable` field optional. This doesn't break the previous users' GraphQL usage because it was required.
p.s. I was worried that using a default value, `false`, would recommend `Currency.Legacy`, but fortunately that's not the case as `Currency.Uncapped` does as well.
p.s. I'm not sure where to write these changes in changelog 🤔 (e.g., Backward-compatible API changes...)

Make `CurrencyInputType.totalSupplyTrackable` optional

---

CHANGES.md
Libplanet.Benchmarks/AppendBlock.cs
Libplanet.Benchmarks/BlockChain.cs
Libplanet.Benchmarks/ProposeBlock.cs
Libplanet.Explorer.Tests/GeneratedBlockChainFixture.cs
Libplanet.Net.Tests/Consensus/ConsensusReactorTest.cs
Libplanet.Net.Tests/SwarmTest.Broadcast.cs
Libplanet.RocksDBStore.Tests/RocksDBStoreTest.cs
Libplanet.Tests/Action/ActionContextTest.cs
Libplanet.Tests/Action/ActionEvaluationTest.cs
Libplanet.Tests/Action/ActionEvaluatorTest.cs
Libplanet.Tests/Action/Sys/InitializeTest.cs
Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
Libplanet.Tests/Blockchain/BlockChainTest.ProposeBlock.cs
Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
Libplanet.Tests/Blockchain/BlockChainTest.cs
Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs
Libplanet.Tests/Blockchain/Policies/StagePolicyTest.cs
Libplanet.Tests/Blockchain/Renderers/AnonymousActionRendererTest.cs
Libplanet.Tests/Blockchain/Renderers/LoggedActionRendererTest.cs
Libplanet.Tests/Blocks/PreEvaluationBlockTest.cs
Libplanet.Tests/Fixtures/IntegerSet.cs
Libplanet.Tests/Store/StoreTest.cs
Libplanet.Tests/TestUtils.cs
Libplanet/Action/ActionContext.cs
Libplanet/Action/ActionEvaluator.cs
Libplanet/Action/IActionContext.cs
Libplanet/Blockchain/BlockChain.Evaluate.cs
Libplanet/Blockchain/BlockChain.cs

See #1972.
The property isn't being used in any meaningful way. On the other hand, it clashes with the changing design of requiring an `IActionEvaluator` before creating a `BlockChain<T>`. It isn't at all intuitive how to properly use an `IActionEvaluator` that creates a proper `IActionContext.GenesisHash`. I see this more of as a hinderance to the client-side developers. 🙄

Removed `IActionContext.GenesisHash`

---

CHANGES.md
Libplanet.Net.Tests/Consensus/GossipTest.cs
Libplanet.Net/Consensus/Gossip.cs

This PR delays reply of `HaveMessage`, to remove total amount of message in the network.
You may concern that this patch may delay the network, but gossip broadcasts messages via `Publish()` method at first, and than gossips through `HaveMessage` if any peer fails to receive published message. If a peer failed to receive published message, it means the message is already delayed, so this PR does not significantly affect delay.

Periodic `MessageId` handling in `Gossip`

---

CHANGES.md
Libplanet/HashDigest.cs
Libplanet/Store/Trie/MerkleTrie.cs

As the title suggests, this PR improves `StateStoreExtensions.Commit()` and `MerkleTrie.Commit()` methods by limiting the size of batch writes.
And more, this PR fixes `ReadOnlySpan<T>` usages in `HashDigest<T>`, to improve the performance when .NET Standard 2.1+.

Improve commit() perf on trie related APIs

---

CHANGES.md
Libplanet/State/AccountStateDeltaImpl.cs
Libplanet/State/AccountStateDeltaImplV0.cs

This PR tweaks the codes maintaining `AccountStateDeltaImpl.TotalUpdatedFungibles`, to care performance even in the extreme case of updating many addresses in one action.

Eager TotalUpdatedFungibles update

---

CHANGES.md
Libplanet.Tests/Action/AccountStateDeltaImplTest.cs
Libplanet.Tests/Action/ActionEvaluatorTest.cs
Libplanet.Tests/Blockchain/BlockChainTest.cs
Libplanet/Action/ActionEvaluator.cs
Libplanet/State/AccountStateDeltaImpl.cs

Null getters are no longer necessary as expanded API of `IBlockChainStates` in #3214 now return "sensible" values for empty states.

♻️ Remove null getters for `ActionEvaluator`

---

CHANGES.md
Libplanet.Tests/Action/AccountStateDeltaImplTest.cs
Libplanet.Tests/Action/AccountStateDeltaTest.cs
Libplanet.Tests/Action/ActionContextTest.cs
Libplanet.Tests/Action/ActionEvaluationTest.cs
Libplanet.Tests/Action/ActionEvaluatorTest.cs
Libplanet.Tests/Action/Sys/InitializeTest.cs
Libplanet.Tests/Blockchain/BlockChainTest.cs
Libplanet.Tests/Blockchain/Renderers/AnonymousActionRendererTest.cs
Libplanet.Tests/Blockchain/Renderers/LoggedActionRendererTest.cs
Libplanet.Tests/Fixtures/IntegerSet.cs
Libplanet/Action/ActionEvaluator.cs
Libplanet/Action/FeeCollector.cs
Libplanet/State/AccountStateDeltaImpl.cs
Libplanet/State/IAccountStateDelta.cs

Like #3229, this further removes context dependency from `IAccountStateDelta`. Assuming `IAccountStateDelta` is always used inside an `IAction.Execute(IActionContext)` from the client side, hopefully, there won't be much trouble updating. 😕

♻️ Explicit `IActionContext` dependency for `MintAsset()` and `BurnAsset()`

---

CHANGES.md

Since JSONs technically don't allow comments, GitHub's parser was acting up in #3238 due to having code snippets for `json` **with comments**. This should resolve the issue.

🧹 Removed `json` syntax highlighting in changelog

---

CHANGES.md
Libplanet.Tests/Action/AccountStateDeltaTest.cs
Libplanet.Tests/Action/AccountStateDeltaV1Test.cs
Libplanet.Tests/Action/ActionContextTest.cs
Libplanet.Tests/Action/ActionEvaluatorTest.cs
Libplanet/Action/ActionEvaluationsExtensions.cs
Libplanet/Blockchain/BlockChain.TxExecution.cs
Libplanet/State/AccountStateDelta.cs
Libplanet/State/AccountStateDeltaExtensions.cs
Libplanet/State/IAccountStateDelta.cs

Rationale:
- Internally, the actual data is held as `Dictionary<(Address, Currency), BigInteger>`.
- There are unnecessary parsing/data transformation happening at various levels due to this discrepancy.
- As flatter structure, it'd be easier to aggregate for `Currency` as well.
- Probably faster in most cases.

♻️ Returned data structures for `IAccountStateDelta` changed for more consistency

---

CHANGES.md
Libplanet.Tests/Action/ActionContextTest.cs
Libplanet/State/AccountDelta.cs
Libplanet/State/AccountStateDelta.cs
Libplanet/State/IAccountDelta.cs
Libplanet/State/IAccountStateDelta.cs

Reworked #3220. Decided to rename `IDelta` to `IAccountDelta` to be more concise as we might need something like `IWorldDelta` in the future. 😗
There are some inconsistencies between `IAccountDelta` and `IAccountStateDelta` on handling `ValidatorSet` data. This will be addressed one way or another in a follow-up PR.

✨ Introduce `IAccountDelta`

---

CHANGES.md
Libplanet.Explorer.Tests/Queries/StateQueryTest.cs
Libplanet/Blockchain/BlockChain.cs
Libplanet/Blockchain/BlockChainStates.cs
Libplanet/Blockchain/IBlockChainStates.cs
Libplanet/Blockchain/NullChainStates.cs
Libplanet/Blocks/BlockStates.cs
Libplanet/Blocks/IBlockStates.cs
Libplanet/State/AccountStateDelta.cs
Libplanet/State/IAccountState.cs
Libplanet/State/IAccountStateDelta.cs
Libplanet/State/TotalSupplyNotTrackableException.cs

Simplifies naming and aligns APIs for consistency.

♻️ Rename `IAccountStateView` to `IAccountState`

---

CHANGES.md
Libplanet.Tests/Action/AccountStateDeltaTest.cs
Libplanet.Tests/Action/ActionEvaluationTest.cs
Libplanet.Tests/Action/ActionEvaluatorTest.cs
Libplanet.Tests/Action/Sys/InitializeTest.cs
Libplanet.Tests/Blockchain/BlockChainTest.cs
Libplanet.Tests/Blockchain/Renderers/AnonymousActionRendererTest.cs
Libplanet.Tests/Blockchain/Renderers/LoggedActionRendererTest.cs
Libplanet.Tests/Fixtures/IntegerSet.cs
Libplanet.Tests/Mocks/MockAccountState.cs
Libplanet/Action/ActionEvaluator.cs
Libplanet/Blocks/BlockStates.cs
Libplanet/Blocks/IBlockStates.cs
Libplanet/State/AccountStateDelta.cs

Now only allows `IAccountState` as an argument. Additionally, `IBlockStates` now inherits `IAccountState`.

♻️ Refactor `AccountStateDelta` internal API

---

CHANGES.md
Libplanet.Tests/Action/ActionEvaluatorTest.cs
Libplanet.Tests/Blockchain/BlockChainTest.Internals.cs
Libplanet.Tests/Store/StoreFixture.cs
Libplanet/Action/ActionEvaluationsExtensions.cs
Libplanet/Blockchain/BlockChain.Evaluate.cs
Libplanet/Blockchain/BlockChain.cs
Libplanet/Blocks/BlockStates.cs
Libplanet/State/AccountDeltaExtensions.cs
Libplanet/State/AccountStateDeltaExtensions.cs
Libplanet/State/KeyConverters.cs

Generally, what we are interested in is `IAccountDelta` arithmetic (at least under current implementation). I've made a purposeful decision to make these methods `public` as lib9c and 9c-headless might be interested in these methods. Hopefully these should help reduce code duplication.

✨ Added `IAccountDelta` sum and raw-delta

---

CHANGES.md
Libplanet.Tests/Action/AccountStateDeltaTest.cs
Libplanet.Tests/Action/AccountStateDeltaV1Test.cs
Libplanet.Tests/Action/ActionEvaluatorTest.cs
Libplanet/Action/ActionEvaluator.cs
Libplanet/Blockchain/BlockChain.TxExecution.cs
Libplanet/State/AccountStateDelta.cs
Libplanet/State/IAccountStateDelta.cs

Generally to reduce dependency scope (and hopefully discourage using delta data in general). 🙄

♻️ Reroute `IAccountDelta` access

---

CHANGES.md
Libplanet.Net.Tests/Consensus/ConsensusContextNonProposerTest.cs
Libplanet.Net.Tests/Consensus/ConsensusContextTest.cs
Libplanet.Net.Tests/Consensus/ContextNonProposerTest.cs
Libplanet.Net.Tests/Consensus/ContextProposerTest.cs
Libplanet.Net.Tests/Consensus/ContextProposerValidRoundTest.cs
Libplanet.Net.Tests/Consensus/ContextTest.cs
Libplanet.Net.Tests/Consensus/GossipTest.cs
Libplanet.Net.Tests/Consensus/MessageCacheTest.cs
Libplanet.Net.Tests/SwarmTest.cs
Libplanet.Net.Tests/TestUtils.cs
Libplanet.Net/Consensus/ConsensusContext.Event.cs
Libplanet.Net/Consensus/ConsensusContext.cs
Libplanet.Net/Consensus/ConsensusReactor.cs
Libplanet.Net/Consensus/Context.Async.cs
Libplanet.Net/Consensus/Context.Event.cs
Libplanet.Net/Consensus/Context.Mutate.cs
Libplanet.Net/Consensus/Context.cs
Libplanet.Net/Consensus/Gossip.cs
Libplanet.Net/Consensus/GossipConsensusMessageCommunicator.cs
Libplanet.Net/Consensus/HeightVoteSet.cs
Libplanet.Net/Consensus/IConsensusMessageCommunicator.cs
Libplanet.Net/Consensus/MessageCache.cs
Libplanet.Net/Messages/ConsensusPreCommitMsg.cs
Libplanet.Net/Messages/ConsensusPreVoteMsg.cs
Libplanet.Net/Messages/ConsensusProposalMsg.cs
Libplanet.Net/Messages/ConsensusVoteMsg.cs

Instead of using additional bootstrapping logic for consensus,
Maintaining round-life gossip cache would solve bootstrapping problem.
- Introduced `IConsensusMessageCommunicator` interface for `Context`.
- Gossip cache no longer forgets message by time or adding of new message. Instead, explicit call of `Gossip.ClearCache()` would trigger to forget all messages at one time.
- `Gossip.ClearCache()` will be explicitly called on the start of new context round.
- Spam filter logic now add peer to denylist, with message's public key.

Update gossip to forget only with NewRound

---

CHANGES.md
Libplanet.Tests/Action/ActionTypeAttributeTest.cs
Libplanet/Action/ActionTypeAttribute.cs
Libplanet/Action/Loader/TypedActionLoader.cs

~~Not sure we even need `ValueOf()` as it can be a simple one liner. In any case, I think there would be an infinitesimal amount of performance improvement. 😗~~
Came back after working on [lib9c](https://github.com/planetarium/lib9c) a little. I think having `ValueOf()` just adds more confusion. 😐

🧹 Remove `ActionTypeAttribute.ValueOf()`

---

CHANGES.md
Libplanet.Net.Tests/Consensus/ConsensusContextTest.cs
Libplanet.Net.Tests/Consensus/ContextTest.cs
Libplanet.Net.Tests/Messages/NetMQMessageCodecTest.cs
Libplanet.Net/Consensus/ConsensusContext.cs
Libplanet.Net/Consensus/ConsensusReactor.cs
Libplanet.Net/Consensus/Context.Mutate.cs
Libplanet.Net/Consensus/Context.cs
Libplanet.Net/Consensus/Gossip.cs
Libplanet.Net/Messages/ConsensusMaj23Msg.cs
Libplanet.Net/Messages/ConsensusProposalClaimMsg.cs
Libplanet.Net/Messages/ConsensusVoteSetBitsMsg.cs
Libplanet.Net/Messages/MessageContent.cs
Libplanet.Net/Messages/NetMQMessageCodec.cs
Libplanet.Tests/Consensus/Maj23Test.cs
Libplanet.Tests/Consensus/ProposalClaimMetadataTest.cs
Libplanet.Tests/Consensus/ProposalClaimTest.cs
Libplanet.Tests/Consensus/VoteSetBitsMetadataTest.cs
Libplanet.Tests/Consensus/VoteSetBitsTest.cs
Libplanet/Consensus/ProposalClaim.cs
Libplanet/Consensus/ProposalClaimMetadata.cs
Libplanet/Consensus/VoteSetBits.cs
Libplanet/Consensus/VoteSetBitsMetadata.cs

This PR introduces two new classes `Maj23`, `VoteSetBits` and its related classes to solve following problem.
1. There exists 4 validator, where one of them (validator D) is attacker.
2. Validator D is the proposer for the round and height, and validator D sends block X's proposal to validator A, and send Y's proposal to validator B and C.
| |ValidatorA|ValidatorB|ValidatorC|ValidatorD|
|-|-|-|-|-|
|Proposal|X|Y|Y|XY|
3. Each validator broadcasts prevote vote according to received proposal. But validator D sends X's prevote to validator A and B, and sends Y's prevote to validaotr C.
| |ValidatorA|ValidatorB|ValidatorC|ValidatorD|
|-|-|-|-|-|
|Proposal|X|Y|Y|XY|
|PreVote|XYYX|XYYX|XYYY|XYYY|
4. Validator A and B failed to collect +2/3 prevote for block X, and validator C and D collected …

Replace proposal when +2/3 valid votes are collected

---

CHANGES.md
Libplanet.Tests/Action/ActionEvaluatorTest.cs
Libplanet.Tests/Fixtures/IntegerSet.cs
Libplanet/Action/ActionEvaluator.cs

🔧 Evaluate all `IAction`s regardless of errors

---

CHANGES.md
Libplanet.Explorer/GraphTypes/TxResult.cs
Libplanet.Tests/Action/ActionContextTest.cs
Libplanet.Tests/Store/StoreTest.cs
Libplanet.Tests/Tx/TxFailureTest.cs
Libplanet.Tests/Tx/TxSuccessTest.cs
Libplanet/Action/ActionContext.cs
Libplanet/Action/ActionEvaluation.cs
Libplanet/Action/ActionEvaluator.cs
Libplanet/Action/IActionContext.cs
Libplanet/Action/IActionEvaluation.cs
Libplanet/Store/BaseStore.cs
Libplanet/Tx/TxExecution.cs
Libplanet/Tx/TxFailure.cs
Libplanet/Tx/TxSuccess.cs

There's probably no reason for `TxExecution.ActionsLogList` to be `nullable`. Left as it is just in case things break. 😶

Expose `Logs` for `ActionContext`

---

Libplanet/Blockchain/BlockChain.cs

Forgot to rename one instance of `GetBlockStates` to `GetBlockState`. 😅

🧹 Rename for consistency

---

Libplanet.Tests/Action/AccountStateDeltaTest.cs
Libplanet.Tests/Action/AccountStateDeltaV0Test.cs
Libplanet.Tests/Action/AccountStateDeltaV1Test.cs
Libplanet.Tests/Action/ActionEvaluationTest.cs
Libplanet.Tests/Fixtures/IntegerSet.cs
Libplanet.Tests/Mocks/MockAccountState.cs

Backported(?) from a lib9c [PR](https://github.com/planetarium/lib9c/pull/1996). Sticking it in `Libplanet.Tests` for now. I haven't quite decided how, but it might be better to have a separate project to provide these kinds of classes to lib9c and 9c-headless directly to reduce code duplication. 🙄
Also this prepares the project to get rid of `IAccountStateDelta`'s getter `delegates`.

♻️ Better `MockAccountState`

---

Libplanet.Net.Tests/Consensus/ConsensusContextTest.cs

Since current context can also generate `PreVote`, +2/3 can be accomplished without 3th vote adding.
To remove flakiness of test, removed a vote.

Fix `HandleVoteSetBits` test

---

CHANGES.md
Libplanet.Net.Tests/Consensus/ConsensusContextTest.cs
Libplanet.Net/Consensus/Context.Event.cs
Libplanet.Net/Consensus/Context.Mutate.cs
Libplanet.Net/Consensus/VoteSet.cs

Added an event that invoked when the `VoteSet` is modified.
Fixed flakiness of `ConsensusContextTest.GetVoteSetBits()` test by using the added event handler.

Add `Context.VoteSetModified` event handler

---

CHANGES.md
Libplanet.Explorer.Tests/GraphTypes/TxResultTypeTest.cs
Libplanet.Explorer/GraphTypes/TxResult.cs
Libplanet.Explorer/GraphTypes/TxResultType.cs
Libplanet.Explorer/Queries/TransactionQuery.cs
Libplanet.Tests/Blockchain/BlockChainTest.Internals.cs
Libplanet.Tests/Store/StoreTest.cs
Libplanet.Tests/Tx/TxFailureTest.cs
Libplanet.Tests/Tx/TxSuccessTest.cs
Libplanet/Blockchain/BlockChain.TxExecution.cs
Libplanet/Store/BaseStore.cs
Libplanet/Tx/TxExecution.cs
Libplanet/Tx/TxFailure.cs
Libplanet/Tx/TxSuccess.cs

Reasons for removal:
- Not in real use.
- Its source, `IActionContext.Logs`, is poorly implemented anyway. 🙄
Other than "it might be nice to have logs data flow back to libplanet and be useful somehow", I don't see a strong rationale for keeping it, at least for now.

🧹 Removed ActionsLogsList from TxExecution

---

.github/workflows/lint.yml
CHANGES.md
Libplanet.Net.Tests/Consensus/ConsensusContextProposerTest.cs
Libplanet.Net.Tests/Consensus/ContextNonProposerTest.cs
Libplanet.Net/Consensus/Context.cs
Libplanet.Net/Swarm.BlockSync.cs
Libplanet.Net/Transports/ITransport.cs
Libplanet.RocksDBStore/RocksDBStore.cs
Libplanet.Stun.Tests/Stun/Messages/BindingRequestSuccessTest.cs
Libplanet.Stun/Stun/TurnClient.cs
Libplanet.Tests/Store/StoreTest.cs
Libplanet/Blockchain/BlockChain.Evaluate.cs
Libplanet/Blockchain/BlockChain.ProposeBlock.cs
Libplanet/Blockchain/BlockChain.Validate.cs
Libplanet/Blocks/BlockCommit.cs
Libplanet/Blocks/BlockMarshaler.cs
Libplanet/Blocks/BlockMetadata.cs
Libplanet/ByteUtil.cs

This pull request fixes some typos with the `crates-ci/typos` CLI tool. And it introduces a new GitHub Actions workflow to check the `CHANGES.md` file's spelling at least.

ci(gh-actions): check typos

---

CHANGES.md
Libplanet.RocksDBStore/RocksDBStore.cs

Tested with 1,000,000 byte string pairs (or triples) of length `WordSize` below. Obviously as words get longer, the proportion of LINQ overhead decreases. However, for the most part, we are only concatenating small byte strings for most, if not all, cases.
BenchmarkDotNet=v0.13.2, OS=Windows 10 (10.0.19045.3086)
11th Gen Intel Core i7-1185G7 3.00GHz, 1 CPU, 8 logical and 4 physical cores
.NET SDK=7.0.203
[Host]     : .NET 6.0.5 (6.0.522.21309), X64 RyuJIT AVX2
DefaultJob : .NET 6.0.5 (6.0.522.21309), X64 RyuJIT AVX2
|            Method | WordSize |        Mean |     Error |     StdDev |      Median |        Gen0 |  Allocated |
|------------------ |--------- |------------:|----------:|-----------:|------------:|------------:|-----------:|
|   WithConcatPairs |       10 |   243.32 ms | …

⚡ `RocksDBStore` Concat optimization

---

CHANGES.md
Libplanet/ByteUtil.cs

Just squeezing some micro performance improvement. 😗
Tested on batch size of `100_000`.
|      Method | ByteStringSize |      Mean |    Error |    StdDev |    Median | Allocated |
|------------ |--------------- |----------:|---------:|----------:|----------:|----------:|
|  HexWithNew |             10 |  24.02 ms | 0.474 ms |  0.680 ms |  24.03 ms |  12.97 MB |
| HexWithRent |             10 |  13.21 ms | 0.259 ms |  0.505 ms |  13.17 ms |   6.87 MB |
|  HexWithNew |            100 |  92.30 ms | 1.844 ms |  4.558 ms |  91.67 ms |  81.64 MB |
| HexWithRent |            100 |  58.31 ms | 1.151 ms |  1.758 ms |  58.21 ms |   41.2 MB |
|  HexWithNew |           1000 | 409.74 ms | 8.723 ms | 25.306 ms | 402.72 ms | 768.28 MB |
| HexWithRent |           1000 | 327.40 ms | 6.537 ms | 11.619 ms | …

⚡ Faster `Hex` for netstandard2.1 and up

---

CHANGES.md
Libplanet.Net.Tests/Consensus/GossipConsensusMessageCommunicatorTest.cs
Libplanet.Net/Consensus/Gossip.cs

Fix flaky `GossipConsensusMessageCommunicatorTest` by checking `Gossip.DeniedPeers`.
- Add Gossip.DeniedPeers property
- Still sometimes this test cannot cover the cases when receiver couldn't received all messages within the delay. But at least, this test isn't flaky for test success any more.
(Not flaky for success, but still flaky for its coverage)

Fix flaky test `GossipConsensusMessageCommunicatorTest`

---

Docs/api/index.md
Docs/toc.yml

This pull request resolves https://github.com/planetarium/libplanet/issues/3301. After this pull request, the `API reference` tab will redirect to `api/Libplanet.Action.html` I chose `Libplanet.Action`because it is on the top of the left list. If you think other project should be the entry point, please leave a comment 🙏🏻

docs: fix docfx toc configuration

---

CHANGES.md
Libplanet.Action.Tests/State/KeyConvertersTest.cs
Libplanet.Action/ActionEvaluationsExtensions.cs
Libplanet.Action/State/AccountDeltaExtensions.cs
Libplanet.Action/State/AccountStateDeltaExtensions.cs
Libplanet.Action/State/BlockState.cs
Libplanet.Action/State/KeyConverters.cs
Libplanet.Store/StateStoreExtensions.cs
Libplanet.Tests/Fixtures/IntegerSet.cs
Libplanet.Tests/Store/StateStoreExtensionsTest.cs
Libplanet.Tests/Store/TrieStateStoreTest.cs
Libplanet/Blockchain/BlockChain.Evaluate.cs

Tested with 1,000,000 batch.
By "bypass" I mean direct `byte[]` to `byte[]` conversion without obtaining `string` representation in the middle.
Speed-wise not that great, but still reduces quite a bit in memory usage.
|                 Method |       Mean |      Error |     StdDev | Allocated |
|----------------------- |-----------:|-----------:|-----------:|----------:|
|             ToStateKey | 321.206 ms |  6.4224 ms | 13.8248 ms | 312.81 MB |
|       ToStateKeyBypass | 262.234 ms |  5.0044 ms |  5.7631 ms |  129.7 MB |
|               ToFAVKey | 536.196 ms | 10.3974 ms | 15.2403 ms | 785.83 MB |
|         ToFAVKeyBypass | 430.898 ms |  8.5690 ms | 19.5161 ms | 221.25 MB |
|       ToTotalSupplyKey | 408.493 ms |  7.9977 ms | 21.6222 ms | 427.25 MB |
| ToTotalSupplyKeyBypass | 312.920 …

⚡ Optimize `KeyBytes` derivation

---

.github/workflows/lint.yml
@planetarium/account-web3-secret-storage/test/TtyPassphraseEntry.test.ts
Libplanet.Action.Tests/Common/DumbAction.cs
Libplanet.Explorer.Tests/GraphQLTestUtils.cs
Libplanet.Explorer.ruleset
Libplanet.Explorer/GraphTypes/ActionType.cs
Libplanet.Net/Consensus/GossipConsensusMessageCommunicator.cs
Libplanet.Net/Transports/NetMQTransport.cs
Libplanet.Tests.ruleset
Libplanet.Tests/KeyStore/Kdfs/KdfTest.cs
Libplanet.ruleset
_typos.toml

This pull request makes the *Libplanet* repository's CI runs typos over all files, while it runs on only the `CHANGES.md` file before.
You can apply the `typos` command's check result by running it with the `-w` option. (i.e., `typos -w`).
You can see the `_typos.toml` spec in https://github.com/crate-ci/typos/blob/143cc59fab61e34b96188ba6745f902d7867bda0/docs/reference.md#config-fields.
You can see the TOML's syntax in https://toml.io/ko/v1.0.0 (Korean ver).

ci(gh-actions): check typos over all files

---

CHANGES.md
Libplanet.Action.Tests/State/KeyConvertersTest.cs
Libplanet.Extensions.Cocona.Tests/Commands/MptCommandTest.cs
Libplanet.Extensions.Cocona/Commands/MptCommand.cs
Libplanet.Store/StateStoreExtensions.cs
Libplanet.Store/Trie/KeyBytes.cs
Libplanet.Store/Trie/TrieExtensions.cs
Libplanet.Tests/Store/StateStoreExtensionsTest.cs
Libplanet.Tests/Store/Trie/KeyBytesTest.cs
Libplanet.Tests/Store/TrieStateStoreTest.cs

Removing encoding responsibility from `StateStoreExtensions`.
- It isn't at all clear which entity should actually be responsible for the encoding scheme.
- The general codebase is already severely infected with hardcoded encoding scheme (UTF8).
- Having `KeyBytes` to be encoding agnostic is nice and all, but in reality, there is no real way to use the library with a different encoding.
- Technically, `IStateStore` can be responsible for tracking how `string`s are encoded into bytes, but then `IStateStore` should track the encoding scheme not an extension class.
- On another note, allowing to mix `byte[]` and `string` to be mixed seem like a bad idea, as there is no way to determine whether a `KeyBytes` is derived from a byte string or a text string. 🙄
- To be usable at a higher level, …

🧹 Refactor to use `KeyBytes` instead of `string`s in general

---

@planetarium/account-web3-secret-storage/package.json
@planetarium/account-web3-secret-storage/src/Web3Account.ts
@planetarium/account-web3-secret-storage/test/Web3Account.test.ts
yarn.lock

Since @noble/hashes includes Scrypt, which is very reliable and fast,
I replaced scrypt-js with it. this also removes unnecessary dependency.
Quite surprisingly, while replacing this, I found out test vector for Web3 Secret Storage using Scrypt provided by ethereum official documentation was incorrectly generated. so I generated new correct test vector for Scrypt. you can find about this issue from https://github.com/ethereum/ethereum-org-website/pull/10825

Use @noble/hashes/scrypt instead of scrypt-js

---

CHANGES.md
Libplanet.Store/Trie/MerkleTrie.cs

Aside from unnecessarily being complicated and requiring more overhead, the previous version iterated over unnecessary elements.
Below was tested with a `MerkleTrie` with `Commit` number of commits where each commit has `Batch` number of fixed size random `Text`s and reading everything back.
|          Method | Commit | Batch |       Mean |      Error |     StdDev | Allocated |
|---------------- |------- |------ |-----------:|-----------:|-----------:|----------:|
|        GetBatch |    100 |     4 |   6.313 ms |  0.3403 ms |  0.3919 ms |   9.43 MB |
| GetBatchUpdated |    100 |     4 |   5.652 ms |  0.3036 ms |  0.3496 ms |   8.93 MB |
|        GetBatch |    100 |    16 |  30.940 ms |  1.5592 ms |  1.7956 ms |  43.85 MB |
| GetBatchUpdated |    100 |    16 |  27.860 ms |  1.3925 ms | …

♻️ Cleanup and optimize `MerkleTrie.Get()`

---

CHANGES.md
Libplanet.Store/Trie/ITrie.cs
Libplanet.Store/Trie/MerkleTrie.cs
Libplanet.Tests/Store/Trie/MerkleTrieTest.cs

Long overdue change to `ITrie`. Performance-wise, new `ITrie.Get(KeyBytes)` is not that significantly better as the overhead was minimal.
However, `MerkleTrie.Get()` can be more than twice as fast, depending on the environment and the number of `KeyBytes` given.
In order to leverage this properly, `IAccount.GetStates()` and `IAccount.GetState()` should refer to different `ITrie.Get()`. Depending on where the parallelism should reside, it might even be a good idea to get rid of `ITrie.Get(IReadOnlyList<KeyBytes>)`. 🙄

♻️ Added single `Get()` to `ITrie`

---

CHANGES.md
Libplanet.Net/Swarm.BlockSync.cs

This pull request just cherry-picks #3353 changes to the 3.1-maintenance branch to release 3.1.1 patch version. (because I suffer from the BlockCandidate bug...)

Cherry-pick #3353 to 3.1.1 version

---

CHANGES.md
Libplanet.Explorer.Executable/Program.cs
Libplanet.Store/IStateStore.cs
Libplanet.Store/Trie/VolatileKeyValueStore.cs
Libplanet.Store/TrieStateStore.cs
Libplanet.Tests/Store/StateStoreTracker.cs
Libplanet.Tests/Store/Trie/KeyValueStoreTest.cs
Libplanet.Tests/Store/Trie/VolatileKeyValueStoreTest.cs
Libplanet.Tests/Store/TrieStateStoreTest.cs
Libplanet/Blockchain/BlockChainStates.cs

Not quite usable yet since `IActionEvaluator` does not have direct access to `IStateStore`. Probably we'd want to change `IBlockChainStates` to give only read-only state view. 🙄

Introduce `VolatileKeyValueStore`

---

.circleci/config.yml

fix(ci): change macos resource

---

CHANGES.md
Libplanet.RocksDBStore/RocksDBKeyValueStore.cs
Libplanet.RocksDBStore/RocksDBStore.cs
Libplanet.RocksDBStore/RocksDBUtils.cs

This pull request resolves #3354.
RocksDB supports read-only mode so Libplanet's wrapper class supports it too. https://github.com/facebook/rocksdb/wiki/Read-only-and-Secondary-instances

feat(#3354): support rocksdb read-only mode

---

CHANGES.md
Libplanet.Store/Trie/MerkleTrie.Path.cs
Libplanet.Store/Trie/MerkleTrie.cs
Libplanet.Store/Trie/MerkleTrieExtensions.cs
Libplanet.Store/Trie/Nodes/BaseNode.cs
Libplanet.Store/Trie/Nodes/NodeDecoder.cs
Libplanet.Store/Trie/Nodes/ShortNode.cs
Libplanet.Tests/Store/Trie/MerkleTrieExtensionsTest.cs
Libplanet.Tests/Store/Trie/MerkleTriePathCursorTest.cs
Libplanet.Tests/Store/Trie/MerkleTrieTest.cs
Libplanet.Tests/Store/Trie/TrieTest.cs

Some notes on performance:
- `MerkleTrie.Get()` has become slightly slower.
- This is possibly due to using recursion on path resolution instead of a for loop with custom data `struct`ure.
- `MerkleTrie.Set()` and `MerkleTrie.Commit()` has become slightly faster.
- Probably because of lower amount of recursion and removal of `PathCursor`'s internal `byte` array copying.
I doubt the performance change is significant.
I could probably optimize this a bit, but I'd say its good enough for now. 🙄
Should be tested on a live chain before this gets merged. It isn't still clear that resulting trie layout will have
"the canonical layout", but the updated version is quite a bit more constrained than the existing one, which
heavily relied on code path and `KeyConverter` not producing a `KeyBytes` …

♻️ `MerkleTrie` overhaul

---

CHANGES.md
Libplanet.RocksDBStore/RocksDBKeyValueStore.cs
Libplanet.Store/Trie/CacheableKeyValueStore.cs
Libplanet.Store/Trie/DefaultKeyValueStore.cs
Libplanet.Store/Trie/IKeyValueStore.cs
Libplanet.Store/Trie/MemoryKeyValueStore.cs
Libplanet.Tests/Store/Trie/KeyValueStoreTest.cs

Closes #3362.
Probably a relic from the past where `IKeyValueStore` was being used directly. I can't quite see a specific use-case where this method might be handy. If we want multi-get at `IKeyValueStore` level instead of `ITrie` layer for performance reasons, then we might want to guarantee the ordering with `null`able return values. 🙄

🧹 Removed unused `IKeyValueStore.Get()`

---

Libplanet.Store/StoreExtensions.cs
Libplanet/Blockchain/BlockChain.Evaluate.cs

Resolves #3394.
Not the best looking solution. 🙄
This covers an edge case where a genesis `Block` is completely empty.

🧹 Fix `BlockChain.DetermineStateRootHash`

---

CHANGES.md
Libplanet.Store/Trie/MerkleTrie.Path.cs
Libplanet.Tests/Store/Trie/MerkleTrieTest.cs

Seems like the bug has been present since before 3.3.0. Fixes a possible early termination while traversing an `ITrie` due to a missing constraint.
For example, a `ValueNode` at path `1234` could be fetched at the end of a `ShortNode` with path `12345678`. 🙄

🐛 Fix `ITrie.Get()`

---

CHANGES.md
Libplanet.Action/ActionContext.cs
Libplanet.Action/CommittedActionContext.cs
Libplanet.Action/CommittedActionEvaluation.cs
Libplanet.Action/ICommittedActionContext.cs
Libplanet.Action/ICommittedActionEvaluation.cs
Libplanet.Action/Random.cs
Libplanet.Net/Consensus/Context.cs
Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
Libplanet.Tests/Blockchain/Renderers/AnonymousActionRendererTest.cs
Libplanet.Tests/Blockchain/Renderers/LoggedActionRendererTest.cs
Libplanet/Blockchain/BlockChain.Evaluate.cs
Libplanet/Blockchain/BlockChain.Swap.cs
Libplanet/Blockchain/BlockChain.TxExecution.cs
Libplanet/Blockchain/BlockChain.Validate.cs
Libplanet/Blockchain/BlockChain.cs
Libplanet/Blockchain/Renderers/AnonymousActionRenderer.cs
Libplanet/Blockchain/Renderers/AtomicActionRenderer.cs
Libplanet/Blockchain/Renderers/Debug/RecordingActionRenderer.cs
Libplanet/Blockchain/Renderers/Debug/RenderRecord.cs
Libplanet/Blockchain/Renderers/Debug/ValidatingActionRenderer.cs
Libplanet/Blockchain/Renderers/IActionRenderer.cs
Libplanet/Blockchain/Renderers/LoggedActionRenderer.cs

While committing, converts `IActionEvaluation`s to `ICommittedActionEvaluation`s. This should be temporary and be removed (or rather `IActionEvaluation` should be changed to match `ICommittedActionEvaluation`s format) once the commit process moves to `IActionEvaluator`.

♻️ Commit once for `IActionEvaluation`s

---

CHANGES.md
Libplanet.Action/ActionEvaluator.cs
Libplanet.Action/IActionEvaluator.cs
Libplanet.Tests/Action/ActionEvaluatorTest.cs
Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
Libplanet.Tests/Blocks/PreEvaluationBlockTest.cs
Libplanet.Tests/Store/StoreFixture.cs
Libplanet/Blockchain/BlockChain.Evaluate.cs
Libplanet/Blockchain/BlockChain.Swap.cs
Libplanet/Blockchain/BlockChain.cs

Finally moves commit to `IActionEvaluator`.
API-wise, there isn't much change, but a shift in responsibility could be considered rather big. 🙄

♻️ Commit from `IActionEvaluator`

---

CHANGES.md
Libplanet.Types/Blocks/BlockMarshaler.cs

⚡ 
I'd say we need to get rid of `Dictionary.GetValue<T>()` from `Bencodex`. 🙄
- Albeit trivial, it's not intuitively clear that its behavior is the same as `(T)dict[key]`.
- It is longer to type. So it isn't even that convenient to use.
- It is also missing `Dictionary.GetValue<T>(IKey)`, which should be the base implementation.
The only upside is not having to use additional pair of parentheses in certain cases. 🙄

⚡ Slightly optimized `BlockMarshaler`

---

Libplanet.Types/Consensus/Validator.cs
Libplanet.Types/Consensus/Vote.cs
Libplanet.Types/Consensus/VoteMetadata.cs
Libplanet/Consensus/Maj23.cs
Libplanet/Consensus/Maj23Metadata.cs
Libplanet/Consensus/Proposal.cs
Libplanet/Consensus/ProposalClaim.cs
Libplanet/Consensus/ProposalClaimMetadata.cs
Libplanet/Consensus/ProposalMetadata.cs
Libplanet/Consensus/VoteSetBits.cs
Libplanet/Consensus/VoteSetBitsMetadata.cs

🧹 In preparation for removal of such method in [bencodex.net](https://github.com/planetarium/bencodex.net).

🧹 Partial removal of `Bencodex.Types.Dictionary.GetValue<T>()` usage

---

@planetarium/account-aws-kms/package.json
@planetarium/account/package.json
@planetarium/tx/package.json

Previous update added mjs supports to `"import"`. It should be cjs supports for `"require"` because default module system is esm.

fix import mjs to require cjs

---

CHANGES.md
Libplanet.Action/Libplanet.Action.csproj
Libplanet.Common/Libplanet.Common.csproj
Libplanet.Crypto/Libplanet.Crypto.csproj
Libplanet.Explorer.Tests/GraphTypes/TransactionTypeTest.cs
Libplanet.Explorer/GraphTypes/ActionType.cs
Libplanet.Explorer/Libplanet.Explorer.csproj
Libplanet.Extensions.Cocona/Commands/ApvCommand.cs
Libplanet.Store/BaseStore.cs
Libplanet.Store/Libplanet.Store.csproj
Libplanet.Store/Trie/MerkleTrie.Path.cs
Libplanet.Store/Trie/MerkleTrie.cs
Libplanet.Store/Trie/Nodes/NodeDecoder.cs
Libplanet.Tests/Blocks/BlockMarshalerTest.cs
Libplanet.Types/Libplanet.Types.csproj
Libplanet.Types/Tx/TxMarshaler.cs
Libplanet/Libplanet.csproj

Upgrade `Bencodex` to `0.16.0`

---

.github/workflows/build.yaml

Since Node.js 20 became LTS, the `Build artifact and push` workflow has started to fail. I'm not sure about the relationship between the LTS release and the failure from `.pnp.cjs` file. Anyway, because the package deployment should be fixed, this pull request fixes the Nodejs' version to `18` from `lts/*`.
You can see the CI works at https://github.com/planetarium/libplanet/actions/runs/6687408748/job/18168014391?pr=3466.
When this pull request is merged, #3460 will be closed. And a new issue will be opened with `ci(gh-actions): use Nodejs 20 in CI`.
- `yarn / @planetarium/cli installation test` jobs are failing because the `3.7.0` tag was pushed but the packages were not deployed.

Use Nodejs 18

---

Libplanet.Action/AccountMetrics.cs
Libplanet.Action/ActionEvaluator.cs

Since `AccountMetrics.GetStateTimer` cannot be initialized, log always returns null value.
Fix above to log properly.

Fix `AccountMetrics` to initialize

---

@planetarium/tx/src/index.ts

Since the `encodeFungibleAssetValue` is not exported, users should import the function from the internal path like `@planetarium/tx/dist/assets...`. And it doesn't work in ESM mode. This pull request just re-exports the function to make users use it easily.

🔨 @planetarium/tx: export encodeFungibleAssetValue

---

CHANGES.md
Libplanet.Explorer.Tests/GeneratedBlockChainFixture.cs
Libplanet.Extensions.Cocona.Tests/Commands/StoreCommandTest.cs
Libplanet.Net.Tests/Consensus/ContextNonProposerTest.cs
Libplanet.Net.Tests/Consensus/ContextTest.cs
Libplanet.Net.Tests/SwarmTest.Preload.cs
Libplanet.Tests/Action/ActionEvaluatorTest.cs
Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
Libplanet.Tests/Blockchain/BlockChainTest.Internals.cs
Libplanet.Tests/Blockchain/BlockChainTest.ProposeBlock.cs
Libplanet.Tests/Blockchain/BlockChainTest.cs
Libplanet.Tests/Blocks/BlockContentTest.cs
Libplanet.Tests/Fixtures/BlockContentFixture.cs
Libplanet.Tests/Fixtures/IntegerSet.cs
Libplanet.Tests/Store/StoreFixture.cs
Libplanet.Tests/Store/StoreTest.cs
Libplanet.Tests/Tx/TransactionExtensionsTest.cs
Libplanet.Tests/Tx/TransactionTest.cs
Libplanet.Tests/Tx/TxFixture.cs
Libplanet.Tests/Tx/TxInvoiceTest.cs
Libplanet.Tests/Tx/UnsignedTxTest.cs
Libplanet.Types/AssemblyInfo.cs
Libplanet.Types/Tx/ITxInvoice.cs
Libplanet.Types/Tx/Transaction.cs
Libplanet.Types/Tx/TxInvoice.cs
Libplanet/Blockchain/BlockChain.cs

This partially deprecates uses of `Transaction.UpdatedAddresses` property. It is no longer allowed to create a `Transaction` with non-empty `UpdatedAddresses` property through normal means.
As it is still possible to create a `Transaction` with a non-empty `UpdatedAddresses` (in particular, when unmarshalling a marshalled `Transaction`) most `Transaction`s used in tests are left intact (especially those using fixtures) to keep the old behavior intact.

♻️ Disallow creation of new `Transaction`s with a non-empty `UpdatedAddresses`

---

.circleci/config.yml
CHANGES.md
Libplanet.RocksDBStore/Libplanet.RocksDBStore.csproj
Libplanet.RocksDBStore/RocksDBStore.cs

Our [Planetarium.RocksDbSharp](https://github.com/planetarium/rocksdb-sharp) is no longer a follow-up original [RocksDB](https://github.com/facebook/rocksdb) version.
But we need a new version of `RocksDB` for our new feature. So we decided to change to [RocksDb](https://github.com/curiosity-ai/rocksdb-sharp) by Curiosity-AI for the backend.
close https://github.com/planetarium/libplanet/issues/1848

replace: use `RocksDb` instead `Planetarium.RocksDbSharp`

---

package.json

🐛 Temporary workaround to `yarn build` fail

---

CHANGES.md
Libplanet.Common/NameValueCollectionExtensions.cs
Libplanet.RocksDBStore.Tests/RocksDBKeyValueStoreTest.cs
Libplanet.RocksDBStore.Tests/RocksDBStoreTest.cs
Libplanet.RocksDBStore/RocksDBInstanceType.cs
Libplanet.RocksDBStore/RocksDBKeyValueStore.cs
Libplanet.RocksDBStore/RocksDBStore.cs
Libplanet.RocksDBStore/RocksDBUtils.cs
Libplanet.RocksDBStore/RocksDbInstanceType.cs

**Caution: Merge https://github.com/planetarium/libplanet/pull/3487 first**
`RocksDb` has 3 instance types: `Primary`, `ReadOnly`, and `Secondary`. [(see also)](https://github.com/facebook/rocksdb/wiki/Read-only-and-Secondary-instances) But we support only `Primary` and `ReadOnly` right now.
For more scalable rocksdb, we introduce the `Secondary` instance type on `Libplanet.RocksDBStore`.

➕  introduce: `RocksDb` instance type

---

CHANGES.md
Libplanet.Net/Consensus/GossipConsensusMessageCommunicator.cs

There's a bug on gossip denial, and this PR fixes it.
Though adding `_peerCatchupRounds.Clear()` on `GossipConsensusMessageCommunicator.cs L69` is enough to solve the problem, added some height validation not to be confused.
(This will be needless after sync between `Gossip` and `HeightVoteSet`)
This PR Resolves
- https://github.com/planetarium/libplanet/issues/3518

Fix bug on gossip denial

---

package.json

See #3492. Running the command twice is presented as a temporary workaround until the culprit is found.

Workaround for yarn install fail

---

CHANGES.md
Libplanet.Action/ActionEvaluator.cs
Libplanet.Net.Tests/Consensus/ContextNonProposerTest.cs
Libplanet.Net.Tests/Messages/MessageTest.cs
Libplanet.Tests/Action/ActionEvaluatorTest.cs
Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
Libplanet.Tests/Blockchain/BlockChainTest.Internals.cs
Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
Libplanet.Tests/Blocks/BlockMetadataTest.cs
Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
Libplanet.Types/Blocks/BlockMetadata.cs

Migrate legacy states to `World-Account`-based structure when evaluating block with protocol version `5`.

Adjust timing of the state migration

---

CHANGES.md
Libplanet.Tests/Tx/TxInvoiceTest.cs
Libplanet.Types/Tx/TxInvoice.cs

Allowing all possible combinations of `null` and non-`null` leads to some non-sensical scenarios concerning fee collection.
This strictly prohibits such possibility by restricting possible cases.
- Both `MaxGasPrice` and `GasLimit` are `null`: This is allowed for backward compatibility.
- Both `MaxGasPrice` and `GasLimit` are non-`null`: This is used for "normal" fee collection process.
As [Lib9c](https://github.com/planetarium/lib9c) started to filter those `Transaction`s with either `MaxGasPrice` and `GasLimit` being `null` at the same time as `MaxGasPrice` and `GasLimit` were introduced, we can safely assume all `Transaction`s included in 9c chain are among the types listed above.

♻️ Update `TxInvoice` specification

---

CHANGES.md
Libplanet.Action.Tests/ActionContextTest.cs
Libplanet.Action.Tests/ActionEvaluationTest.cs
Libplanet.Action.Tests/Sys/InitializeTest.cs
Libplanet.Action/ActionContext.cs
Libplanet.Action/ActionEvaluator.cs
Libplanet.Action/IActionContext.cs
Libplanet.Action/ITxContext.cs
Libplanet.Action/State/Account.cs
Libplanet.Action/State/IAccount.cs
Libplanet.Action/TxContext.cs
Libplanet.Explorer.Tests/Queries/StateQueryTest.cs
Libplanet.Tests/Action/AccountDiffTest.cs
Libplanet.Tests/Action/AccountV0Test.cs
Libplanet.Tests/Action/AccountV1Test.cs
Libplanet.Tests/Blockchain/Renderers/AnonymousActionRendererTest.cs
Libplanet.Tests/Blockchain/Renderers/LoggedActionRendererTest.cs

We've been kicking this can down the road for far too long. The recurring cost induced by the lack of an additional scope seems far too great (yet I suspect it'll incur even more down the road when we try to implement PoS).
The problem is essentially trying to do **everything** with `IActionContext` which is single-scoped, while the data structure and its evaluation is three-layered, i.e. `Block`, `Transaction`, and `Action`.
I've tried to leave much of the API intact as much as possible.

♻️ `ActionEvaluator` context scoping

---

@planetarium/tx/src/tx/signed.ts
CHANGES.md

Since `SystemAction` and `CustomAction` are unified, there is only `UnsignedTx`, not `UnsignedTxWithCustomActions` & `UnsignedTxWithSystemAction`. So `SignedTx<T>`'s `T` generic argument became useless. This pull request just cleans up it.

@planetarium/tx: Remove useless template variable

---

CHANGES.md
Libplanet.Action.Tests/State/AccountBaseStateTest.cs
Libplanet.Action.Tests/State/WorldBaseStateTest.cs
Libplanet.Action/ActionEvaluator.cs
Libplanet.Action/IActionEvaluator.cs
Libplanet.Action/State/AccountBaseState.cs
Libplanet.Action/State/TrieExtensions.cs
Libplanet.Action/State/TrieMetadata.cs
Libplanet.Action/State/TrieType.cs
Libplanet.Action/State/WorldBaseState.cs
Libplanet.Tests/Action/ActionEvaluatorTest.cs
Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
Libplanet/Blockchain/BlockChain.Evaluate.cs
Libplanet/Blockchain/BlockChain.Swap.cs

This PR adds metadata to trie, which to address of length 0, cannot be created through provided APIs.
Afterwards, `World` will be treated as `non-legacy` if given trie has metadata. If not, the trie will be treated as legacy.

Add metadata for tries

---

CHANGES.md
Libplanet.Explorer.Tests/GeneratedBlockChainFixture.cs
Libplanet.Explorer.Tests/GraphTypes/TxResultTypeTest.cs
Libplanet.Explorer.Tests/Queries/TransactionQueryGeneratedTest.cs
Libplanet.Explorer/GraphTypes/TxStatusType.cs
Libplanet.Explorer/Queries/TransactionQuery.cs

Since `Libplanet.Explorer` is half broken, this doesn't work properly on 9c-mainnet. Appropriate changes should be made in `TransactionHeadlessQuery` on the [9c-headless](https://github.com/planetarium/NineChronicles.Headless) side to utilize this feature. 🙄

✨ Added `TxStatus.INCLUDED`

---

CHANGES.md
Libplanet.Explorer.Tests/Queries/StateQueryTest.cs
Libplanet.Explorer/GraphTypes/BencodexValueType.cs

See [this discussion](https://github.com/planetarium/libplanet/discussions/3548). In particular, this breaks `stateQuery`, but it isn't yet being used widely yet (and I have plans to entirely overhaul the whole thing). 🙄

♻️ Allow to choose output format of `BencodexValueType`

---

Libplanet.RocksDBStore/RocksDBKeyValueStore.cs

Since we updated `RocksDb`, it was newly introduced`PendingCompactionLimit`. But its default value is too low to use `NineChronicles`.
We introduce the `DbOptions` argument for the `RocksDBKeyValueStore.ctor` and optimize the default `PendingCompactionLimit` value.

feat: new argument for `RocksDBKeyValueStore.ctor`

---

Libplanet.Action/ActionEvaluator.cs

♻️ It turns out there are cases where `ActionEvaluator` fails to evaluate a `IPreEvaluationBlock` but no logging occurs. 😥

♻️ Additional error logging for better debugging

---

CHANGES.md
Libplanet.Explorer.Tests/Queries/HelperQueryTest.cs
Libplanet.Explorer/Queries/ExplorerQuery.cs
Libplanet.Explorer/Queries/HelperQuery.cs

Same as #3552. Just reopening it for more sensible PR timeline. 😗

✨ QoL GraphQL queries

---

CHANGES.md
Libplanet.Explorer.Tests/Queries/TransactionQueryGeneratedTest.cs
Libplanet.Explorer/Queries/ExplorerQuery.cs
Libplanet.Explorer/Queries/TransactionQuery.cs
Libplanet.Explorer/Store/IRichStore.cs
Libplanet.Explorer/Store/LiteDBRichStore.cs
Libplanet.Explorer/Store/MySQLRichStore.cs

`UpdatedAddresses` has pretty much lost its meaning, and is no longer used. There really isn't any reason to index this property anymore. 😗
Unless there is a plan to use `IRichStore`, we should remove `IRichStore` entirely if we get a chance.
- `TxId` to `BlockHash` mapping is already being handled by `IStore` (although, `IStore`'s version has its own problems).
- The only remaining functionality not supported by `IStore` directly is `Address` (signer) to `TxId` mapping.
My personal thought on this matter is that there should be a clear distinction between what should be the "core" functionalities of `IStore` (necessary for `BlockChain`'s operation) and "auxiliary" functionalities.
For instance, `TxId` -> `BlockHash` indexing, `Address` -> `TxId` indexing, and `TxResult` all could be …

♻️ Removed updated addresses from `IRichStore`

---

CHANGES.md
Libplanet.Tests/Action/ActionEvaluatorTest.cs
Libplanet.Tests/Tx/TxInvoiceTest.cs
Libplanet.Types/Tx/ITxInvoice.cs
Libplanet.Types/Tx/TxInvoice.cs

Still running diagnostics on 9c chain (both Odin and Heimdall). Heimdall was clean, and I'm about 50% done with Odin. So far there doesn't seem to be any problem (i.e. no `Transaction`s with a negative gas value). I'll merge once the entire chain is inspected.

♻️ Refactor tx gas policy

---

CHANGES.md
Libplanet.Store/Trie/Nodes/NodeDecoder.cs
Libplanet.Store/Trie/Nodes/ShortNode.cs

`ShortNode` doesn't share enough structure/functionality with `FullNode` to be siblings to each other. 🙄
I'll be refactoring `FullNode` shortly.

♻️ Refactor `ShortNode`

---

CHANGES.md
Libplanet.Store/Trie/ITrie.cs
Libplanet.Store/Trie/MerkleTrie.Remove.cs
Libplanet.Store/Trie/MerkleTrie.cs
Libplanet.Store/Trie/Nodes/FullNode.cs
Libplanet.Tests/Store/Trie/MerkleTrieTest.cs

Finally adds "value removal" to `ITrie`.
Added `ITrie.SetNull()` and `FullNode.RemoveChild()` as separate methods in order to keep backwards compatibility as much as possible.
I'll add `IAccount.RemoveState()` in a separate PR.

✨ Add `Trie.Remove()`

---

CHANGES.md
Libplanet.Action/State/Account.cs
Libplanet.Action/State/IAccount.cs
Libplanet.Explorer.Tests/Queries/StateQueryTest.cs
Libplanet.Tests/Action/AccountTest.cs

Related to #3576. Allows access to newly added `ITrie.Remove()` from `IAccount.RemoveState()`.

✨ Add `IAccount.RemoveState()`

---

CHANGES.md
Libplanet.Explorer.Tests/Queries/StateQueryTest.cs
Libplanet.Explorer/GraphTypes/LegacyBencodexValueType.cs
Libplanet.Explorer/Queries/StateQuery.cs

This should resolve the backwards compatibility issue with services already using the `states` query.
It needs to be phased out anyway, so might as well keep it. 🙄
P.S. From what I gather, `LegacyBencodexValueType` was implemented wrongly in the first place (serialization and parse mismatch, implicit base64 representation in playground, etc.). Hence, resulting in such an awkward way to force backwards compatibility in this PR. 😐

♻️ ⏪ Revert changes for old queries

---

CHANGES.md
Libplanet.Explorer.Tests/Queries/StateQueryTest.cs
Libplanet.Explorer/GraphTypes/AccountStateType.cs
Libplanet.Explorer/Queries/StateQuery.cs

Adds more modular and reusable `AccountStateType` to GraphQL queries.
As seen in its implementation, this is pretty lousy. I tried to remove `Currency`/`FungibleAssetValue` context from state query, but this has resulted in severe API inconsistency. 😥
This issue is mainly due to `IAccount` having two roles:
- Knowing the data model stored in the database: Where to retrieve the data by using an "appropriate" key-conversion.
- Interpreting the retrieved data: Implicitly converting `null` to zero-amount `FungibleAssetValue` for given `Currency`.
As it stands, there is **no possible way** to know (although whether this is necessary might be debatable) how `Currency` related data is stored within the storage entirely from the library side ([libplanet]) or the client side ([lib9c]).
- When …

✨ New state querying scheme

---

CHANGES.md
Libplanet.Action/State/IBlockChainStates.cs
Libplanet.Explorer.Tests/Queries/StateQueryTest.cs
Libplanet.Tests/Action/AccountTest.cs
Libplanet.Tests/Action/AccountV0Test.cs
Libplanet.Tests/Action/AccountV1Test.cs
Libplanet/Blockchain/BlockChain.States.cs
Libplanet/Blockchain/BlockChainStates.cs

This PR refactors `IBlockChainStates` interface's parameter order as following order.
- `BlockHash` > `AccountAddress` > `Address`
- `StateRootHash` > `Address`

Refactor `IBlockChainStates` interface

---

.github/workflows/yarn.yaml

I got an alert from GitHub about https://github.com/advisories/GHSA-mcph-m25j-8j63. As I understood there are no parts to be injected like the examples but I don't think I'll be able to recognize it when I use it in the future, so I proactively upgrade the version.

ci(gh-actions): bump tj-actions/changed-files action 

---

CHANGES.md
Libplanet.Action/State/IBlockChainStates.cs
Libplanet.Explorer.Tests/Queries/StateQueryTest.Mocks.cs
Libplanet/Blockchain/BlockChain.States.cs
Libplanet/Blockchain/BlockChainStates.cs

Also with more consistent API. 😶
For example, most methods use either `BlockHash` or `HashDigest<SHA256>` as a reference point in time, but a method pair such as `GetState(BlockHash, Address)` and `GetState(HashDigest<SHA256>, Address, Address)` is quite **confusing** as to what it does and/or how `IBlockChainStates` was designed. 🙄

🧹 Leaner `IBlockChainStates`

---

Libplanet.Types/Blocks/IBlockMetadata.cs

📝 Just so that we can find relevant changes more easily pertaining to `BlockProtocolVersion`. 😗

📝 History of `BlockProtocolVersion`

---

CHANGES.md
Libplanet.Action/ActionEvaluator.cs
Libplanet.Action/IActionEvaluator.cs
Libplanet.Tests/Action/ActionEvaluatorTest.cs
Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
Libplanet/Blockchain/BlockChain.Evaluate.cs
Libplanet/Blockchain/BlockChain.Swap.cs

⏪ This changes (removes) the assumption that a block's output state's version is the same as the block's protocol version.
The rationale being:
- This **does not change** the fact that when evaluating a block, every `IAction` inside the block expects a state that has the same version as the block's protocol version (for those with version number greater than or equal to 5). This is because migration happens during the preparation phase.
- As far as I know, the assumption, for example, that the output state of a block with protocol version `5` has a state version `5` is not used anywhere (there may be certain cases where this may be useful, but the development/overhead cost is too great to impose such restriction). The first point, that is, every `IAction` in any block with protocol …

⏪ Revert changes to `IActionEvaluator` interface

---

CHANGES.md
Libplanet.Store/IStateStore.cs
Libplanet.Store/Trie/MerkleTrie.Diff.cs
Libplanet.Store/Trie/MerkleTrie.Insert.cs
Libplanet.Store/TrieStateStore.Commit.cs
Libplanet.Tests/Store/TrieStateStoreCommitTest.cs

With better specification. 😶
This only affects edge cases where the committed `ITrie` is so small its entire `IValue` encoding length is than `HashDigest<SHA256>.Size`. There are possible cases where other storage related methods may fail due to this.

🐛 Fixed `IStateStore.Commit()`

---

Libplanet.Store/TrieStateStore.cs
Libplanet.Tests/Store/TrieStateStoreTest.cs

Should work for now unless some value has been set to an empty `KeyBytes` (which is unlikely) by some outside means. 🙄

♻️ Refactor `TrieStateStore.CopyStates()`

---

CHANGES.md
Libplanet.Store/Trie/TrieExtensions.cs
Libplanet.Store/Trie/TrieMetadata.cs
Libplanet.Tests/Store/TrieStateStoreTest.cs

♻️ Seems like it'd be more suitable to have it in `Libplanet.Store` than `Libplanet.Action.State`.

♻️ Move `TrieMetadata` to `Libplanet.Store`

---

CHANGES.md
Libplanet.Store/Trie/MerkleTrie.cs

Does depth first iteration instead of breath first iteration, which should reduce the amount of memory used to a negligible size.

⚡ Optimize `TrieStateStore.CopyStates()`

---

Libplanet.Action.Tests/Libplanet.Action.Tests.csproj
Libplanet.Analyzers.Tests/Libplanet.Analyzers.Tests.csproj
Libplanet.Crypto.Secp256k1.Tests/Libplanet.Crypto.Secp256k1.Tests.csproj
Libplanet.Explorer.Cocona.Tests/Libplanet.Explorer.Cocona.Tests.csproj
Libplanet.Explorer.Tests/Libplanet.Explorer.Tests.csproj
Libplanet.Extensions.Cocona.Tests/Libplanet.Extensions.Cocona.Tests.csproj
Libplanet.Net.Tests/Consensus/ConsensusContextTest.cs
Libplanet.Net.Tests/Consensus/ContextProposerTest.cs
Libplanet.Net.Tests/Libplanet.Net.Tests.csproj
Libplanet.RocksDBStore.Tests/Libplanet.RocksDBStore.Tests.csproj
Libplanet.Stun.Tests/Libplanet.Stun.Tests.csproj
Libplanet.Tests/Libplanet.Tests.csproj

⬇️ Downgrade xUnit packages to fix CI

---

CHANGES.md
Libplanet.Explorer/GraphTypes/BlockCommitType.cs
Libplanet.Explorer/GraphTypes/BlockType.cs
Libplanet.Explorer/GraphTypes/CurrencyType.cs
Libplanet.Explorer/GraphTypes/HashDigestSHA256Type.cs
Libplanet.Explorer/GraphTypes/TransactionType.cs
Libplanet.Explorer/GraphTypes/TxResultType.cs
Libplanet.Explorer/Queries/BlockQuery.cs
Libplanet.Explorer/Queries/StateQuery.cs
Libplanet.Explorer/Queries/TransactionQuery.cs

🔀 Merge 4.0.3 to main

---

Libplanet.Action.Tests/Libplanet.Action.Tests.csproj
Libplanet.Analyzers.Tests/Libplanet.Analyzers.Tests.csproj
Libplanet.Crypto.Secp256k1.Tests/Libplanet.Crypto.Secp256k1.Tests.csproj
Libplanet.Explorer.Cocona.Tests/Libplanet.Explorer.Cocona.Tests.csproj
Libplanet.Explorer.Tests/Libplanet.Explorer.Tests.csproj
Libplanet.Extensions.Cocona.Tests/Libplanet.Extensions.Cocona.Tests.csproj
Libplanet.Net.Tests/Libplanet.Net.Tests.csproj
Libplanet.RocksDBStore.Tests/Libplanet.RocksDBStore.Tests.csproj
Libplanet.Stun.Tests/Libplanet.Stun.Tests.csproj
Libplanet.Tests/Libplanet.Tests.csproj

This PR resolves problems when running command `dotnet test --filter <option>`
* Fix an issue where the collected test list differs from the expected one.
- https://xunit.net/releases/visualstudio/2.5.1
* Fixed an issue that caused an error when running `dotnet test` command.
Additionally, I've set the package versions to the same value across all test projects.
```xml
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.3.1" />
<PackageReference Include="xunit.runner.visualstudio" Version="2.5.6" />
```

Fixed an issue that caused an error when testing dotnet

---

CHANGES.md
Libplanet.Net.Tests/BlockCandidateTableTest.cs
Libplanet.Net/AppProtocolVersion.cs
Libplanet.Net/AssemblyInfo.cs
Libplanet.Net/BlockCompletion.cs
Libplanet/Blockchain/Branch.cs

🔪 This PR contains only other changes, excluding code related to swarm and transfer.

Removal of '#nullable disable' from the Libplanet.Net project (etc)

---

CHANGES.md
Libplanet.Action/ActionEvaluator.cs

This removes unnecessary multiple commits for data at `(Address, Address)`. 😶

♻️ ⚡ Optimized action evaluator

---

CHANGES.md
Libplanet.Action/FeeCollector.cs
Libplanet.Tests/Action/ActionEvaluatorTest.cs

`TotalUpdatedFungibleAssets` has been omitted since replacement of `Account` has been happend on `Mortgage`.
This makes `TotalUpdatedFungibleAssets` of transactions untractable, except last transaction of block.
This was an unintended error, so fix on this PR.

Fix Mortgage not to clean TotalUpdatedFungibleAssets

---

CHANGES.md
Libplanet.Store/Trie/MerkleTrie.cs

This should've been done in #3634. 🙄

⚡ Optimized `ITrie.IterateNodes()`

---

Libplanet.Net.Tests/NullableSemaphoreTest.cs

Sometimes `NullableSemaphoreTest` test failed.
Because of resource (count variable) sharing between threads, `count` value can be smaller than expected value.
So instead of simply incrementing the count, I improved it by using `Interlocked` to make sure the test doesn't fail.

Fixed a test failure due to resource sharing between threads.

---

.github/workflows/benchmarks-merged.yml
.github/workflows/benchmarks-pr.yml

SSIA
Note we do not have the `macos-8cores`. For effectiveness, opt out of the macos benchmark until we introduce macos self-hosted large runner.

🔀 ci: use large runner

---

CHANGES.md

-  Removed the '#nullable disable' from 3 projects
(Action, Common, Explorer). [[#3622]]
-  Removed the '#nullable disable' from the Libplanet.Store project. [[#3644]]
-  Removed the '#nullable disable' from the Libplanet.RocksDBStore project.
[[#3651]]
-  Removed `BaseIndex` class and changed `BlockSet` base class from
`BaseIndex<BlockHash, Block>` to `IReadOnlyDictionary<BlockHash, Block>`.
[[#3686]]
-  (Libplanet.Net) Changed some types due to removal of 'nullable keyword'.
[[#3669]]
- Changed `blocks` parameter type of `Branch` class constructor from
`IEnumerable<(Block, BlockCommit)>` to
`IEnumerable<(Block, BlockCommit?)>`.
- Changed `AppProtocolVersion.Extra` field type from `IValue` to `IValue?`.
- Changed `extra` parameter type of `AppProtocolVersion` class constructor
from …

🚀  release: 4.1.0

---

CHANGES.md
Libplanet.Action/ActionEvaluator.cs
Libplanet.Action/State/IWorldDelta.cs
Libplanet.Action/State/WorldDelta.cs

🧹 Closes #3694.
Since `TotalUpdatedFungibleAssets` have moved to `IWorld`, `IWorldDelta` can be cleared during commit. 🙂

🧹 Removed unnecessary methods and properties from `IWorldDelta`

---

CHANGES.md
Libplanet.Action/ActionContext.cs
Libplanet.Action/ActionEvaluator.cs
Libplanet.Action/IActionContext.cs
Libplanet.Tests/Action/ActionEvaluatorTest.cs

In preparation to remove `TotalUpdatedFungibleAssets` from `IWorld`.
Having volatile non-state dependency in two different places, namely `IActionContext` and `IWorld`, is causing too much trouble. 🙄
Also since `ActionEvaluator` is doing more and more heavy lifting in terms of context management, I've widened the scope from which its evaluating methods can pull necessary context from (it was also to avoid adding an additional parameter to numerous methods). This might come in handy later when we introduce evidences. 😗

✨ ♻️ Added `Txs` property to `IActionContext`

---

CHANGES.md
Libplanet.Action/ActionEvaluator.cs
Libplanet.Action/State/IWorld.cs
Libplanet.Action/State/IWorldExtensions.cs
Libplanet.Action/State/IWorldState.cs
Libplanet.Action/State/World.cs
Libplanet.Action/State/WorldBaseState.cs
Libplanet.Mocks/MockWorldState.cs

Now that `TotalUpdatedFungibleAssets` property has been removed in #3714, we can move `Currency` related manipulation logic up one layer. 😗

♻️ 🚚 Moved `Currency` and `Validator` related methods from `IWorldState` and `IWorld` to an extension `class`

---

Libplanet.Action.Tests/ActionEvaluationTest.cs
Libplanet.Action.Tests/Common/DumbAction.cs
Libplanet.Action.Tests/Common/DumbModernAction.cs
Libplanet.Action.Tests/Loader/IndexedActionLoaderTest.cs
Libplanet.Action.Tests/Sys/RegistryTest.cs
Libplanet.Benchmarks/AppendBlock.cs
Libplanet.Benchmarks/ProposeBlock.cs
Libplanet.Net.Tests/SwarmTest.Broadcast.cs
Libplanet.Net.Tests/SwarmTest.Fixtures.cs
Libplanet.Net.Tests/SwarmTest.Preload.cs
Libplanet.Net.Tests/SwarmTest.cs
Libplanet.Tests/Action/ActionEvaluatorTest.cs
Libplanet.Tests/Action/WorldTest.cs
Libplanet.Tests/Action/WorldV0Test.cs
Libplanet.Tests/Action/WorldV1Test.cs
Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
Libplanet.Tests/Blockchain/BlockChainTest.ProposeBlock.cs
Libplanet.Tests/Blockchain/BlockChainTest.cs
Libplanet.Tests/Tx/TransactionExtensionsTest.cs
Libplanet.Tests/Tx/TransactionTest.cs
Libplanet.Tests/Tx/TxActionListTest.cs
Libplanet.Tests/Tx/TxInvoiceTest.cs
Libplanet.Tests/Tx/UnsignedTxTest.cs

♻️ I presume refactoring of `DumbAction` has been neglected in order to avoid updating other tests, especially the fixtures. As such, `DumbAction`s behavior is not so "dumb" anymore with several convoluted edge cases. This is an attempt to modernize `DumbAction` itself. This only changes the API in preparation to redefine `DumbAction` in a follow-up PR. 🙄

♻️ Overhaul `DumbAction`

---

Libplanet.Action.Tests/ActionEvaluationTest.cs
Libplanet.Action.Tests/Common/DumbAction.cs
Libplanet.Action.Tests/Common/DumbModernAction.cs
Libplanet.Action.Tests/Loader/IndexedActionLoaderTest.cs
Libplanet.Action.Tests/Sys/RegistryTest.cs
Libplanet.Benchmarks/AppendBlock.cs
Libplanet.Benchmarks/ProposeBlock.cs
Libplanet.Net.Tests/SwarmTest.Broadcast.cs
Libplanet.Net.Tests/SwarmTest.Fixtures.cs
Libplanet.Net.Tests/SwarmTest.Preload.cs
Libplanet.Net.Tests/SwarmTest.cs
Libplanet.Tests/Action/ActionEvaluatorTest.cs
Libplanet.Tests/Action/WorldTest.cs
Libplanet.Tests/Action/WorldV0Test.cs
Libplanet.Tests/Action/WorldV1Test.cs
Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
Libplanet.Tests/Blockchain/BlockChainTest.ProposeBlock.cs
Libplanet.Tests/Blockchain/BlockChainTest.cs
Libplanet.Tests/Tx/TransactionExtensionsTest.cs
Libplanet.Tests/Tx/TransactionTest.cs
Libplanet.Tests/Tx/TxActionListTest.cs
Libplanet.Tests/Tx/TxInvoiceTest.cs
Libplanet.Tests/Tx/UnsignedTxTest.cs

♻️ `Create()` factory method was added to have all operations optional. Mint and burn operations are differentiated from transfer by nullability. I'll add test codes regarding this new feature in a follow-up PR.

♻️ Add mint and burn functionality to `DumbAction`

---

Libplanet.Action.Tests/Common/DumbAction.cs
Libplanet.Action.Tests/Common/DumbModernAction.cs

See #3722. Testing the behavior of random has been moved to `ContextRecordingAction` and is no longer used by `DumbAction`.

🧹 Removed RecordRandom from DumbAction

---

Libplanet.Action.Tests/Common/Currencies.cs
Libplanet.Tests/Action/WorldTest.cs

See also #3724. It turns out, `DumbAction` is too dumb in terms of handling variety of scenarios needed. 🙄

♻️ Shared `Currencies` for testing

---

CHANGES.md
Libplanet.Action/State/Account.cs
Libplanet.Action/State/IAccount.cs
Libplanet.Tests/Action/AccountTest.cs

Actually, just opens private method to public.

Introduce `IAccount.SetValidatorSet()` method

---

CHANGES.md
Libplanet.Explorer.Executable/Program.cs
Libplanet.Store/DefaultStore.cs
Libplanet.Store/Libplanet.Store.csproj

⬆️ Older versions have a known critical security vulnerability. See [Here](https://nvd.nist.gov/vuln/detail/CVE-2022-23535).
I haven't thoroughly gone through the changes, but the following options have been removed:
- `journal`: Seems like this option has been entirely removed by [LiteDB]. I presume this is controlled automatically depending on the type of disk used.
- `indexCahceSize`: This has been changed to a constant in [LiteDB] with no control possible on our end.
- `flush`: Seems like the option has been taken away in [LiteDB] and always flushes to disk when a disk is being used.
PS. Newer versions such as 5.0.17 and 5.0.19 doesn't work properly for some reason and I have failed to resolve the issue. 😥
[LiteDB]: https://github.com/mbdavid/LiteDB

⬆️ Bump Litedb to 5.0.15

---

CHANGES.md

🚀 Release 4.3.0

---

CHANGES.md
Libplanet.Store/Trie/TrieMetadata.cs
Libplanet.Tests/Store/Trie/TrieMetadataTest.cs

♻️ As we need more granular control over `IWorld` data model, `TrieMetadata` needs to be more well defined.

♻️ Refactor `TrieMetadata`

---

CHANGES.md
Libplanet.Net.Tests/Messages/MessageTest.cs
Libplanet.Tests/Action/ActionEvaluatorTest.cs
Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
Libplanet.Tests/Blocks/BlockMetadataTest.cs
Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
Libplanet.Types/Blocks/BlockMetadata.cs

Preparatory work to introduce a new backend `ITrie` model. Done in advance due to `TrieMetadata` no longer being able to be created with future protocol version. 🙄

♻️ ⬆️ Bump block protocol version to 6

---

CHANGES.md
Libplanet.Action/ActionEvaluator.cs
Libplanet.Action/State/IWorldExtensions.cs
Libplanet.Action/State/ReservedAddresses.cs
Libplanet.Action/State/ValidatorSetAccount.cs
Libplanet.Mocks/MockWorldState.cs
Libplanet.Store/Trie/TrieMetadata.cs
Libplanet.Tests/Action/ActionEvaluatorTest.Migration.cs
Libplanet.Tests/Action/ActionEvaluatorTest.cs
Libplanet.Tests/Action/WorldTest.cs
Libplanet.Tests/Action/WorldV6Test.cs
Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
Libplanet.Types/Blocks/BlockMetadata.cs

Similar to how `ITrie` migrated to `IWorld.Modern`, this introduces migration to a new backend model where validator sets are stored in a separate `IAccount` specifically for `ValidatorSet`.

✨ Introduce `ValidatorSetAccount`

---

CHANGES.md
Libplanet.Explorer.Tests/Queries/StateQueryTest.cs
Libplanet.Explorer/GraphTypes/WorldStateType.cs

This is to accommodate `RemoteWorldState` in [lib9c](https://github.com/planetarium/lib9c).

✨ Added version field to world state query

---

CHANGES.md
Libplanet.Explorer.Executable/Program.cs
Libplanet.Store/DefaultStore.cs
Libplanet.Store/Libplanet.Store.csproj

⏪ Due to a feedback that this is unusually slow for 9c local development.

⏪ Revert litedb upgrade

---

CHANGES.md
Libplanet.Types/Blocks/BlockMetadata.cs

♻️ More descriptive constants together with addition of `CurrencyAccountProtocolVersion` (which does nothing at the moment). This is done to split the introduction of `CurrencyAccount` and `ITrie` migration. 😗

♻️ Updated `BlockMetadata`

---

Libplanet.Action/ActionEvaluator.cs
Libplanet.Action/State/IStateStoreExtensions.cs
Libplanet.Tests/Action/ActionEvaluatorTest.Migration.cs
Libplanet.Tests/Action/ActionEvaluatorTest.cs
Libplanet.Tests/Blockchain/BlockChainTest.cs

Separates `IWorld` interpretation logic from `IActionEvaluator`.

♻️ Refactor world migration

---

CHANGES.md
Libplanet.Action/State/CurrencyAccount.cs
Libplanet.Action/State/IStateStoreExtensions.cs
Libplanet.Action/State/IWorldExtensions.cs
Libplanet.Mocks/MockWorldState.cs
Libplanet.Tests/Action/ActionEvaluatorTest.Migration.cs
Libplanet.Tests/Action/WorldTest.cs
Libplanet.Tests/Action/WorldV7Test.cs

The implementation is pretty convoluted at the moment. 🙄
There are numerous issues regarding `Currency`:
- It isn't at all clear who should be responsible of keeping a state "consistent" regarding a `Currency`.
- "Consistency" is purely enforced by code, not stored data.
- The whole `Currency` manipulation pipeline is running on top of the assumption that a state is "consistent"
- There are two relations that can be checked purely from state + `Currency`:
- Whether `TotalSupply` does not exceed `MaximumSupply`
- Whether `TotalSupply` is being tracked and is **correct**.
- `TotalSupplyTrackable` loses its meaning starting with `BlockMetadata.CurrencyAccountProtocolVersion`.
- Read operation throwing an `Exception` for `TotalSupply`.
- It is put in as a safety measure, but in reality, this …

✨ Add `CurrencyAccount` to handle all `Currency` related logic

---

CHANGES.md
Libplanet.Action/State/CurrencyAccount.cs
Libplanet.Action/State/IStateStoreExtensions.cs
Libplanet.Action/State/IWorldExtensions.cs

Using `IWorldExtensions` class as a separate layer conceptually, moved all `IActionContext` dependent logic from `CurrencyAccount` to `IWorldExtensions` to prevent context dependent logic seeping into what is essentially an `IAccount`.

♻️ Refactor `CurrencyAccount`

---

Libplanet.Tests/Blocks/BlockMarshalerTest.Legacy.cs
Libplanet.Tests/Blocks/BlockMarshalerTest.cs
Libplanet.Types/Blocks/BlockMetadata.cs

🔧 Related to #3790.
Few notes:
- As written in the comments, took valid blocks from past versions.
- However, some modifications were made. Specifically, during protocol version 0 and 1, it seems like it was possible to have `Block.StateRootHash` to be null. This is not compatible with the current implementation.
- Disabled warning of `MEN002` as this should be easier to maintain and does not affect code readability much. 🙄

🔧 Added tests for unmarsahling PoW blocks

---

CHANGES.md
Libplanet.Action.Tests/BlockProtocolVersionNotSupportedExceptionTest.cs
Libplanet.Action/ActionEvaluator.cs
Libplanet.Action/BlockProtocolVersionNotSupportedException.cs
Libplanet.Action/IActionEvaluator.cs
Libplanet.Tests/Action/ActionEvaluatorTest.cs
Libplanet.Tests/Action/WorldTest.cs
Libplanet.Tests/Action/WorldV0Test.cs
Libplanet.Tests/Action/WorldV1Test.cs
Libplanet.Tests/Blocks/BlockMarshalerTest.Legacy.cs
Libplanet.Tests/Fixtures/LegacyBlocks.cs
Libplanet.Types/Blocks/BlockMarshaler.cs

Related to #3790.
See the changelog for the ramification for deprecating PoW evaluation.
Further API fixes will be in subsequent PRs. These include
- Removing `IActionContext` typed parameter from `IWorld.TransferAsset()`
- Preventing `IWorld` with `IWorld.Version` less than `BlockMetadata.PBFTProtocolVersion`
and possibly more as they come up. 😶

💥 Deprecate PoW evaluation

---

CHANGES.md
Libplanet.Explorer.Tests/Queries/StateQueryTest.Mocks.cs
Libplanet.Explorer.Tests/Queries/StateQueryTest.cs
Libplanet.Explorer/GraphTypes/AccountStateType.cs
Libplanet.Explorer/GraphTypes/WorldStateType.cs

Closes #3792.
♻️ The old scheme is no longer applicable as currency and validator set handling is done on `IWorld` layer instead of `IAccount` layer. This changes the API. Let's just hope this doesn't break anything. 😣
Also, we need more tests to see if the queries work on both an old state and a new state. 😥

♻️ Moved balance and validator query from account to world

---

CHANGES.md
Libplanet.Explorer/GraphTypes/VoteType.cs
Libplanet.Net/Consensus/HeightVoteSet.cs
Libplanet.Tests/Blocks/BlockCommitTest.cs
Libplanet.Tests/Consensus/VoteMetadataTest.cs
Libplanet.Tests/Consensus/VoteTest.cs
Libplanet.Types/Consensus/IVoteMetadata.cs
Libplanet.Types/Consensus/Vote.cs
Libplanet.Types/Consensus/VoteMetadata.cs

To prevent `KeyNotFoundException` while deserializing old blocks, make field nullable.

Make `IVoteMetadata.ValidatorPower` nullable

---

CHANGES.md
Libplanet.Action/State/IBlockChainStates.cs
Libplanet.Mocks/MockBlockChainStates.cs
Libplanet.Tests/Action/ActionEvaluatorTest.cs
Libplanet.Tests/Fixtures/IntegerSet.cs
Libplanet/Blockchain/BlockChain.States.cs
Libplanet/Blockchain/BlockChainStates.cs

The method is left intact for `BlockChain` class. From what I see in [this PR](https://github.com/planetarium/lib9c/pull/2622), seems like it isn't being used in [lib9c](https://github.com/planetarium/lib9c).

🧹 Removed `GetNextWorldState()` from `IBlockChainStates`

---

Libplanet.Types/Consensus/ValidatorSet.cs

Check only `PublicKey` sequence if given `ValidatorPower` is null.
Followup of https://github.com/planetarium/libplanet/pull/3813

Fix `ValidatorSet.ValidateBlockCommitValidators()` behavior

---

Libplanet/Blockchain/BlockChain.cs

NSRH generation on `BlockChain.Create()` is duplicated and needless since constructor of `BlockChain` do the same thing.

Remove duplicated NSRH generation on BlockChain.Create()

---

Libplanet.Net.Tests/SwarmTest.Preload.cs
Libplanet.Net/Swarm.BlockCandidate.cs
Libplanet.Tests/Blockchain/BlockChainTest.cs
Libplanet/Blockchain/BlockChain.Swap.cs

♻️ Under normal circumstances, `Swap()` should never be called with a `BlockChain` that is of lower height. This is to eliminate unnecessary scenario considerations.

♻️ Stricter `Swap()` condition

---

CHANGES.md
Libplanet.Net.Tests/Consensus/ContextNonProposerTest.cs
Libplanet.Net.Tests/Consensus/ContextProposerTest.cs
Libplanet.Net.Tests/Consensus/ContextTest.cs
Libplanet.Net.Tests/Consensus/HeightVoteSetTest.cs
Libplanet.Net.Tests/TestUtils.cs
Libplanet.Net/Consensus/ConsensusContext.cs
Libplanet.Net/Consensus/Context.Async.cs
Libplanet.Net/Consensus/Context.cs
Libplanet.Net/Consensus/IConsensusMessageCommunicator.cs
Libplanet/Blockchain/BlockChain.cs

Resolves #3833.
Changed to store `ConsensusMsg`s in a `HashSet<T>` instead of creating a new `Context`.
Also removed a requirement for needing `lastCommit` from `Context.Start()`.
As a result, a lock should no longer happen due to receiving a `ConsensusMsg` from other `Peer`s.

Remove a possible `ConsensusContext` lock due to a future `ConsensusMsg`.

---

.github/bin/dist-nuget.sh

The `dist-nuget.sh` script is run after merging the PR into the main branch.
Therefore, I didn't have a chance to test this script.
The problem I found was that the project path was set incorrectly.
I fixed it so that the dotnet nuget command uses the correct project path.

Fix dist-nuget script running error

---

CHANGES.md
src/Libplanet.Net/Consensus/ConsensusContext.Event.cs
src/Libplanet.Net/Consensus/ConsensusContext.cs
src/Libplanet.Net/Consensus/Context.Async.cs
src/Libplanet.Net/Consensus/Context.Event.cs
src/Libplanet.Net/Consensus/Context.Mutate.cs
src/Libplanet.Net/Consensus/Context.cs
test/Libplanet.Net.Tests/Consensus/ContextNonProposerTest.cs
test/Libplanet.Net.Tests/Consensus/ContextProposerTest.cs
test/Libplanet.Net.Tests/Consensus/ContextProposerValidRoundTest.cs
test/Libplanet.Net.Tests/Consensus/ContextTest.cs
test/Libplanet.Net.Tests/TestUtils.cs

♻️ Remove `IConsensusMessageCommunicator` from `Context`

---

test/Libplanet.Net.Tests/Consensus/ConsensusContextTest.cs

🔧 Added timeout to `async` tests

---

CHANGES.md
src/Libplanet.Net/Consensus/ConsensusContext.cs
src/Libplanet.Net/Consensus/ConsensusReactor.cs
src/Libplanet.Net/Consensus/ConsensusStep.cs
test/Libplanet.Net.Tests/Consensus/ConsensusContextNonProposerTest.cs
test/Libplanet.Net.Tests/Consensus/ConsensusContextProposerTest.cs
test/Libplanet.Net.Tests/Consensus/ConsensusContextTest.cs
test/Libplanet.Net.Tests/Consensus/ContextTest.cs

Overview:
- `ConsensusContext` now only holds a single `Context` internally. This is no longer `null`-able.
- `NewHeight()` is only responsible for switching the "view".
- New `Running` property determines whether a `Context` held by `ConsensusContext` will be running.

♻️ Refactor `ConsensusContext`

---

CHANGES.md
src/Libplanet/Libplanet.csproj

🔧 Prepare 5.1.0

---

src/Libplanet.Net/Swarm.BlockCandidate.cs

🧹 It's been a while where `BlockChain.Tip` has been non-nullable. 🙄

🧹 Remove unnecessary `null` checks

---

.github/workflows/benchmarks-merged.yml
.github/workflows/check-build.yaml
CONTRIBUTING.md
Dockerfile.explorer
tools/Libplanet.Explorer/run.ps1

Fixed an error when running push-docker-image.yml
Changed dotnet option from `-p` to `--project`, because `--project` is deprecated.
Changed dotnet command from `build` to `pack` to check if it builds in a different target framework.

Fix CI errors

---

CHANGES.md

🚀 Release 5.1.0

---

CHANGES.md
Libplanet.Action.Tests/ActionContextTest.cs
Libplanet.Action.Tests/ActionEvaluationTest.cs
Libplanet.Action.Tests/Sys/InitializeTest.cs
Libplanet.Action/ActionContext.cs
Libplanet.Action/ActionEvaluator.cs
Libplanet.Action/GasTracer.cs
Libplanet.Action/IActionContext.cs
Libplanet.Tests/Action/AccountDiffTest.cs
Libplanet.Tests/Action/ActionEvaluatorTest.cs
Libplanet.Tests/Action/WorldTest.cs
Libplanet.Tests/Blockchain/Renderers/AnonymousActionRendererTest.cs
Libplanet.Tests/Blockchain/Renderers/LoggedActionRendererTest.cs

Since we track gas usage by transaction, `ActionContext.GasMeter` is not a good choice when tracking gas usage.

wip: Introduce/gas tracer

---

CHANGES.md
src/Libplanet.Store/Trie/MerkleTrie.Proof.cs
test/Libplanet.Tests/Store/Trie/MerkleTrieProofTest.cs

I'm rather on the fence about whether `GenerateProof()` should be part of the `ITrie` interface. 🙄

✨ Introduce Merkle inclusion proof

---

CHANGES.md
src/Libplanet.Types/Assets/Currency.cs

In dotnet6, the following error occurs when building.
`CS0188, CS8885: The this object cannot be used before all of its fields are assigned to`
I tried to change the `Hash` field of `Currency` to a property, but it was not the correct way to modify it.
According to the error message, I just need to avoid calling this method, so I changed the method to static and used it.
The code is less readable, but I was able to solve the problem for now.

Fix an issue where currency does not work correctly in dotnet6

---

src/Libplanet.Action/State/IAccount.cs
src/Libplanet.Action/State/IWorld.cs

`This method method ~` seems typo of `This method ~`. If it is not typo, please close this pull request 🙏🏻

fix: correct typo

---

.github/bin/dist-pack.sh
.github/workflows/build.yaml

Clicking the `Source repository` link in the above image(Nuget package website) will take you to the actual Github repository used for the build.

Add SHA value to RepositoryUrl in nuget package

---

src/Libplanet.Net/Protocols/KBucket.cs
src/Libplanet.Net/Protocols/KBucketDictionary.cs
src/Libplanet.Net/Protocols/RoutingTable.cs
src/Libplanet.Types/Evidence/EvidenceBase.cs
src/Libplanet.Types/Evidence/EvidenceId.cs
src/Libplanet.Types/Tx/TxActionList.cs
src/Libplanet.Types/Tx/TxSigningMetadata.cs
src/Libplanet/Blockchain/BlockLocator.cs

🧹 Fixed mistakes for arguments when throwing an `ArgumentOutOfRangeException`

---

src/Libplanet/Blockchain/BlockChain.cs

🧹 `Tip` is no longer `null`able, so the check is unnecessary.

🧹 Cleaned up `BlockChain.FindNextHashes()`

---

src/Libplanet.Net/Swarm.BlockSync.cs
src/Libplanet.Net/Swarm.cs

🧹 Just crossed my mind following #3905 that there may be more unnecessary `null` checks. 🙄

🧹 Removed null check for Tip

---

src/Libplanet.Net/AppProtocolVersion.cs
src/Libplanet.Store/Trie/KeyBytes.cs

Tested with 1,000,000 samples of `ImmutableArray<byte>`s.
|         Method | Length |     Mean |    Error |   StdDev |       Gen0 |       Gen1 | Allocated |
|--------------- |------- |---------:|---------:|---------:|-----------:|-----------:|----------:|
|    WithBuilder |     10 | 236.2 ms |  4.70 ms | 10.80 ms | 18333.3333 |  5666.6667 | 122.81 MB |
| WithoutBuilder |     10 | 247.3 ms |  5.38 ms | 15.78 ms |  6000.0000 |  2000.0000 |  54.15 MB |
|    WithBuilder |    100 | 387.9 ms | 14.09 ms | 40.89 ms | 45000.0000 | 12000.0000 | 290.66 MB |
| WithoutBuilder |    100 | 348.1 ms | 11.00 ms | 30.84 ms | 20000.0000 | 10000.0000 | 138.07 MB |
There isn't much gain in terms of speed, but more than halves the memory usage.

⚡ Removed unnecessary `ToBuilder()`

---

CHANGES.md
tools/Libplanet.Explorer/Queries/BlockQuery.cs
tools/Libplanet.Explorer/Queries/ExplorerQuery.cs

RocksDBStore's `store.IterateIndexes` causes too much CPU usage. So we use `BlockChain`'s blocks cache temporarily.

🔧  fix: use cache instead of get block from store

---

CHANGES.md
src/Libplanet.Store/Trie/Nodes/HashNode.cs

Resolves #3922.
Sample benchmark with 1,000,000 `HashDigest<SHA256>`s:
|      Method |     Mean |   Error |   StdDev |       Gen0 |       Gen1 |     Gen2 | Allocated |
|------------ |---------:|--------:|---------:|-----------:|-----------:|---------:|----------:|
|   ByteArray | 214.1 ms | 4.20 ms |  7.14 ms | 12000.0000 |  4333.3333 | 666.6667 | 116.67 MB |
| ToByteArray | 417.9 ms | 9.98 ms | 28.97 ms | 29000.0000 | 10000.0000 |        - | 223.48 MB |

⚡ Optimized `HashNode.ToBencodex()`

---

CHANGES.md
src/Libplanet.Action/State/KeyConverters.cs

|      Method |     Mean |   Error |   StdDev |   Median |       Gen0 |      Gen1 |     Gen2 | Allocated |
|------------ |---------:|--------:|---------:|---------:|-----------:|----------:|---------:|----------:|
|     WithNew | 261.6 ms | 5.19 ms | 11.81 ms | 265.0 ms | 20500.0000 | 5500.0000 | 500.0000 |  129.7 MB |
|    WithPool | 384.0 ms | 7.76 ms | 22.87 ms | 390.3 ms | 17000.0000 | 6000.0000 |        - | 114.44 MB |
| WithBuilder | 265.6 ms | 5.30 ms | 14.05 ms | 269.0 ms | 15500.0000 | 5500.0000 | 500.0000 |  99.18 MB |
|  WithUnsafe | 147.7 ms | 2.90 ms |  6.38 ms | 147.2 ms | 10600.0000 | 3800.0000 | 400.0000 |  68.66 MB |

⚡ Optimized KeyConverters

---

tools/Libplanet.Tools/README.md

[This issue](https://github.com/planetarium/homebrew-brew/issues/41) causes a warning after installation, and fixing it requires several authentication steps.
Until it's resolved, I'm removing the installation guide from the documentation :pray:

Remove `Homebrew Cask` Guide

---

src/Libplanet.Net/Swarm.BlockCandidate.cs
src/Libplanet.Net/Swarm.BlockSync.cs
src/Libplanet.Net/Swarm.cs
test/Libplanet.Net.Tests/SwarmTest.Preload.cs
test/Libplanet.Net.Tests/SwarmTest.cs

- Changed the return type to `List<T>` as the return type of `IAsyncEnumerable<T>` does not make much sense. Things were internally being unnecessarily cast to various collection types.
- Changed the behavior of `GetBlockDemandHashes()` to **not** aggregate `BlockHash`es from various peers. The rest of the block syncing stack pretty much assumes `BlockHash`es from `GetBlockDemandHashes()` is from a single continuous branch.
This is to mainly fix the behavior of `GetBlockDemandHashes()` in accordance to the whole block syncing process.
No changelog is provided as all the changes are internal.

♻️ Refactor `GetDemandBlockHashes()`

---

CHANGES.md
src/Libplanet.Net/BlockDemand.cs
src/Libplanet.Net/BlockDemandTable.cs
src/Libplanet.Net/Swarm.BlockCandidate.cs

Just a minor change to increase its reusability.

♻️ Changed `BlockDemand` to hold an `IBlockExcerpt` instead of `BlockHeader`

---

CHANGES.md
src/Libplanet.Net/Swarm.BlockCandidate.cs
src/Libplanet.Net/Swarm.BlockSync.cs
src/Libplanet.Net/Swarm.MessageHandlers.cs
src/Libplanet.Net/Swarm.cs
src/Libplanet/Blockchain/BlockChain.cs
test/Libplanet.Net.Tests/SwarmTest.Broadcast.cs
test/Libplanet.Net.Tests/SwarmTest.Preload.cs

- Removed internal "stitching" of `BlockHash`es over multiple attempts.
- Removed `chunkSize` parameter. This was never clearly defined and was being used improperly in the first place.
- When attempting to get `BlockHash`es from a `Peer`, the `Peer` selection is done randomly (instead of trying to attempt from the "highest" `Peer` first).
- As a result, the overall behavior of preloading has changed.

♻️ Simplified the internal behavior of `GetDemandBlockHashes()`

---

src/Libplanet.Net/Swarm.BlockCandidate.cs
src/Libplanet.Net/Swarm.BlockSync.cs
src/Libplanet.Net/Swarm.cs
test/Libplanet.Net.Tests/SwarmTest.Preload.cs
test/Libplanet.Net.Tests/SwarmTest.cs

One final cleanup PR before actually removing `Fork()` and `Swap()`. 😗
- Removes unnecessary unused dependencies.
- Removes unnecessary validations.
- Adds validations for received messages.
- Changes the behavior slightly when processing received messages.
- Reduces throwing `Exceptions` when not necessary.
- For example, `GetBlockHashes()` needn't necessarily throw an `Exception` because it times out or receives an
unexpected message. Only an `Exception` thrown for an unexpected reason should bubble up. The same goes for
`GetBlocks()`.

♻️ 🧹 Streamline block syncing

---

CHANGES.md
src/Libplanet.Net/Messages/BlockHashesMsg.cs
src/Libplanet.Net/Messages/GetBlockHashesMsg.cs
src/Libplanet.Net/Messages/MessageContent.cs
src/Libplanet.Net/Swarm.MessageHandlers.cs
src/Libplanet/Blockchain/BlockChain.cs
test/Libplanet.Net.Tests/Messages/BlockHashesTest.cs
test/Libplanet.Net.Tests/Messages/NetMQMessageCodecTest.cs
test/Libplanet.Tests/Blockchain/BlockChainTest.cs

♻️ Changed encoding of `GetBlockHashesMsg` and `BlockHashesMsg`

---

scripts/determine-version.js

Fixes https://github.com/planetarium/libplanet/issues/3955. I declared variables to store each formatted portion of the date for readability. Please let me know if you'd liked anything changed.

 fix: add zero padding to version timestamp

---

src/Libplanet.Types/Blocks/BlockMetadata.cs
src/Libplanet.Types/Consensus/ValidatorSet.cs
src/Libplanet/Blockchain/BlockChain.Validate.cs
test/Libplanet.Tests/Consensus/ValidatorSetTest.cs

Upgrade BPV to handle vote power

---

CHANGES.md
src/Libplanet.Action/ActionEvaluator.cs
src/Libplanet.Action/IPolicyActionsRegistry.cs
src/Libplanet.Action/PolicyActionsRegistry.cs
src/Libplanet/Blockchain/Policies/BlockPolicy.cs
src/Libplanet/Blockchain/Policies/IBlockPolicy.cs
src/Libplanet/Blockchain/Policies/NullBlockPolicy.cs
test/Libplanet.RocksDBStore.Tests/RocksDBStoreBlockChainTest.cs
test/Libplanet.RocksDBStore.Tests/RocksDBStoreFixture.cs
test/Libplanet.Tests/Blockchain/BlockChainTest.cs
test/Libplanet.Tests/Blockchain/DefaultStoreBlockChainTest.cs
test/Libplanet.Tests/Store/DefaultStoreFixture.cs
test/Libplanet.Tests/Store/MemoryStoreFixture.cs
test/Libplanet.Tests/Store/StoreFixture.cs
tools/Libplanet.Explorer.Cocona/Libplanet.Explorer.Cocona.csproj
tools/Libplanet.Explorer.Executable/Program.cs

For a rich, pluggable `ActionEvaluator`, we need to separate the interface of `PolicyActionsRegistry` from the concrete types.

🔧 refactor: interfacing policy action registy

---

test/Libplanet.Net.Tests/SwarmTest.Evidence.cs

Throwing exceptions on the test is not a good practice. Use `Assert` instead.

🔧  fix: use `Assert` instead of exception

---

CHANGES.md
src/Libplanet.Store/BlockSet.cs
src/Libplanet.Store/HashNodeCache.cs
src/Libplanet.Store/Libplanet.Store.csproj

Benchmark says at all.
```
BenchmarkDotNet v0.14.0, macOS Sequoia 15.0 (24A335) [Darwin 24.0.0]
Apple M2 Max, 1 CPU, 12 logical and 12 physical cores
.NET SDK 8.0.101
[Host]     : .NET 8.0.1 (8.0.123.58001), Arm64 RyuJIT AdvSIMD
DefaultJob : .NET 8.0.1 (8.0.123.58001), Arm64 RyuJIT AdvSIMD
```
|    Method      |    Mean   |   Error   |   StdDev  |
|:--------------|:---------|:---------|:---------|
| ConcurrentLru  | 5.156 μs  | 0.0171 μs | 0.0133 μs |
| ConcurrentTLru | 5.372 μs  | 0.0161 μs | 0.0150 μs |
| Planetarium.LruCacheNet       | 15.479 μs | 0.0444 μs | 0.0416 μs |
| Method         | Mean     | Error    | StdDev   |
|----------------|----------|----------|----------|
| ConcurrentLru  | 26.45 μs | 0.186 μs | 0.165 μs |
| ConcurrentTLru | 26.05 μs | 0.056 μs | 0.047 μs |
| …

🔴 refactor: use `Bitfaster.Caching` instead of `Libplanet.LruCahceNet`

---

test/Libplanet.Net.Tests/Messages/MessageTest.cs
test/Libplanet.Tests/Action/ActionEvaluatorTest.cs
test/Libplanet.Tests/TestUtils.cs

This Fixes: #3781 
The code I updated
```
txs.AddRange(
validatorSet.Validators.Select(
validator => Transaction.Create(
nonce++,
GenesisProposer,
null,
actions: new IAction[]
{
new Initialize(
validatorSet: validatorSet,
states: ImmutableDictionary.Create<Address, IValue>()),
}.Select(x => x.PlainValue),
timestamp: DateTimeOffset.MinValue)));
```
to
```
txs.Add(
Transaction.Create(
nonce++,
GenesisProposer,
null,
actions: new IAction[]
{
new Initialize(
validatorSet: validatorSet,
states: ImmutableDictionary.Create<Address, IValue>()),
}.Select(x => x.PlainValue),
timestamp: DateTimeOffset.MinValue));
```

Update ProposeGenesis in TestUtils to remove redundant Initialize()

---

CHANGES.md
src/Libplanet/Blockchain/BlockChain.Validate.cs
src/Libplanet/Blockchain/BlockChain.cs
test/Libplanet.Tests/Blockchain/BlockChainTest.Append.cs

fix: do not check action is valid when append block

---

CHANGES.md
src/Libplanet.Action/ActionEvaluator.cs
src/Libplanet.Action/GasMeter.cs
src/Libplanet.Action/GasTracer.cs
test/Libplanet.Tests/Action/ActionEvaluatorTest.GasTracer.cs

* Added Added `CancelTrace` method to `GasTracer`.

Refactor GasTracer

---

CHANGES.md
src/Libplanet/Blockchain/BlockChain.Validate.cs
src/Libplanet/Blockchain/BlockChain.cs
test/Libplanet.Tests/Blockchain/BlockChainTest.Append.cs

🔀 Port 5.3.2 to main

---

CHANGES.md
src/Libplanet.Net/Messages/IMessageCodec.cs
src/Libplanet.Net/Messages/NetMQMessageCodec.cs
src/Libplanet.Net/Transports/BoundPeerExtensions.cs
src/Libplanet.Net/Transports/NetMQTransport.cs
test/Libplanet.Net.Tests/Messages/BlockHashesTest.cs
test/Libplanet.Net.Tests/Messages/MessageTest.cs
test/Libplanet.Net.Tests/Messages/NetMQMessageCodecTest.cs

This serves several purposes:
- Makes `IMessageCodec` interface more symmetric.
- Postpones encoding of `Message` to `NetMQMessage` until it is necesary.
- Allows message type to be observable without unnecessarily parsing raw `byte`s

Refactor `MessageRequest` and `IMessageCodec`

---

CHANGES.md
src/Libplanet.RocksDBStore/RocksDBStore.Prune.cs
src/Libplanet.RocksDBStore/RocksDBStore.cs
src/Libplanet.Store/IStore.cs

Notes:
- The new implementation works only under an assumption that the `Stack` of chain infos are either sequential or overlapping.
- This is much weaker assumption than the original where every chain info's index has been managed correctly and is uncorrupted.
- Some implementation decisions are made assuming that this will be a one-off "script" to prune outdated chains.
- Internally, `int` indices are used pretty haphazardly assuming that currently there is no chain with its `Tip.Index` exceeding the max `int` value.
- Again, assuming that there is no chain that is "too long", internal iteration instantiates an entire list of `BlockHash`es, which should not be a problem in terms of memory usage.
- Due to using `List<BlockHash>` for iteration, the method should be safe (will throw an …

Fixed `PruneOutdatedChains()`

---

CHANGES.md
test/Libplanet.Explorer.Tests/GraphTypes/BlockTypeTest.cs
tools/Libplanet.Explorer/GraphTypes/BlockType.cs

This PR introduces raw field to block query as bencodex serialized raw block.
It intends to allow other services such as StateProxy to fetch blocks in simpler and efficient manner.

feat: add raw field to blockQuery

---

sdk/node/Libplanet.Node.Tests/Services/BlockChainServiceTest.cs
sdk/node/Libplanet.Node/Libplanet.Node.csproj
sdk/node/Libplanet.Node/Options/GenesisOptions.cs
sdk/node/Libplanet.Node/Options/GenesisOptionsConfigurator.cs
sdk/node/Libplanet.Node/Options/GenesisOptionsValidator.cs
sdk/node/Libplanet.Node/Services/BlockChainService.cs
src/Libplanet.Action/State/KeyConverters.cs
tools/Libplanet.Explorer.Cocona/Libplanet.Explorer.Cocona.csproj
tools/Libplanet.Extensions.Cocona/Libplanet.Extensions.Cocona.csproj

This provides genesis base state configuration option.
Use "Genesis:GenesisConfigurationPath" and pass JSON represented base genesis state.
The structure of the JSON file is:
```JSON
{
"<AccountAddress>":
{
"<Address>":"<Serialized IValue as Hex string>"
}
}
```
For more detail, please take a look at `sdk/node/Libplanet.Node.Tests/Services/BlockChainServiceTest.cs`

Add genesis config option for Node

---

CHANGES.md
test/Libplanet.Extensions.Cocona.Tests/Commands/StoreCommandTest.cs
tools/Libplanet.Extensions.Cocona/Commands/StoreCommand.cs

planet store get-tx-nonce
planet store set-tx-nonce

Introduce tx nonce command
