CHANGES.md
=> 🧹 Fixed typos

Libplanet.Net.Tests/Libplanet.Net.Tests.csproj, Libplanet.Net.Tests/SwarmTest.AppProtocolVersion.cs, Libplanet.Net.Tests/SwarmTest.Broadcast.cs, Libplanet.Net.Tests/SwarmTest.Consensus.cs, Libplanet.Net.Tests/SwarmTest.Fixtures.cs, Libplanet.Net.Tests/SwarmTest.Preload.cs, Libplanet.Net.Tests/SwarmTest.cs, Libplanet.Net.Tests/Transports/NetMQTransportTest.cs, Libplanet.Net.Tests/Transports/TransportTest.cs
#2569
May this change help with the CI testing?
=> fix: Adjustment effective changes from hang in the CI research

CHANGES.md, Libplanet.Explorer/Libplanet.Explorer.csproj, Libplanet.Extensions.Cocona/Libplanet.Extensions.Cocona.csproj, Libplanet/Libplanet.csproj
=> ⬆️ Bump dependencies

Libplanet.Net/Transports/NetMQTransport.cs
https://ptb.discord.com/channels/928926944937013338/1070202998036369409
=> fix/transport: `ProcessMessageHandler` consumes reference of message

CHANGES.md, Libplanet.Explorer/Queries/ExplorerQuery.cs
=> Fix `stateQuery`

CHANGES.md, Libplanet.Extensions.Cocona/Commands/BlockCommand.cs, Libplanet.Node/NodeUtils.cs, Libplanet/Store/DefaultStore.cs
See also (Korean): <https://discord.com/channels/928926944937013338/1019473728628867092/1070259942545690624>.
=> Fix incorrect uses of `FileMode.OpenOrCreate`

Libplanet.Net/Transports/NetMQTransport.cs
=> log/transport: alternative Identity for NetMQTransport log

Docs/docfx.json
This pull request renews copyright years at the `docs.libplanet.io` footer.
=> Renew copyright years

CHANGES.md, Libplanet.Net/Messages/NetMQMessageCodec.cs, Libplanet.Net/Transports/NetMQTransport.cs
=> 🔧 Fix transport log

CHANGES.md
=> 🚀  Release 0.46.1

CHANGES.md, Libplanet/Libplanet.csproj
=> 🚀  Prepare 0.46.2

CHANGES.md, Libplanet.Net/BlockCandidateTable.cs, Libplanet.Net/Messages/NetMQMessageCodec.cs, Libplanet.Net/Protocols/KademliaProtocol.cs, Libplanet.Net/Swarm.BlockCandidate.cs, Libplanet.Net/Transports/NetMQTransport.cs, Libplanet/KeyStore/Web3KeyStore.cs
=> 🔀 Merge 0.46.1 to main

CHANGES.md, Libplanet.Explorer/GraphTypes/AddressType.cs, Libplanet.Tests/AddressTest.cs, Libplanet/Address.cs
Addresses (pun intended) #2764.
=> Updated `DeriveAddress()` to be more stringent

Libplanet.Net.Tests/Consensus/Context/MessageLogTest.cs, Libplanet.Tests/Blocks/BlockCommitTest.cs, Libplanet/Blockchain/BlockChain.cs, Libplanet/Blocks/BlockCommit.cs
TODO: Should add test case for newly added logic
=> Use voting power instead of vote count when validating blockcommit

Libplanet.Net.Tests/SwarmTest.cs, Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs, Libplanet.Tests/Fixtures/IntegerSet.cs, Libplanet.Tests/TestUtils.cs, Libplanet/Blockchain/BlockChain.cs
This test covers two scenario:
1. Validation success when power is big even count is small.
2. Validation fails when power is small even count is big.
=> Add test for validator power

CHANGES.md, Libplanet.Tests/AddressTest.cs, Libplanet.Tests/TestUtils.cs, Libplanet.Tests/Tx/TxIdTest.cs, Libplanet/Address.cs, Libplanet/Tx/TxExecution.cs, Libplanet/Tx/TxFailure.cs, Libplanet/Tx/TxId.cs, Libplanet/Tx/TxSuccess.cs
=> ♻️ `IBencodable` `TxId`

Libplanet.Net/Swarm.MessageHandlers.cs
Related to #2742. For better log parsing.
=> 🧹 Aligned identity with request id format

Libplanet.Net/BlockCandidateTable.cs
🧹 Mistakes were found right after the merge. 😣
=> 🧹  Fixed logging mistake

CHANGES.md, Libplanet.Net/Swarm.MessageHandlers.cs, Libplanet.Net/Swarm.cs
=> Reply with zero blocks when no corresponding blocks are found

CHANGES.md
=> 🚀 Release libplanet 0.48.0

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 0.48.1

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 0.49.0

CHANGES.md, Libplanet.Net.Tests/SwarmTest.Broadcast.cs, Libplanet.Net/Swarm.BlockCandidate.cs, Libplanet.Net/Swarm.cs
=> Prevent duplicated ProcessBlockDemand

Libplanet.Net.Tests/SwarmTest.Broadcast.cs, Libplanet.Net/Swarm.BlockCandidate.cs, Libplanet.Net/Swarm.cs
Cherry picked from https://github.com/planetarium/libplanet/pull/2814
=> Cherrypick 2814 to PBFT

CHANGES.md
=> 🚀  Release 0.46.2

CHANGES.md, Libplanet.Net/Swarm.BlockSync.cs
=> 🧹 Merge 0.46.2 to main

CHANGES.md, Libplanet/Libplanet.csproj
=> ⬆️  Prepare 0.46.3

Libplanet/Action/ActionEvaluator.cs
The `test/block-transport-log` branch is a direct fork from `test/block-transport`. The log related PRs should be submitted to this branch until further update. cc @sky1045
=> update action evaluator log level

Libplanet.Net.Tests/Protocols/TestTransport.cs, Libplanet.Net/Swarm.BlockCandidate.cs, Libplanet.Net/Swarm.MessageHandlers.cs, Libplanet.Net/Swarm.cs, Libplanet.Net/TxCompletion.cs, Libplanet/Blockchain/BlockChain.cs, Libplanet/Blockchain/Policies/VolatileStagePolicy.cs, Libplanet/Blockchain/Renderers/LoggedActionRenderer.cs
=> update some log level from Debug to Information

CHANGES.md
=> 🚀 Release libplanet 0.49.0

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 0.50.0

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 0.49.1

CHANGES.md, Libplanet.Net/Swarm.BlockCandidate.cs, Libplanet.Net/Transports/NetMQTransport.cs
=> Removed ConsumeBlockCandidates log

CHANGES.md
=> 🚀 Release 0.49.1

CHANGES.md, Libplanet.Net/Swarm.BlockCandidate.cs, Libplanet.Net/Transports/NetMQTransport.cs
=> 🔀 Port 0.49.1 to main

.github/bin/dist-pack.sh, scripts/determine-version.js
=> CI: fix parameters

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 0.49.2

Libplanet.Net/Transports/NetMQTransport.cs, Libplanet.Tests/EnumerableMeasurementTest.cs, Libplanet/Action/ActionEvaluator.cs, Libplanet/Blockchain/BlockChain.Swap.cs, Libplanet/Blockchain/BlockChain.cs, Libplanet/Store/TrieStateStore.cs
=> 🧹 Updated metric logging

Libplanet.Net/Transports/NetMQTransport.cs
=> 🧹 Added info for transport logging

Libplanet.Tests/TestUtils.cs
Related to #1486 and #2585.
Again, some preparatory work to separate `BlockChain<T>` creation and loading. There might be some degradation in performance for testing. However, passing an empty `IStore` together with an `IStateStore` containing the state root hash seemed hack-ish at best.
=> 🧹 Use ephemeral `IStateStore` for generating genesis block

Libplanet.Net/Transports/NetMQTransport.cs, Libplanet.Tests/EnumerableMeasurementTest.cs, Libplanet/Action/ActionEvaluator.cs, Libplanet/Blockchain/BlockChain.Swap.cs, Libplanet/Blockchain/BlockChain.cs, Libplanet/Store/TrieStateStore.cs
=> 🧹 Better logging

CHANGES.md
=> 🚀 Release 0.50.0

Libplanet.Net/BlockCandidateTable.cs, Libplanet/Blockchain/Policies/VolatileStagePolicy.cs
=> 🧹  Added contexts for logging; additional metric logging

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 0.51.0

CHANGES.md, Libplanet.Net/BlockCandidateTable.cs, Libplanet.Net/Transports/NetMQTransport.cs, Libplanet.Tests/EnumerableMeasurementTest.cs, Libplanet/Action/ActionEvaluator.cs, Libplanet/Blockchain/BlockChain.Swap.cs, Libplanet/Blockchain/BlockChain.cs, Libplanet/Blockchain/Policies/VolatileStagePolicy.cs, Libplanet/Store/TrieStateStore.cs
=> 🧹 Logging sanitization

Libplanet.Net/Transports/NetMQTransport.cs, Libplanet.Net/TxCompletion.cs, Libplanet/Blockchain/Policies/VolatileStagePolicy.cs
🧹 Skipping changelog since there is already #2874 as a filler 😶
=> 🧹  General update to logging

CHANGES.md
=> 🚀 Release 0.49.2

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 0.49.3

CHANGES.md
=> 🚀 Release 0.50.1

.github/workflows/yarn.yaml
It's cherry-picked from <https://github.com/planetarium/libplanet/pull/2876>.
=> Always test @planetarium/cli install with the latest version

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 0.50.2

Libplanet.Net/BlockCandidateTable.cs, Libplanet.Net/Transports/NetMQTransport.cs, Libplanet.Net/TxCompletion.cs, Libplanet/Action/ActionEvaluator.cs, Libplanet/Blockchain/Policies/VolatileStagePolicy.cs
=> 🔀 Port 0.50.1 to main

Libplanet/Store/DefaultStore.cs
🧹 Just some separate cleanup while working on #2878 😗
=> 🧹 Minor cleanup for `DefaultStore` code comprehension

.github/bin/dist-pack.sh, .github/workflows/build.yaml, .github/workflows/yarn.yaml
It cherry-picks <https://github.com/planetarium/libplanet/pull/2876> as well.
=> Fix release script

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 0.51.1

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 0.52.0

CHANGES.md, Libplanet/Action/PolymorphicAction.cs
This pull request cherry-pick bab18f62afc5f40032a614eed28e0a579a6092b7 commit from the `main` branch to the `0.50-maintenace` branch.
=> Cherry-pick `Make PolymorphicAction<T>._actionTypeLoader configurable`

CHANGES.md
It is for applying #2875 PR to [planetarium/lib9c](https://github.com/planetarium/lib9c). I'll prepare a new pull request `Prepare 0.50.3` after this pull request is merged.
=> Release 0.50.2

Libplanet.Net/Swarm.BlockSync.cs
Maintenance PR for https://github.com/planetarium/libplanet/pull/2916
=> Fix ActionExecutionState total count

CHANGES.md
Fix bug on `ActionExecutionState`.
=> 🚀 Release 0.51.1

CHANGES.md
=> Fix typo 0.51.1

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 0.51.2

CHANGES.md, Libplanet.Net/Swarm.BlockSync.cs
=> Merge 0.51.1 to main

CHANGES.md
=> 🚀 Release 0.52.0

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 0.53.0

CHANGES.md, Libplanet.Tests/Action/Sys/SetValidatorTest.cs, Libplanet/Consensus/Validator.cs
=> ♻️🚀 Updated `Validator` bencoding and release 0.46.3

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 0.46.4

CHANGES.md, Libplanet.Net/Swarm.BlockSync.cs, Libplanet.Tests/Action/Sys/SetValidatorTest.cs, Libplanet/Consensus/Validator.cs
=> 🔀🚀 Port 0.46.2 and 0.46.3 to 0.47.1 and release 0.47.1

CHANGES.md, Libplanet.Net/Swarm.BlockSync.cs, Libplanet.Tests/Action/Sys/SetValidatorTest.cs, Libplanet/Consensus/Validator.cs
=> 🔀🚀 Port 0.47.1 to 0.48.1 and release 0.48.1

CHANGES.md, Libplanet.Tests/Action/Sys/SetValidatorTest.cs, Libplanet/Consensus/Validator.cs
=> 🔀🚀 Port 0.48.1 to 0.49.3 and release 0.49.3

CHANGES.md, Libplanet.Tests/Action/Sys/SetValidatorTest.cs, Libplanet/Consensus/Validator.cs
=> 🔀🚀 Port 0.49.3 to 0.50.3 and release 0.50.3

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 0.47.2

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 0.48.2

CHANGES.md, Libplanet.Tests/Action/ActionEvaluatorTest.cs, Libplanet/Blocks/BlockCommit.cs
♻️ An accompanying PR to #2927. 😗
=> ♻️ Refactor `BlockCommit` encoding

CHANGES.md, Libplanet.Tests/Action/ActionEvaluatorTest.cs, Libplanet/Consensus/Proposal.cs, Libplanet/Consensus/ProposalMetadata.cs, Libplanet/Consensus/Vote.cs, Libplanet/Consensus/VoteMetadata.cs
=> ♻️ Updated `Vote.Encoded` and `Proposal.Encoded`

CHANGES.md
=> 🚀 Release 0.51.2

CHANGES.md, Libplanet.Net.Tests/Messages/MessageTest.cs, Libplanet.Tests/Action/ActionEvaluatorTest.cs, Libplanet.Tests/Action/Sys/SetValidatorTest.cs, Libplanet.Tests/Blocks/BlockMetadataTest.cs, Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs, Libplanet/Blocks/BlockCommit.cs, Libplanet/Consensus/Proposal.cs, Libplanet/Consensus/ProposalMetadata.cs, Libplanet/Consensus/Validator.cs, Libplanet/Consensus/Vote.cs, Libplanet/Consensus/VoteMetadata.cs
=> 🔀🚀 Port 0.51.2 to 0.52.1 and release 0.52.1

.github/bin/constants.sh, .github/workflows/yarn.yaml, .vscode/settings.json, @planetarium/account-web3-secret-storage/.gitignore, @planetarium/account-web3-secret-storage/README.md, @planetarium/account-web3-secret-storage/examples/cli.ts, @planetarium/account-web3-secret-storage/package.json, @planetarium/account-web3-secret-storage/src/KeyId.ts, @planetarium/account-web3-secret-storage/src/PassphraseEntry.ts, @planetarium/account-web3-secret-storage/src/TtyPassphraseEntry.ts, @planetarium/account-web3-secret-storage/src/Web3KeyStore.ts, @planetarium/account-web3-secret-storage/src/index.ts, @planetarium/account-web3-secret-storage/test/TtyPassphraseEntry.test.ts, @planetarium/account-web3-secret-storage/test/Web3KeyStore.test.ts, @planetarium/account-web3-secret-storage/test/fixtures/UTC--2023-03-14T07-05-42Z--babfe5e0-f0f1-4f51-8b8e-97f1a461c690, @planetarium/account-web3-secret-storage/test/fixtures/UTC--2023-03-14T07-05-52Z--3b948485-9bd0-4149-9a36-59999b36abf3, @planetarium/account-web3-secret-storage/tsconfig.json, @planetarium/account-web3-secret-storage/vitest.config.ts, @planetarium/account/README.md, @planetarium/account/src/KeyStore.ts, @planetarium/account/src/index.ts, @planetarium/tx/README.md, @planetarium/tx/package.json, @planetarium/tx/test/__snapshots__/action.test.ts.snap, @planetarium/tx/test/__snapshots__/assets.test.ts.snap, @planetarium/tx/test/tx/__snapshots__/metadata.test.ts.snap, CHANGES.md, package.json, yarn.lock
This PR provides account-web3-secret-storage, which provides `Web3KeyStore` that implements Ethereum Web3 Secret Storage and complies to the `KeyStore` interface that `@planetarium/account` provides (also included in this PR.)
=> `@planetarium/account-web3-secret-storage`

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 0.52.2

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 0.49.4

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 0.50.4

CHANGES.md, Libplanet.Tests/Action/Sys/SetValidatorTest.cs, Libplanet/Consensus/Validator.cs
=> ♻️ Changed validator power to use Integer instead of Binary

CHANGES.md, Libplanet.Net.Tests/Messages/MessageTest.cs, Libplanet.Tests/Action/ActionEvaluatorTest.cs, Libplanet.Tests/Action/Sys/SetValidatorTest.cs, Libplanet.Tests/Blocks/BlockMetadataTest.cs, Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs, Libplanet/Blocks/BlockCommit.cs, Libplanet/Consensus/Proposal.cs, Libplanet/Consensus/ProposalMetadata.cs, Libplanet/Consensus/Validator.cs, Libplanet/Consensus/Vote.cs, Libplanet/Consensus/VoteMetadata.cs
=> 🔀 Port 0.52.1 to main

CHANGES.md
=> 🚀 Release 0.50.4

CHANGES.md, Libplanet.Net.Tests/Messages/MessageTest.cs, Libplanet.Tests/Action/ActionEvaluatorTest.cs, Libplanet.Tests/Action/Sys/SetValidatorTest.cs, Libplanet.Tests/Blocks/BlockMetadataTest.cs, Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs, Libplanet/Consensus/Validator.cs
=> 🔀 Port 0.50.4 to main

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 0.50.5

CHANGES.md, Libplanet.Tests/Action/Sys/SetValidatorTest.cs, Libplanet.Tests/Consensus/ValidatorTest.cs, Libplanet/Action/AccountStateDeltaExtensions.cs, Libplanet/Action/ActionEvaluationsExtensions.cs, Libplanet/Action/Sys/SetValidator.cs, Libplanet/Consensus/Validator.cs, Libplanet/Consensus/ValidatorSet.cs
=> ♻️ `IBencodable` `Validator` and `ValidatorSet`

CHANGES.md, Libplanet/Blocks/BlockCommit.cs, Libplanet/Consensus/Validator.cs, Libplanet/Consensus/ValidatorSet.cs
=> ♻️ `IBencodable` `BlockCommit`

CHANGES.md, Libplanet.Net/Transports/BoundPeerExtensions.cs
=> 🚀 Release 0.50.5

CHANGES.md, Libplanet/Blocks/BlockCommit.cs, Libplanet/Consensus/Vote.cs, Libplanet/Consensus/VoteMetadata.cs
=> ♻️ `IBencodable` for `VoteMetadata` and `Vote`

CHANGES.md, Libplanet.Benchmarks/Commit.cs, Libplanet.Net/Messages/ConsensusPreCommitMsg.cs, Libplanet.Net/Messages/ConsensusPreVoteMsg.cs, Libplanet.Net/Swarm.MessageHandlers.cs, Libplanet.Net/Swarm.cs, Libplanet.RocksDBStore/RocksDBStore.cs, Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs, Libplanet.Tests/Blocks/BlockCommitTest.cs, Libplanet.Tests/Blocks/BlockMarshalerTest.cs, Libplanet.Tests/Consensus/VoteMetadataTest.cs, Libplanet.Tests/Consensus/VoteTest.cs, Libplanet/Blocks/BlockCommit.cs, Libplanet/Blocks/BlockMarshaler.cs, Libplanet/Consensus/Vote.cs, Libplanet/Consensus/VoteMetadata.cs, Libplanet/Store/DefaultStore.cs
=> ♻️ Refactor `Block<T>.LastCommit` encoding

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 0.51.4

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 0.50.6

CHANGES.md
=> 🚀  Release 0.50.6

Libplanet/Action/ActionEvaluator.cs
=> ♻️ Added additional metrics to measure evaluation duration

Libplanet/Action/AccountStateDeltaImpl.cs
=> 🔧 Added logging info

Libplanet/Blockchain/BlockChainStates.cs
=> 🔧 Added state caching

Libplanet/Action/AccountStateDeltaImpl.cs, Libplanet/Blockchain/BlockChainStates.cs
=> 🔧 Added caching to `AccountStateDeltaImpl`

Libplanet/Action/AccountStateDeltaImpl.cs
=> ♻️ Reduced call to lower level `GetStates()` with empty addresses

Libplanet/Blockchain/KeyConverters.cs
=> ♻️ Improved `KeyConverters` performance

Libplanet/Action/AccountStateDeltaImpl.cs
♻️ Probably only added some additional overhead due to how `AccountStateDeltaImpl` behaves.
=> ♻️ Remove state delta cache

Libplanet/Blockchain/BlockChain.cs, Libplanet/Blockchain/BlockChainStates.cs
=> 🔧 Cache during commit

Libplanet/Blockchain/StateCache.cs
=> 🔧 Fixed improper cache fetching

CHANGES.md, Libplanet/Libplanet.csproj
=> 🚀  Prepare 0.50.7

Libplanet/Action/AccountStateDeltaImpl.cs
=> 🧹 General code readability

CHANGES.md
=> 🚀 Release 0.51.4

CHANGES.md
=> 🚀 Release 0.52.2

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 0.52.3

Libplanet/Action/ActionEvaluator.cs, Libplanet/Blockchain/BlockChain.cs
=> 🧹 Cleaned up some logs and added more info

CHANGES.md, Libplanet.Net/Transports/BoundPeerExtensions.cs
=> 🔀 Port 0.51.3 to main

CHANGES.md, Libplanet/Action/ActionEvaluator.cs, Libplanet/Blockchain/KeyConverters.cs, Libplanet/ByteUtil.cs
=> ⚡ Optimize key conversion

CHANGES.md
=> 🚀  Release 0.53.1

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧  Prepare 0.53.2

CHANGES.md, Libplanet.Net.Tests/Messages/MessageTest.cs, Libplanet.Tests/Action/ActionEvaluatorTest.cs, Libplanet.Tests/Action/Sys/InitializeTest.cs, Libplanet.Tests/Blockchain/BlockChainTest.cs, Libplanet.Tests/Blocks/BlockMetadataTest.cs, Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs, Libplanet.Tests/Common/Action/SetValidator.cs, Libplanet.Tests/Fixtures/BlockContentFixture.cs, Libplanet.Tests/TestUtils.cs, Libplanet/Action/Sys/Initialize.cs, Libplanet/Action/Sys/Registry.cs
=> 🔀 Port 0.51.4 to main

CHANGES.md, Libplanet.Net.Tests/Messages/MessageTest.cs, Libplanet.Tests/Action/ActionEvaluatorTest.cs, Libplanet.Tests/Blockchain/BlockChainTest.cs, Libplanet.Tests/Blocks/BlockMetadataTest.cs, Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
=> 🔀 Port 0.52.2 to main

CHANGES.md
=> 🔀 Port 0.53.1 to main

Libplanet/Action/AccountStateDeltaImpl.cs, Libplanet/Action/ActionContext.cs, Libplanet/Action/ActionEvaluator.cs
Adds `GetState` call count and its duration.
(cherry picked from commit 9d89ee4362b95e3fb85bb936484eae3c96145f02)
=> Add measure metric for `GetState` method

Libplanet/Blockchain/BlockChainStates.cs
=> ⚡ Parallel get states

CHANGES.md, Libplanet/Action/IValidatorSupportStateDelta.cs
=> Make `IValidatorSupportStateDelta` to public

CHANGES.md
=> 🚀  Release 0.50.7

CHANGES.md, Libplanet/Action/AccountStateDeltaImpl.cs, Libplanet/Action/ActionContext.cs, Libplanet/Action/ActionEvaluator.cs, Libplanet/Action/IValidatorSupportStateDelta.cs, Libplanet/Blockchain/BlockChain.cs, Libplanet/Blockchain/BlockChainStates.cs, Libplanet/Blockchain/ChainStateCache.cs, Libplanet/Blockchain/KeyConverters.cs, Libplanet/ByteUtil.cs
=> 🔀 Port 0.50.7 to 0.53.2

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧  Prepare 0.53.3

Libplanet/Action/ActionEvaluator.cs
=> 🧹 Small logging fix for consistency

CHANGES.md, Libplanet/Action/AccountStateDeltaImpl.cs, Libplanet/Action/ActionContext.cs, Libplanet/Action/ActionEvaluator.cs, Libplanet/Action/IValidatorSupportStateDelta.cs, Libplanet/Blockchain/BlockChain.cs, Libplanet/Blockchain/BlockChainStates.cs, Libplanet/Blockchain/ChainStateCache.cs, Libplanet/Blockchain/KeyConverters.cs, Libplanet/ByteUtil.cs
=> 🔀 Port 0.50.7 to 0.51.4

CHANGES.md, Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs, Libplanet/Action/AccountStateDeltaImpl.cs, Libplanet/Action/ActionContext.cs, Libplanet/Action/ActionEvaluator.cs, Libplanet/Action/IValidatorSupportStateDelta.cs, Libplanet/Blockchain/BlockChain.cs, Libplanet/Blockchain/BlockChainStates.cs, Libplanet/Blockchain/ChainStateCache.cs, Libplanet/Blockchain/KeyConverters.cs, Libplanet/ByteUtil.cs
=> 🔀 Merge 0.53.2 to main

Libplanet.Net/Consensus/Context.cs, Libplanet/Blockchain/BlockChain.Validate.cs, Libplanet/Blockchain/BlockChain.cs
🧹 Just plumbing work like #3043. 😗
Notable changes are:
- Extracting policy related validations to be done separately.
- ~~Change validation methods to throw exceptions instead of returning.~~
**Addendum**: I'm having troubles as to why tests are failing. I'm splitting this into multiple PRs. 😥
=> 🧹 Refactor block validate code

CHANGES.md, Libplanet.Explorer.Tests/Queries/StateQueryTest.cs, Libplanet.Explorer/GraphTypes/PublicKeyType.cs, Libplanet.Extensions.Cocona/Commands/ApvCommand.cs, Libplanet.Extensions.Cocona/Commands/KeyCommand.cs, Libplanet.Net.Tests/BoundPeerTest.cs, Libplanet.Net/BoundPeer.cs, Libplanet.Tests/AddressTest.cs, Libplanet.Tests/Crypto/PublicKeyTest.cs, Libplanet.Tests/HashDigestTest.cs, Libplanet/Address.cs, Libplanet/Crypto/PublicKey.cs, Libplanet/FixedSizedQueue.cs, Libplanet/HashDigest.cs
=> Implement TypeConverter for commonly used types 

CHANGES.md, Libplanet.Net.Tests/Consensus/Context/MessageLogTest.cs, Libplanet.Net/Consensus/ConsensusContext.cs, Libplanet.Net/Consensus/Context.Async.cs, Libplanet.Net/Consensus/Context.Mutate.cs, Libplanet.Net/Consensus/Context.cs, Libplanet.Net/Consensus/Gossip.cs, Libplanet.Net/Consensus/MessageLog.cs, Libplanet/Action/Sys/Registry.cs
=> 🔀 Port 0.53.3 to main

.github/bin/dist-pack.sh, @planetarium/tx/src/index.ts, CHANGES.md
=> 🔀 Port 0.53.4 to main

Libplanet.Net/Consensus/Context.cs, Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs, Libplanet/Blockchain/BlockChain.Validate.cs, Libplanet/Blockchain/BlockChain.cs
♻️ Follow-up on #3037. Logical changes will be made in a follow-up PR.
=> ♻️ Make validate methods throw exceptions instead of returning

Libplanet.Tests/TestUtils.cs, Libplanet.Tests/Tx/TransactionTest.cs, Libplanet.Tests/Tx/TxActionListTest.cs, Libplanet.Tests/Tx/TxInvoiceTest.cs, Libplanet.Tests/Tx/TxSigningMetadataTest.cs, Libplanet.Tests/Tx/UnsignedTxTest.cs, Libplanet/Tx/TxActionList.cs
I mistakenly pushed the commit that includes the JSON serialization test for tx types to a non-pr branch. 😅
=> JSON serialization tests for tx types (post #2986)

Libplanet.Net/Consensus/ConsensusContext.cs
PR leading from
- https://github.com/planetarium/libplanet/pull/3063
Reflected the comments below
- https://github.com/planetarium/libplanet/pull/3063#discussion_r1158401257
- https://github.com/planetarium/libplanet/pull/3063#discussion_r1158415801
=> Fix local variable startTime to be assigned safely

CHANGES.md, Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs, Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs, Libplanet.Net.Tests/Consensus/ConsensusReactorTest.cs, Libplanet.Net.Tests/TestUtils.cs, Libplanet.Net/Consensus/ConsensusContext.cs, Libplanet.Net/Consensus/ConsensusReactor.cs, Libplanet.Net/Consensus/Context.Async.cs, Libplanet.Net/Consensus/Context.cs
Revert below PRs, since those will break GST.
- https://github.com/planetarium/libplanet/pull/3063
- https://github.com/planetarium/libplanet/pull/3064
=> Revert #3063, #3064

CHANGES.md, Libplanet.Tests/Blockchain/BlockChainTest.ProposeBlock.cs
♻️ Also missing changelog from #3072. 😑
=> ♻️ Simple renaming

CHANGES.md, Libplanet.Extensions.Cocona/Commands/BlockCommand.cs
=> Add initialize state for genesis block

CHANGES.md, Libplanet/Libplanet.csproj
=> Release 1.0.0

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 1.1.0

CHANGES.md, Libplanet.Tests/Action/ActionEvaluatorTest.cs, Libplanet.Tests/Blockchain/BlockChainTest.cs, Libplanet.Tests/TestUtils.cs, Libplanet/Action/ActionEvaluator.cs, Libplanet/Action/IActionEvaluator.cs, Libplanet/Blockchain/BlockChain.cs
This pull request introduces the `IActionEvaluator` interface to abstract `ActionEvaluator` implementation.
note. I just requested reviews by my feeling. They can be replaced with more suitable ones.
=> Introduce `IActionEvaluator`

CHANGES.md, Libplanet.Tests/Action/ActionTypeAttributeTest.cs, Libplanet.Tests/Action/PolymorphicActionTest.cs, Libplanet.Tests/Action/StaticActionTypeLoaderTest.cs, Libplanet/Action/ActionEvaluator.cs, Libplanet/Action/ActionTypeAttribute.cs, Libplanet/Action/IActionTypeLoader.cs, Libplanet/Action/PolymorphicAction.cs, Libplanet/Action/StaticActionTypeLoader.cs
This is mainly in preparation to get rid of a distinction between system actions and custom actions. 😗
=> More generic action type attribute

CHANGES.md, Libplanet.Tests/Action/Sys/InitializeTest.cs, Libplanet.Tests/Action/Sys/MintTest.cs, Libplanet.Tests/Action/Sys/RegistryTest.cs, Libplanet.Tests/Action/Sys/TransferTest.cs, Libplanet.Tests/Tx/TxSystemActionListTest.cs, Libplanet/Action/Sys/Initialize.cs, Libplanet/Action/Sys/Mint.cs, Libplanet/Action/Sys/Registry.cs, Libplanet/Action/Sys/SysActionJsonConverter.cs, Libplanet/Action/Sys/Transfer.cs, Libplanet/Tx/Transaction.cs, Libplanet/Tx/TxSystemActionList.cs
In preparation for getting rid of `Transaction<T>.SystemAction`. 😗
=> ♻️ Refactor system actions

CHANGES.md
`IActonEvaluator` -> `IActionEvaluator`
=> Correct typo

Libplanet.Net.Tests/Consensus/GossipTest.cs, Libplanet.Net.Tests/SwarmTest.cs, Libplanet.Net/Consensus/Gossip.cs
=> Exclude seed peer when heartbeat in `Gossip`

Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
=> Add regression test for appending hotfix

CHANGES.md, Libplanet.RocksDBStore/RocksDBStore.cs, Libplanet.Tests/Blockchain/BlockChainTest.Append.cs, Libplanet/Blockchain/BlockChain.cs
=> Port changes from 1.0.1

CHANGES.md
=> 🚀 Release 1.1.0

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 1.2.0

CHANGES.md, Libplanet.Net.Tests/SwarmTest.Broadcast.cs, Libplanet.Net.Tests/SwarmTest.Preload.cs, Libplanet.Net.Tests/SwarmTest.cs, Libplanet.Tests/Blockchain/BlockChainTest.Append.cs, Libplanet.Tests/Blockchain/BlockChainTest.cs, Libplanet.Tests/Blockchain/Renderers/AnonymousActionRendererTest.cs, Libplanet.Tests/Blockchain/Renderers/AtomicActionRendererTest.cs, Libplanet.Tests/Blockchain/Renderers/LoggedActionRendererTest.cs, Libplanet.Tests/TestUtils.cs, Libplanet/Blockchain/BlockChain.Swap.cs, Libplanet/Blockchain/Renderers/AnonymousActionRenderer.cs, Libplanet/Blockchain/Renderers/AtomicActionRenderer.cs, Libplanet/Blockchain/Renderers/Debug/RecordingActionRenderer.cs, Libplanet/Blockchain/Renderers/Debug/RenderRecord.cs, Libplanet/Blockchain/Renderers/Debug/ValidatingActionRenderer.cs, Libplanet/Blockchain/Renderers/IActionRenderer.cs, Libplanet/Blockchain/Renderers/LoggedActionRenderer.cs
This pull request continues #3089.
=> Render `IValue` action instead of `IAction`

Libplanet.Explorer.Executable/Program.cs, Libplanet.Tests/Action/Sys/MintTest.cs, Libplanet.Tests/Action/Sys/TransferTest.cs, Libplanet.Tests/Store/StoreFixture.cs, Libplanet.Tests/TestUtils.cs, Libplanet/Action/ActionContext.cs
Just cleaning up some stuff missed in #3153.
=> 🧹 Remove remaining native tokens related API

CHANGES.md, Libplanet/Action/PolymorphicAction.cs, Libplanet/Action/PolymorphicActionLoader.cs
Temporary method added to allow standalone development testing with custom actions for debugging in [lib9c](https://github.com/planetarium/lib9c).
=> 🔧 Added `ReloadLoader()` method

CHANGES.md, Libplanet.Tools/download.mjs
=> Release 1.1.1 (a port of 1.0.3)

CHANGES.md, Libplanet.Tools/download.mjs
See also:
- #3107
- #3160
- #3161
=> Port 1.0.3 & 1.1.1 to main (1.2.x)

CHANGES.md
=> 🚀 Release 1.2.0

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 1.2.1

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 1.3.0

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 1.2.2

CHANGES.md, Libplanet.Explorer.Executable/Program.cs, Libplanet.Explorer.Tests/GeneratedBlockChainFixture.cs, Libplanet.Extensions.Cocona/Commands/BlockCommand.cs, Libplanet.Tests/Action/ActionEvaluatorTest.cs, Libplanet.Tests/Blockchain/BlockChainTest.Append.cs, Libplanet.Tests/Blockchain/BlockChainTest.ProposeBlock.cs, Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs, Libplanet.Tests/Blockchain/BlockChainTest.cs, Libplanet.Tests/Blocks/PreEvaluationBlockTest.cs, Libplanet.Tests/Fixtures/IntegerSet.cs, Libplanet.Tests/Store/StoreFixture.cs, Libplanet.Tests/Store/StoreTest.cs, Libplanet.Tests/TestUtils.cs, Libplanet/Blockchain/BlockChain.Evaluate.cs, Libplanet/Blockchain/BlockChain.ProposeBlock.cs, Libplanet/Blockchain/BlockChain.cs
Final preparation before removing `<T>` from `BlockChain<T>`. 😗
=> ♻️ Refactor `BlockChain<T>` constructors

CHANGES.md, Libplanet.Explorer.Executable/Program.cs, Libplanet.Explorer.Tests/Queries/MockBlockChainContext.cs, Libplanet.Explorer/Interfaces/IBlockChainContext.cs, Libplanet.Net.Tests/BlockCandidateTableTest.cs, Libplanet.Net.Tests/BlockCompletionTest.cs, Libplanet.Net.Tests/SwarmTest.Broadcast.cs, Libplanet.Net.Tests/SwarmTest.Fixtures.cs, Libplanet.Net.Tests/SwarmTest.Preload.cs, Libplanet.Net.Tests/SwarmTest.cs, Libplanet.Net.Tests/Transports/BoundPeerExtensionsTest.cs, Libplanet.Net/BlockCandidateTable.cs, Libplanet.Net/BlockCompletion.cs, Libplanet.Net/BlockDemand.cs, Libplanet.Net/DifferentAppProtocolVersionEncountered.cs, Libplanet.Net/Options/AppProtocolVersionOptions.cs, Libplanet.Net/Options/HostOptions.cs, Libplanet.Net/Options/SwarmOptions.cs, Libplanet.Net/Options/TimeoutOptions.cs, Libplanet.Net/Swarm.BlockCandidate.cs, Libplanet.Net/Swarm.BlockSync.cs, Libplanet.Net/Swarm.MessageHandlers.cs, Libplanet.Net/Swarm.cs, Libplanet.Net/Transports/DifferentAppProtocolVersionException.cs, Libplanet.Net/TxCompletion.cs, Libplanet/Action/ActionEvaluator.cs
=> 🧹 Remove `<T>` from `Swarm<T>`

CHANGES.md
=> 🚀 Release 1.3.0

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 1.4.0

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 1.3.1

CHANGES.md, Libplanet.Tests/Action/ActionContextTest.cs, Libplanet.Tests/Action/ActionEvaluatorTest.cs, Libplanet.Tests/Action/Sys/InitializeTest.cs, Libplanet/Action/ActionContext.cs, Libplanet/Action/ActionEvaluator.cs, Libplanet/Action/IActionContext.cs, Libplanet/Blockchain/BlockChain.cs, Libplanet/Blockchain/BlockChainStates.cs, Libplanet/Blockchain/IBlockChainStates.cs
=> 🧹 Removed GetTrie() from IBlockChainStates

CHANGES.md, Libplanet.Extensions.Cocona/Commands/BlockCommand.cs, Libplanet.Tests/Action/ActionEvaluatorTest.cs, Libplanet.Tests/Blockchain/BlockChainTest.ProposeBlock.cs, Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs, Libplanet.Tests/Blockchain/BlockChainTest.cs, Libplanet.Tests/Blocks/PreEvaluationBlockTest.cs, Libplanet.Tests/Fixtures/IntegerSet.cs, Libplanet.Tests/Store/StoreFixture.cs, Libplanet.Tests/Store/StoreTest.cs, Libplanet.Tests/TestUtils.cs, Libplanet/Blockchain/BlockChain.Evaluate.cs, Libplanet/Blockchain/BlockChain.ProposeBlock.cs, Libplanet/Blockchain/BlockChain.cs
=> ♻️ General API cleanup for `BlockChain.Create()`

CHANGES.md
=> 🚀 Release 1.4.0

CHANGES.md, Libplanet.Tests/Action/ActionEvaluatorTest.cs, Libplanet.Tests/Action/Sys/InitializeTest.cs, Libplanet/Action/ActionContext.cs, Libplanet/Action/ActionEvaluator.cs, Libplanet/Action/IActionContext.cs
♻️ 
- General clarification on `IActionContext` properties.
- Removed `blockAction` parameter from `ActionContext()` due to undefined behavior.
=> ♻️ Refactor `ActionContext`

CHANGES.md
=> 🚀 Release 2.0.0

CHANGES.md
=> Fix typo on changelog

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 2.1.0

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 2.0.1

CHANGES.md
=> 🚀 Release 2.1.0

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 2.1.1

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 2.2.0

CHANGES.md
You can see the changes in https://github.com/planetarium/libplanet/compare/2.0.0..2.0-maintenance.
=> Release 2.0.1

CHANGES.md
=> 🚀 Release 2.1.1

CHANGES.md, Libplanet.Tests/Action/AccountStateDeltaTest.cs, Libplanet.Tests/Action/AccountStateDeltaV0Test.cs, Libplanet.Tests/Action/AccountStateDeltaV1Test.cs, Libplanet.Tests/Action/ActionEvaluationTest.cs, Libplanet.Tests/Action/ActionEvaluatorTest.cs, Libplanet.Tests/Action/Sys/InitializeTest.cs, Libplanet.Tests/Blockchain/BlockChainTest.cs, Libplanet.Tests/Blockchain/Renderers/AnonymousActionRendererTest.cs, Libplanet.Tests/Blockchain/Renderers/LoggedActionRendererTest.cs, Libplanet.Tests/Fixtures/IntegerSet.cs, Libplanet/Action/ActionEvaluator.cs, Libplanet/State/AccountStateDelta.cs
🧹 Just some minor cleanup here and there. No API changes.
=> 🧹 Housekeeping

CHANGES.md
=> 🚀 Release 2.2.0

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 2.1.2

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 2.2.1

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 2.3.0

CHANGES.md, Libplanet.Tests/Action/AccountStateDeltaTest.cs, Libplanet.Tests/Action/AccountStateDeltaV1Test.cs, Libplanet.Tests/Action/ActionContextTest.cs, Libplanet/Action/ActionEvaluationsExtensions.cs, Libplanet/State/AccountStateDelta.cs, Libplanet/State/AccountStateDeltaExtensions.cs, Libplanet/State/IAccountStateDelta.cs, Libplanet/Tx/TxSuccess.cs
=> ♻️ API streamlining related to `IAccountStateDelta`

CHANGES.md
=> 🚀 Release 2.3.0

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 2.3.1

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 2.4.0

Libplanet.Tests/Action/ActionContextTest.cs
=> 🧹  Removed unnecessary test code

CHANGES.md
=> 🚀 Release 2.4.0

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 2.4.1

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 2.5.0

CHANGES.md, Libplanet.Net.Tests/Consensus/GossipConsensusMessageCommunicatorTest.cs, Libplanet.Net.Tests/Consensus/GossipTest.cs, Libplanet.Net/Consensus/Gossip.cs, Libplanet.Net/Consensus/GossipConsensusMessageCommunicator.cs
- https://github.com/planetarium/libplanet/issues/3266
=> Add spam filter logic on communicator #3271

Libplanet.Benchmarks/Store.cs, Libplanet.Crypto.Secp256k1.Tests/Secp256k1CryptoBackendTest.cs, Libplanet.Net.Tests/Messages/NetMQMessageCodecTest.cs, Libplanet.Net.Tests/SwarmTest.cs, Libplanet.Net/Swarm.MessageHandlers.cs, Libplanet.RocksDBStore/RocksDBStore.cs, Libplanet.Tests/Blockchain/BlockChainTest.ProposeBlock.cs, Libplanet/Blockchain/BlockChain.cs, Libplanet/ByteUtil.cs, Libplanet/HashDigest.cs, Libplanet/Tx/TxMarshaler.cs
For micro improvement on performance.
=> ⚡ Use `Array.Empty`

Libplanet.Net/Consensus/Context.cs, Libplanet.Net/Consensus/GossipConsensusMessageCommunicator.cs, Libplanet.Net/Consensus/HeightVoteSet.cs, Libplanet.Net/Consensus/VoteSet.cs
Bugfix for unhandled exceptions
=> Catch when RoundVoteSet not found

Libplanet.Tests/Action/ActionContextTest.cs, Libplanet.Tests/Action/ActionEvaluatorTest.cs, Libplanet/Action/ActionEvaluator.cs
Mostly decluttering arguments before exposing `EvaluateActions` and `EvaluateTx`. No real visible changes. 😗
=> ♻️ Refactor `Evaluate`

CHANGES.md, Libplanet.Benchmarks/AppendBlock.cs, Libplanet.Benchmarks/BlockChain.cs, Libplanet.Benchmarks/ProposeBlock.cs, Libplanet.Explorer.Executable/Program.cs, Libplanet.Explorer.Tests/GeneratedBlockChainFixture.cs, Libplanet.Extensions.Cocona/Commands/BlockCommand.cs, Libplanet.Net.Tests/Consensus/ConsensusReactorTest.cs, Libplanet.Net.Tests/SwarmTest.Broadcast.cs, Libplanet.RocksDBStore.Tests/RocksDBStoreTest.cs, Libplanet.Tests/Action/ActionEvaluatorTest.cs, Libplanet.Tests/Blockchain/BlockChainTest.Append.cs, Libplanet.Tests/Blockchain/BlockChainTest.ProposeBlock.cs, Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs, Libplanet.Tests/Blockchain/BlockChainTest.cs, Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs, Libplanet.Tests/Blockchain/Policies/StagePolicyTest.cs, Libplanet.Tests/Blocks/PreEvaluationBlockTest.cs, Libplanet.Tests/Fixtures/IntegerSet.cs, Libplanet.Tests/Store/StoreFixture.cs, Libplanet.Tests/Store/StoreTest.cs, Libplanet.Tests/TestUtils.cs, Libplanet/Action/ActionEvaluator.cs, Libplanet/Action/IFeeCalculator.cs, Libplanet/Blockchain/Policies/BlockPolicy.cs, Libplanet/Blockchain/Policies/IBlockPolicy.cs, Libplanet/Blockchain/Policies/NullBlockPolicy.cs
=> 🧹 Removed `IFeeCalculator`

Libplanet/Crypto/CryptoConfig.cs
=> 🧹 Nullable crypto

CHANGES.md, Libplanet.Tests/Action/ActionContextTest.cs, Libplanet/Action/ActionContext.cs, Libplanet/Action/ActionEvaluation.cs, Libplanet/Action/ActionEvaluator.cs, Libplanet/Action/IActionContext.cs, Libplanet/Action/IActionEvaluation.cs
=> 🧹 Removed `Logs` from `IActionContext` and `IActionEvaluation`

Libplanet.Net/Swarm.BlockSync.cs
=> Log empty block demand as success on `PullBlocksAsync`

CHANGES.md, Libplanet/Assets/Currency.cs
=> Fix `Currency` backward compability broken bug 

CHANGES.md
=> 🚀 Release 2.5.0

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 2.6.0

CHANGES.md, Libplanet.Explorer/Libplanet.Explorer.csproj, Libplanet/Libplanet.csproj
=> ⬆️ Bump Bencodex to 0.11.0

CHANGES.md
=> 🚀 Release 2.4.1

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 2.4.2

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 2.5.1

CHANGES.md, Libplanet.Common/ByteUtil.cs, Libplanet.Explorer/Libplanet.Explorer.csproj, Libplanet.RocksDBStore/RocksDBStore.cs, Libplanet/Libplanet.csproj
=> 🔀 Merge 2.4.1 to main

CHANGES.md, Libplanet.Explorer/Libplanet.Explorer.csproj, Libplanet.RocksDBStore/RocksDBStore.cs, Libplanet/ByteUtil.cs, Libplanet/Libplanet.csproj
=> 🔀 Merge 2.4.1 to 2.5.x

CHANGES.md
=> 🚀 Release 3.0.0

Libplanet/Libplanet.csproj
Since commit d4b7fb4ddff53907b8e97d43c7928e32147fd3bf doesn't update project version, this commit has been added to fix.
=> Release 3.0.0

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 3.1.0

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 3.0.1

Libplanet.Action/Libplanet.Action.csproj, Libplanet.Action/State/AccountDeltaExtensions.cs, Libplanet.Action/State/BlockState.cs, Libplanet.Action/State/IBlockChainStates.cs, Libplanet.Action/State/InsufficientBalanceException.cs, Libplanet.Action/State/TotalSupplyNotTrackableException.cs
=> 🧹 Edited `csproj`

Libplanet.Action.Tests/DuplicateActionTypeIdentifierExceptionTest.cs
=> 🔧 Simple test fix

CHANGES.md, Docs/api/index.md, Docs/toc.yml, Libplanet.Action.Tests/DuplicateActionTypeIdentifierExceptionTest.cs, Libplanet.Action/Libplanet.Action.csproj, Libplanet.Action/State/AccountDeltaExtensions.cs, Libplanet.Action/State/BlockState.cs, Libplanet.Action/State/IBlockChainStates.cs, Libplanet.Action/State/InsufficientBalanceException.cs, Libplanet.Action/State/TotalSupplyNotTrackableException.cs
Cherry picked from #3320, #3322, #3324.
=> 🔨 Fix tests and builds

CHANGES.md
=> 🚀 Release 3.0.1

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔀 Merge 3.0.1 to main

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 3.0.2

CHANGES.md, Libplanet.Action/Libplanet.Action.csproj, Libplanet.Crypto/Libplanet.Crypto.csproj, Libplanet.Store/Libplanet.Store.csproj, Libplanet.Types/Libplanet.Types.csproj, Libplanet/Libplanet.csproj
=> ⬆️ Bump bencodex to 0.12.0

CHANGES.md
=> 🚀 Release 3.1.0

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 3.2.0

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 3.1.1

Libplanet.Explorer.Executable/Libplanet.Explorer.Executable.csproj, Libplanet.RocksDBStore/Libplanet.RocksDBStore.csproj, Libplanet.Tests/Libplanet.Tests.csproj
=> 🧹 Fix `csproj` files

Libplanet.Store/Trie/MerkleTrie.cs
=> 🧹  Remove offloading from MerkleTrie

Libplanet.Tests/Libplanet.Tests.csproj
=> 🔧 Fix csproj

Libplanet.Net/Swarm.BlockSync.cs
This pull request resolves #3253.
=> fix: check block is in chain

Libplanet.Store/Trie/MerkleTrie.cs, Libplanet.Tests/Store/TrieStateStoreTest.cs
=> 🧹 Removed Bencodex `Fingerprint` support

CHANGES.md
=> 🚀  Release 3.1.1

CHANGES.md, Libplanet.Action/Libplanet.Action.csproj, Libplanet.Crypto/Libplanet.Crypto.csproj, Libplanet.Store/Libplanet.Store.csproj, Libplanet.Types/Libplanet.Types.csproj, Libplanet/Libplanet.csproj
=> ⬆️ Bump Bencodex to 0.14.0

CHANGES.md
=> 🔀 Merge 3.1.1 into main

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 3.1.2

CHANGES.md, Libplanet.Action/Libplanet.Action.csproj, Libplanet.Crypto/Libplanet.Crypto.csproj, Libplanet.Store/Libplanet.Store.csproj, Libplanet.Store/Trie/MerkleTrie.cs, Libplanet.Types/Libplanet.Types.csproj, Libplanet/Libplanet.csproj
=> 🔀 ⬆️ Backport Bencodex bump to 0.14.0

CHANGES.md
=> 🚀 Release 3.1.2

CHANGES.md
=> 🔀 Port 3.1.2 to main

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 3.1.3

CHANGES.md
=> 🚀 Release 3.2.0

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 3.3.0

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 3.2.1

Libplanet.Net.Tests/SwarmTest.Broadcast.cs, Libplanet.Net.Tests/SwarmTest.Preload.cs, Libplanet.Net.Tests/SwarmTest.cs, Libplanet.Net/Transports/NetMQTransport.cs
=> fix(test): Cleaning Swarm when finish each tests

Libplanet.Extensions.Cocona.Tests/Commands/StatsCommandTest.cs, Libplanet.Extensions.Cocona.Tests/Commands/StoreCommandTest.cs
=> fix: dispose rocksdb when finish tests

Libplanet.Extensions.Cocona.Tests/Commands/StatsCommandTest.cs, Libplanet.Extensions.Cocona.Tests/Commands/StoreCommandTest.cs
=> fix(test): dispose TextWriter

.circleci/config.yml
=> fix(ci): add more parallelism

.circleci/config.yml
=> fix(ci): ignore malicious tests

.circleci/config.yml
=> fix: ignore malicious tests (Tools)

.circleci/config.yml
=> fix: do not use codecov when running circle ci

.circleci/config.yml
=> fix(ci): no output timeout 2m to 3m

Libplanet.Net.Tests/Transports/TransportTest.cs
=> fix(test): call `StopAsync` before dispose

CHANGES.md, Libplanet.Store/Trie/Nodes/FullNode.cs, Libplanet.Store/Trie/Nodes/HashNode.cs, Libplanet.Store/Trie/Nodes/ShortNode.cs, Libplanet.Store/Trie/Nodes/ValueNode.cs
Preparatory work before implementing `ITrie` "diff".
=> Fix node equality for `INode`

CHANGES.md, Libplanet.Store/Trie/ITrie.cs, Libplanet.Store/Trie/MemoryKeyValueStore.cs, Libplanet.Store/Trie/MerkleTrie.Path.cs, Libplanet.Store/Trie/MerkleTrie.cs, Libplanet.Store/Trie/PathCursor.cs, Libplanet.Store/TrieStateStore.Commit.cs, Libplanet.Tests/Store/Trie/MerkleTrieTest.cs, Libplanet.Tests/Store/Trie/PathCursorTest.cs
Preparatory PR to introduce trie diff. Also fixes a small bug.
=> ✨ Introduce `ITrie.GetNode()`

Libplanet.Store/Trie/MerkleTrie.cs, Libplanet.Store/Trie/Nodes/NodeDecoder.cs, Libplanet.Tests/Store/Trie/Nodes/NodeDecoderTest.cs
Mostly additional safety features. If implemented correctly, performance degradation should be unnoticeable. 😗
=> ♻️ Refactor `NodeDecoder`

Libplanet.Action/State/Account.cs
Resolves #3396. Long time coming. More streamlined `Account` mutation. 😗
=> ♻️ Refactor `Account`

CHANGES.md
=> 🚀 Release 3.3.0

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 3.3.1

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 3.4.0

CHANGES.md
=> 🚀 Release 3.3.1

CHANGES.md, Libplanet.Store/Trie/MerkleTrie.Path.cs, Libplanet.Tests/Store/Trie/MerkleTrieTest.cs
=> 🔀 Merge 3.3.1 to main

CHANGES.md, Libplanet.Action/State/IBlockChainStates.cs, Libplanet.Explorer.Tests/Queries/StateQueryTest.cs, Libplanet/Blockchain/BlockChain.cs, Libplanet/Blockchain/BlockChainStates.cs, Libplanet/Blockchain/NullChainStates.cs
Preparatory work to move to more `ITrie` based state handling.
=> Added new GetAccountState() interface method

CHANGES.md, Libplanet.Action.Tests/Sys/InitializeTest.cs, Libplanet.Action/ActionRenderContext.cs, Libplanet.Action/IActionRenderContext.cs, Libplanet.Action/State/IBlockChainStates.cs, Libplanet.Explorer.Tests/Queries/StateQueryTest.cs, Libplanet.Tests/Action/ActionEvaluatorTest.cs, Libplanet.Tests/Blockchain/BlockChainTest.Append.cs, Libplanet.Tests/Blockchain/BlockChainTest.cs, Libplanet.Tests/Blockchain/Renderers/AnonymousActionRendererTest.cs, Libplanet.Tests/Blockchain/Renderers/LoggedActionRendererTest.cs, Libplanet.Tests/Store/TrieStateStoreTest.cs, Libplanet/Blockchain/BlockChain.Swap.cs, Libplanet/Blockchain/BlockChain.cs, Libplanet/Blockchain/BlockChainStates.cs, Libplanet/Blockchain/NullChainStates.cs, Libplanet/Blockchain/Renderers/AnonymousActionRenderer.cs, Libplanet/Blockchain/Renderers/AtomicActionRenderer.cs, Libplanet/Blockchain/Renderers/Debug/RecordingActionRenderer.cs, Libplanet/Blockchain/Renderers/Debug/RenderRecord.cs, Libplanet/Blockchain/Renderers/Debug/ValidatingActionRenderer.cs, Libplanet/Blockchain/Renderers/IActionRenderer.cs, Libplanet/Blockchain/Renderers/LoggedActionRenderer.cs
Should resolve the issue of double commit before merging to main. It'll be handled in a separate PR. 🙄
=> ♻️ Refactor `IActionRenderer`

CHANGES.md, Libplanet.Store/BaseStore.cs, Libplanet.Tests/Blockchain/BlockChainTest.Append.cs, Libplanet.Tests/Blockchain/BlockChainTest.Internals.cs, Libplanet.Tests/Store/StoreTest.cs, Libplanet.Tests/Tx/TxFailureTest.cs, Libplanet.Tests/Tx/TxSuccessTest.cs, Libplanet.Types/Tx/TxExecution.cs, Libplanet.Types/Tx/TxFailure.cs, Libplanet.Types/Tx/TxSuccess.cs
Removing some clutter before overhauling to use `HashDigest<SHA256>`s. 🙄
=> ♻️ Cleanup `TxSuccess` and `TxFailure`

Libplanet/Blockchain/BlockChain.Swap.cs
=> 🧹 Remove unnecessary clutter

Libplanet.Store/IStore.cs
=> 🧹 Docs fix

CHANGES.md
=> 🚀 Release 3.4.0

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 3.3.2

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 3.5.0

CHANGES.md, Libplanet.Action.Tests/ActionContextTest.cs, Libplanet.Action.Tests/Common/DumbAction.cs, Libplanet.Action.Tests/Common/RandomAction.cs, Libplanet.Action/ActionContext.cs, Libplanet.Action/ActionEvaluator.cs, Libplanet.Action/CommittedActionContext.cs, Libplanet.Action/IActionContext.cs, Libplanet.Action/ICommittedActionContext.cs, Libplanet.Analyzers.Tests/ActionAnalyzerTest.cs, Libplanet.Analyzers/ActionAnalyzer.cs, Libplanet.Tests/Action/ActionEvaluatorTest.cs, Libplanet.Tests/Blockchain/BlockChainTest.cs, Libplanet/Blockchain/BlockChain.Evaluate.cs, Libplanet/Blockchain/BlockChain.Swap.cs
Tested on mainnet.  Skipping changelog for `ICommittedActionContext` as it will be removed in a follow-up PR.
=> ♻️ Immutable `IActionContext`

CHANGES.md, Libplanet.Action/ActionEvaluator.cs, Libplanet.Action/IActionEvaluator.cs, Libplanet.Tests/Action/ActionEvaluatorTest.cs, Libplanet.Tests/Blockchain/BlockChainTest.cs, Libplanet/Blockchain/BlockChain.Evaluate.cs, Libplanet/Blockchain/BlockChain.Swap.cs
`IActionEvaluator` should not really care about `IStore`. 🙄
=> ♻️ Partially remove `IStore`/`BlockChain` dependency from `IActionEvaluator`

CHANGES.md
=> 🚀 Release 3.5.0

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 3.6.0

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 3.5.1

CHANGES.md, Libplanet.Explorer.Tests/GraphTypes/TxResultTypeTest.cs, Libplanet.Explorer/GraphTypes/HashDigestSHA256Type.cs, Libplanet.Explorer/GraphTypes/TxResult.cs, Libplanet.Explorer/GraphTypes/TxResultType.cs, Libplanet.Explorer/Queries/TransactionQuery.cs
=> ✨ Add `InputState` and `OutputState` to `TxResult`

CHANGES.md
=> 🚀 Release 3.6.0

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 3.7.0

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 3.6.1

Libplanet.Action.Tests/Common/BattleResult.cs, Libplanet.Action.Tests/Common/DumbAction.cs, Libplanet.Action.Tests/Common/MinerReward.cs, Libplanet.Action.Tests/Common/RandomAction.cs, Libplanet.Action.Tests/Common/SetStatesAtBlock.cs, Libplanet.Action.Tests/Common/SetValidator.cs, Libplanet.Action.Tests/Common/ThrowException.cs, Libplanet.Action/IAction.cs, Libplanet.Store/BlockDigest.cs, Libplanet.Tests/Store/StoreTest.cs, Libplanet.Tests/Tx/TxMarshalerTest.cs, Libplanet.Types/Blocks/BlockCommit.cs, Libplanet.Types/Tx/TxMetadata.cs
🧹 Should be all of 'em unless I've missed something. 😗
=> 🧹 General refactoring to remove `Dictionary.GetValue<T>()`

CHANGES.md
=> 🚀 Release 3.7.0

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 4.0.0

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 3.7.1

Libplanet.Action/ActionEvaluator.cs, Libplanet.Action/State/World.cs, Libplanet.Explorer.Tests/Queries/StateQueryTest.cs, Libplanet/Blockchain/BlockChain.cs
=> 🧹 Fix build warnings

Libplanet/Blockchain/BlockChain.States.cs, Libplanet/Blockchain/BlockChain.cs
=> 🧹 Reorganize and cleanup `BlockChain`

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 3.8.0

Libplanet.Action.Tests/Common/Attack.cs, Libplanet.Action.Tests/Common/DetectRehearsal.cs, Libplanet.Action.Tests/Common/DumbAction.cs, Libplanet.Action.Tests/Common/SetStatesAtBlock.cs, Libplanet.Action.Tests/Loader/IndexedActionLoaderTest.cs, Libplanet.Tests/Action/ActionEvaluatorTest.cs, Libplanet.Tests/Blocks/BlockMarshalerTest.cs, Libplanet.Tests/Tx/TxMarshalerTest.cs, Libplanet.Tests/Tx/TxMetadataTest.cs, Libplanet.Types/Assets/Currency.cs, Libplanet.Types/Blocks/BlockMarshaler.cs, Libplanet.Types/Blocks/BlockMetadata.cs, Libplanet.Types/Tx/TxMarshaler.cs, Libplanet.Types/Tx/TxMetadata.cs
=> 🧹 Use `Address.Bencoded` instead of `Address.ByteArray`

CHANGES.md
=> 🚀 Release 3.6.1

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 3.6.2

CHANGES.md, Libplanet/Libplanet.csproj
⏪ This reverts commit 585f4ed3ed66691c663e6e789ea87a50001ec8ea.
=> ⏪ Revert "Prepare 3.6.2"

CHANGES.md, Libplanet.Net/Consensus/ContextTimeoutOption.cs
=> 🔧 Changed default ContextTimeoutOption values

CHANGES.md
=> 🚀 Release 3.6.2

CHANGES.md, Libplanet.Net/Consensus/ContextTimeoutOption.cs
=> 🔀 Port 3.6.2 to 3.7.1

CHANGES.md
=> 🚀 Release 3.7.1

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 3.6.3

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 3.7.2

CHANGES.md
=> 🚀 Release 3.8.0

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 3.9.0

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 3.8.1

CHANGES.md, Libplanet.Action/AccountMetrics.cs, Libplanet.Action/ActionEvaluator.cs
=> Fix AccountMetrics to initialize

CHANGES.md
=> 🚀 Release 3.8.1

CHANGES.md, Libplanet.Action/ActionEvaluator.cs, Libplanet.Tests/Action/ActionEvaluatorTest.cs
Mainly to mitigate unnecessary code rigidity by removing premature optimization and/or coupling.
=> ♻️ Refactor random seed generation

CHANGES.md, Libplanet.Action/AccountMetrics.cs, Libplanet.Action/ActionEvaluator.cs, Libplanet.Net/Consensus/GossipConsensusMessageCommunicator.cs
=> 🔀 Port 3.8.1 to 3.9.0

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 3.8.2

CHANGES.md, Libplanet.Explorer.Executable/Program.cs, Libplanet.Tests/Blockchain/BlockChainTest.Append.cs, Libplanet.Tests/Blockchain/BlockChainTest.ProposeBlock.cs, Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs, Libplanet.Tests/Blockchain/BlockChainTest.cs, Libplanet.Tests/TestUtils.cs, Libplanet/Blockchain/BlockChain.States.cs, Libplanet/Blockchain/BlockChain.cs, Libplanet/Blockchain/BlockChainStates.cs
This PR restores `BlockChainStates` class which was removed in #3462
=> Restore `BlockChainState`

CHANGES.md, Libplanet.Action/ActionEvaluator.cs, Libplanet.Action/State/Account.cs
=> 🧹 Remove internal tracking of amounts for `TotalUpdatedFungibleAssets`

CHANGES.md
🚀 Let's just hope this is final and we won't need 3.10.0. 😗
=> 🚀 Release 3.9.0

CHANGES.md
=> 🚀 Release 3.9.1

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 3.9.2

Libplanet.Explorer.Tests/Queries/TransactionQueryTest.cs, Libplanet.Net.Tests/Consensus/ConsensusContextNonProposerTest.cs, Libplanet.Net.Tests/Consensus/ConsensusContextProposerTest.cs, Libplanet.Net.Tests/Consensus/ConsensusContextTest.cs, Libplanet.Net.Tests/Consensus/ContextNonProposerTest.cs, Libplanet.Net.Tests/Consensus/ContextTest.cs, Libplanet.Net.Tests/Messages/NetMQMessageCodecTest.cs, Libplanet.Net.Tests/SwarmTest.Broadcast.cs, Libplanet.Net.Tests/SwarmTest.Fixtures.cs, Libplanet.Net.Tests/SwarmTest.Preload.cs, Libplanet.Net.Tests/SwarmTest.cs, Libplanet.Net.Tests/TestUtils.cs, Libplanet.Net.Tests/Transports/BoundPeerExtensionsTest.cs, Libplanet.Tests/Action/AccountTest.cs, Libplanet.Tests/Action/ActionEvaluatorTest.cs, Libplanet.Tests/Blockchain/BlockChainTest.Append.cs, Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs, Libplanet.Tests/Blockchain/BlockChainTest.cs, Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs, Libplanet.Tests/TestUtils.cs
Remove remaining `<T>`s from tests.
=> Replace <T> with IActionLoader param

CHANGES.md, Libplanet.Explorer.Tests/GeneratedBlockChainFixture.cs, Libplanet.Explorer.Tests/GraphTypes/TxResultTypeTest.cs, Libplanet.Explorer.Tests/Queries/TransactionQueryGeneratedTest.cs, Libplanet.Explorer/GraphTypes/TxStatusType.cs, Libplanet.Explorer/Queries/TransactionQuery.cs, Libplanet.Tests/Action/AccountTest.cs
=> 🔀 Port 3.9.1 to 4.0.0

CHANGES.md
=> 🚀 Release 3.9.2

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 3.9.3

Libplanet.Explorer.Tests/Queries/StateQueryTest.cs, Libplanet.Explorer/Queries/ExplorerQuery.cs, Libplanet.Explorer/Queries/StateQuery.cs
=> 🧹 Removed `IBlockPolicy` as generic type parameter for `StateQuery`

Libplanet.Action/ActionContext.cs, Libplanet.Analyzers.Tests/Helpers/DiagnosticResult.cs, Libplanet.Benchmarks/AppendBlock.cs, Libplanet.Benchmarks/BlockChain.cs, Libplanet.Benchmarks/Program.cs, Libplanet.Benchmarks/ProposeBlock.cs, Libplanet.Crypto.Secp256k1.Tests/Secp256k1CryptoBackendTest.cs, Libplanet.Crypto.Secp256k1/Secp256k1CryptoBackend.cs, Libplanet.Explorer.Tests/GraphQLTestUtils.cs, Libplanet.Explorer.Tests/GraphTypes/FungibleAssetValueTypeTest.cs, Libplanet.Explorer.Tests/GraphTypes/HashDigestTypeTest.cs, Libplanet.Explorer.Tests/Indexing/RocksDbBlockChainIndexTest.cs, Libplanet.Explorer.Tests/Queries/MockBlockChainContext.cs, Libplanet.Explorer.Tests/Queries/StateQueryTest.cs, Libplanet.Explorer.Tests/Queries/TransactionQueryGeneratedWithIndexTest.cs, Libplanet.Explorer.Tests/Queries/TransactionQueryTest.cs, Libplanet.Explorer/GraphTypes/BoundPeerType.cs, Libplanet.Explorer/Interfaces/IBlockChainContext.cs, Libplanet.Explorer/Queries/ExplorerQuery.cs, Libplanet.Extensions.Cocona.Tests/BlockPolicyParamsTest.cs, Libplanet.Extensions.Cocona/BlockPolicyParams.cs, Libplanet.Extensions.Cocona/Utils.cs, Libplanet.Net/Consensus/Context.Mutate.cs, Libplanet.Store/MemoryStore.cs, Libplanet.Store/Trie/PathCursor.cs, Libplanet.Tests/Blockchain/BlockChainTest.Append.cs, Libplanet.Tests/Blockchain/BlockChainTest.Internals.cs, Libplanet.Tests/Crypto/SymmetricKeyTest.cs, Libplanet.Types/Consensus/ValidatorSet.cs, Libplanet/Blockchain/BlockChain.TxExecution.cs
=> 🧹 Remove unnecessary usings

CHANGES.md, Libplanet.Store/Trie/MerkleTrie.cs, Libplanet.Store/Trie/Nodes/FullNode.cs, Libplanet.Tests/Store/Trie/Nodes/NodeDecoderTest.cs
Increase in performance is likely to be miniscule and not worth running a benchmark. 🙄
=> ⚡ ♻️ Slightly optimized `FullNode`

CHANGES.md
=> 🚀 Release 3.9.3

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 3.9.4

CHANGES.md, Libplanet.Action/ActionEvaluator.cs, Libplanet.RocksDBStore/RocksDBKeyValueStore.cs
=> 🔀 Merge 3.9.2 to main

Libplanet.Net.Tests/Consensus/GossipConsensusMessageCommunicatorTest.cs, Libplanet.Net/Consensus/GossipConsensusMessageCommunicator.cs
- Fix `GossipConsensusMessageCommunicator` to use `ConcurrentDictionary`
- Simplify & fix `GossipConsensusMessageCommunicatorTest.ReceiveHigherMessage()`
- Still `GossipConsensusMessageCommunicatorTest.ReceiveHigherMessage()` is hanged sometimes, though test has been fixed. This have to be handled later on.
=> Fix GossipConsensusMessageCommunicator

Libplanet.Action/State/WorldBaseState.cs
=> 🧹 Clutter removal

CHANGES.md
=> 🧹 Updated changelog

Libplanet.Action.Tests/Mocks/MockWorldState.cs, Libplanet.Action/State/AccountState.cs, Libplanet.Action/State/IAccountState.cs, Libplanet.Action/State/IWorld.cs, Libplanet.Action/State/IWorldState.cs, Libplanet.Action/State/World.cs, Libplanet.Action/State/WorldBaseState.cs, Libplanet.Action/State/WorldExtensions.cs, Libplanet.Explorer.Tests/Queries/StateQueryTest.Mocks.cs, Libplanet.Explorer/GraphTypes/WorldStateType.cs, Libplanet.Explorer/Queries/StateQuery.cs, Libplanet.Net.Tests/Consensus/ContextTest.cs, Libplanet.Net.Tests/SwarmTest.Preload.cs, Libplanet.Net.Tests/SwarmTest.cs, Libplanet.Net.Tests/TestUtils.cs, Libplanet.Net/Consensus/ConsensusContext.cs, Libplanet.Tests/Action/AccountTest.cs, Libplanet.Tests/Action/AccountV0Test.cs, Libplanet.Tests/Action/AccountV1Test.cs, Libplanet.Tests/Action/ActionEvaluatorTest.cs, Libplanet.Tests/Blockchain/BlockChainTest.Append.cs, Libplanet.Tests/Blockchain/BlockChainTest.ProposeBlock.cs, Libplanet.Tests/Blockchain/BlockChainTest.cs, Libplanet.Tests/Blocks/PreEvaluationBlockTest.cs, Libplanet.Tests/Fixtures/IntegerSet.cs, Libplanet/Blockchain/BlockChain.Validate.cs
=> ♻️ Refactor `IWorldState` to be read-only

CHANGES.md
=> 🚀 Release 3.9.4

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 3.9.5

Libplanet.Action/ActionEvaluator.cs, Libplanet.Action/State/World.cs
=> 🧹 Minor cleanup for `IWorldState`

Libplanet.Action/State/World.cs, Libplanet.Action/State/WorldBaseState.cs, Libplanet.Tests/Action/ActionEvaluatorTest.cs
🧹 Just encountered more while working on refactoring `IWorldState` 🙄
=> 🧹 Removed unnecessary code

CHANGES.md, Libplanet.Explorer.Executable/Program.cs, Libplanet.Store/IStateStore.cs, Libplanet.Store/TrieStateStore.cs, Libplanet.Tests/Blockchain/BlockChainTest.cs, Libplanet.Tests/Store/StateStoreTracker.cs, Libplanet.Tests/Store/TrieStateStoreTest.cs
=> ♻️ 🧹 Removed `IStateStore.PruneStates()`

CHANGES.md
=> 🚀 Release 3.9.5

CHANGES.md, Libplanet.Explorer.Executable/Program.cs, Libplanet.Store/IStateStore.cs, Libplanet.Store/Trie/MerkleTrie.Diff.cs, Libplanet.Store/Trie/MerkleTrie.Insert.cs, Libplanet.Store/Trie/MerkleTrie.cs, Libplanet.Store/TrieStateStore.Commit.cs, Libplanet.Store/TrieStateStore.cs, Libplanet.Tests/Blockchain/BlockChainTest.cs, Libplanet.Tests/Store/StateStoreTracker.cs, Libplanet.Tests/Store/TrieStateStoreCommitTest.cs, Libplanet.Tests/Store/TrieStateStoreTest.cs
=> 🔀 Merge 3.9.5 to main

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 3.9.6

CHANGES.md
=> 🚀 Release 4.0.0

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 4.1.0

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 4.0.1

CHANGES.md, Libplanet.Action/State/AccountState.cs, Libplanet.Action/State/IWorld.cs, Libplanet.Action/State/World.cs, Libplanet.Action/State/WorldDelta.cs, Libplanet.Tests/Action/AccountTest.cs
=> ♻️ More strict `IWorld.SetAccount()` behavior

CHANGES.md
=> 🚀 Release 3.9.6

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 3.9.7

CHANGES.md, Libplanet.Store/Trie/MerkleTrie.cs
=> 🔀 Merge 3.9.6 to 4.0-maintenance

CHANGES.md
=> 🧹 Fix changelog

CHANGES.md
=> 🚀 Release 4.0.1

CHANGES.md, Libplanet.Action/State/AccountState.cs, Libplanet.Action/State/IWorld.cs, Libplanet.Action/State/World.cs, Libplanet.Action/State/WorldDelta.cs, Libplanet.Store/Trie/MerkleTrie.cs, Libplanet.Tests/Action/AccountTest.cs
=> 🔀 Merge 4.0.1 to main

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 4.0.2

Libplanet.Tests/Blockchain/BlockChainTest.Stage.cs, Libplanet.Tests/Blockchain/BlockChainTest.cs, Libplanet.Tests/Store/StoreFixture.cs
=> 🧹 Remove unnecessary test code

CHANGES.md, Libplanet.Explorer.Tests/Queries/TransactionQueryGeneratedTest.cs, Libplanet.Explorer/Indexing/BlockChainIndexBase.cs, Libplanet.Explorer/Queries/ExplorerQuery.cs, Libplanet.Store/BaseIndex.cs, Libplanet.Store/BaseStore.cs, Libplanet.Store/BlockSet.cs, Libplanet.Store/DefaultStore.cs, Libplanet.Store/IStore.cs, Libplanet.Store/MemoryStore.cs, Libplanet.Store/StoreExtensions.cs
=> Removal of '#nullable disable' from the Libplanet.Store project

CHANGES.md, Libplanet.Net/AppProtocolVersion.cs
=> 🔊 Added which string caused an APV parsing error to log

CHANGES.md, Libplanet.Explorer/schema.graphql
=> 📝 Updated graphql schema

CHANGES.md
=> 🚀 Release 4.0.2

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 4.0.3

.github/workflows/check-changelog.yml, CHANGES.md, Libplanet.Explorer/schema.graphql, Libplanet.Net/AppProtocolVersion.cs
=> 🔀 Merge 4.0.2 to main

CHANGES.md, Libplanet.Explorer/GraphTypes/BlockCommitType.cs, Libplanet.Explorer/GraphTypes/BlockType.cs, Libplanet.Explorer/GraphTypes/CurrencyType.cs, Libplanet.Explorer/GraphTypes/HashDigestSHA256Type.cs, Libplanet.Explorer/GraphTypes/TransactionType.cs, Libplanet.Explorer/GraphTypes/TxResultType.cs, Libplanet.Explorer/Queries/BlockQuery.cs, Libplanet.Explorer/Queries/StateQuery.cs, Libplanet.Explorer/Queries/TransactionQuery.cs
=> ⏪ Revert graphql type changes

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 4.0.4

CHANGES.md, Libplanet.Explorer/Queries/TransactionQuery.cs
=> ⏪ Revert query argument type to be compatible with legacy queries

CHANGES.md
=> 🚀 Release 4.0.4

CHANGES.md, Libplanet.RocksDBStore/RocksDBStore.cs
=> Removal of '#nullable disable' from the Libplanet.RocksDBStore project

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 4.0.5

CHANGES.md, Libplanet.Explorer/Queries/TransactionQuery.cs
=> 🔀 Merge 4.0.4 to main

CHANGES.md
=> 🚀 Release 4.0.5

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 4.0.6

CHANGES.md, Libplanet.Action/ActionEvaluator.cs
=> 🔀 Merge 4.0.5 to main

CHANGES.md
=> 🚀 Release 4.0.6

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 4.0.7

CHANGES.md, Libplanet.Action/FeeCollector.cs, Libplanet.Tests/Action/ActionEvaluatorTest.cs
=> 🔀 Merge 4.0.6 to main

CHANGES.md, Libplanet/Libplanet.csproj
=> 🚀 prepare: 4.2.0

CHANGES.md, Libplanet.Action.Tests/Common/DumbAction.cs, Libplanet.Action.Tests/Common/DumbModernAction.cs, Libplanet.Action.Tests/Common/SetValidator.cs, Libplanet.Action.Tests/Mocks/MockWorldState.cs, Libplanet.Action.Tests/Sys/InitializeTest.cs, Libplanet.Action/State/Account.cs, Libplanet.Action/State/IAccount.cs, Libplanet.Action/State/IAccountState.cs, Libplanet.Action/State/IWorld.cs, Libplanet.Action/State/IWorldState.cs, Libplanet.Action/State/World.cs, Libplanet.Action/State/WorldBaseState.cs, Libplanet.Action/Sys/Initialize.cs, Libplanet.Explorer.Tests/Queries/StateQueryTest.Mocks.cs, Libplanet.Explorer/Queries/StateQuery.cs, Libplanet.Net.Tests/Consensus/ContextTest.cs, Libplanet.Net.Tests/TestUtils.cs, Libplanet.Net/Consensus/ConsensusContext.cs, Libplanet.Tests/Action/AccountDiffTest.cs, Libplanet.Tests/Action/AccountTest.cs, Libplanet.Tests/Action/WorldTest.cs, Libplanet.Tests/Blockchain/BlockChainTest.cs, Libplanet/Blockchain/BlockChain.Validate.cs
Related to #3694 and a follow-up of #3697.
=> 🚚 Move `Validator` related methods from `IAccount` to `IWorld`

Libplanet.Action/State/Account.cs, Libplanet.Action/State/World.cs, Libplanet.Action/State/WorldBaseState.cs, Libplanet.Action/State/WorldDelta.cs
=> ♻️ Docs cleanup

CHANGES.md
=> 🚀 Release 4.2.0

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 4.3.0

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 4.2.1

changes/v0.md, changes/v2.md
=> chore: fix typos

Libplanet.Action.Tests/Common/DumbAction.cs, Libplanet.Action.Tests/Common/DumbModernAction.cs, Libplanet.Net.Tests/SwarmTest.Fixtures.cs, Libplanet.Tests/Blockchain/BlockChainTest.cs
=> 🧹 Cleanup `DumbAction`

Libplanet.Action.Tests/Common/DumbAction.cs, Libplanet.Action.Tests/Common/DumbModernAction.cs
=> 🧹 Minor cleanup

Libplanet.Action.Tests/ActionEvaluationTest.cs, Libplanet.Action.Tests/Common/DumbAction.cs, Libplanet.Action.Tests/Common/DumbModernAction.cs, Libplanet.Net.Tests/SwarmTest.Fixtures.cs, Libplanet.Tests/Action/ActionEvaluatorTest.cs, Libplanet.Tests/Blockchain/BlockChainTest.Append.cs, Libplanet.Tests/Blockchain/BlockChainTest.ProposeBlock.cs, Libplanet.Tests/Blockchain/BlockChainTest.Stage.cs, Libplanet.Tests/Blockchain/BlockChainTest.cs, Libplanet.Tests/TestUtils.cs, Libplanet.Tests/Tx/TransactionTest.cs, Libplanet.Tests/Tx/TxActionListTest.cs, Libplanet.Tests/Tx/TxInvoiceTest.cs, Libplanet.Tests/Tx/UnsignedTxTest.cs
♻️ Still in progress. 😕
The end goal is to make it so that `DumbAction` is **properly** capable of all basic functionality related to `IWorld`.
=> ♻️ Refactor `DumbAction`

Libplanet.Action.Tests/Common/DumbAction.cs, Libplanet.Action.Tests/Common/DumbModernAction.cs, Libplanet.Tests/Action/WorldTest.cs, Libplanet.Tests/Action/WorldV1Test.cs
=> 🧹 More descriptive currency ticker and documentation for easier testing

CHANGES.md, Libplanet.Action.Tests/Common/DumbAction.cs, Libplanet.Action.Tests/Common/DumbModernAction.cs, Libplanet.Action/State/IWorldExtensions.cs, Libplanet.Net.Tests/SwarmTest.Preload.cs, Libplanet.Tests/Action/ActionEvaluatorTest.cs, Libplanet.Tests/Action/WorldTest.cs, Libplanet.Tests/Action/WorldV0Test.cs, Libplanet.Tests/Action/WorldV1Test.cs, Libplanet.Tests/Blockchain/BlockChainTest.Append.cs, Libplanet.Tests/Blockchain/BlockChainTest.cs, Libplanet.Tests/TestUtils.cs
=> ♻️ Removed negative balance feature

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 4.4.0

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 4.3.1

CHANGES.md, Libplanet.Action/ActionEvaluator.cs, Libplanet.Store/BlockSet.cs, Libplanet.Tests/Action/ActionEvaluatorTest.cs, Libplanet.Tests/Blockchain/BlockChainTest.Append.cs, Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs, Libplanet.Tests/TestUtils.cs, Libplanet.Types/Blocks/BlockHeader.cs, Libplanet.Types/Blocks/BlockMetadata.cs, Libplanet.Types/Blocks/PreEvaluationBlockHeader.cs, Libplanet/Blockchain/BlockChain.Validate.cs, Libplanet/Blockchain/BlockChain.cs
=> ♻️ Changed constant reference block protocol versions

CHANGES.md
=> 🧹 Fixed changelog typo

CHANGES.md, Libplanet.Action/State/IWorldState.cs, Libplanet.Action/State/World.cs, Libplanet.Action/State/WorldBaseState.cs, Libplanet.Mocks/MockWorldState.cs
=> ♻️ Added `Version` property to `IWorldState`

Libplanet.Tests/Action/WorldTest.cs, Libplanet.Tests/Action/WorldV0Test.cs, Libplanet.Tests/Action/WorldV1Test.cs, Libplanet.Tests/Action/WorldV5Test.cs
♻️ Just streamlining `IWorld` test for each protocol version. New tests will be added for the latest version in a separate PR.
=> ♻️ Refactor `IWorld` tests

CHANGES.md
=> 🚀 Release 4.4.0

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 4.4.1

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 4.5.0

CHANGES.md
=> 🧹 Fixed typo

CHANGES.md
=> 🚀 Release 4.3.1

CHANGES.md, Libplanet.RocksDBStore/RocksDBStore.cs, Libplanet.Store/BaseStore.cs, Libplanet.Store/DefaultStore.cs, Libplanet.Store/IStore.cs, Libplanet.Store/MemoryStore.cs, Libplanet.Tests/Store/ProxyStore.cs, Libplanet.Tests/Store/StoreTracker.cs
=> Add CRUD for NextStateRootHash on IStore

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 4.3.2

CHANGES.md
=> 🚀 Release 4.4.1

Libplanet.Tests/Store/StoreTest.cs
Related to https://github.com/planetarium/libplanet/pull/3752
=> Add tests for NestStateRootHash

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 4.4.2

CHANGES.md, Libplanet.Action.Tests/ActionContextTest.cs, Libplanet.Action.Tests/ActionEvaluationTest.cs, Libplanet.Action.Tests/Sys/InitializeTest.cs, Libplanet.Action/ActionContext.cs, Libplanet.Action/ActionEvaluator.cs, Libplanet.Action/IActionContext.cs, Libplanet.Tests/Action/AccountDiffTest.cs, Libplanet.Tests/Action/AccountV0Test.cs, Libplanet.Tests/Action/AccountV1Test.cs, Libplanet.Tests/Blockchain/Renderers/AnonymousActionRendererTest.cs, Libplanet.Tests/Blockchain/Renderers/LoggedActionRendererTest.cs
=> Add max gas price to `IActionContext`

CHANGES.md, Libplanet.Explorer.Tests/Queries/HelperQueryTest.cs, Libplanet.Explorer.Tests/Queries/RawStateQueryTest.cs, Libplanet.Explorer.Tests/Queries/StateQueryTest.Mocks.cs, Libplanet.Explorer/GraphTypes/KeyBytesType.cs, Libplanet.Explorer/GraphTypes/TrieType.cs, Libplanet.Explorer/Queries/ExplorerQuery.cs, Libplanet.Explorer/Queries/HelperQuery.cs, Libplanet.Explorer/Queries/RawStateQuery.cs
✨ Adds new queries to make it possible search `ITrie` directly.
=> ✨ Added `RawStateQuery`

CHANGES.md
=> 🚀 Release 4.4.2

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 4.4.3

CHANGES.md, Libplanet.Explorer.Executable/Program.cs, Libplanet.Store/DefaultStore.cs, Libplanet.Store/Libplanet.Store.csproj
=> 🔀 Port 4.4.1 to main

CHANGES.md, Libplanet.Explorer.Tests/Queries/HelperQueryTest.cs, Libplanet.Explorer.Tests/Queries/RawStateQueryTest.cs, Libplanet.Explorer.Tests/Queries/StateQueryTest.Mocks.cs, Libplanet.Explorer/GraphTypes/KeyBytesType.cs, Libplanet.Explorer/GraphTypes/TrieType.cs, Libplanet.Explorer/Queries/ExplorerQuery.cs, Libplanet.Explorer/Queries/HelperQuery.cs, Libplanet.Explorer/Queries/RawStateQuery.cs
=> 🔀 Port 4.4.2 to main

CHANGES.md, Libplanet.Store/Trie/MerkleTrie.cs, Libplanet.Tests/Store/Trie/MerkleTrieTest.cs
In preparation to migrate `Currency`.
=> ✨ Added methods to traverse subtries of a `MerkleTrie`

Libplanet.Net.Tests/Consensus/ContextTest.cs, Libplanet.Net.Tests/Messages/MessageTest.cs, Libplanet.Net.Tests/SwarmTest.cs, Libplanet.Net/Consensus/ConsensusContext.cs, Libplanet.Net/Consensus/Context.Mutate.cs, Libplanet.Net/Consensus/Context.cs, Libplanet.Net/Swarm.BlockCandidate.cs
- Update `Swarm.AppendPreviousBlocks()`.
- Affects preloading and block synchronization
- Update `Context.IsValid()`
- Affects block appending via consensus
---
Found malfunction under time-consuming action evaluation, so converted as a draft temporarily
---
- Adjust timing (timeouts, block interval)
- Rebasing
=> Sloth update for Libplanet.Net

Libplanet.Store/Trie/ITrie.cs, Libplanet.Tests/Store/Trie/MerkleTrieTest.cs
Just to make sure things work as intended. 😗
=> ✅ Added tests for `ITrie`

CHANGES.md, Libplanet.Explorer.Tests/Queries/StateQueryTest.Legacy.cs, Libplanet.Explorer.Tests/Queries/StateQueryTest.Mocks.cs, Libplanet.Explorer.Tests/Queries/StateQueryTest.cs, Libplanet.Mocks/MockWorldState.cs, Libplanet.Tests/Action/ActionEvaluatorTest.cs, Libplanet.Tests/Action/WorldTest.cs
- Removed `ToModern()` as there are now multiple schemes, not just two.
- Removed `SetTotalSupply()` and changed `SetBalance()` to track total supply automatically.
=> ♻️ Updated `MockWorldState`

.vscode/settings.json
=> 🔧 Updated `./vscode/settings.json` to comply with the newest version of vscode json schema

CHANGES.md
=> 🚀 Release 4.5.0

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 4.6.0

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 4.5.1

CHANGES.md, Libplanet.Explorer.Executable/Options.cs, Libplanet.Explorer.Executable/Program.cs
=> 🧹 Removed unused parameter for the executable

CHANGES.md, Libplanet.Store/Libplanet.Store.csproj, Libplanet/Libplanet.csproj
=> 🔧 Suppressed security warnings during build

CHANGES.md
=> 🚀 Release 4.5.1

CHANGES.md, Libplanet.Store/Libplanet.Store.csproj, Libplanet/Libplanet.csproj
=> 🔀 Port 4.5.1 to main

CHANGES.md
=> 🚀 Release 4.6.0

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 4.5.2

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 4.6.1

CHANGES.md
=> 🚀 Release 4.5.2

CHANGES.md, Libplanet.Net.Tests/Consensus/ConsensusContextTest.cs, Libplanet.Net.Tests/Consensus/ContextTest.cs, Libplanet.Net/Consensus/ConsensusContext.cs, Libplanet.Net/Consensus/Context.Async.cs, Libplanet.Net/Consensus/Context.Mutate.cs, Libplanet.Net/Swarm.BlockCandidate.cs, Libplanet.Tests/Action/WorldTest.cs, Libplanet.Tests/Blockchain/BlockChainTest.Append.cs, Libplanet.Tests/Blockchain/BlockChainTest.ProposeBlock.cs, Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs, Libplanet.Tests/TestUtils.cs, Libplanet.Types/Blocks/BlockMetadata.cs, Libplanet/Blockchain/BlockChain.Evaluate.cs, Libplanet/Blockchain/BlockChain.ProposeBlock.cs, Libplanet/Blockchain/BlockChain.Validate.cs, Libplanet/Blockchain/BlockChain.cs
1. Regenerate NextStateRootHash on construct BlockChain
2. Fire-and-forget block appending
3. Rename protocol version for sloth
=> Minor fixes for Sloth

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 4.5.3

CHANGES.md, Libplanet.Explorer.Tests/GraphTypes/BlockTypeTest.cs, Libplanet.Explorer/GraphTypes/BlockType.cs
=> 🔀 Port 4.5.2 to 4.6.1

CHANGES.md
=> 🚀 Release 4.6.2

CHANGES.md, Libplanet.Explorer.Tests/GraphTypes/BlockTypeTest.cs, Libplanet.Explorer/GraphTypes/BlockType.cs, Libplanet/Libplanet.csproj
=> 🔀 Port 4.6.1 to main

Libplanet/Libplanet.csproj
=> ✏️ Fixed version prefix

CHANGES.md, Libplanet/Libplanet.csproj
=> 🔧 Prepare 4.6.2

Libplanet.Tools/bin/npm-test.sh
=> 👷 Changed to more elaborate version matching

Libplanet.Net/Consensus/ConsensusContext.cs
=> 📝 Added some clarifications

Libplanet.Tools/bin/npm-test.ps1
=> Fix ci installation test error

Libplanet/Blockchain/BlockChain.cs
=> 🧹 Minor cleanup for #3832

.github/workflows/ai-code-reviewer.yaml
We need to adapt to a new era.
=> ✨  ci: introduce ai-code-reviewer

.github/workflows/ai-code-reviewer.yaml
=> fix: use pull_request_target

Libplanet/Blockchain/BlockChain.Evaluate.cs
=> 🔧 Fixed `BlockChain.EvaluateBlock()`

@planetarium/account/package.json, @planetarium/account/src/Address.ts, @planetarium/account/src/PublicKey.ts, @planetarium/account/src/RawPrivateKey.ts, yarn.lock
It makes `@planetarium/account` to use `buffer` dependency to use `Buffer` in browser environment. It also has not related changes because of biomejs.
=> Use `buffer` dependency for browser environment

CHANGES.md, src/Libplanet.Net/Consensus/Context.Async.cs, test/Libplanet.Net.Tests/Consensus/ContextTest.cs
=> ♻️ Changed `Context.Start()` to throw an `Exception` in an invalid state

Libplanet.Store/HashNodeCache.cs
=> Reduce cache size

CHANGES.md
=> 🚀 Release 5.0.0

CHANGES.md, src/Libplanet/Libplanet.csproj
=> 🔧 Prepare 5.0.1

CHANGES.md, src/Libplanet/Libplanet.csproj
This reverts commit a4881e5a1d36ba33464b23785ec7e13e5f003f73.
=> Revert "Prepare 5.1.0"

.github/bin/dist-github-release.sh
Fix an error occurred when the dist-github-release.sh script is executed
=> Fix github-release script error

CHANGES.md, src/Libplanet/Libplanet.csproj
=> 🔧 Prepare 5.1.0

CHANGES.md, src/Libplanet/Libplanet.csproj
=> 🔧Prepare 5.0.1

CHANGES.md, Directory.Build.props, src/Libplanet.Types/Evidence/EvidenceBase.cs, test/Libplanet.Tests/Blockchain/Evidence/EvidenceTest.cs, test/Libplanet.Tests/Blocks/BlockMetadataTest.cs, test/Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
=> 🔧Prepare 5.1.1

CHANGES.md, Directory.Build.props, src/Libplanet.Types/Evidence/EvidenceBase.cs, test/Libplanet.Tests/Blockchain/Evidence/EvidenceTest.cs, test/Libplanet.Tests/Blocks/BlockMetadataTest.cs, test/Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
=> 🔀 Port 5.1.1 to main

CHANGES.md, Directory.Build.props
=> 🔧Prepare 5.2.0

CHANGES.md, Directory.Build.props
=> 🔧 Prepare 5.1.2

src/Libplanet.Action/Libplanet.Action.csproj, src/Libplanet.Action/State/AccountState.cs, src/Libplanet.Action/State/WorldBaseState.cs, src/Libplanet.Net/Libplanet.Net.csproj, src/Libplanet.Net/Transports/NetMQTransport.cs, src/Libplanet/Blockchain/BlockChainStates.cs, src/Libplanet/Libplanet.csproj
This PR enables libplanet to track its activity in the `AccountState`, `WorldBaseState`, NetMQTransport`, and `BlockChainStates`.
=> add pyroscope

src/Libplanet.Action/Libplanet.Action.csproj, src/Libplanet.Action/State/AccountState.cs, src/Libplanet.Action/State/WorldBaseState.cs, src/Libplanet.Net/Libplanet.Net.csproj, src/Libplanet.Net/Transports/NetMQTransport.cs, src/Libplanet/Blockchain/BlockChainStates.cs, src/Libplanet/Libplanet.csproj
https://github.com/planetarium/libplanet/pull/3878
=> 🔀 Port pyroscope from main to 5.1.2

CHANGES.md, tools/Libplanet.Explorer/Queries/EvidenceQuery.cs
=> Fix evidence query errors in Explorer

.github/bin/dist-pack.sh, .github/workflows/check-build.yaml, CHANGES.md
=> 🚀 Release 5.1.2

CHANGES.md, Directory.Build.props
=> 🔧 Prepare 5.1.3

.github/bin/dist-pack.sh, .github/workflows/check-build.yaml, CHANGES.md, src/Libplanet.Types/Assets/Currency.cs, tools/Libplanet.Explorer/Queries/EvidenceQuery.cs
=> 🔀 Port 5.1.2 to main

CHANGES.md
=> 🚀 Release 5.2.0

CHANGES.md, Directory.Build.props
=> 🔧 Prepare 5.3.0

CHANGES.md, Directory.Build.props
=> 🔧 Prepare 5.2.1

CHANGES.md
=> 🚀 Release 5.1.3

CHANGES.md
=> 🚀 Release 5.2.1

CHANGES.md, Directory.Build.props
=> 🔧 Prepare 5.2.2

.circleci/config.yml, .vscode/launch.json, .vscode/settings.json, global.json, hooks/check-projects, sdk/.editorconfig, sdk/Directory.Build.props, sdk/node/Libplanet.Node.Executable/Dockerfile, sdk/node/Libplanet.Node.Executable/Program.cs, sdk/node/Libplanet.Node.Executable/Properties/launchSettings.json, sdk/node/Libplanet.Node.Executable/Services/GreeterService.cs, sdk/node/Libplanet.Node/Services/SoloProposeService.cs, sdk/stylecop.json, tools/Libplanet.Explorer.Cocona/Libplanet.Explorer.Cocona.csproj
=> Bump dotnet to 8 in Libplanet SDK

CHANGES.md
=> 🚀  Release 5.2.2

CHANGES.md, Directory.Build.props
=> 🔧 Prepare 5.2.3

CHANGES.md, tools/Libplanet.Explorer/Queries/BlockQuery.cs, tools/Libplanet.Explorer/Queries/ExplorerQuery.cs
=> 🔀 Port 5.2.2 to main

sdk/node/Libplanet.Node.Executable/Program.cs, sdk/node/Libplanet.Node.Executable/Protos/schema.proto, sdk/node/Libplanet.Node.Executable/Services/SchemaGrpcService.cs, sdk/node/Libplanet.Node.Executable/appsettings-schema.json, sdk/node/Libplanet.Node.Executable/appsettings.Development.json, sdk/node/Libplanet.Node.Executable/appsettings.json, sdk/node/Libplanet.Node/Libplanet.Node.csproj, sdk/node/Libplanet.Node/Options/GenesisOptions.cs, sdk/node/Libplanet.Node/Options/NodeOptions.cs, sdk/node/Libplanet.Node/Options/Schema/OptionsSchemaBuilder.cs, sdk/node/Libplanet.Node/Options/SeedOptions.cs, sdk/node/Libplanet.Node/Options/StoreOptions.cs
* A `OptionsSchemaBuilder` was added to create schemas to be used in `appsettings.json`.
* Added `OptionsAttribute` to options classes to add properties to the schema.
* Added schema file `appsettings-schema.json`.
* You can get the schema by connecting to http://localhost:5259/schema.
=> Add json schema builder for appsettings.json

sdk/node/Libplanet.Node.Executable/appsettings-schema.json, sdk/node/Libplanet.Node/DataAnnotations/ArrayAttribute.cs, sdk/node/Libplanet.Node/Options/Schema/OptionsSchemaBuilder.cs, sdk/node/Libplanet.Node/Options/Schema/OptionsSchemaGenerator.cs, sdk/node/Libplanet.Node/Options/StoreType.cs
* If the property is an array, each member can have a regular expression pattern specified for it.
* Enumeration members are output as strings.
=> Improve option schema builder

sdk/node/Libplanet.Node.Executable/appsettings-schema.json, sdk/node/Libplanet.Node.Executable/appsettings.Development.json, sdk/node/Libplanet.Node.Extensions/LibplanetServicesExtensions.cs, sdk/node/Libplanet.Node.Tests/RandomPrivateKey.cs, sdk/node/Libplanet.Node.Tests/Services/PeerTest.cs, sdk/node/Libplanet.Node.Tests/Services/SeedTest.cs, sdk/node/Libplanet.Node/DataAnnotations/AppProtocolVersionAttribute.cs, sdk/node/Libplanet.Node/Options/AppProtocolOptionsBase.cs, sdk/node/Libplanet.Node/Options/GenesisOptions.cs, sdk/node/Libplanet.Node/Options/GenesisOptionsConfigurator.cs, sdk/node/Libplanet.Node/Options/GenesisOptionsValidator.cs, sdk/node/Libplanet.Node/Options/Schema/OptionsSchemaBuilder.cs, sdk/node/Libplanet.Node/Options/SeedOptions.cs, sdk/node/Libplanet.Node/Options/SwarmOptions.cs, sdk/node/Libplanet.Node/Options/SwarmOptionsConfigurator.cs, sdk/node/Libplanet.Node/Options/ValidatorOptions.cs, sdk/node/Libplanet.Node/Options/ValidatorOptionsConfigurator.cs, sdk/node/Libplanet.Node/Services/BlockChainService.cs, sdk/node/Libplanet.Node/Services/Seed.cs, sdk/node/Libplanet.Node/Services/SwarmService.cs
* Added `GenesisBlockPath` to `GenesisOptions` to load from specifed path.
* Added `AppProtocolVersion` to `SwarmOptions`.
=> Refactor GenesisOptions

CHANGES.md, src/Libplanet.Net/Swarm.cs
=> 🧹 📝 Minor docs change

CHANGES.md, src/Libplanet.Net/ActionExecutionState.cs, src/Libplanet.Net/BlockVerificationState.cs, src/Libplanet.Net/Swarm.BlockCandidate.cs, src/Libplanet.Net/Swarm.BlockSync.cs, src/Libplanet.Net/Swarm.cs, test/Libplanet.Net.Tests/SwarmTest.Broadcast.cs, test/Libplanet.Net.Tests/SwarmTest.Preload.cs
=> 🧹 Disable progress reporting

CHANGES.md
=> 🚀  Release 5.3.0

CHANGES.md, Directory.Build.props
=> 🧹  Prepare 5.4.0

CHANGES.md, tools/Libplanet.Extensions.Cocona/Libplanet.Extensions.Cocona.csproj
see https://github.com/advisories/GHSA-8g4q-xg66-9fp4
=> resolve CVE-2024-43485

CHANGES.md, tools/Libplanet.Extensions.Cocona/Libplanet.Extensions.Cocona.csproj
=> 🔧 Patch: CVE-2024-43485 to `5.3-maintenance`

CHANGES.md, src/Libplanet.Crypto/Libplanet.Crypto.csproj, src/Libplanet/Libplanet.csproj
=> 🔧 Patch:  CVE-2024-29857 to `5.3-maintenance`

CHANGES.md
- (Libplanet.Extensions.Cocona) Changed System.Text.Json from [6.0.7] to [6.0.*]. [[#3967](https://github.com/planetarium/libplanet/pull/3967)]
- Changed BouncyCastle.Cryptography from [2.0.0] to [2.4.0]. [[#3968](https://github.com/planetarium/libplanet/pull/3968)]
- (Libplanet.Crypto) Changed BouncyCastle.Cryptography from [2.0.0] to [2.4.0]. [[#3968](https://github.com/planetarium/libplanet/pull/3968)]
=> 🚀 release: 5.3.1

CHANGES.md, src/Libplanet.Crypto/Libplanet.Crypto.csproj, src/Libplanet/Libplanet.csproj
=> 🧹 chore: backmerge 5.3.1 into main

CHANGES.md, Directory.Build.props
=> 🧹  prepare: 5.3.2

CHANGES.md, Directory.Build.props
=> 🔧 Prepare 5.4.1

.circleci/config.yml
=> 🔧  ci: run full ci when only merged

CHANGES.md
=> 🚀 Release 5.4.1

CHANGES.md, Directory.Build.props
=> 🔧 Prepare 5.5.0

.circleci/config.yml
=> ci: downsize executor

CHANGES.md, Directory.Build.props
=> 🔧 Prepare 5.4.2

src/Libplanet.Common/FixedSizedQueue.cs, src/Libplanet.Store/BlockSet.cs
=> Remove nullable-related warnings

src/Libplanet.Action/ActionEvaluator.cs
**Fix Typo in `ActionEvaluator.cs`**
This pull request addresses a minor typo in the `ActionEvaluator.cs` file, correcting the spelling of "dependant" to "dependent" in the comment.
- **File Modified:** `src/Libplanet.Action/ActionEvaluator.cs`
- **Summary of Changes:**
- Corrected "dependant" to "dependent" in the comment on line 445.
N/A
N/A (Typo fix in the comment)
This fix improves the clarity of the comment, ensuring there are no typographical errors.
---
**Allow edits by maintainers:** [x]
=> typo fix ActionEvaluator.cs

src/Libplanet.Action/State/World.cs
=> Docs: Update World.cs added close XML element

.github/workflows/yarn.yaml
https://www.cve.org/CVERecord?id=CVE-2025-30066
https://github.com/step-security/changed-files
=> Use step-security/changed-files
