- Docs/articles/design.md
Added two missing words:
- <q>From the perspective this library's user</q> → <q>From the perspective <ins>of</ins> this library's user</q>
- <q>t will be more cost-efficient make a high quality open source
library</q> → <q>t will be more cost-efficient <ins>to</ins> make a high quality open source
library</q>
> Fix typo on the design docs

- Libplanet.Tests/BlockchainTest.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/BlockLocator.cs
- Libplanet/Blockchain.cs
- Libplanet/Net/NetMQSocketExtension.cs
- Libplanet/Net/PeerNotFoundException.cs
- Libplanet/Net/Swarm.cs
it's first PR of P2P exchange protocol [Bitcoin P2P protocol](https://bitcoin.org/en/developer-reference#p2p-network).
- Added `GetBlocksAsync()` to `Swarm` (like [`getblocks`](https://bitcoin.org/en/developer-reference#getblocks) at Bitcoin)
- for this, Added `LocateBlocks()` to `Blockchain` to query blockhashes
- Implement reply of `GetBlockAsync()` on `RunAsync()` (like [`inv`](https://bitcoin.org/en/developer-reference#inv) at Bitcoin)
In addition, the following are also not directly related to P2P implementations.
- Changed `Swarm._dealers`'s key type from `Uri` to `Address` to lookup peer easily.
- Hide methods(e.g. `Swarm.ProcessDeltaAsync()`) that do not need to be exposed to the outside.
- Added cancellation support to `Swarm`'s async methods.
@dahlia @kijun @ipdae
> Added feature that can query block hashes to other peer

- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/Messages/GetBlocks.cs
- Libplanet/Net/Messages/Inventory.cs
- Libplanet/Net/Messages/Message.cs
- Libplanet/Net/Messages/PeerSetDelta.cs
- Libplanet/Net/Messages/Ping.cs
- Libplanet/Net/Messages/Pong.cs
- Libplanet/Net/NetMQFrameExtension.cs
- Libplanet/Net/Swarm.cs
This PR moves message related features (e.g. parsing, signing) from `Swarm` to `Libplanet.Net.Messages`. 
- In this process, I've made `Message` abstract class for more naturally abstracting of `NetMQMessage`, and added a concrete class for each message.
- It also applied the missing message sign/verify to all messages using common code in `Message`.
- Added a missing `stop` parameter to `Swarm.GetBlocksAsync()` in the previous PR(#34).
> Separate message related features from Swarm.

- Libplanet.Tests/Blocks/BlockTest.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet.Tests/Tx/TransactionTest.cs
- Libplanet/Blocks/Block.cs
- Libplanet/Libplanet.csproj
- Libplanet/Net/Messages/Block.cs
- Libplanet/Net/Messages/GetData.cs
- Libplanet/Net/Messages/Message.cs
- Libplanet/Net/NetMQSocketExtension.cs
- Libplanet/Net/Swarm.cs
- Libplanet/Store/FileStore.cs
- Libplanet/Tx/Transaction.cs
This PR implements `GetData` / `Block` message to request and transfer blocks. (it relies [AsyncEnumerator](https://github.com/Dasync/AsyncEnumerable) to create async-generator)
Also it has some other minor changes.
- Renamed bencodex related methods. (see also. https://github.com/planetarium/libplanet.net/pull/46#pullrequestreview-195368085)
- Separated message processing logic from `ReceiveMesseageAsync()` to (new) `ProcessMessageAsync()`
- Replaced `CancellationToken` overload in `Swarm` and `NetMQSocketExtension` with default parameters
> Implement GetData / Block message 

- Libplanet.Tests/Action/ActionContextTest.cs
- Libplanet.Tests/Common/Action/Attack.cs
- Libplanet.Tests/Common/Action/BaseAction.cs
- Libplanet.Tests/Common/Action/DummyAction.cs
- Libplanet.Tests/Common/Action/Sleep.cs
- Libplanet.Tests/TestUtils.cs
- Libplanet/Action/ActionContext.cs
- Libplanet/Action/IAction.cs
- Libplanet/Action/IActionContext.cs
- Libplanet/Action/IRandom.cs
- Libplanet/Action/Random.cs
- Libplanet/Blockchain.cs
It implements #49.
Context includes Random object.
Seed of Random object is generated using block hash and extra seed.
Extra seed is incremented for each transaction starting at 0.
Thus, each action uses same random seed, but each transaction will use a different random seed.
> Pass a context including Random object to IAction.Execute() method

- Libplanet/Libplanet.csproj
Since some packages purpose to generate or analyze code, these are unnecessary at runtime.  This patch turns these dependencies into [`<PrivateAssets>`][1].
[1]: https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-assets
> Turn packages only for development into private assets

- Libplanet.Tests/BlockchainTest.cs
- Libplanet.Tests/Net/SwarmTest.cs
Currently,  `CanFindNextHashes` and `CanGetBlock` occasionally fail due to the timestamp issue.
I added `Thread.Sleep()` to prevent test failure.
> Add sleep to prevent test failure

- Libplanet.Tests/Common/Action/BaseAction.cs
- Libplanet/Action/ActionTypeAttribute.cs
- Libplanet/Action/AddressStateMap.cs
- Libplanet/Action/IAction.cs
- Libplanet/Action/IActionContext.cs
- Libplanet/Action/IRandom.cs
Wrote API docs for `Libplanet.Action` namespace.  It also made the return type of `IAction.RequestStates()` method immutable.
There's some example code as well in docs of `Libplanet.Action.IAction` interface.  Please review carefully that code as well.
Preview: <https://planetarium.github.io/libplanet.net/pulls/63/api/Libplanet.Action.html>
> API docs for Libplanet.Action namespace

- Libplanet/Crypto/PrivateKey.cs
Adjusted words in `PrivateKey` docs to get rid of ambiguity.  Also provides more helpful links than an  irrelevant link to a random Wikipedia page.
> PrivateKey docs: disambiguate words and provide more helpful links

- Libplanet.Tests/BlockchainTest.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet.Tests/Store/FileStoreTest.cs
- Libplanet/Blockchain.cs
- Libplanet/Net/Swarm.cs
- Libplanet/Store/BaseStore.cs
- Libplanet/Store/FileStore.cs
- Libplanet/Store/IStore.cs
This PR implements `Swarm.BroadcastBlocksAsync()` for miner can broadcast mined block to known peers. the following points have also been changed to accomplish it.
- Added `DeleteIndex()` to `IStore` / `FileStore` to able to give up own block indexes when other longest chain appears. 
- Added `Blockchain.DeleteAfter()` to same reason.
- Added `Blockchain.GetBlockLocator()` to query block hashes to broadcasting peer.
- `Blockchain.FindNextHash()` returns result containing branch point.
> Add Swarm.BroadcastBlocksAsync()

- Libplanet.Tests/BlockchainTest.cs
- Libplanet.Tests/Blocks/BlockTest.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Blockchain.cs
- Libplanet/Blocks/Block.cs
It resolves #65. as mentioned in #65, it loosens the `Block.Timestamp`'s constraint [like Ethereum](https://github.com/ethereum/wiki/blob/c02254611f218f43cbb07517ca8e5d00fd6d6d75/Block-Protocol-2.0.md#block-validation-algorithm).
Also, the validation related to the current time has been moved from `Blockchain.Validate()` to `Block.Validate()`.
> Loosen Block.Timestamp constraints (#65)

- .travis.dotCover.xml
- .travis.yml
- README.md
- codecov.yml
- publish.sh
This patch makes Travis CI to measure code coverage of the test suite.  It uses JetBrains' [dotCover] for instrumentation and [Codecov] for visual reports.  Codecov also leaves a comment if a pull request drops or raises code coverage.
[![Codecov](https://codecov.io/gh/planetarium/libplanet.net/branch/master/graph/badge.svg)][Codecov]
[dotCover]: https://www.jetbrains.com/dotcover/
[Codecov]: https://codecov.io/gh/planetarium/libplanet.net
> Code coverage

- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/Swarm.cs
This PR simplifies `Swarm`'s interface as #69. specifically, the following changes have been made.
- Renamed `RunAsync()` / `DisposeAsync()` to `StartAsync()` / `StopAsync()`
- Integrated `InitContextAsync()` into `RunAsync()`
- Removed `_delta` queue and replace related logic with worker task.
- Resolved ambiguous constructor overloading.
- Made interval in StartAsync() to optional
> Simplify swarm interface

- Libplanet.Explorer/Controllers/ExplorerController.cs
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Blockchain/BlockLocator.cs
- Libplanet/Blockchain/Policies/BlockPolicy.cs
- Libplanet/Blockchain/Policies/IBlockPolicy.cs
- Libplanet/Blocks/Block.cs
- Libplanet/Net/Messages/GetBlockHashes.cs
- Libplanet/Net/Swarm.cs
This patch abstracts out the standard between what kind of blocks are valid and what are invalid from blockchain objects.  It separates `IBlockPolicy<T>` (`where T : IAction`) and its default implementation `BlockPolicy<T>` from `BlockChain<T>` (renamed from `Blockchain<T>`).  Hard-coded interval between blocks (it was 5 seconds) now can be configured through `BlockPolicy<T>.BlockInterval`.  A new namespace `Libplanet.Blockchain` is also introduced.
> Make intervals between blocks configurable

- Libplanet.Tests/Net/SwarmTest.cs
It resolves blocking problem in `SwarmTest.CanNotStartTwice()`. (if the second `Swarm.StartAsync()` was called before the first `Swarm.StartAsync()`, the expected exception did not occur.)
> Fix blocking test case

- Libplanet.Tests/Tx/TransactionTest.cs
- Libplanet.Tests/Tx/TxIdTest.cs
- Libplanet/Store/FileStore.cs
- Libplanet/Tx/InvalidTxException.cs
- Libplanet/Tx/InvalidTxIdException.cs
- Libplanet/Tx/InvalidTxPublicKeyException.cs
- Libplanet/Tx/InvalidTxSignatureException.cs
- Libplanet/Tx/Transaction.cs
- Libplanet/Tx/TxId.cs
Wrote API docs for `Libplanet.Tx` namespace, and fixed some error-prone behaviors:
- The public constructor of `Transaction` had thrown `NullReferenceException` when some parameters of reference types.  It's changed to throw `ArgumentNullException` instead.  See also added tests.
- `Transaction.Signature` property had shared its internal state with others.  That means, if a `byte` array returned by the property or will be passed to the constructor mutates it affects the `Transaction` object too.  It's now changed to be copied when it is taken through the public constructor or returned through the property.  See also added tests.
It maybe better to be `ImmutableArray<byte>` or to have its own type named `Signature`.
> API docs for Libplanet.Tx namespace and some adjustments

- Libplanet.Explorer/ViewModels/TransactionViewModel.cs
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs
- Libplanet.Tests/Blocks/BlockTest.cs
- Libplanet.Tests/Net/PeerSetDeltaTest.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet.Tests/Store/FileStoreFixture.cs
- Libplanet.Tests/TestUtils.cs
- Libplanet.Tests/Tx/TransactionTest.cs
- Libplanet.Tests/Tx/TxFixture.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Blockchain/Policies/BlockPolicy.cs
- Libplanet/Blockchain/Policies/IBlockPolicy.cs
- Libplanet/Blocks/Block.cs
- Libplanet/Net/PeerSetDelta.cs
- Libplanet/Net/Swarm.cs
- Libplanet/Store/FileStore.cs
- Libplanet/Tx/Transaction.cs
It resolves #77.
I replaced all `DateTime` with `DateTimeOffset`, except `ToDateTime` in `Libplanet/Serialization/BencodexFormatterConverter.cs`.
> Replace DateTime with DateTimeOffset

- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/Swarm.cs
Many tests in the `SwarmTest` class assume `Swarm` objects are running after spawn them through threads.  The assumption is usually true for the most part, but on some slow machines like Travis CI workers, spawning a new thread and a NetMQ socket binding take longer time, so that tests get run in the main thread before things are all prepared.
In order to make tests to satisfy the assumption, I added a new method named `Swarm.WaitForRunning()` which returns a `Task` completed when `Swarm.Running` becomes `true`.  I also a façade method named `SwarmTest.StartAsync()` to eliminate duplicates.
Hope this patch to stabilize CI builds.
> Awaiting method to ensure a Swarm instance is running

- .vscode/tasks.json
I added two Visual Studio Code tasks to build and run tests.  These tasks are used in a [Korean tutorial to set up development environment][1] (relevant: #84).
[1]: https://gist.github.com/dahlia/5333634f62509293cd46c0e4ba65b2f5
> Tasks for Visual Studio Code

- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet.Tests/Store/FileStoreFixture.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Net/Messages/BlockHashes.cs
- Libplanet/Net/Messages/Message.cs
- Libplanet/Net/Messages/TxIds.cs
- Libplanet/Net/Swarm.cs
- Libplanet/Store/BaseStore.cs
- Libplanet/Store/FileStore.cs
- Libplanet/Store/IStore.cs
This PR contains some enhancements / bug fixes that occured while testing on Unity3d as below.
- Replaced `Swarm._listenUrl` with `_ipAddress` (optional) and `_listenPort`(also optional) for easy configuration.
- Added some log messages for debugging.
- Exposed broadcast related methods (`Swarm.BroadcastBlocksAsync()` / `Swarm.BroadcastTxsAsync()`)
- Made to create a new DealerSocket for each request to avoid response overlapping.
- Fixed an issue where `Swarm` does not correctly respond to peer that are registered but never actually connected.
- Fixed `ProcessBlockHash()`
> Network polishing

- CONTRIBUTING.md
- Libplanet/Libplanet.csproj
- README.md
As we discussed in #105, I renamed the repository from planetarium/libplanet.net to planetarium/libplanet.  Although GitHub maintains the old links and redirects them to the new links, the redirection does not work for GitHub Pages.  With this situation, I gave the new domain docs.libplanet.net to the docs, and replaced all old links to the docs with the new domain.
This fixes #95 and #105.
> Replace links to the old repository name with the new name

- .travis.yml
- CHANGES.md
As I made a GitHub App called [Changelog Check][] (code is [here][1]), remove the equivalent check from the Travis CI build script.
Note that this looks like:
[Changelog Check]: https://github.com/apps/changelog-check
[1]: https://github.com/planetarium/changelog-check
> Check changelog using Changelog Check instead

- CHANGES.md
- Libplanet/Libplanet.csproj
- publish.sh
As we've just released 0.1.1, I bumped the version to 0.1.2-dev, and fixed a bug that *.nupkg* file had been uploaded to NuGet twice for stable version numbers (i.e., no `-dev` suffix).
> Version bump & fix a double uploading bug for stable version numbers

- CHANGES.md
- Libplanet.Tests/Net/PeerSetDeltaTest.cs
- Libplanet.Tests/Net/PeerTest.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/Peer.cs
- Libplanet/Net/Swarm.cs
> Change Peer Uri to IPEndPoint

- CHANGES.md
- Libplanet.Tests/Net/PeerSetDeltaTest.cs
- Libplanet.Tests/Net/PeerTest.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/Peer.cs
- Libplanet/Net/Swarm.cs
This PR replaces `Peer.EndPoints` with `Peer.EndPoint`. (as suggested in #126)
> Peer.EndPoints to Peer.EndPoint

- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/Swarm.cs
In [failed test](https://api.travis-ci.com/v3/job/184409651/log.txt), `Swarm.DialPeerAsync()` seems to add unreachable peer. 
```
05:59:47[@8eFB6385bAB28Fc189D4692333b8926AFb23Fa3c][13] - TimeoutException occured in DialAsync (127.0.0.1:50040).
05:59:47[@8eFB6385bAB28Fc189D4692333b8926AFb23Fa3c][13] - DialPeerAsync(0x43056260567c13B4Dce2b3ac6F6F6a86ecE5EB8E.127.0.0.1:50040) is complete.
05:59:47[@8eFB6385bAB28Fc189D4692333b8926AFb23Fa3c][13] - 3/13/2019 5:59:30 AM +00:00 0x43056260567c13B4Dce2b3ac6F6F6a86ecE5EB8E.127.0.0.1:50040 > +0x43056260567c13B4Dce2b3ac6F6F6a86ecE5EB8E.127.0.0.1:50040
05:59:47[@8eFB6385bAB28Fc189D4692333b8926AFb23Fa3c][13] - 3/13/2019 5:59:30 AM +00:00 0x43056260567c13B4Dce2b3ac6F6F6a86ecE5EB8E.127.0.0.1:50040 > …
```
> Fix Swarm.DialPeerAsync()

- CHANGES.md
- Libplanet.Tests/Blocks/BlockTest.cs
- Libplanet.Tests/Common/Action/DetectRehearsal.cs
- Libplanet.Tests/Tx/TransactionTest.cs
- Libplanet/Action/ActionContext.cs
- Libplanet/Action/IActionContext.cs
- Libplanet/Tx/Transaction.cs
> IActionContext.Rehearsal property

- Libplanet.Tests/Net/SwarmTest.cs
This PR fixes `SwarmTest.EnsureRecvAsync()` to check target `swarm` really has received peer. 
In previous implementations, when `swarm.DeltaReceived` was set more than once with `lastReceived` is null, it passed even if it didn't have `peer`.
it also closes #137.
> Fix SwarmTest.EnsureRecvAsync()

- CHANGES.md
- Libplanet.Tests/Crypto/PrivateKeyTest.cs
- Libplanet/Crypto/InvalidCiphertextException.cs
- Libplanet/Crypto/PrivateKey.cs
- Libplanet/Crypto/SymmetricKey.cs
- Made threw an `InvalidCiphertextException` when ciphertext is invalid.
> Throw exception when ciphertext is invalid

- CHANGES.md
- Libplanet.Tests/Store/FileStoreTest.cs
- Libplanet/Store/BaseStore.cs
- Libplanet/Store/FileStore.cs
- Libplanet/Store/IStore.cs
Although I frankly am not sure if it's really necessary, I added a new method `ListNamespaces()` to `IStore` and implemented `FileSystem.ListNamespaces()` too.  I am going to use this to make an ad-hoc solution to #96.
> IStore.ListNamespaces() method

- publish.sh
I hope that this makes our NuGet page can show the content of *README.md*.  (It currently seems to ignore `<PackageDocumentationFile>` tag in *Libplanet.csproj*.)
> Upgrade NuGet to 5.0.0-preview4

- .travis.yml
The arguments syntax of `nuget pack` seems quite picky.  According to the [official docs][1], `-Properties` has to go last and its items have to be separated by semicolons.
[1]: https://docs.microsoft.com/en-us/nuget/tools/cli-ref-pack#options
> Fix NuGet packaging on Travis CI

- .travis.yml
This patch fixes the bug made in the previous PR #143 that a NuGet package without version suffix was made and uploaded to NuGet Gallery.
> Remove unsuffixed version of .nupkg

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet/Action/ActionTypeAttribute.cs
- Libplanet/Tx/InvalidActionTypeException.cs
- Made threw an `InvalidActionTypeException` if an action type is not annotated with `actionTypeAttribute`. #28
> Throw exception when action type is not annotated

- .travis.yml
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet.Tests/Store/FileStoreFixture.cs
This fixes #146.
Note that I replaced all `/o` & `/Option` style options with `-o` & `-Option` style options.  It purposes to work around Cygwin's automatic conversion between Windows/DOS-style path and Unix-style path (or it might be done by MinGW64; I'm not sure).  Since a Windows path like *C:\foo\bar* is represented as */c/foo/bar* in Cygwin, when a command like `cmd /o` is executed, it tries to reinterpret this like `cmd o:\`.  Fortunately `msbuild` supports both styles of options, I decided to use only `-o` & `-Option` style options.
> Make .nupkg to include Libplanet.Stun.dll assembly

- Libplanet/Blockchain/BlockChain.cs
This PR adjusts `BlockChain<T>.Append()` to validate not whole blocks, but only received last block. (there isn't a mention about as-is behaviour so I skipped writing changelogs.)
> Adjust BlockChain<T>.Validate() to validate only last block 

- CHANGES.md
- Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs
- Libplanet/Blockchain/Policies/BlockPolicy.cs
This PR turns `BlockPolicy`'s constructor parameter into milliseconds.
(closes #104)
> Turn into parameter in BlockPolicy's constructor to milliseconds

- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet.Tests/Store/FileStoreFixture.cs
- Libplanet/Net/Swarm.cs
This PR fixes #148. more precisely, it bypassed the problem by letting ignore blocks that we no longer need to synchronize.
It also fixed a bug in the process of handling multiple responses at the same time. This solves the problem that certain test cases do not terminate.
> Fix unexpected access during disposing FileStoreFixture

- .travis.yml
- CONTRIBUTING.md
- Libplanet.Stun.Tests/Libplanet.Stun.Tests.csproj
- Libplanet.Stun.Tests/xunit.runner.mono.json
- Libplanet.Tests/Libplanet.Tests.csproj
- Libplanet.sln
- Libplanet/Libplanet.csproj
This addresses the following problems:
- *Libplanet* uses *Uno.Equality* package but its package metadata hadn't had a dependency on *Uno.Equality*.
- *Libplanet.Stun.Tests* hadn't run for a while, and not been able to run with `msbuild`.
- NuGet metadata had been missing on the NuGet Gallery page (#153).  It's due to `nuget pack` command which is outdated, so I replaced it with `msbuild -t:pack` task again.
- Docs had been outdated so that it hadn't reflected the project separation done by PR #130.
> Use msbuild -t:pack again and update outdated docs

- CHANGES.md
- Libplanet/Net/Swarm.cs
This PR adjusts the timing of `_blockSyncMutex` when receiving blocks from other peers to avoid unnecessary forking.
At this time, block exchange related bug fixes are not affected by the specification change, so the changelog was skipped.
> Fix _blockSyncMutex timing

- CHANGES.md
- Libplanet/Blockchain/BlockChain.cs
This PR adjusts the timing of `_rwlock.ExitReadLock()` to improve write throughput of the `BlockChain<T>`. 
The idea is that - if all blocks are to be added, and they are not changed or deleted , we don't have to lock the entire `GetStates()`, only need to synchronize the part that gets the first block.
> Adjsut _rwlock to improve write throughput

- .travis.yml
I studied the other way to change this beautifully but there is no way to run multiple scripts elegant. Some folks are claiming this issue (travis-ci/dpl#673) but it has been ignored.
(Closes #116)
> Let Travis CI publish the documents

- .travis.yml
This patch fixes planetarium/libplanet#82. While building the code, [Uno.CodeGen][] generates [separated files][^1] so that [DocFX][] catches another automatically generated code. That's why **View Source** link was broken. I changed the `Docs`'s build order to solve this issue.
[Uno.CodeGen]: https://github.com/nventive/Uno.CodeGen
[DocFX]: https://dotnet.github.io/docfx/
[^1]: https://github.com/nventive/Uno.CodeGen/blob/master/doc/Equality%20Generation.md
> Fix the issue that the document's "View Source" link was broken

- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/DifferentAppProtocolVersionException.cs
- Libplanet/Net/DifferentProtocolVersionException.cs
- Libplanet/Net/Messages/Pong.cs
- Libplanet/Net/Swarm.cs
- Added network protocol version. #167 
- Made the peers ignore each other if the protocol version is different.
> Add protocol version and ignore peer if protocol version is different

- CHANGES.md
- Libplanet.Tests/Net/PeerSetDeltaTest.cs
- Libplanet.Tests/Net/PeerTest.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/Peer.cs
- Libplanet/Net/Swarm.cs
This PR changes `Peer.EndPoint`'s type to `DnsEndPoint` to resolve #165.
In this process, I've found a problem that the node behind the NAT can't connect properly, but I will treat it as a separate issue.
> Change type of Peer.EndPoint to DnsEndPoint

- CHANGES.md
- Libplanet.Explorer/Controllers/ExplorerController.cs
- Libplanet.Explorer/ViewModels/BlockViewModel.cs
- Libplanet.Tests/Action/ActionContextTest.cs
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Blocks/BlockTest.cs
- Libplanet.Tests/TestUtils.cs
- Libplanet.Tests/Tx/TransactionTest.cs
- Libplanet/Action/ActionContext.cs
- Libplanet/Action/IActionContext.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Blocks/Block.cs
- Libplanet/Blocks/RawBlock.cs
- Libplanet/Store/FileStore.cs
- Libplanet/Tx/Transaction.cs
- Added `Miner` property to `IActionContext`.
- Renamed `Block<T>.RewardBeneficiary` to `Block<T>.Miner`
Resolves #173
> Add Miner property to IActionContext

- CHANGES.md
- Libplanet.Tests/Net/PeerSetDeltaTest.cs
- Libplanet.Tests/Net/PeerTest.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/DifferentProtocolVersionEventArgs.cs
- Libplanet/Net/Peer.cs
- Libplanet/Net/Swarm.cs
- Added `appProtocolVersion` to `Peer`.
- Made ignore or remove `Peer` if the `appProtocolVersion` is different.
- Added EventHandler to handle different version of Peer.
Please review the name of classes as well. I'm not sure they are appropriate.
> Different protocol version of peer handling

- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/Messages/Pong.cs
- Libplanet/Net/Swarm.cs
This PR addresses #187. the following changes were made for this purpose.
- Added `TipIndex` as current chain tip Index to `Pong` to determine peer that has the longest chain.
- Made `Swarm.StartAsync()` to compare other chain height using `Pong.TipIndex` and download blocks if necessary before starts other tasks.
> Implement simple IBD

- CHANGES.md
- Libplanet/Blockchain/BlockChain.cs
This PR removes the write lock on `BlockChain<T>.MineBlock()` to increase the read throughput. Since `BlockChain<T>.Append()` already has the write lock, it can be assumed that minimal consistency is guaranteed.
> Remove writelock to improve the read throughput.

- Libplanet.Stun.Tests/Stun/Messages/RefreshErrorResponseTest.cs
- Libplanet.Stun/Stun/Messages/RefreshErrorResponse.cs
- Libplanet.Stun/Stun/TurnClient.cs
This PR fixes `TurnClient` to retry `RefreshAllocation` when stale nonce error occurred.
> Retry refreshing when stale nonce error occurred

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Store/FileStoreTest.cs
- Libplanet.Tests/Store/StoreTracker.cs
- Libplanet.Tests/TestUtils.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Store/BaseStore.cs
- Libplanet/Store/BlockSet.cs
- Libplanet/Store/FileStore.cs
- Libplanet/Store/IStore.cs
This patch completely fixes the bug #189.  Besides the patch #192, this deals with nonexistent addresses.
This involves a mask-based index to approximates a set of `Addresses`.  The key idea is that if a certain address had been ever used and included into the mask, the mask ensures to have only non-zero bits (i.e., trues) for the same positions that the address has non-zero bits.  You can also think of it as a kind of bloom filter but no hash functions.  The point is that although a mask cannot ensure if an address is in it but can ensure an address is definitely not in it.
To store a mask for each block, I added a new parameter `Address addressesMask` to `IStore.PutBlock<T>()` method, and a new method named `IStore.GetAddressesMask()` to query this.  I wrote XML comments on these …
> Make BlockChain<T>.GetStates() returns early for nonexistent addresses

- CHANGES.md
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Net/NetworkStreamProxy.cs
- Libplanet/Net/Swarm.cs
This PR aids problem the problem of TURN relay session being disconnected. if the TURN server doesn't receive `CreatePermission` on time, it deletes the registered peer and rejects any request from that. to prevent this, I added a task that iterates `CreatePermission`.
It also fixes the following issues:
- Fixed a bug that `Swarm `attempted to use TURN relay even though `_host` was given.
- Adjusted a lock in `Append()` to increase parallelism.
> Fix disconnecting on TURN relay session

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Blockchain/Policies/BlockPolicy.cs
- Libplanet/Blockchain/Policies/IBlockPolicy.cs
This changes `BlockChain<T>` to implement `IReadOnlyList<Block<T>>`.
> Change BlockChain to implement IReadOnlyList

- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/BlockDownloadState.cs
- Libplanet/Net/Swarm.cs
This PR adds `Swarm.PreloadAsync()` to explicitly downloads the blocks before starting. and, it also adds `BlockDownloadState` to provide current download state to caller(game).
> Add Swarm.PreloadAsync()

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Blockchain/Policies/BlockPolicy.cs
- Libplanet/Blockchain/Policies/IBlockPolicy.cs
- Libplanet/Blockchain/Policies/IBlockPolicyExtension.cs
- Added `ValidateNextBlock(IReadOnlyList<Block<T>>, Block<T>)` to `IBlockPolicy`.
- Changed `BlockChain<T>.Append()` to validate only the next block to be appended.
- Removed `ExpectDifficulties()`.
- Changed `IndexOutOfRangeException` in `BlockChain<T>` to `ArgumentOutOfRangeException`.
- Moved `IBlockPolicy<T>.ValidateBlocks()` to `IBlockPolicyExtension.ValidateBlocks<T>()`.
> Validate only the next block to be appended when append a block

- .travis.yml
- Libplanet.Stun.Tests/Libplanet.Stun.Tests.csproj
- Libplanet.Tests/Libplanet.Tests.csproj
- Libplanet/FodyWeavers.xml
- Libplanet/Libplanet.csproj
This patch fixes <q>Invalid IL code</q> runtime error on Mono (hence also on Unity).
The bug in itself was already fixed in upstream Equals.Fody (see Fody/Equals#81).  However, the fixed version (1.9.6) depends on Fody 5 which dropped MSBuild 15 support (see also Fody/Fody#679).  Our problem is that MSBuild 15 is not widely adopted yet (the latest stable release of .NET Core 2.2 for macOS lacks MSBuild 16, for instance).
So I forked Equals.Fody and make the fork (named [Equals4.Fody][1]) to cherry-pick the recent bug fixes without upgrading Fody to 5.
This patch also makes the tests to run on Mono besides .NET Core.
[1]: https://github.com/planetarium/Equals4.Foldy
> Fix “Invalid IL code” runtime error on Mono (hence also on Unity)

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs
- Libplanet.Tests/Blocks/BlockTest.cs
- Libplanet.Tests/HashcashTest.cs
- Libplanet.Tests/TestUtils.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Blockchain/Policies/BlockPolicy.cs
- Libplanet/Blockchain/Policies/IBlockPolicy.cs
- Libplanet/Blocks/Block.cs
- Libplanet/Blocks/RawBlock.cs
- Libplanet/HashDigest.cs
- Libplanet/Hashcash.cs
- Changed the difficulty calculation algorithm to gradually adjust the difficulty.
- Removed `HashDigest.HasLeadingZeroBits()` method and added `HashDigest.LessThanTarget()` mtehod.
- Changed difficulty type to `long` from `int`.
- Changed `BlockPolicy` interface to receive the minimum difficulty and difficulty bound divisor.
> Adjust difficulty gradually

- .travis.dotCover.xml
- .travis.yml
- CONTRIBUTING.md
- Libplanet.Tests/Net/IceServerTest.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/FodyWeavers.xml
- Libplanet/Libplanet.csproj
- [As the upstream Fody 5.0.1-beta.2 started to support MSBuild 15 again][1], I changed Libplanet to use it instead of our local fork (see also the previous patch #219).
- As Chocolatey packages are installed for every build on Travis CI, I made them cached.
- For unknown reason, tests that depend on `TURN_SERVER_URL` take strangely long time (currently the master builds fails due to timeout), so I temporarily made them skipped on Travis CI.  However, we should turn on these tests again eventually.
[1]: https://github.com/Fody/Equals/issues/81#issuecomment-486672975
> Use upstream Equals.Fody & fix CI issues

- CHANGES.md
- Libplanet/Blockchain/BlockChain.cs
This PR adjusts the locks on `BlockChain<T>`.
- Removed unnecessary writer lock in `BlockChain<T>.StageTransactions()`
- Adjust `BlockChain<T>.GetState()` locks to reduce locking period.
> Tune lock in BlockChain<T>

- CHANGES.md
- Libplanet/Libplanet.csproj
I organized changelogs into four categories:
- Backward-incompatible interface changes<sup>※</sup>
- Added interfaces
- Behavioral changes<sup>※</sup>
- Bug fixes
----
※ This should bump the major version (or the minor version until 1.0.0).
> Organize changelog

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet/Blockchain/BlockChain.cs
This patch adds `BlockChain<T>.UnstageTransactions()` method.
> Add BlockChain<T>.UnstageTransactions()

- Libplanet.Tests/Blockchain/BlockChainTest.cs
Currently, `UnstageTransactions()` sometimes fails because of the order of `TxId`. To successfully take the test in any order, I changed `List<TxId>` to `HashSet<TxId>`.
> Fix UnstageTransactions() test

- CHANGES.md
- Libplanet/Blockchain/Policies/BlockPolicyExtension.cs
- Libplanet/Blockchain/Policies/IBlockPolicy.cs
- Renamed `IBlockPolicyExtension` to `BlockPolicyExtension` to fit naming convention.
> Rename IBlockPolicyExtension to BlockPolicyExtension

- .github/main.workflow
- .travis.yml
- Docs/build.ps1
- Docs/publish.sh
As currently Mono has not been installed in Travis CI builds, DocFX (which is based on .NET Framework/Mono) has not resolved types in the standard library.  So I removed a process to build docs from Travis CI, and added a GitHub Actions workflow to build docs using DocFX with Mono.
> Build docs using GitHub Actions

- CHANGES.md
- Libplanet/Store/BlockSet.cs
- Removed `block.Validate()` when getting a block using `Blocks[index]`.
> Remove validation when getting block

- .travis.yml
- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/Swarm.cs
This PR changes the broadcasting mechanism from TAP to `NetMQPoller` based to prevent unexpected behavior on multi threading environment. to accomplish it, it made some interface changes that convert some asynchronous methods to sync methods.
Also, it adds time out on the unit tests to investigate the test freezing and fixes some problems in CI environment.
> Fix Swarm broadcasting

- CHANGES.md
- Libplanet/Blocks/Block.cs
- Libplanet/Tx/Transaction.cs
This PR adjusts `Block<T>.Hash` and `Transaction<T>.Id` as below to stabilize mining performance irrespective of the number of transactions.
- `Block<T>.Hash` and `Transaction<T>.Id`  determined in their constructor instead of dynamically generated each time.
- `Block<T>.Hash` is no longer calculated using the full data of the `Transaction<T>`, but is calculated using only the `Transaction<T>.Id`.
> Tune `Block<T>.Hash` and `Transaction<T>.Id`

- CHANGES.md
- Libplanet.Tests/Libplanet.Tests.csproj
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/Swarm.cs
This PR aids some unittest errors on Mono runtime.
- Made `Swarm.StopAsync()` closes internal resources(e.g. `_broadcastQueue`) to avoid too many open files error.
- Also, `SwarmTest` now cleans NetMQ resources at the end of each test case.
- Bump .netframework version of `Libplanet.Tests` used by Mono to avoid missing method exception.
I omitted changelog because there is no difference from previous version.
> Fix errors during unittest on Mono

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Store/FileStoreTest.cs
- Libplanet.Tests/Store/StoreTracker.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Store/BaseStore.cs
- Libplanet/Store/BlockSet.cs
- Libplanet/Store/FileStore.cs
- Libplanet/Store/IStore.cs
- Libplanet/Store/NamespaceNotFoundException.cs
- Added `IStore.LookupStateReference<T>()` method.
- Added `IStore.StoreStateReference<T>()` method.
- Added `IStore.ForkStateReferences<T>()` method.
- Changed `BlockChain<T>.GetStates()` to use a state reference, which is a `Block<T>.Hash` that has the state of the `Address`.
- Added documentation of `BlockChain<T>.GetStates()`.
> Add block hash index which has address states

- Libplanet/Libplanet.csproj
- Libplanet/Net/Swarm.cs
- azure-pipelines.yml
This PR bumps the netmq version to [4.0.0.207-pre](https://www.nuget.org/packages/NetMQ/4.0.0.207-pre) to avoid unexpected errors on macOS. 
I omitted change log because it doesn't change behavior.
> Bump netmq version to 4.0.0.207-pre

- CHANGES.md
- Libplanet.Tests/Net/PeerTest.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/Peer.cs
- Libplanet/Net/Swarm.cs
This PR fixes a bug that `Swarm` could not properly communicate with `Peer` behind NAT. to accomplish that, it made changes as belows.
- Added `Peer.PublicIPAddress` which indicates the IP address to be used when the peer connects to another peer.
- it's `internal` and does not affect public interface.
- Made `Swarm.CreatePermission()` uses `Peer.PublicIPAddress` instead of `Peer.Endpoint` if available.
> Fix relaying bug with NAT

- CHANGES.md
- Libplanet.Tests/Action/AccountStateDeltaImplTest.cs
- Libplanet/Action/AccountStateDeltaImpl.cs
This PR removes state comparison in `AccountStateDeltaImpl.SetState()` (used by `IAction.Execute()`) to improve performance of action evaluation.
> Remove state comparison in EvaluateActionsGradually

- CHANGES.md
- Libplanet.Tests/Blocks/BlockTest.cs
- Libplanet/Blocks/Block.cs
- Libplanet/Blocks/SimultaneousTxsException.cs
This patch prevents multiple transactions of the same signer from being stored in one block to prevent transaction replay.  #125
> Prevent multiple transactions of the same signer

- CHANGES.md
- Libplanet.Tests/Blocks/BlockTest.cs
- Libplanet.Tests/Tx/TransactionTest.cs
- Libplanet.Tests/Tx/TxFixture.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Blocks/Block.cs
This PR integrates `Block<T>.Validate()` and `Block<T>.EvaluateActions()` into `Block<T>.Evaluate()` to reduce `Action.Execute()` during `BlockChain<T>.Append()`.
> Integrate Block<T>.Validate() and .EvaluateActions()

- CHANGES.md
- Libplanet/Blocks/InvalidBlockTimestampException.cs
Update access modifier of InvalidBlockTimestampException to public, to resolve #133
> Update access modifier of exception to public, resolve #133

- .github/bin/dist-version.ps1
- .github/main.workflow
This fixes the broken release script run by GitHub Actions.  My previous patch #245 assigned the MSBuild 2003 XML namespace to *\*.csproj* files, and it broke the XPath used by `dist:version` action.
In order to be warned before a pull request is merged, I also made `dist:pack` action run for `pull_request` events.
> Fix broken release script

- .github/bin/dist-version.ps1
This patch appends `+` followed by the commit hash into the version string, so that people can be aware which commit was a package built from.
> Denote build metadata into the version string

- .github/bin/dist-version.ps1
This is a bugfix of my previous patch #253. 🙄
> Typo on version string: +, not .

- .azure-pipelines/mono.yml
- .azure-pipelines/windows-net461.yml
- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Net/Swarm.cs
- azure-pipelines.yml
- This PR mainly aids hanging unit tests running on Mono in Windows by calling `AsyncIO.ForceDotNet.Force()` to enforce using sockets in .NET, not Windows native.
- It's also prevents some other possible hanging unit tests by eliminating `Swarm.Add()` usages.
- It's also fixes `ArgumentOutOfRangeException` that occurred when requesting a hash when `BlockChain <T>` was empty.
> Force dotnet if running on mono

- CHANGES.md
- Libplanet.Stun/Libplanet.Stun.csproj
- Libplanet.Stun/Stun/TurnClient.cs
- Libplanet/Libplanet.csproj
#248 occurs when two or more nodes simultaneously request a TURN relay for one node. this patch fixes it.
Also in this process, I let `Libplanet.Stun` use [Serilog](https://serilog.net/), and upgrade the version used by `Libplanet`.
> Fix concurrency error in TurnClient.AcceptRelayedStreamAsync()

- .github/bin/dist-version.ps1
This is also a bugfix of my previous patches #253 & #254. 🙄
As NuGet doesn't append build metadata to a filename, denote a commit hash to only a VersionSuffix, not a full package version string.
> Denote build metadata only to VersionSuffix

- .azure-pipelines/mono.yml
- .azure-pipelines/windows-net461.yml
- azure-pipelines.yml
This adds a CI job that runs unit tests on Unity player.  In order to run xUnit.net tests on Unity player, I made [xunit-unity-runner][1] as well.
Note that I temporarily disabled `Libplanet.Tests.Blocks.BlockTest.EvaluateActionsPerTx` test, because it causes `MissingMethodException` and I haven't found how to fix this yet.  I guess it's related to this: <https://github.com/dotnet/standard/issues/476#issuecomment-326726613>.
[1]: https://github.com/planetarium/xunit-unity-runner
> Run unit tests on Unity player

- .github/bin/dist-version.ps1
This patch fixes the bug #262.  It caused because GitHub Actions' `schedule` events refer to the commit hash directly (not through the branch name indirectly) to check out the source code, while the *.github/bin/dist-version.ps1* script had assumed *.git/HEAD* has always an indirect ref (e.g., `ref: refs/heads/master`).  This fixes the script able to see both direct and indirect refs.
> Fix broken nightly builds

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet/Blockchain/BlockChain.cs
~This PR adds `includeStage` to `BlockChain<T>.GetNonce()` to refer staged transactions during nonce computation.~
I've changed `BlockChain<T>.GetNonce()` to refer staged transactions without any other options.
> Made BlockChain<T>.GetNonce() to refer staged transactions

- Libplanet.Stun.Tests/Libplanet.Stun.Tests.csproj
- Libplanet.Stun/Libplanet.Stun.csproj
- Libplanet.Tests/Libplanet.Tests.csproj
- Libplanet/Libplanet.csproj
FYI `MEN001` is a rule to enforce use only hard tabs instead soft tabs (i.e., spaces), which contradicts StyleCop's [`SA1027`][1].
[1]: https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1027.md
> Minor fixes for Rider IDE

- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Libplanet.csproj
- Libplanet/Net/Swarm.cs
This PR fixes issues as below.
- Fixed a bug that `Swarm.StopAsync()` didn't stop properly during `Swarm.Preload()`
- Filled up cancellation support with `CancellationToken` on TAP methods.
> Fix Swarm.StopAsync()

- CHANGES.md
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Store/BaseIndex.cs
- Libplanet/Store/BlockSet.cs
- Libplanet/Store/TransactionSet.cs
This PR improves performance of `BlockChain<T>.Blocks.Contains()`, `BlockChain<T>.FindBranchPoint()` and `BlockChain<T>.FindNextHashes()` to reduce response time for block hashes query.
> Improve branch point finding

- CHANGES.md
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet/Store/FileStore.cs
- Libplanet/Store/LiteDBStore.cs
- Fixed a bug where the first `TxNonce` of an address is not stripped when forking using `FileStore.ForkTxNonce()` method.
- Fixed a bug where `LiteDBStore.GetTxNonce()` method throws a `System.IO.IOException` when reading a zero-length file.
> Fix bugs when forking TxNonce

- azure-pipelines.yml
This PR bumps xunit-unity-runner version to [0.2.2](https://github.com/planetarium/xunit-unity-runner/releases/tag/0.2.2) to apply [this patch](https://github.com/planetarium/xunit-unity-runner/pull/1).
> Bump xunit-unity-runner's version to 0.2.2

- CHANGES.md
- Libplanet.Stun.Tests/Stun/Attributes/StunAddressExtensionTest.cs
- Libplanet.Stun/Stun/Attributes/StunAddressExtension.cs
It resolves #267 
This PR adds the following items.
- Add testcase for support IPv6 and implement
- Use `Theory`, `MemberData` to reduce code duplication in testcode
> Add IPv6 support to Libplanet.Stun

- azure-pipelines.yml
This PR bumps the version of [xunit-unity-runner](https://github.com/planetarium/xunit-unity-runner) to [0.2.3](https://github.com/planetarium/xunit-unity-runner/releases/tag/0.2.3) to avoid double invocation.
> Bump xunit-unity-runner to 0.2.3

- CHANGES.md
- Libplanet.Stun/Stun/TurnClient.cs
This PR added cancellation support to async methods in `TurnClient`.
and, it also fixes a bug that `TurnClient.Dispose()` doesn't stop properly when control socket has disconnected.
> Added cancellation support to TurnClient

- .editorconfig
- CHANGES.md
- Libplanet.Tests/Net/PeerTest.cs
- Libplanet/Net/Peer.cs
- Libplanet/Net/Swarm.cs
- Menees.Analyzers.Settings.xml
This patch allows null value to `Peer.AppProtocolVersion`. so this adds version-less `Peer` constructor and `Peer.WithAppProtocolVersion()`.
Also, this PR widens the line length limit to 100 (as #222).
> Allow null to Peer.AppProtocolVersion for easy configuration

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet.Tests/Store/StoreTracker.cs
- Libplanet/Address.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Blockchain/IncompleteBlockStatesException.cs
- Libplanet/Store/BaseStore.cs
- Libplanet/Store/FileStore.cs
- Libplanet/Store/IStore.cs
- Libplanet/Store/LiteDBStore.cs
- Libplanet/Tx/InvalidTxUpdatedAddressesException.cs
This patch makes `BlockChain<T>` to have incomplete states so that we can implement #272 on this.  Where a `BlockChain<T>` does not have complete states and a query to states that it lacks is required, there are two options:
- Throwing `IncompleteBlockStatesException` (which is default).
- Evaluating actions preceding the requested states and filling the states on the fly (`completeStates: true`).
See also *CHANGES.md* as well.
> Allow BlockChain<T> to have incomplete states

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Blockchain/MineBlockEventArgs.cs
- Libplanet/Blocks/Block.cs
- Libplanet/Tx/InvalidTxNonceException.cs
- Combines creating and staging of transaction interfaces with the `BlockChain<T>.MakeTransaction()` method.
> Combine creating and staging transaction interface

- Libplanet/Blocks/Block.cs
This PR aids unstable mining speed after #294. the main problem is, `transactions.OrderBy()` in `Block<T>()`  was too many invoked during `Block<T>.Mine()`.
To fix it, I moved the invocation to Block<T>.Mine() and called only once.
> Stabilize mining speed

- Libplanet/Store/LiteDBStore.cs
This PR adds `journal` and `cacheSize` as optional parameters to `LiteDBStore`'s constructor.
I omitted change log because the mention about `LiteDBStore` has been added `0.0.4` section.
> Made LiteDBStore to be configurable.

- .github/bin/dist-nuget.sh
- Docs/publish.sh
This patch prevents the GitHub Actions process publishing packages/docs a non-release branch by accident.  Without this patch, for example, temporary branches made by the [autorebase] bot are published to NuGet.
[autorebase]: https://github.com/apps/autorebase
> Avoid publishing packages/docs unless a branch is for releases

- CHANGES.md
This fixes `BlockChain<T>.GetNonce()` method name in changelog to `BlockChain<T>.GetNextTxNonce()`.
> Fix method name in changelog

- CHANGES.md
- Libplanet.Stun/Stun/TurnClient.cs
- Libplanet/Net/IceServer.cs
This PR adds improves connectivity of `TurnClient._control` by adding `TurnClient.EnsureConnection` to ensure `_control` connection before processing.
> Improve TurnClient connection

- .vscode/settings.json
- CHANGES.md
- CONTRIBUTING.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Store/StoreExtensionTest.cs
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet.Tests/Store/StoreTracker.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Store/BaseStore.cs
- Libplanet/Store/FileStore.cs
- Libplanet/Store/IStore.cs
- Libplanet/Store/LiteDBStore.cs
- Libplanet/Store/StoreExtension.cs
This consists of two changes on the `IStore` interface and its implementations:
- Tx nonces is no more stacked but encoded as a single 64-bit integer instead.
- Multiple state references for an address can be fetched at a time, without multiple method calls.
These changes are needed for implementing #272.
> Adjust how IStore deals with state references and tx nonce

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet.Tests/Store/StoreTracker.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Store/BaseStore.cs
- Libplanet/Store/FileStore.cs
- Libplanet/Store/IStore.cs
- Libplanet/Store/LiteDBStore.cs
This fixes the bug #309 that tx nonces being missed during fork, because addresses that aren't *stale* are missing.  To correctly fix this, I've needed `IStore.ListTxNonces()` as well (note that `IStore.ListAddresses()` could miss addresses that have never had any states but ever signed some transactions).
> Fix tx nonces being missed during fork

- Libplanet.Stun.Tests/Stun/Attributes/ErrorCodeTest.cs
- Libplanet.Stun.Tests/Stun/Attributes/LifetimeTest.cs
- Libplanet.Stun.Tests/Stun/Attributes/MessageIntegrityTest.cs
- Libplanet.Stun.Tests/Stun/Attributes/NonceTest.cs
- Libplanet.Stun.Tests/Stun/Attributes/RealmTest.cs
- Libplanet.Stun.Tests/Stun/Attributes/RequestedTransportTest.cs
- Libplanet.Stun.Tests/Stun/Attributes/StunAddressExtensionTest.cs
- Libplanet.Stun.Tests/Stun/Attributes/UserNameTest.cs
- Libplanet.Stun.Tests/Stun/Messages/AllocateErrorResponseTest.cs
- Libplanet.Stun.Tests/Stun/Messages/AllocateRequestTest.cs
- Libplanet.Stun.Tests/Stun/Messages/AllocateSuccessResponseTest.cs
- Libplanet.Stun.Tests/Stun/Messages/BindingRequestSucessTest.cs
- Libplanet.Stun.Tests/Stun/Messages/BindingRequestTest.cs
- Libplanet.Stun.Tests/Stun/Messages/ConnectionAttemptTest.cs
- Libplanet.Stun.Tests/Stun/Messages/ConnectionBindRequestTest.cs
- Libplanet.Stun.Tests/Stun/Messages/ConnectionBindSuccessResponseTest.cs
- Libplanet.Stun.Tests/Stun/Messages/CreatePermissionRequestTest.cs
- Libplanet.Stun.Tests/Stun/Messages/CreatePermissionSuccessResponseTest.cs
- Libplanet.Stun.Tests/Stun/Messages/RefreshErrorResponseTest.cs
- Libplanet.Stun.Tests/Stun/Messages/RefreshRequestTest.cs
- Libplanet.Stun.Tests/Stun/Messages/RefreshSuccessResponseTest.cs
- Libplanet.Stun.Tests/Stun/Messages/StunMessageTest.cs
- Libplanet.Stun.Tests/Stun/Messages/TestStunContext.cs
Libplanet.Tests.Stun namespace is outdated. move to Libplanet.Stun.Tests.
> Move namespace Libplanet.Tests.Stun to Libplanet.Stun.Tests

- CHANGES.md
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet/Store/FileStore.cs
> FileStore.IndexBlockhash return null when index out of range

- CHANGES.md
- Libplanet/Net/Swarm.cs
This PR fixes a bug that `Swarm` had not dial to other peer after IBD. This is due to the fact that `Swarm`'s internal `DealerSocket` doesn't connect properly after a certain period of time. 
To solve this problem, every `DialAsync()` has been modified to close the previous `DealerSocket` and create a new `DealerSocket`.
> Fix a bug that DealerSocket has been broken after IBD.

- Libplanet/Store/IStore.cs
This adds the assumption that `StoreStateReference` is called in order.
> Add assumption for StoreStateReference

- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/DifferentAppProtocolVersionException.cs
- Libplanet/Net/DifferentProtocolVersionEventArgs.cs
- Libplanet/Net/Peer.cs
- Libplanet/Net/Swarm.cs
This makes `Swarm` constructor receive `BlockChain<T>` and have a type parameter `T`.
> Make Swarm constructor have BlockChain<T>

- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/Swarm.cs
> Swarm is not ICollection<Peer> anymore

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet.Tests/Store/LiteDBStoreTest.cs
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet.Tests/Store/StoreTracker.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Store/BaseStore.cs
- Libplanet/Store/FileStore.cs
- Libplanet/Store/IStore.cs
- Libplanet/Store/LiteDBStore.cs
This PR enables `BlockChain<T>` to clean up data(index, tx nonces, staterefs) in the previous chain during `.Swap()`. (resolves #322) To accomplish, it also adds `IStore.DeleteNamespace()` and `LiteDBStore` / `FileStore` implementation.
> Delete an index, tx nonces and state references during chain swapping

- CHANGES.md
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Store/IStore.cs
It resolves #282 
Instead of using ImmutableHashSet, I choose to use IEnumerable  
Because it won't load all indexes stored in the `Store`
> Implement BlockChain<T>.FindBranchPoint again,  to reduce memory consumption

- CHANGES.md
- Libplanet/Net/Swarm.cs
This fixes #321 using `NetMQPoller` to receive messages.
> Move ReceiveMessageAsync to poller

- Libplanet/Store/IStore.cs
The order of returned elements was described in the opposite way.
> Fix wrong docs of IStore.IterateIndex()

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Net/Swarm.cs
This PR resolves #279 by removing the `id` parameter from `BlockChain<T>` constructor. it also made `BlockChain<T>.Id` to be automatically determined by chain height.
> Remove `id` from BlockChain<T> constructor

- .github/main.workflow
As NuGet does not allow to remove an once uploaded package, making `dist:nuget` to depend on `dist:github-release` seems more robust.
> Make dist:nuget to fail if dist:github-release fails

- .github/bin/dist-github-release.sh
This fixes the following error during `dist:github-release` action:
```
x509: failed to load system roots and no roots provided
```
> Fix x509 error during dist:github-release action

- .github/bin/dist-nuget.sh
- Docs/publish.sh
This fixes a bug made by the patch #305.
> Do not avoid publishing packages/docs for tag pushes

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Store/StoreExtensionTest.cs
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Store/StoreExtension.cs
This fixes a bug where `GetStates` method does not return the latest state when there are multiple addresses. And also this changes the return value of `LookupStateReference()` method to fix the bug.
> Fix GetStates bug when there are multiple addresses

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Store/StoreExtensionTest.cs
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Store/StoreExtension.cs
This removes `LookupStateReferenceWithIndex()`, a temporary method to ensure backward compatibility with 0.4.1, and changes the return value of `LookupStateReference()`.
> Change return value of LookupStateReference

- Libplanet/Store/IStore.cs
It turns out that it's actually descending order. See also <https://github.com/planetarium/libplanet/pull/333> which made the bug.
> Correct docs about order of IStore.IterateIndex()

- CHANGES.md
- Docs/publish.sh
- Libplanet.Stun.Tests/Libplanet.Stun.Tests.csproj
- Libplanet.Tests.ruleset
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Libplanet.Tests.csproj
- Libplanet.Tests/Net/Messages/RecentStatesTest.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Net/Messages/GetRecentStates.cs
- Libplanet/Net/Messages/Message.cs
- Libplanet/Net/Messages/RecentStates.cs
- Libplanet/Net/Swarm.cs
- Libplanet/Store/IStore.cs
- Menees.Analyzers.Settings.xml
This patch implements (in a quick-and-dirty way) the idea suggested from #272.  There are direct accesses to `IStore` from `Swarm<T>`; these should be fixed in the near future, as they have possibility to cause unexpected behaviors on race conditions.
Closes #272.
> Option to reuse states calculated by trusted peers

- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/Swarm.cs
This PR makes `Swarm<T>` to re-stage transactions when receiving already unstaged.
> Re-stage transactions when receiving already unstaged

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Net/Swarm.cs
This PR reverts #362 and introduces another solution that makes transactions having the future nonce to pending and ignores them.
> Make transaction to pending that have the future nonce

- CHANGES.md
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet/Store/LiteDBStore.cs
This PR fixes a bug that `LiteDBStore.IterateStagedTransactionIds()` returns duplicated transaction ids.
> LiteDBStore.IterateStagedTransactionIds() should returns unique txids

- CHANGES.md
- Libplanet.Tests/AddressTest.cs
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Blockchain/NullPolicy.cs
- Libplanet.Tests/Store/StoreExtensionTest.cs
- Libplanet/Address.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Net/Swarm.cs
- Libplanet/Store/IStore.cs
- Libplanet/Store/StoreExtension.cs
- Menees.Analyzers.Settings.xml
It's only temporary code in a transition code.
> Make Swarm's direct access code to store atomic

- CHANGES.md
- Libplanet.Tests/Action/ActionEvaluationTest.cs
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Blockchain/NullPolicy.cs
- Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs
- Libplanet.Tests/Blocks/BlockTest.cs
- Libplanet.Tests/Common/Action/DumbAction.cs
- Libplanet.Tests/Common/Action/MinerReward.cs
- Libplanet.Tests/Common/Action/RenderRecord.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet.Tests/TestUtils.cs
- Libplanet.Tests/Tx/TransactionTest.cs
- Libplanet/Action/ActionEvaluation.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Blockchain/Policies/BlockPolicy.cs
- Libplanet/Blockchain/Policies/IBlockPolicy.cs
- Libplanet/Blocks/Block.cs
- Libplanet/Tx/Transaction.cs
- azure-pipelines.yml
This implements #319 and replaces #357.
- `IBlockPolicy<T>.BlockAction` is added.
- The type parameter of `ActionEvaluation` is removed.
- `IBlockPolicy<T>.BlockAction` evaluated after Tx evaluation.
> Evaluate Block Action

- CHANGES.md
- Libplanet.Tests/AddressTest.cs
- Libplanet/Address.cs
This PR fixes a bug that `NullReferenceException` occurred when serializing default `Address`.
> Fix a bug when serializing default address

- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/Swarm.cs
This makes `PreloadAsync()` skip state synchronization if the most recent state has already been evaluated.
> Skip sync recent states If it has already been evaluated

- Libplanet/Net/Swarm.cs
This PR removes `Swarm._poller` and introduces `Swarm.Poll()` as a new helper method to avoid unexcepted poller stopping problem.
> Remove Swarm._poller

- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Libplanet.csproj
In order to fix <https://github.com/zeromq/netmq/issues/806> (see also @earlbread's PR: <https://github.com/zeromq/netmq/pull/808>), I made [our own fork of NetMQ][1] and [released it][2] (see also [NuGet][3]).  We can roll back this to the upstream when a new release is made in the upstream.
[1]: https://github.com/planetarium/netmq
[2]: https://github.com/planetarium/netmq/releases/tag/4.0.0.253-planetarium
[3]: https://www.nuget.org/packages/Planetarium.NetMQ/4.0.0.253-planetarium
> Use our own fork of NetMQ

- CHANGES.md
- Libplanet/Net/Swarm.cs
This PR removes `Swarm<T>._receiveMutex` to avoid continuous delays about peer registration (using `.ApplyDelta`).
> Prevent unintended delays in `Swarm<T>.ProcessDeltaAsync()`

- Libplanet/Net/Swarm.cs
This PR reverts #381 partially to allow two processes (receiving and replying) to poll `_router` at the same time. 
it also tweaks `Swarm<T>`'s behavior to increase stability.
> Restore Swarm._poller and tweak something else

- CHANGES.md
- Libplanet/Store/LiteDBStore.cs
This patch works around <https://github.com/mbdavid/LiteDB/issues/1268>.
> Work around LiteDB's file storage bug

- CHANGES.md
- Libplanet.Tests/Store/StoreExtensionTest.cs
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet.Tests/Store/StoreTracker.cs
- Libplanet/Net/Messages/GetRecentStates.cs
- Libplanet/Net/Swarm.cs
- Libplanet/Store/BaseStore.cs
- Libplanet/Store/FileStore.cs
- Libplanet/Store/IStore.cs
- Libplanet/Store/LiteDBStore.cs
- Libplanet/Store/StoreExtension.cs
There had been a corner case where a trusted peer sends inconsistent states and state refs, because the exact times to get both data from the store can subtly differ each other.  In order to avoid that specific case, I added filtering options named `onlyAfter`/`ignoreAfter` to `ListAllStateReferences()` method, and made `Swarm` to query state refs with a strict scope so that state refs to send are consistent with states to send.
> Properly scope state/state refs to download/reuse

- azure-pipelines.yml
This fixes broken builds of other pull requests like #376 and #387.
> Stick with .NET Core SDK compatible with Mono + Linux on Azure Pipelines

- CHANGES.md
- Libplanet/Store/LiteDBStore.cs
It turns out that LiteDB's data corruption (mbdavid/LiteDB#1268) seems to happen due to sudden termination of program.  So the workaround made in the previous workaround (#386) was reverted for the most part, and a new option named `flush` was added to `LiteDBStore()` constructor, so that every write is immediately flushed to disk.  As a bonus, I made `LiteDBStore.GetTransaction()` method to treat corrupted transactions nonexistent, though I am not sure how would it be going and if work well together with other parts of Libplanet (I guess there could be some assumptions that once stored transactions must be existent in a store).
> Second approach to LiteDB's data corruption

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Net/Swarm.cs
As `BlockChain<T>.GetEnumerator()` always fetches block data and instantiates actual `Block<T>` objects, skipping on that still had a lot of redundant operations.  This patch fixes that inefficiency.
> Ffwd already had blocks without fetch during preloading phase

- CHANGES.md
- Libplanet/Store/BaseIndex.cs
- Libplanet/Store/BlockSet.cs
- Libplanet/Store/LiteDBStore.cs
- Libplanet/Store/TransactionSet.cs
This PR tunes `BlockSet<T>.ContainsKey()` and `TransactionSet<T>.ContainsKey()` to accomplish lookup in O(1).
> Tune BaseIndex.ContainsKey()

- CHANGES.md
- Libplanet.Tests/Store/LiteDBStoreTest.cs
- Libplanet/Store/LiteDBStore.cs
This fixes <https://github.com/planetarium/libplanet/issues/395>.
> More efficient way to store state references

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Net/BlockDownloadState.cs
- Libplanet/Net/Swarm.cs
This makes `PreloadAsync` report total block download status instead of chunked download status.
Resolves #396.
> Report total block download status

- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/Swarm.cs
Currently, received count is displayed bigger than total block count if seed node mine another block while IBD. This patch changes the total block count when that situation happens.
> Change total block count when received count is bigger

- Libplanet/Store/LiteDBStore.cs
This PR restores corruption check condition about empty transaction data (implemented #387 ).
> Restore tx corruption check in LiteDBStore

- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/ActionExecutionState.cs
- Libplanet/Net/BlockDownloadState.cs
- Libplanet/Net/BlockStateDownloadState.cs
- Libplanet/Net/PreloadState.cs
- Libplanet/Net/StateReferenceDownloadState.cs
- Libplanet/Net/Swarm.cs
It resolves #397.
Before this, there was no way to know progress of download state-references or block-states.
So this make swarm report progress with `State` classes inherited `PreloadState` during preload. :cat2:
> Make swarm report more progresses during preload

- CHANGES.md
- Libplanet/Net/NetworkStreamProxy.cs
- Libplanet/Net/Swarm.cs
This PR fixes a bug that `NetworkStreamProxy.StartAsync()` never stops even if the connection had disconnected by a remote peer.
> Fix bug that NetworkStreamProxy.StartAsync() never stops

- CHANGES.md
- Libplanet/Net/Swarm.cs
This PR apply a timeout to `Message.GetBlockBlockHash`, `Message.GetBlocks` and `Message.Tx` to avoid hanging when a remote peer had gone.
> Apply timeout to receving BlockHashes, Blocks and Tx

- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet/Net/Swarm.cs
- Libplanet/Store/FileStore.cs
- Libplanet/Store/IStore.cs
- Libplanet/Store/LiteDBStore.cs
This patch is an alternative solution to the same problem that #411 aims to address.
> Make LiteDBStore & FileStore to atomically store transactions

- CHANGES.md
- Libplanet/Net/Swarm.cs
This PR makes `Swarm<T>.PreloadAsync()` to be omitted when there is no suitable peer.
> Skip PreloadAsync when there is no suitable peer

- CHANGES.md
- Libplanet/Net/Swarm.cs
This PR adjusts the order of processes in `Swarm<T>.StartAsync()` to avoid disabling TURN allocation even if `Swarm<T>.PreloadAsync()` takes a long time.
> Re-ordering Swarm<T>.StartAsync()

- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/Swarm.cs
- Libplanet/Store/IStore.cs
- Menees.Analyzers.Settings.xml
`Swarm<T>.PreloadAsync()` became to cleanup its working chain (store namespace) whether it normally finishes or is cancelled.  Also `Swarm` now more properly addresses cancellation requests.
> Better cancellation & atomicity for PreloadAsync()

- CHANGES.md
- Libplanet/Action/IAction.cs
- Libplanet/Action/IRandom.cs
> Get rid of IRandom.NextDouble()

- CHANGES.md
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet.Tests/Store/StoreTracker.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Store/BaseStore.cs
- Libplanet/Store/FileStore.cs
- Libplanet/Store/IStore.cs
- Libplanet/Store/LiteDBStore.cs
This fixes a problem where `BlockChain.FinxNextHashes()` method is slow when there are many blocks.
> Fix slow FindNextHashes

- CHANGES.md
- Libplanet/Net/Swarm.cs
- Menees.Analyzers.Settings.xml
This PR fixes a bug that `Swarm<T>` hadn't retried TURN related methods automatically when an exception occurred.
> Continue RefreshAllocate and RefreshPermission even if exc occurred.

- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/Swarm.cs
It resolves #430 
The states may be reported not in sorted.
So I changed the part to assert.
> Fix swarm test preload fails

- Libplanet/Net/Swarm.cs
Currently, `_blockChain.Swap` is performed when an exception occurred while preloading. We need to check the completeness of preloading before swapping.
> Check Preload completeness

- CHANGES.md
- Libplanet.Tests/AddressTest.cs
- Libplanet/Address.cs
- Resolve #442 
- `Address(byte[])` became to throw `ArgumentNullException`
instead of `NullReferenceException`.
> Add Address(ImmutableArray<byte>) constructor

- CHANGES.md
- Libplanet/Blockchain/BlockChain.cs
This PR fixes behavior of peer—which responses `getBlockHashes()`—to contains one more higher block hash for satisfy `FindNextHashesChunkSize` (Since the peer which performs `PreloadAsync()` drops the lowest block from the response of `getBlockHashes()` except initial phase). 
Resolves #408.
> Correct GetBlockHashes chunk size after first phase

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Store/StoreExtensionTest.cs
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet.Tests/Store/StoreTracker.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Net/StateReferenceDownloadState.cs
- Libplanet/Net/Swarm.cs
- Libplanet/Store/BaseStore.cs
- Libplanet/Store/IStore.cs
- Libplanet/Store/LiteDBStore.cs
- Libplanet/Store/StoreExtension.cs
This patch enhances the performance of `Swarm.PreloadAsync()` using two tricks as below.
- Instead of using `RecentStates.StateReferences` directly, `PreloadAsync` became to translate this message as `Dictionary<HashDigest<SHA256>, ISet<Address>>` to reduce file I/O.
- To accomplish this, `IStore.StoreStateReference` became to take `blockHash` and `blockIndex`, not whole `Block`.
- `PreloadAsync()` are currently fork its chain to prevent corruption by unexpected termination. this patch reduces its file I/O by `IStore.ForkIndexes()`
> Boost PreloadAsync()

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet/Blockchain/BlockChain.cs
This fixes <https://github.com/planetarium/libplanet/issues/454>.  I'm going to make another patch to remove the `addressesToStrip` parameter at all from `IStore.ForkStateReferences()` method (see also `FIXME` comment) to the master branch.
> Fix ArgumentNullException thrown by BlockChain<T>.Fork() where it has incomplete states

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet.Tests/Store/StoreTracker.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Store/BaseStore.cs
- Libplanet/Store/IStore.cs
- Libplanet/Store/LiteDBStore.cs
It's a port of the patch #466, and removes unnecessary `addressesToStrip` parameter from `IStore.ForkStateReferences()` method.
> Remove unnecessary addressesToStrip parameter from IStore.ForkStateReferences()

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet.Tests/Store/StoreTracker.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Net/Swarm.cs
- Libplanet/Store/BaseStore.cs
- Libplanet/Store/IStore.cs
- Libplanet/Store/LiteDBStore.cs
Removed the concept of “staged transactions that should not be broadcasted,” because its primary usage had been to make a transaction of a reward action for a candidate for block miner, and the case became achieved through `IBlockPolicy<T>.BlockAction` property which was made by the patch #367.
So all staged transactions became broadcasted.
> Make all staged transactions broadcasted

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet/Blockchain/BlockChain.cs
This fixes an issue where `FindBranchPoint()` returns a branch point if it exists in the `BlockSet` even if the block does not exist in the chain.
> Fix FindBranchPoint

- .azure-pipelines/mono.yml
- .azure-pipelines/windows-net461.yml
- CHANGES.md
- Libplanet.Stun/Stun/TurnClient.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Blockchain/BlockChain.cs
- azure-pipelines.yml
I believe this fixes <https://github.com/planetarium/libplanet/issues/352>, but I haven't found any concise way to reproduce this in unit tests…
> Fix Swarm<T>.BroadcastTxAsync() an exception from IStore on some race conditions

- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/Messages/GetRecentStates.cs
- Libplanet/Net/Swarm.cs
> Download trusted states from a likely branchpoint

- Libplanet.Tests/Net/IceServerTest.cs
- Libplanet.Tests/Net/SwarmTest.cs
- azure-pipelines.yml
It seems to be able to run IceServerTests on Windows again.
Resolves #221 
Resolves #249 
Resolves #478.
> Restore IceServerTest on Windows

- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/Swarm.cs
> Ignore containing block hashes

- CHANGES.md
- Libplanet/Net/Swarm.cs
> Broadcast transaction as soon as new transactions received

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Common/Action/MinerReward.cs
- Libplanet/Blockchain/BlockChain.cs
This fixes bug where `GetState` hadn't return proper state when the block action is evaluated.
> Fix GetState of block action to return proper state

- CHANGES.md
- Libplanet.Tests/Action/ActionContextTest.cs
- Libplanet/Action/ActionContext.cs
- Libplanet/Action/IActionContext.cs
- Libplanet/Action/RandomExtension.cs
I think getting a random `Guid` in `IActionContext` is a bad usage because dummy objects (for testing, debugging or etc ...) using random `Guid` in games don't need `IActionContext`. `IRandom`s are enough to acquire the same thing.
So I removed `IActionContext.NewGuid()`.
Instead I added an extension class, `RandomExtension` that includes a extension method, `GenerateRandomGuid()`.
Since `RandomExtension` is an extension class, I implemented generating a random `Guid`.
> Remove `IActionContext.NewGuid()` & Add `RandomExtension.GenerateRandomGuid()`

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Action/PolymorphicAction.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Net/Swarm.cs
This patch fixes a bug, made by 6e7249f8e0feee76292acfbd256a6645bf1c00f5, that `Swarm<T>.PreloadAsync()` silently misses the states resulted from actins in a genesis block (both tx actions and block actions) when it downloads states from trusted peers.
As the change made this bug hasn't been released yet, I skipped the changelog.
> Fix Swarm<T>.PreloadAsync() missing genesis states

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Blocks/BlockTest.cs
- Libplanet.Tests/Tx/TxIdTest.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Blocks/Block.cs
- Libplanet/Tx/TxId.cs
This resolves #244.
- `Block<T>.Transactions` became to present ordered transactions
- Removed `Block<T>.OrderedTransactions`
> Remove OrderedTransactions

- .azure-pipelines/dotnet-core.yml
- .azure-pipelines/mono.yml
- .azure-pipelines/windows-net461.yml
This increases test timeout to 11 min to avoid frequent test failures due to timeout.
> Increase test timeout to 11min

- CHANGES.md
- Libplanet.Tests/Blocks/BlockTest.cs
- Libplanet/Blocks/Block.cs
See also the changelog and comments in the `Block<T>()` constructor.
> Make the order of Block<T>.Transactions aware of their nonce

- CHANGES.md
- Libplanet/Action/ActionEvaluation.cs
This PR fixes a bug that `IActionContext.Random` had generated the same result in different `IAction.Execute()` against the same `Block<T>`.
> Hash signature before feeding as seed

- CHANGES.md
- Libplanet.Tests/Store/StoreFixture.cs
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet/Store/LiteDBStore.cs
Fixed a bug that `LiteDBStore.ForkStateReferences<T>()` had thrown `ChainIdNotFoundException` where a `sourceChainId` exists but it has no state references (#509).
> Fix a bug that LiteDBStore.ForkStateReferences<T>() throws ChainIdNotFoundException even if sourceChinId exists

- .azure-pipelines/dotnet-core.yml
- .azure-pipelines/mono.yml
- .azure-pipelines/windows-net461.yml
- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet.Tests/Store/LiteDBStoreFixture.cs
- Libplanet/Store/LiteDBStore.cs
This improves the test speed by using in-memory LiteDBStore in tests and restores test timeout to 10 minutes.
> Use in-memory LiteDBStore in tests

- CHANGES.md
- Libplanet.Benchmarks/MineBlock.cs
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Blockchain/NullPolicy.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Blocks/Block.cs
- Libplanet/Hashcash.cs
This patch implements and closes #460. Some XML descriptions and test cases are included in this PR.
> Cancel mining if blockchain's tip index is changed

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet/Blockchain/BlockChain.cs
Instead of providing only a new tip index, this patch adds a tip hash and a previous tip.
> Provide richer data for the TipChanged event

- azure-pipelines.yml
After mono version upgrade to 6.4.0.198, some tests seem to fail. So temporary roll back mono version to 6.0.0.334.
> Fix mono version to 6.0.0.334

- Libplanet/Net/Protocols/KademliaProtocol.cs
Unlike `KademliaProtocol<T>.BootstrapAsync`, `KademliaProtocol<T>.RebuildConnectionAsync` now searches for all peers on network. Additionally, it runs on `Swarm<T>.StartAsync` since `KademliaProtocol<T>.BootstrapAsync` does not ensures to find all peers on network.
This resolves #524.
> Fix KademliaProtocol<T>.RebuildConnectionAsync

- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/Swarm.cs
This removes forked chain when `FillBlocksAsync` fail.
> Remove forked chain when FillBlocksAsync fail

- Libplanet/Net/Swarm.cs
- Libplanet/Store/BlockSet.cs
This PR fixes #531 
The direct reason for #531 is `target` that doesn't exist on the sender was used for a log message. so I've added condition about this.
This bug was caused by #512 that was not filing, so I also omit the changelog.
> Fix KeyNotFoundException on Swarm<T>.TransferRecentStates()

- CHANGES.md
- Libplanet/Net/Swarm.cs
This removes forked chain when `FillBlocksAsync` fail.
> Remove forked chain when AppendBlocksAsync fail

- Libplanet/Net/Peer.cs
- Libplanet/Net/Swarm.cs
This fixes `NullReferenceException` in `AppendBlocksAsync()` and adds `ToString()` to `Peer`.
I skipped the changelog because `Peer` is changed at 0.6.0.
> Fix NullReferenceException in AppendBlocksAsync

- CHANGES.md
- Libplanet/Action/IRandom.cs
Rename variables in the `IRandom` interface according to #555
> Rename variable according to #555

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet.Tests/Store/StoreTracker.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Store/BaseStore.cs
- Libplanet/Store/IStore.cs
- Libplanet/Store/LiteDBStore.cs
Also renamed the corresponding StoreTest and StoreTracker-Methods to comply with the new name.
This change resolves issue [462](https://github.com/planetarium/libplanet/issues/462)
> Renamed InterateIndex to IterateIndexes (resolves issue #462)

- CHANGES.md
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet.Tests/Store/StoreTracker.cs
- Libplanet/Store/BaseStore.cs
- Libplanet/Store/IStore.cs
- Libplanet/Store/LiteDBStore.cs
- Libplanet/Store/StoreExtension.cs
To mitigate #447, this improves `IStore.LookupStateReference()` method by limiting the number of results.
> Improve LookupStateReference

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Blockchain/BlockChain.cs
An attempt to solve Issue #510 
It feels super wonky to still use AddressStateMap as a returnvalue, because it will always have just the one entry. I tried to make it return the (object) value instead, but failed misserably on a serialization-issue, breaking most of the use-cases.
If you guys want me to pursuit a better return value, i could try again...
Anyways, looking forward to your feedback :)
> Turn BlockChain.GetStates() into GetState()

- Libplanet/Net/Swarm.cs
This fixes `expectedResponses` parameter in `GetBlocksAsync`.
It should be 1 if the `hashCount` and `request.ChunkSize` are the same.
> Fix expectedResponses in GetBlocksAsync

- CHANGES.md
- Libplanet/Libplanet.csproj
> Target netstandard2.0 as well as netcoreapp2.2 

- CHANGES.md
- Libplanet/Blockchain/BlockChain.cs
This fixes a bug that accessed all blocks from the genesis block when a swap occurred.
> Access only blocks to related to render

- CHANGES.md
- Libplanet.Stun/Stun/TurnClient.cs
This PR fixes unrecoverable `IOException` during `TurnClient.AcceptRelayedStreamAsync()` by muting it.
> Mute IOException during AcceptRelayedStreamAsync()

- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/Swarm.cs
This PR fixes #528 through propagating reorg from sync node to IBD node. To accomplish that, I've changed `Swarm<T>` as below.
- `Swarm<T>.SyncPreviousBlocksAsync()` became to return nothing, but it mutates `Swarm<T>.BlockChain` directly.
- Branchpoint checking moved from `Swarm<T>.SyncPreviousBlocksAsync()` to `Swarm<T>.FillBlocskAsync()`.
- `Swarm<T>.SyncPreviousBlocksAsync()` became to clean temporary chains before exiting.
> Handle reorg in synchronizing properly

- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/Protocols/IProtocol.cs
- Libplanet/Net/Protocols/Kademlia.cs
- Libplanet/Net/Protocols/KademliaProtocol.cs
- Libplanet/Net/Swarm.cs
If a bucket is full, later peers who requested connection were cached into `Bucket.ReplacementCache`. If a peer is removed from a bucket then cached peer will be added automatically after liveness checking.
Previously, live check had a bug so check procedure repeats infinitely. This patch fixes such bug and added two test cases for the case and fixed one test case.
> Avoid infinite loop when a peer is evicted from routing table and add cached peer

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Net/Swarm.cs
#409 occurs when a task tries to read a block or transaction from `BlockChain<T>.Blocks` or `BlockChain<T>.Transactions` while another task is writing it. This fixes #409 by changing blocks and transactions in the `BlockChain<T>` so that it cannot be accessed without the lock from the outside of the chain.
> Access blocks and transactions of the chain with lock

- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/Swarm.cs
This PR refactor `Swarm<T>`'s constructor as below
- The `linger` parameter is replaced with `waitFor` in `Swarm<T>.StopAsync()`.
- The `dialTimeout` parameter is moved to `Swarm<T>.PreloadAsync()` and `Swarm<T>.StartAsync()`.
And, it also makes some changes as below
- Removed `Swarm<T>._blockChain` using the auto-implemented property.
- Removed `Swarm<T>._protocol` using the auto-implemented property.
> Refactor `Swarm<T>` constructor

- Libplanet/Net/Swarm.cs
This PR fixes `Swarm<T>.AppendBlocksAsync()` by using `BlockChain<T>.Contains(HashDigest<SHA256>)`.
> Fix slow block appending

- CHANGES.md
- Libplanet.Tests/Common/Action/DumbAction.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Net/Swarm.cs
- Menees.Analyzers.Settings.xml
This PR fixes a bug that some actions were not rendered which are included in blocks that were received by `SyncPreviousBlocksAsync()` method by adding `BlockChain<T>.Render()` method.
This also fixes a bug that some actions were rendered multiple times when sync happened.
> Fixed a bug that some actions were not rendered

- CHANGES.md
- Libplanet/Net/Swarm.cs
This PR makes `Swarm<T>.PreloadAsync()` to ignore peers with lower tip than itself.
> Ignore peers with lower tip

- Docs/build.ps1
- Docs/docfx.json
Fixed a problem where documents API could not be built after a7b5c157da399ada711f17ab178bafa0b8fedd2b.
> Fix docs build

- CHANGES.md
- Libplanet/Net/Swarm.cs
This PR aids #453 by adding linger to dealer sockets in `Swarm<T>` to avoid discarding before reading.
> Add linger to dealers

- CHANGES.md
- Libplanet/Net/Protocols/KBucket.cs
- Libplanet/Net/Protocols/KademliaProtocol.cs
Fixed a bug that `KademliaProcol<T>.RefreshTableAsync()` did not remove staled peers. And became to check only least recently used peers in each table to prevent too frequent live checking.
This closes #568.
> Fix behavior of KademliaProtocol<T>.RefreshTableAsync

- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/Protocols/IProtocol.cs
- Libplanet/Net/Protocols/KBucket.cs
- Libplanet/Net/Protocols/KademliaProtocol.cs
- Libplanet/Net/Swarm.cs
This PR consist of several changes.
- `KademliaProtocol<T>.RefreshTableAsync()` and `KademliaProtocol<T>.RebuildConnectionAsync()` now loops in `Swarm<T>` instead of protocol.
- Comparing peer is now done via `.Equals()` method instead of `==`.
- Added a test case for removing stale peer.
> Fixed behavior of KademliaProtocol

- CHANGES.md
- Libplanet/Address.cs
- Libplanet/HashDigest.cs
I made `Address` and `HashDigest` readonly.
> Mark Address and HashDigest as readonly #605

- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/Protocols/IProtocol.cs
- Libplanet/Net/Protocols/KademliaProtocol.cs
- Libplanet/Net/Swarm.cs
This patch separates `KademliaProtocol<T>.CheckReplacementCacheAsync()` from `KademliaProtocol<T>.RemovePeerAsync()`.
> Separate cache checking with removing

- CHANGES.md
- Libplanet.Stun/Stun/TurnClient.cs
#618 seems to be a concurrency issue. To fix #618, I changed `_responses` to `ConcurrentDictionary`
> Change to ConcurrentDictionary

- Libplanet.Benchmarks/Libplanet.Benchmarks.csproj
- Libplanet.Stun.Tests/Libplanet.Stun.Tests.csproj
- Libplanet.Stun/Libplanet.Stun.csproj
- Libplanet.Tests/Libplanet.Tests.csproj
- Libplanet/Libplanet.csproj
> Fix a bug that VS2019 hadn't used .netcore 3.0 even if has MSBuild 16.3+

- Libplanet.Tests/Net/ProtocolTest.cs
- Libplanet/Net/Protocols/KBucket.cs
Peer getter in `KBucket` was throwing `ArgumentOutOfRangeException` when list `_peers` is empty.
> Fixed a bug peer getter in KBucket throws ArgumentOutOfRangeException

- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/Protocols/IProtocol.cs
- Libplanet/Net/Protocols/KademliaProtocol.cs
- Libplanet/Net/Protocols/RoutingTable.cs
- Libplanet/Net/Swarm.cs
This PR contains followings:
- Update routing table when any messages are received. (Excluding replies)
- Do not live check least recently used peer when a peer is updated.
For these changes, some tests were modified.
> Update routing table when non-protocol-messages received

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet/Blockchain/BlockChain.cs
Fixed a bug where `BlockChain<T>.GetNextTxNonce` only returned the same nonce when transactions with an old nonce were staged.
> Fix GetNextTxNonce when transactions with old nonce are staged

- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/Swarm.cs
Fixed a bug that chain is reset when IBD fails.
> SyncPreviousBlocksAsync deletes chains only created during FillBlocksAsync

- CHANGES.md
- Libplanet/Net/InvalidMessageException.cs
- Libplanet/Net/Swarm.cs
I believe this patch resolves #628.
> Remove Trace.Fail in Swarm.ProcessMessageAsync

- Libplanet/KeyStore/ProtectedPrivateKey.cs
I missed the docs of exceptions that `ProtectedPrivateKey.Unprotect()` method may raise in the previous patch #614.
> Missed docs of ProtectedPrivateKey.Unprotect() method

- CHANGES.md
- Libplanet/Store/IStore.cs
- Libplanet/Store/LiteDBStore.cs
Resolving https://github.com/planetarium/libplanet/issues/616 ,
PutBlock method in LiteDBStore.cs checks whether a block exists and if the answer is yes it returns from the method without writing the block (performance upgrades).
> PutBlock method checks whether a block exists. [skip changelog]

- CHANGES.md
- Libplanet/Blockchain/BlockChain.cs
When there is no block state when evaluating an action, it is changed to calculate the state from the beginning to avoid `IncompleteBlockStatesException`.
> Calculate state when evaluating an action if the block state doesn't exist

- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/BlockDownloadState.cs
- Libplanet/Net/Swarm.cs
It was aborted if block-download peer became unavailable though it can download blocks from another peers. so it became to continue block-download with another peers if changed.
This pr might be related with #634.
> Make preload continue with peers when block download failed

- Libplanet/Net/Protocols/KademliaProtocol.cs
Previous PR had made `KademliaProtocol<T>.ReceivePingAsync()` to update routing table after replied. This patch makes all type of protocol message to update routing table after replied. Thus, `KademliaProtocol<T>.ReceivePing()` and `KademliaProtocol<T>.ReceiveFindPeer()` are no more `async`.
> Update routing table after reply done

- CHANGES.md
- Libplanet.Benchmarks/MineBlock.cs
- Libplanet.Benchmarks/Store.cs
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet.Tests/Store/BlockSetTest.cs
- Libplanet.Tests/Store/DefaultStoreFixture.cs
- Libplanet.Tests/Store/DefaultStoreTest.cs
- Libplanet.Tests/Store/StoreExtensionTest.cs
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet.Tests/Store/StoreTrackerTest.cs
- Libplanet.Tests/Store/TransactionSetTest.cs
- Libplanet/Libplanet.csproj
- Libplanet/Store/DefaultStore.cs
This makes blocks and transactions stored as bare files, instead of LiteDB's `FileStorage`.  Therefore, now it cannot be called just `LiteDBStore` anymore, so I renamed it to `DefaultStore`.  As more than a single file are made, it became to take a directory instead of a single file.
Note that this still has only a single LiteDB file yet.  I'm going to make another patch to make each chain ID has its own LiteDB file.
Here are small and not-that-accurate benchmarks:
```
BenchmarkDotNet=v0.11.5, OS=ubuntu 18.04
Intel Xeon CPU E5-2673 v4 2.30GHz, 1 CPU, 2 logical and 2 physical cores
.NET Core SDK=3.0.100
[Host]   : .NET Core 3.0.0 (CoreCLR 4.700.19.46205, CoreFX 4.700.19.46214), 64bit RyuJIT
ShortRun : .NET Core 3.0.0 (CoreCLR 4.700.19.46205, CoreFX 4.700.19.46214), 64bit RyuJIT …
```
> Store blocks and transactions as bare files instead of embeded files in LiteDB

- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/Swarm.cs
- Menees.Analyzers.Settings.xml
This fixed a bug where the canonical chain would be deleted if block download failed.
> Fix the canonical chain is deleted

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet.Tests/Store/StoreTracker.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Net/Swarm.cs
- Libplanet/Store/BaseStore.cs
- Libplanet/Store/DefaultStore.cs
- Libplanet/Store/IStore.cs
- Libplanet/Store/TransactionSet.cs
This PR moves `BlockChain<T>.Contains(TxId)` to `IStore` to separate the global transaction view from `BlockChain<T>`.
> Move BlockChain<T>.Contains(TxId) to IStore

- CHANGES.md
- Libplanet.Benchmarks/BlockChain.cs
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet.Tests/Store/StoreTracker.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Net/Swarm.cs
- Libplanet/Store/BaseStore.cs
- Libplanet/Store/BlockSet.cs
- Libplanet/Store/DefaultStore.cs
- Libplanet/Store/IStore.cs
This PR makes some changes in block related features in `BlockChain<T>` and `IStore` to distinguish `BlockChain<T>.ContainsBlock` and `IStore.ContainsBlock()`.
> Refactor block related features in BlockChain<T> and IStore

- Libplanet.Tests/Store/DefaultStoreFixture.cs
- Libplanet.Tests/Store/StoreFixture.cs
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet/Store/DefaultStore.cs
This PR fixes a bug that `DefaultStore.ContainsBlock()` and `.ContainsTransaction()` hadn't worked properly if the block or transaction hadn't existed in the cache.
I omit the changelog because `DefaultStore` was introduced in 0.8.0 isn't released.
> Fix a bug in DefaultStore.ContainsBlock and ContainsTransaction

- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Net/Swarm.cs
This fixes a bug that the workspace chain is deleted during the `FillBlocksAsync` retry.
This fix revealed that `HandleReorgInSynchronizing` did not work properly. We need to fix the test to work deterministically.
> Fix the workspace chain is deleted during the `FillBlocksAsync` retry

- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/Swarm.cs
- Menees.Analyzers.Settings.xml
This reduces `SwarmTest` code size and test time.
- Add `SwarmTest.CreateSwarm()` method for `SwarmTest` to reduce code size.
- Remove unnecessary delay in `SwarmTest`.
- Make `Swarm<T>.BlockHashRecvTimeout` configurable.
- Reduce `Swarm<T>.StopAsync()` delay for SwarmTest from 1s to 10ms.
> Reduce SwarmTest code size and test time

- Libplanet/Libplanet.csproj
This bumps Planetarium.NetMQ to 4.0.0.260-planetarium and fixes #653.
> Bump Planetarium.NetMQ to 4.0.0.260-planetarium

- CHANGES.md
- Libplanet.Benchmarks/Protocol.cs
- Libplanet.Tests/Net/Protocols/ProtocolTest.cs
- Libplanet.Tests/Net/Protocols/RoutingTableTest.cs
- Libplanet.Tests/Net/Protocols/TestMessage.cs
- Libplanet.Tests/Net/Protocols/TestSwarm.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/ISwarm.cs
- Libplanet/Net/Messages/Message.cs
- Libplanet/Net/Protocols/IProtocol.cs
- Libplanet/Net/Protocols/KBucket.cs
- Libplanet/Net/Protocols/Kademlia.cs
- Libplanet/Net/Protocols/KademliaProtocol.cs
- Libplanet/Net/Protocols/RoutingTable.cs
- Libplanet/Net/Swarm.cs
Previously protocol is tested with swarm, thus it is unsure whether the error is caused by network or protocol. Added `ISwarm` interface and `TestSwarm` which act like network, so cause of error is more clear.
Additionally, bootstrap procedure became faster by preventing peer to re-send `FindNeighbors` request to same peer.
> Implement protocol test and boost bootstrapping by using cache

- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/PreloadBlockDownloadFailEventArgs.cs
- Libplanet/Net/Swarm.cs
When the block downloading fails in `Swarm<T>.PreloadAsync`, `Swarm<T>` became to call `Swarm<T>.PreloadBlockDownloadFailed` event handler. If the event handler doesn't exist, `Swarm<T>` throws `SwarmException`.
> Add PreloadBlockDownloadFailed event handler

- CHANGES.md
- Libplanet.Tests/Store/StoreExtensionTest.cs
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet.Tests/Store/StoreTracker.cs
- Libplanet/Store/BaseStore.cs
- Libplanet/Store/DefaultStore.cs
- Libplanet/Store/IStore.cs
- Libplanet/Store/StoreExtension.cs
This moves `StoreExtension.ListAllStateReferences` to `IStore.ListAllStateReferences` and improve the preformance of the method.
> Improve ListAllStateReferences performance

- CHANGES.md
- Libplanet.Benchmarks/BlockChain.cs
- Libplanet.Benchmarks/MineBlock.cs
- Libplanet.Benchmarks/SwarmBenchmark.cs
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet.Tests/Store/StoreFixture.cs
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet.Tests/TestUtils.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Blocks/InvalidGenesisBlockException.cs
- Libplanet/Net/Swarm.cs
- Libplanet/Store/DefaultStore.cs
- Libplanet/Tx/Transaction.cs
In this pull-request, `BlockChain` became to have *genesis-block*. Also it doesn't allow to create new chain for another chain, having other genesis-block, during fork, because we can't know before append.
> Provide genesis block API

- CHANGES.md
- Libplanet/Net/Swarm.cs
This PR adjusts the logging level(`Debug` → `Verbose`) of some log messages related to state transfer.
> Omit state transfer log on debug

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Store/DefaultStore.cs
Fixed a bug where the state reference would not be updated when forking a chain and adding existed blocks.
> Update state ref even if block state exists

- CHANGES.md
- Libplanet/Net/NetworkStreamProxy.cs
- Libplanet/Net/Swarm.cs
This PR aids some bugs in `Swarm<T>` and loosen timeout value. (see changelog)
> Fix some bugs in Swarm<T>

- CHANGES.md
- Libplanet/Net/Swarm.cs
This PR increases block and state chunk for transmission since our storage implementation can handle this. (block: 500, state: 1,000)
> Increase block / state transmission chunk size

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet/Blockchain/BlockChain.cs
It had returned duplicated tx nonce when `prevNonce` is in staged transactions somehow.
> Fixed a bug in BlockChain<T>.GetNextTxNonce

- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Blockchain/BlockChain.cs
- Menees.Analyzers.Settings.xml
Fixed a bug where mined transactions were staged again.
> Do not stage already mined transactions

- Libplanet.ruleset
- Libplanet/Store/DefaultStore.cs
> remove rule S1066

- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/Swarm.cs
> Configurable NetMQRuntime count

- Libplanet.Stun/Stun/Crc32.cs
- Libplanet.ruleset
Add a 'static' keyword to `Crc32` class
fix #664
> Add a 'static' keyword to the class declaration.

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet/Blockchain/BlockChain.cs
Added the unstage logic when BlockChain.Append() called (from Non-miner's Swarm.AppendBlockAsync() and Miner's BlockChain.MineBlock())
> Fixes #721, Unstage Transaction with same signer's lower nonce.

- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/Swarm.cs
This fixes a bug where the states were empty between the tip of the peer to receive the states and the tip of the downloaded block.
> Calculate state if received state height is shorter than Tip

- CHANGES.md
- Libplanet/Net/Swarm.cs
User of libplanet may want to get information of peers in its routing table.
> Introduce Swarm<T>.Peers property to public

- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Store/StoreTrackLog.cs
- Libplanet.Tests/Store/StoreTracker.cs
- Libplanet.Tests/Store/StoreTrackerTest.cs
`StoreTracker` logged the history which methods called, as triple tuple. So arguments of it couldn't be logged properly.
In this pull-request, it replaces triple tuple type with `StoreTrackLog` type to log all arguments properly.
> Log all arguments in StoreTracker

- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/Protocols/KademliaProtocol.cs
- Libplanet/Net/Swarm.cs
- Menees.Analyzers.Settings.xml
Addresses #570 
Let me know if there is a better way to approach this.  I initially had it setup as having a target address and a specific address but switched it just having a flag being set to say whether they want a list of neighbors to the target or the BoundPeer for the target address.
> Added search for a specific peer given the address

- Libplanet.Tests/Net/Protocols/ProtocolTest.cs
- Libplanet.Tests/Net/Protocols/RoutingTableTest.cs
- Libplanet.Tests/Net/Protocols/TestSwarm.cs
- Libplanet/Net/Protocols/IProtocol.cs
- Libplanet/Net/Protocols/KBucket.cs
- Libplanet/Net/Protocols/KademliaProtocol.cs
- Libplanet/Net/Protocols/RoutingTable.cs
- Libplanet/Net/Swarm.cs
This patch modifies `KademliaProtocol.PeersToBroadcast` prevent message to be re-broadcast to  previous broadcaster peer.
> Prevent redundant message broadcasting

- CHANGES.md
- Libplanet/Net/Protocols/KademliaProtocol.cs
`SwarmException` is thrown when connecting to seed is failed, instead of `TimeoutException`.
> Fix a bug where Swarm<T>.BootstrapAsync had reported invalid timeout

- CHANGES.md
- Libplanet/Net/Swarm.cs
This PR addresses some issues as below
- Fixed a bug where `Swarm<T>.StartAsync()` had thrown `NullReferenceException` when without using NAT and `host` parameter.
- To stabilize request processing, `Swarm<T>._runtimeProcessor` became a long-running task. (it's a dedicated thread.)
- `Swarm<T>` became spawn more `BindingProxies()` to handle TURN request concurrently.
- We should parameterize its count in the future.
> Tune Swarm<T>

- Libplanet.Stun/Stun/Attributes/Attribute.cs
- Libplanet.Stun/Stun/Messages/StunMessage.cs
It documented `enum Libplanet.Stun.Attributes.Attribute.AttributeType` and some part in `class Libplanet.Stun.Messages.StunMessage`. 📖 
It's based on documents below. 
- https://www.iana.org/assignments/stun-parameters/stun-parameters.xhtml
- https://tools.ietf.org/html/rfc5389
- https://tools.ietf.org/html/rfc5766, etc..
If there is some mistake or unnaturalness, please leave your comment or suggestion. 💪
> Document Libplanet.Stun partially

- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Blocks/InvalidGenesisBlockException.cs
- Libplanet/Net/Swarm.cs
- Menees.Analyzers.Settings.xml
There was no action when `Swarm<T>` received blocks of other network (chain). It caused that the node entered to wrong network but it couldn't realize. So I made it to throw exception in the case. In addition, IMO it's better to remove the peer from the peers table but I'm not sure it's okay.
Please leave commnets if you have some opinions about that. 😁
> Throw exception with network based on different genesis

- CHANGES.md
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet/Store/DefaultStore.cs
- Libplanet/Store/StoreExtension.cs
This patch adds the `compress` option to `DefaultStore()` constructor, which is turned off by default, to reduce the size of stored data.  This option does not compress blocks or transactions, but only block states.  The effect is ~31%: 5.1 GB → 1.6 GB.
> Add compress option to DefaultStore

- CHANGES.md
- Libplanet/Crypto/CryptoConfig.cs
- Libplanet/Crypto/DefaultCryptoBackend.cs
- Libplanet/Crypto/ICryptoBackend.cs
- Libplanet/Crypto/PublicKey.cs
This PR adds `CryptoConfig` and` ICryptoBackend` to enable signing and verification library changes.
> Add CryptoBackend

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet/Store/DefaultStore.cs
Originally, when the chain has forked, it was able to execute the genesis block multiple times and it caused invalid states cache because states cache works on only `SetBlockStates()`, `GetBlockStates()`.  So `ForkStateReferences()` became to clear state references cache after the end of the task.
> Fix a bug to have invalid state references cache

- CHANGES.md
- Libplanet.Benchmarks/SwarmBenchmark.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/Swarm.cs
> Distinguish the starting stages of Swarm clearly

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Common/Action/DumbAction.cs
- Libplanet.Tests/Common/Action/ExecuteRecord.cs
- Libplanet.Tests/TestUtils.cs
- Libplanet/Blockchain/BlockChain.cs
This PR fixes a bug where `BlockChain<T>` had evaluated and render actions in the genesis block during forking.
> BlockChain<T>.Fork() should skip eval and render the genesis

- CHANGES.md
- Libplanet.Benchmarks/SwarmBenchmark.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Blocks/BlockHeader.cs
- Libplanet/Net/Messages/BlockHashes.cs
- Libplanet/Net/Messages/BlockHeaderMessage.cs
- Libplanet/Net/Messages/Message.cs
- Libplanet/Net/Swarm.cs
We can ignore a block in different branch with lower index by this patch. See #757.
> Broadcast single block header instead of block hashes

- CHANGES.md
- Libplanet.Tests/Net/Protocols/ProtocolTest.cs
- Libplanet.Tests/Net/Protocols/TestTransport.cs
- Libplanet/Net/Protocols/RoutingTable.cs
If the number of total peers in routing table is less then 10, broadcast messages to all peers.
If not, pick one from each bucket, and pick additional peers which were not selected in first step until total peers count reach 10.
Closes #765.
> Guarantee at least 10 peers to broadcast

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Store/DefaultStoreTest.cs
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet.Tests/Store/StoreTracker.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Net/Swarm.cs
- Libplanet/Store/BaseStore.cs
- Libplanet/Store/DefaultStore.cs
- Libplanet/Store/IStore.cs
- Libplanet/Store/StoreExtension.cs
It's the first step to refer to states by arbitrary `string` keys instead of `Address`es, as I suggested in the issue #368:
> Although it's further than the topic, I've recently started to believe keys of the global state map don't have to be (and shouldn't be) addresses, but arbitrary strings instead, which is more easier to understand to existing programmers who are familiar to Redis or memcached.
I am going to send more patches to make state keys arbitrary `string`s instead of `Address`es in the whole of Libplanet.
> Make IStore to represent state keys as string (was Address)

- Libplanet.Tests/Store/StoreTest.cs
- Libplanet/Store/DefaultStore.cs
It fixes a bug where `DefaultStore.ForkStateReferences()` forked state references except the genesis block.
> Fork state references included the genesis block

- CHANGES.md
- Libplanet.Tests/Net/Protocols/ProtocolTest.cs
- Libplanet.Tests/Net/Protocols/RoutingTableTest.cs
- Libplanet/Net/NetMQTransport.cs
- Libplanet/Net/PeerState.cs
- Libplanet/Net/Protocols/KBucket.cs
- Libplanet/Net/Protocols/KademliaProtocol.cs
- Libplanet/Net/Protocols/RoutingTable.cs
- Libplanet/Net/Swarm.cs
Routing table now stores peers with its last updated time, last checked (ping/pong) time and its latency.
> Enrich routing table

- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Blockchain/BlockChain.cs
- Menees.Analyzers.Settings.xml
It fixes a bug where transactions included in unrendered blocks, could not be included in a block when reorg happened. It's based on network problem which they were not propagated sufficiently, so IMO it will be better to see this PR while looking message propagation after #767 PR was merged.
> Stage transactions not included in swapped chain

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Blockchain/BlockLocatorTest.cs
- Libplanet.Tests/Net/BlockCompletionTest.cs
- Libplanet.Tests/Net/Messages/BlockHashesTest.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Blockchain/BlockLocator.cs
- Libplanet/Net/BlockCompletion.cs
- Libplanet/Net/BlockDownloadState.cs
- Libplanet/Net/BlockHashDownloadState.cs
- Libplanet/Net/Messages/BlockHashes.cs
- Libplanet/Net/Messages/Message.cs
- Libplanet/Net/StateDownloadState.cs
- Libplanet/Net/Swarm.cs
- Menees.Analyzers.Settings.xml
This patch makes IDL parallel by requesting chunks of blocks to multiple peers.  As complexity of IDL logic grows up, I added a separated class named `BlockCompletion<T>` which has only a pure logic of dealing with block demands and completion without actual I/Os, and made `Swarm<T>.PreloadAsync()` method to use it.
> Preload blocks from multiple peers at a time

- Libplanet/FixedSizedQueue.cs
- Libplanet/Net/NetMQTransport.cs
- Libplanet/Net/Swarm.cs
This patch introduces message history queue for `NetMQTransport`. Since all related changes are internal, skipped changelog.
> Introduce message history for testing

- CHANGES.md
- Libplanet.Tests/Store/StoreTracker.cs
- Libplanet/Blocks/Block.cs
- Libplanet/Blocks/BlockDigest.cs
- Libplanet/Blocks/BlockHeader.cs
- Libplanet/Store/BaseStore.cs
- Libplanet/Store/DefaultStore.cs
- Libplanet/Store/IStore.cs
This makes `BlockHeader` and `BlockDigest` class public to implement `RocksDBStore`.
> Make BlockHeader and BlockDigest public

- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/NetMQTransport.cs
- Libplanet/Net/Swarm.cs
- Menees.Analyzers.Settings.xml
This patch makes swarm to poll blocks and transactions from other peers. I guess it can be replaced with #707 for the case of blocks.
Todo:
> Poll blocks and txs

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet/Blockchain/BlockChain.cs
There was a problem that `BlockChain.MineBlock()` method couldn't mine valid block when there was transactions having lower nonce than expected nonce. So, in this PR, `BlockChain.MineBlock()` method became to ignore the transactions and to mine.
> Mine block without txs having lower nonce

- .azure-pipelines/dotnet-core.yml
- .github/workflows/benchmarks.yml
- .github/workflows/main.yml
- CONTRIBUTING.md
- Libplanet.Stun/Libplanet.Stun.csproj
- Libplanet/Libplanet.csproj
- README.md
- azure-pipelines.yml
Introduce C# 8.0 so that we use native async streams and null reference checks (#468).  However, in this patch we just upgrade only *Libplanet* and *Libplanet.Stun* projects to use C# 8.0, without such new features.  `<Nullable>enable</Nullable>` is not turned on yet, and *AsyncEnumerator* package is still there (see also the `TODO` comment in the *Libplanet.csproj*).  *Libplanet.Tests* and *Libplanet.Stun.Tests* projects are still stuck with C# 7.1 as Unity is still so too.  This patch is a smallest change to keep the build barely unbroken.
So this also require @planetarium/libplanet you folks to upgrade .NET Core SDK to 3.1+ and Mono (MDK) to 6.4+.
> Upgrade C# to 8.0 with maintaining .NET Standard 2.0

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Blockchain/BlockLocatorTest.cs
- Libplanet.Tests/Libplanet.Tests.csproj
- Libplanet.Tests/LoggerExtensions.cs
- Libplanet.Tests/Net/BlockCompletionTest.cs
- Libplanet.Tests/Net/Messages/BlockHashesTest.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Blockchain/BlockLocator.cs
- Libplanet/Libplanet.csproj
- Libplanet/Net/ActionExecutionState.cs
- Libplanet/Net/BlockCompletion.cs
- Libplanet/Net/BlockDownloadState.cs
- Libplanet/Net/BlockHashDownloadState.cs
- Libplanet/Net/BlockVerificationState.cs
- Libplanet/Net/Messages/BlockHashes.cs
- Libplanet/Net/Messages/Message.cs
- Libplanet/Net/NetMQTransport.cs
- Libplanet/Net/PreloadState.cs
- Libplanet/Net/StateDownloadState.cs
- Libplanet/Net/Swarm.cs
- Menees.Analyzers.Settings.xml
The first commit is a commit squashed from the PR #707, except for some adjustments to resolve conflicts and make the build to pass.
This also introduces C# 8's new [async streams syntax][1] to replace Dasync's *[AsyncEnumerator]* package with it.  Although this removed the dependency on *AsyncEnumerator* package and introduce the new syntax into *Libplanet* project, note *Libplanet.Tests* project still uses C# 7.2 and the third-party package, which is intended.
Instead of *AsyncEnumerator*, *Libplanet* project has a new dependency on the *[System.Linq.Async]* package, which provides several LINQ extension methods laid on `IAsyncEnumerator<T>`.
The key changes over the reverted PR #707 in this patch are of course fixing #707's bugs and more `PreloadState`s.  See also each commit message. …
> Restore BlockCompletion<T> (#707) and more

- .azure-pipelines/mono.yml
- CONTRIBUTING.md
- Libplanet.Benchmarks/Libplanet.Benchmarks.csproj
- Libplanet.RocksDBStore.Tests/Libplanet.RocksDBStore.Tests.csproj
- Libplanet.RocksDBStore.Tests/RocksDBStoreFixture.cs
- Libplanet.RocksDBStore.Tests/RocksDBStoreTest.cs
- Libplanet.RocksDBStore/Libplanet.RocksDBStore.csproj
- Libplanet.Stun.Tests/Libplanet.Stun.Tests.csproj
- Libplanet.sln
This restores `Libplanet.RocksDBStore.Tests` removed in 63b1c457b44bf26c5fd54c2acaf43a0f56bbd8ff.
Currently, the tests only run on .NET Core.
> Restore Libplanet.RocksDBStore.Tests

- CHANGES.md
- Libplanet.RocksDBStore/RocksDBStore.cs
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet.Tests/Store/StoreTracker.cs
- Libplanet/Store/BaseStore.cs
- Libplanet/Store/DefaultStore.cs
- Libplanet/Store/IStore.cs
This removes `IStore.DeleteIndex()` method.
> Remove IStore.DeleteIndex method

- CHANGES.md
- Libplanet.RocksDBStore.Tests/RocksDBStoreTest.cs
- Libplanet.RocksDBStore/RocksDBStore.cs
- Libplanet.Stun.Tests/Stun/Attributes/StunAddressExtensionsTest.cs
- Libplanet.Stun/Stun/Attributes/StunAddressExtensions.cs
- Libplanet.Stun/Stun/BytesConvertExtensions.cs
- Libplanet.Tests/AddressExtensionsTest.cs
- Libplanet.Tests/ByteArrayExtensionsTest.cs
- Libplanet.Tests/ByteUtilTest.cs
- Libplanet.Tests/HashSetExtensions.cs
- Libplanet.Tests/Store/DefaultStoreTest.cs
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet/Action/RandomExtensions.cs
- Libplanet/Address.cs
- Libplanet/AddressExtensions.cs
- Libplanet/ByteArrayExtensions.cs
- Libplanet/ByteUtil.cs
- Libplanet/HashDigest.cs
- Libplanet/Net/NetMQFrameExtensions.cs
- Libplanet/Net/NetMQSocketExtensions.cs
- Libplanet/Serialization/SerializationInfoExtensions.cs
- Libplanet/Store/StoreExtensions.cs
This replaces to use RocksDB for Tx Nonce and Canonical Chain ID in `Libplanet.RocksDBStore`. The remainder of using LiteDB will be replaced in the next PRs.
> Replace to use RocksDB for Tx Nonce and Canonical Chain ID 

- Libplanet.RocksDBStore/RocksDBStore.cs
This replaces to use RocksDB for chain indexes in Libplanet.RocksDBStore.
> Replace to use RocksDB for Chain Index

- .github/bin/dist-github-release.sh
- .github/bin/dist-nuget.sh
- .github/bin/dist-pack.sh
- .github/workflows/main.yml
- hooks/validate-release
- Fixed a bug that tag pushes hadn't triggered the `build` job on GitHub Actions. (GitHub Actions recently changed `on:`'s behavior.)
- Fixed a bug that *Libplanet.RocksDBStore* package hadn't properly versioned for stable releases.
- Fixed a bug that *Libplanet.RocksDBStore.\*.nupkg* hadn't uploaded to GitHub releases.
- Fixed an XPath bug on pre-commit hook made due to XML namespaces.
> Fix release script bugs

- .github/bin/bundle.sh
- .github/bin/constants.sh
- .github/bin/dist-github-release.sh
- .github/bin/dist-nuget.sh
- .github/bin/dist-pack.sh
- .github/bin/github-release.sh
- .github/workflows/main.yml
For development environments that cannot leverage NuGet like Unity, distribute all-in-one bundles that include all referenced assemblies including Libplanet in itself.
Bundles are an archive file which consists of all required assemblies (*\*.dll*) for a target framework.  Currently 4 target frameworks are supported:
<https://github.com/planetarium/libplanet/blob/4db8cd603325f75d57445a417d568cb409f07382/.github/workflows/main.yml#L107>
There are 2 types of bundle packages: *Libplanet* & *Libplanet.RocksDBStore*.  A *Libplanet.RocksDBStore* bundle consists of all assemblies in a *Libplanet* bundle with RocksDB-related assemblies.
For every push (and pull request), 2 packages × 4 target frameworks = 8 bundles are made in GitHub Actions, and these are uploaded as a single artifact named …
> All-in-one bundles

- .github/bin/dist-nuget.sh
This patch fixes a bug, where nupkg is not submitted to NuGet Gallery, made by my previous PR #809.  In Bash, `$@` does not contain `$0` from the outset, so `shift` is unnecessary.
> Fix a bug where nupkg is not submitted to NuGet

- .azure-pipelines/windows-net471.yml
This fixes an issue where the test ran twice on Windows .NET Framework.
> Run only once per test

- Libplanet.RocksDBStore/RocksDBStore.cs
- Libplanet.RocksDBStore/RocksDBStoreBitConverter.cs
- Libplanet.Tests/Store/StoreTest.cs
This replaces to use RocksDB for state references in Libplanet.RocksDBStore.
> Replace State Reference to use RocksDB

- Libplanet.RocksDBStore/RocksDBStore.cs
This replaces to use RocksDB for staged transactions in Libplanet.RocksDBStore and split tx and state from block database.
> Replace StagedTx to use RocksDB

- CHANGES.md
- Libplanet.RocksDBStore/RocksDBStore.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet.Tests/Store/StoreTracker.cs
- Libplanet/Net/Swarm.cs
- Libplanet/Store/BaseStore.cs
- Libplanet/Store/DefaultStore.cs
- Libplanet/Store/IStore.cs
Since trusted peers became not to transfer *recent* states, receiver with trusted validators prunes states after preloading finished.
> Prune state after sync state from trusted peers

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Net/Swarm.cs
This PR fixes a bug where `Swarm<T>` had stopped if received invalid tx from the network.
To fix it, I changed some API in `BlockChain<T>`.
- `StageTransactions()` → `StageTransaction()`
- `UnstageTransactions()` → `UnstageTransaction()`
> Fix `Swarm<T>` halting 

- .editorconfig
This PR forces 2 spaces indent on YAML config file. Previously it forces 4 spaces for indent and 8 spaces for tab while using VS Code. 
Since there is no requirement for indent size in YAML spec—see [SO](https://stackoverflow.com/a/42248984)—, but I think it might be better to specify an indent size in a`.editorconfig`.
> Update .editorconfig for YAML config file

- Libplanet.RocksDBStore/RocksDBStore.cs
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet/Store/DefaultStore.cs
This fixes `RocksDBStore.ForkBlockIndex()` method and adds `StoreTest.ForkBlockIndex`.
> Fix RocksDBStore ForkBlockIndex

- CHANGES.md
- Libplanet.Benchmarks/MineBlock.cs
- Libplanet.Tests/Action/AccountStateDeltaImplTest.cs
- Libplanet.Tests/Action/ActionEvaluationTest.cs
- Libplanet.Tests/Action/PolymorphicActionTest.cs
- Libplanet.Tests/AddressExtensionsTest.cs
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Blocks/BlockTest.cs
- Libplanet.Tests/KeyStore/ProtectedPrivateKeyTest.cs
- Libplanet.Tests/Net/AppProtocolVersionTest.cs
- Libplanet.Tests/Net/Messages/RecentStatesTest.cs
- Libplanet.Tests/Net/Protocols/TestTransport.cs
- Libplanet.Tests/Net/SwarmTest.AppProtocolVersion.cs
- Libplanet.Tests/Net/SwarmTest.Fixtures.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet.Tests/Store/DefaultStoreTest.cs
- Libplanet.Tests/Tx/TransactionTest.cs
- Libplanet/AddressExtensions.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/KeyStore/ProtectedPrivateKey.cs
- Libplanet/Net/AppProtocolVersion.cs
- Libplanet/Net/NetMQTransport.cs
- Libplanet/Net/Swarm.cs
In order to make `AppProtocolVersion` values easy to copy and paste, the concept of tokens is added to `AppProtocolVersion`.  Tokens consist of ASCII characters so that they can be pasted without escaping into command arguments or strings in shells and JSON/YAML etc.
As a bonus, I added the `PrivateKey.ToAddress()` extension method as well.  As this change affected many files, I recommend you to review each single commit.
> AppProtocolVersion tokens & PrivateKey.ToAddress()

- Libplanet/Net/BlockCompletion.cs
This changes some expensive logs to be written only when the level is enabled.
> Write log only when the level is enabled

- Libplanet.Tests/Net/AppProtocolVersionTest.cs
- Libplanet.Tests/Net/PeerTest.cs
- Libplanet/Net/AppProtocolVersion.cs
- Libplanet/Net/Peer.cs
This patch makes `default(AppProtocolVersion)` to have an empty `Signature` (instead of `default(ImmutableArray<byte>)` so that `Peer` values can be serialized with `default(AppProtocolVersion)`.
> Make default(AppProtocolVersion) to have an empty Signature

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Blockchain/NullPolicy.cs
- Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Blockchain/Policies/BlockPolicy.cs
- Libplanet/Blockchain/Policies/IBlockPolicy.cs
- Libplanet/Net/Swarm.cs
- Libplanet/Tx/InvalidTxByBlockPolicyException.cs
- Libplanet/Tx/TxViolatingBlockPolicyException.cs
This adds `IBlockPolicy.IsValidTransaction` method which is a method to determine if a transaction is valid.
> Add IBlockPolicy.IsTransactionValid

- .github/workflows/main.yml
This PR changes the scheduled jobs and publishing artifact to be allowed only upstream. It was motivated by nightly builds on my forked repo that trigger email notifications for failed runs.
> Do not run upstream specific workfolows in forks

- CHANGES.md
- Libplanet.Tests/KeyStore/KeyStoreTest.cs
- Libplanet.Tests/KeyStore/Web3KeyStoreTest.cs
- Libplanet/KeyStore/IKeyStore.cs
- Libplanet/KeyStore/KeyStoreException.cs
- Libplanet/KeyStore/NoKeyException.cs
- Libplanet/KeyStore/Web3KeyStore.cs
This patch finally implements the complete [Web3 Secret Storage][1].
I also experimented with C# 8's [nullable reference types][2].  We could gradually adopt it by enabling [nullable context][3] per file (instead of the whole project, i.e., #458).
[1]: https://github.com/ethereum/wiki/wiki/Web3-Secret-Storage-Definition
[2]: https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references
[3]: https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references#nullable-contexts
> IKeyStore & Web3KeyStore

- Libplanet.RocksDBStore/Libplanet.RocksDBStore.csproj
This fixes an issue where an `ExecutionEngineException: String conversion error` occurred when `RocksDbException` occurred.
> Bump Planetarium.RocksDbSharp to 6.2.2.3-planetarium

- CHANGES.md
- Libplanet/Store/BlockSet.cs
- Libplanet/Store/TransactionSet.cs
Hi.
This PR should be resolve #806
> Remove Trace.Assert() in Blockset and TransactionSet

- CHANGES.md
- Libplanet/Net/NetMQSocketExtensions.cs
- Libplanet/Net/Swarm.cs
This PR improves the performance of `Swarm<T>` by preventing unnecessary task creation.
> Improve performance of `Swarm<T>`

- .github/bin/constants.sh
- .github/bin/dist-github-release.sh
- .github/bin/dist-pack.sh
- .github/bin/dist-version.ps1
- CHANGES.md
- CONTRIBUTING.md
- Docs/CONTRIBUTING.md
- Docs/docfx.json
- Docs/toc.yml
- Libplanet.RocksDBStore/Libplanet.RocksDBStore.csproj
- Libplanet.Stun/Libplanet.Stun.csproj
- Libplanet.Tools/Apv.cs
- Libplanet.Tools/Key.cs
- Libplanet.Tools/Keys.cs
- Libplanet.Tools/Libplanet.Tools.csproj
- Libplanet.Tools/Program.cs
- Libplanet.Tools/README.md
- Libplanet.Tools/Utils.cs
- Libplanet.sln
- Libplanet/Libplanet.csproj
- hooks/check-projects
- hooks/pre-commit
In order to sign a new `AppProtocolVersion` from command-line/automated process, I added a `planet` command.  See also *Libplanet.Tools/README.md* for details.
```bash
Usage: Libplanet.Tools [command]
Usage: Libplanet.Tools [--help] [--version]
Libplanet.Tools
Commands:
apv    App protocol version utilities.
key    Manage private keys.
Options:
-h, --help    Show help message
--version     Show version
```
A sample session to sign a new `AppProtocolVersion`:
```bash
planet key create
planet apv sign 39eaaed4-d03a-40d9-b7be-175b2ba2c1e5 123 \
-e macOSBinaryUrl=... \
-e windowsBinaryUrl=...
```
Give a try in advance by downloading the following builds:
- [planet-0.9.0-dev.20200401104502-linux-x64.tar.xz](https://send.firefox.com/download/c2448eed62e282c0/#TjCESvQdQQsj79dXIOxJpw)
- …
> CLI tools (planet command)

- CHANGES.md
- Libplanet.Tests/Net/BlockCompletionTest.cs
- Libplanet/Net/BlockCompletion.cs
This PR addresses two problems of `Swarm<T>.Preload()`.
- Fixed a bug where `Swarm<T>` hadn't reported preload states correctly.
- Fixed a `Swarm<T>.PreloadAsync()` method's bug that it had hung forever when a block fetch failed due to an unexpected error.
> Fix Swarm<T>.Preload()

- CHANGES.md
- Libplanet.Tests/KeyStore/Kdfs/KdfTest.cs
- Libplanet.Tests/KeyStore/ProtectedPrivateKeyTest.cs
- Libplanet/KeyStore/Kdfs/Pbkdf2.cs
- Libplanet/Libplanet.csproj
See also the changelog.  Also upgraded Bouncy Castle to the latest version.
> Fix unexpected error on non-ASCII passphrases

- CHANGES.md
- Libplanet/Net/Swarm.cs
This PR increases the performance of `Swarm<T>.PreloadAsync()` by parallelizing `DialToExistingPeers()`.
> Parallelizing Swarm<T>.PreloadAsync()

- CHANGES.md
- Libplanet/Net/NetMQTransport.cs
This PR improves response throughput of `Swarm<T>` by arranging the timing of `.ToNetMQMessage()`. Moving it to the outside of `DoReply()` can help with its concurrency.
> Improve reply throughput of `Swarm<T>`

- CHANGES.md
- Libplanet.Tests/Net/Messages/RecentStatesTest.cs
- Libplanet/Net/Messages/Message.cs
- Libplanet/Net/Messages/RecentStates.cs
This PR modifies `RecentStates` message to compress its states to improve network latency.
> Compressed RecentStates message

- .github/bin/dist-pack.sh
- .github/workflows/main.yml
There had been a bug in *dist-pack.sh* that made *Libplanet.Tools.\*.nupkg* lacks a `<packageType name="DotnetTool" />` metadata.  This bug had been happened because the second-pass build of the *Libplanet.Tools* project for making a single-file executables had overwritten the *Libplanet.Tools.nuspec* file.  I fixed it by reversing the order of two build passes each other.
There had been a bug in *Docs/publish.sh* that every push to the master branch updates the root *index.html*, while the intention was to update it only for a new tag.  The bug was due to the empty output of `git tag -l`.  To fix this, I added an explicit instruction to fetch tags into the `docs` job of the *main.yml* workflow.
> Fix two bugs from GitHub Actions scripts

- CHANGES.md
- Libplanet/Net/NetMQTransport.cs
This PR divides `_poller` by `_routerPoller` and `_broadcastPoller` to avoid unexpected blocking and improve throughput.
> Separate _poller in NetMQTransport

- CHANGES.md
- Libplanet/Net/NetMQTransport.cs
This PR addresses #847 by ignoring `InvalidOperationException` during `tcs.SetResult()` and `tcs.SetException()`.
> Avoid overwrapped SetResult and SetException

- CHANGES.md
- Libplanet.Tests/Action/PolymorphicActionTest.cs
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Common/Action/BaseAction.cs
- Libplanet.Tests/Common/Action/DumbAction.cs
- Libplanet.Tests/Common/Action/MinerReward.cs
- Libplanet.Tests/Common/Action/ThrowException.cs
- Libplanet.Tests/Net/SwarmTest.Preload.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet.Tests/Tx/TransactionTest.cs
- Libplanet/Action/ActionEvaluation.cs
- Libplanet/Action/IAction.cs
- Libplanet/Action/PolymorphicAction.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Store/StoreExtensions.cs
- Libplanet/Tx/Transaction.cs
This PR addresses #860. specifically, it has the following changes.
- Added `IAction.RenderError()` and `IAction.UnrenderError()` to report an exception raised by `IAction.Execute()` to game developer.
- Added `ActionEvalution.Exception` to record whether an exception occurred while executing an action.
- `ActionEvalution.EvaluateActionsGradually()` (and related methods) no longer throw `UnexpectedlyTerminatedActionException`. instead, they record it to `ActionEvaluation`s.
> Expose exception in IAction.Execute()

- Libplanet.Tests/Blocks/BlockTest.cs
This PR resolve #754.
In the original issue, it wanted to make the test case random so that all cases could be examined.
But rather because it would harm the deterministic action, we made additional PR for the empty case.
- Add cases _'if a transaction has empty action list'_
> Add empty action test case

- CHANGES.md
- Libplanet/Net/NetMQTransport.cs
- Libplanet/Net/Swarm.cs
This PR addresses #871. I've benchmarked via Libplanet.Benchmark. (it tests a scenario using 10 skewed `Swarm<T>`s.) 
```
|                    Method |    Mean |    Error |   StdDev |  Median |
|-------------------------- |--------:|---------:|---------:|--------:|
|            BroadcastBlock | 1.202 s | 0.0341 s | 0.1005 s | 1.198 s |
| BroadcastBlockWithoutFill | 1.110 s | 0.0277 s | 0.0816 s | 1.131 s |
```
```
|                    Method |     Mean |    Error |   StdDev |
|-------------------------- |---------:|---------:|---------:|
|            BroadcastBlock | 820.2 ms | 20.15 ms | 57.18 ms |
| BroadcastBlockWithoutFill | 652.8 ms | 20.38 ms | 58.81 ms |
```
> Improve block propagation performance

- CHANGES.md
- Libplanet.Tests/ActionProgress.cs
- Libplanet.Tests/Net/SwarmTest.Preload.cs
- Libplanet/Net/Swarm.cs
This fixes the bug #880.
- Make `Swarm<T>.GetDemandBlockHashes()` method `internal` (was `private`) and add unit tests on it.
- Prevent `Swarm<T>.GetDemandBlockHashes()` method from being hanged when a peer's chain is during reorg.
> Prevent Swarm<T>.GetDemandBlockHashes() from being hanged when a peer's chain is during reorg

- .github/bin/dist-nuget.sh
Made the condition to determine whether to submit *.nupkg* files to NuGet Gallery or skip easier to understand, and fixed the wrong case (*\*-maintenance*, not *maintenance-\**).  Also added the case for *9c-\** branches.
The following script a minimum test code for the new bash conditional:
```bash
#!/bin/bash
for GITHUB_REPOSITORY in {planetarium/libplanet,dahlia/libplanet}; do
for GITHUB_REF in {refs/heads/master,refs/heads/0.9-maintenance,refs/heads/9c-beta,refs/tags/0.9.2,refs/heads/foobar}; do
label="GITHUB_REPOSITORY=$GITHUB_REPOSITORY GITHUB_REF=$GITHUB_REF"
if [ "$GITHUB_REPOSITORY" = "planetarium/libplanet" ] && [[ \
"$GITHUB_REF" = refs/tags/* || \
"$GITHUB_REF" = refs/heads/master || \
"$GITHUB_REF" = refs/heads/*-maintenance || \
"$GITHUB_REF" = refs/heads/9c-* \
]]; then …
```
> Fix NuGet distribution condition

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Net/Swarm.cs
This adds `allowRender` option to `BlockChain<T>`.
> Add render option to BlockChain<T>() constructor

- CHANGES.md
- Libplanet.RocksDBStore/RocksDBStore.cs
- Libplanet.Tests/Store/StoreTest.cs
According to `IStore.DeleteChainId()` method's XML comment:
> If there is no such `chainId` it does nothing.
Howver, `RocksDBStore.DeleteChainId()` hadn't been like that.  This fixed the bug.
> Make RocksDBStore.DeleteChainId() idempotent

- Libplanet/Net/NetMQTransport.cs
This PR addresses broadcast stopping when the remote peer had been gone. it's caused by trying to retry even for a socket that has already been disconnected. so I've fixed it to close immediately when a timeout occurs.
- I omitted the changelog because #890 that made this bug is not released yet.
- I guess we should apply this patch to the current CBT cluster. so I've targeted this PR to `9c-beta` instead of `master`.
> Fix a infinite timeout when remote peer had been gone

- CHANGES.md
- Libplanet.Tests/Blocks/BlockHeaderTest.cs
- Libplanet/Blocks/Block.cs
- Libplanet/Blocks/BlockHeader.cs
- Libplanet/Net/Swarm.cs
- Libplanet/Store/BaseStore.cs
This PR fixes `Swarm<T>` to ignore invalid block header immediately.
> Ignore invalid header immediately

- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.Preload.cs
- Libplanet/Net/Swarm.cs
This PR fixes `Swarm<T>.Preload` to clean up temporary chains only.
> Clean up only temporary chains only

- CHANGES.md
- Libplanet.Tests/Action/AccountStateDeltaExtensions.cs
- Libplanet.Tests/Action/AccountStateDeltaImplTest.cs
- Libplanet.Tests/Action/ActionContextTest.cs
- Libplanet.Tests/Action/ActionEvaluationExtensions.cs
- Libplanet.Tests/Action/ActionEvaluationTest.cs
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Blocks/BlockTest.cs
- Libplanet.Tests/Common/Action/DumbAction.cs
- Libplanet.Tests/CurrencyTest.cs
- Libplanet.Tests/Libplanet.Tests.csproj
- Libplanet.Tests/Menees.Analyzers.Settings.xml
- Libplanet.Tests/Tx/TransactionTest.cs
- Libplanet/Action/AccountBalanceGetter.cs
- Libplanet/Action/AccountStateDeltaImpl.cs
- Libplanet/Action/AccountStateGetter.cs
- Libplanet/Action/ActionEvaluation.cs
- Libplanet/Action/CurrencyPermissionException.cs
- Libplanet/Action/IAccountStateDelta.cs
- Libplanet/Action/InsufficientBalanceException.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Blocks/Block.cs
- Libplanet/Currency.cs
- Libplanet/Tx/Transaction.cs
This implements fungible asset states APIs, the first half of the proposal #861.  As non-fungible asset states APIs will be orthogonal to this, I am going to send a separated pull request for that later.
The usage can be found in the proposal issue #861 (please read comments I left as well).
> Fungible asset states

- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.Preload.cs
- Libplanet/Net/Swarm.cs
This fixes a bug that did not properly receive block hashes after the chain has reorged.
> Demand block hashes from branch point

- CHANGES.md
- Libplanet.Stun/Stun/Messages/AllocateErrorResponse.cs
- Libplanet.Stun/Stun/Messages/StunMessage.cs
- Libplanet.Stun/Stun/TurnClient.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/NetMQTransport.cs
This fixes a bug where `Swarm<T>` had terminated when disconnected from TURN. The flaky `StopGracefullyWhileStarting` test was also fixed.
> Reconnect to TURN when the connection is lost

- CHANGES.md
- Libplanet.Tests/Common/Action/DumbAction.cs
- Libplanet.Tests/Net/Messages/RecentStatesTest.cs
- Libplanet.Tests/Net/SwarmTest.Preload.cs
- Libplanet/Blocks/BlockDigest.cs
- Libplanet/Blocks/BlockHeader.cs
- Libplanet/Blocks/RawBlock.cs
- Libplanet/Libplanet.csproj
- Libplanet/Net/Messages/Message.cs
- Libplanet/Net/Messages/RecentStates.cs
- Libplanet/Net/Swarm.cs
- Libplanet/Tx/RawTransaction.cs
This changes `StateReference` key to string to fix a bug in which pre-computed state delivery had failed when a state key is not an `Address` when preloading.
> Change StateReference key to string

- CHANGES.md
- Libplanet.Tests/Action/UnexpectedlyTerminatedActionExceptionTest.cs
- Libplanet/Action/UnexpectedlyTerminatedActionException.cs
This PR fixes a problem that `UnexpectedlyTerminatedActionException` hadn't been compatible with .NET serialization.
> Fix serialization bug on UnexpectedlyTerminatedActionException

- CHANGES.md
- Libplanet.Stun/Stun/TurnClient.cs
This PR addresses that `TurnClient.SendMessageAsync()` hadn't been applied cancellation token as expected.
> Fixed TurnClient's cancellation bug

- Libplanet.RocksDBStore/RocksDBStore.cs
- Libplanet/Net/Swarm.cs
This fixes an issue that attempted to delete the chain multiple times. Also, in order to facilitate debugging, the deletion log of  `_chainDb` and the `_stateRefDb`  are separated.
> Fix for deleting chain ID

- CHANGES.md
- Libplanet.Tests/Net/Protocols/TestTransport.cs
- Libplanet.Tests/Net/SwarmTest.Preload.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/BlockHashDemand.cs
- Libplanet/Net/Messages/Message.cs
- Libplanet/Net/Messages/Pong.cs
- Libplanet/Net/Swarm.cs
Includes:
- Select the peer with the most difficult chain to preload.
- Demand only more difficult chain than current.
Closes #459.
> Promoting the most difficult chain as canonical chain

- CHANGES.md
- Libplanet.Tests/Blocks/BlockHeaderTest.cs
- Libplanet.Tests/Blocks/BlockTest.cs
- Libplanet/Blocks/BlockHeader.cs
This fixes `BlockHeader.TimestampThreshold` to 15s to mitigate #922. It should be changed later to be the same as `BlockPolicy.BlockInterval`.
> Fix TimestampThreshold to 15s

- CHANGES.md
- Libplanet/Net/Swarm.cs
- Libplanet/Net/SwarmOptions.cs
Separate timeouts in `Swarm<T>` to `SwarmOptions` to be configurable.
> Separate timeouts in Swarm<T> to SwarmOptions

- .github/bin/constants.sh
- .github/bin/dist-npm.sh
- .github/bin/dist-nuget.sh
- .github/bin/dist-pack.sh
- .github/workflows/main.yml
- CHANGES.md
- Libplanet.Tools/.gitignore
- Libplanet.Tools/README.md
- Libplanet.Tools/bin/planet
- Libplanet.Tools/download.js
- Libplanet.Tools/install.js
- Libplanet.Tools/package.json
To make Libplanet CLI tools easily installable without .NET Core SDK, I packaged it using `npm`: [@planetarium/cli](https://www.npmjs.com/package/@planetarium/cli).  The `npm` package in itself actually does not contain any executable binary/code for CLI tools, but includes downloader/installer for the `planet` command.  FYI [Elm's npm installer][1] inspired this approach.
Here's a demo session:
[![asciicast](https://asciinema.org/a/347262.svg)](https://asciinema.org/a/347262)
[1]: https://github.com/elm/compiler/tree/master/installers/npm
> Make CLI tools installable through npm

- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.Preload.cs
- Libplanet/Net/Messages/ChainStatus.cs
- Libplanet/Net/Messages/GetChainStatus.cs
- Libplanet/Net/Messages/Message.cs
- Libplanet/Net/Swarm.cs
`Ping` and `Pong` messages were used in both health checks and chain status checking. Thus, added new messages `GetChainStatus` and `ChainStatus` for the case of chain status checking. Now `Ping` and `Pong` used in health checks only.
Closes #920.
> Separate Ping/Pong message

- CHANGES.md
- Libplanet/Crypto/CryptoConfig.cs
- Libplanet/Crypto/DefaultCryptoBackend.cs
- Libplanet/Crypto/ICryptoBackend.cs
- Libplanet/Crypto/PrivateKey.cs
This adds `ICryptoBackend.Sign()` method to enable signing library changes. Also, this modifies `PrivateKey` to store `PublicKey` instead of generating it every time.
> Add ICryptoBackend.Sign

- CHANGES.md
- Libplanet/Blockchain/BlockChain.cs
This PR adjust _rwlock's scope in BlockChain<T>.GetRawState() to prevent write access to block states during execution.
> Adjust read-write lock for BlockChain<T>.GetRawState()

- CHANGES.md
- Libplanet/Net/Protocols/KademliaProtocol.cs
This PR changes to not throw an exception in `Swarm.BootstrapAsync()` when connecting to all neighbors fails.
> Don't throw exception when connecting to all neighbors fails

- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/PeerChainState.cs
- Libplanet/Net/PeerChainStatus.cs
- Libplanet/Net/Swarm.cs
This adds `PeerChainStatus` struct and `Swarm<T>.GetPeerChainStatus()` method to check the chain status of the connected peers.
> Add PeerChainState

- CHANGES.md
- Libplanet.Tests/Action/InsufficientBalanceExceptionTest.cs
- Libplanet.Tests/Action/UnexpectedlyTerminatedActionExceptionTest.cs
- Libplanet.Tests/CurrencyTest.cs
- Libplanet/Action/InsufficientBalanceException.cs
- Libplanet/Action/UnexpectedlyTerminatedActionException.cs
- Libplanet/Currency.cs
- Libplanet/Serialization/SerializationInfoExtensions.cs
This PR fixes `InsufficientBalanceException` to be serialized properly by .NET serialization mechanism.
And more, it also fixes a bug that `UnexpectedlyTerminatedActionExceptions` doesn't contain its properties after de-serialization.
> Serializable InsufficientBalanceException

- .idea/.idea.Libplanet/.idea/vcs.xml
- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Net/SwarmTest.Preload.cs
- Libplanet.Tools/.gitignore
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Blockchain/FungibleAssetStateCompleter.cs
- Libplanet/Blockchain/FungibleAssetStateCompleters.cs
- Libplanet/Blockchain/StateCompleter.cs
- Libplanet/Blockchain/StateCompleterSet.cs
- Libplanet/Blockchain/StateCompleters.cs
This changes is a prior work to address the issue #929.  The existing option `bool completeStates` on `BlockChain<T>.GetState()` and `BlockChain<T>.GetBalance()` methods had provided only two ways to handle *incomplete block states*:
- `completeStates: true` recalculates actions from scratch and fills the incomplete block states with the recalculated states.  Of course this probably takes a long time.
- `completeStates: false` rejects inquiry on a state value and throws `IncompleteBlockStatesException` instead.  This prevents high latency, but also prevents to *use* 🙄 at the same time.
However, in order to achieve the idea of #929, we need to add one more option, and make `BlockChain<T>` to depend on `Swarm<T>`, which causes circular dependency (`BlockChain<T>` → `Swarm<T>` → …
> More flexible state complement

- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.Fixtures.cs
- Libplanet.Tests/Net/SwarmTest.Preload.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/InvalidStateTargetException.cs
- Libplanet/Net/Swarm.cs
- Libplanet/Net/SwarmOptions.cs
This replaces #941.
This fixes NullReferenceException in TransferRecentStates when `GetRecentStates.TargetBlockHash` doesn't exist in the chain. Also, this makes retry preload when `GetRecentStates.TargetBlockHash` is missing.
> Retry preload when RecentState target is missing

- Libplanet/Blockchain/BlockChain.cs
This adds logs for the reorg.
Before:
```
16:43:50:115234Z[@][15] - Swapping block chain. (from: 31fd07a8-df6d-48c3-bffe-c1f1d148eaca) (to: a91b78aa-83d8-49fd-a6c9-f78db2e7e277)
```
After:
```
16:43:50:115234Z[@][15] - Swapping block chain. (from: 31fd07a8-df6d-48c3-bffe-c1f1d148eaca, TipIndex - 10, TipHash - "2fe9bdf8026ffc4a0da658adeab7689a698c03157c502af63ceff422f7d18152") (to: a91b78aa-83d8-49fd-a6c9-f78db2e7e277, TipIndex - 9, TipHash - "4360218110c4dab3d32b6c7ff83a0c6004c45c7a94f081e116e38ca5f254018e")
```
> More log for the reorg

- CHANGES.md
- Libplanet.Tests/Net/Messages/BlockHashesTest.cs
- Libplanet.Tests/Net/Messages/BlockStatesTest.cs
- Libplanet.Tests/Net/Messages/MessageTest.cs
- Libplanet.Tests/Net/Messages/RecentStatesTest.cs
- Libplanet.Tests/Net/PeerTest.cs
- Libplanet.Tests/Net/Protocols/RoutingTableTest.cs
- Libplanet.Tests/Net/Protocols/TestTransport.cs
- Libplanet.Tests/Net/SwarmTest.AppProtocolVersion.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/BoundPeer.cs
- Libplanet/Net/DifferentAppProtocolVersionException.cs
- Libplanet/Net/Messages/DifferentVersion.cs
- Libplanet/Net/Messages/Message.cs
- Libplanet/Net/NetMQTransport.cs
- Libplanet/Net/Peer.cs
- Libplanet/Net/Protocols/KademliaProtocol.cs
- Libplanet/Net/Swarm.cs
Removed `Peer.AppProtocolVersion` which were used to check version between swarms. Instead, added `AppProtocolVersion`-typed `Version` property to `Message` and use it to check validity of messages.
If received message has different app protocol version, `NetMQTransport` will reply a `DifferentVersion` message regardless of received message's type and does not process anything.
> Introduce Version property to messages

- CHANGES.md
- Libplanet.Tests/Action/AccountStateDeltaExtensions.cs
- Libplanet.Tests/Action/AccountStateDeltaImplTest.cs
- Libplanet.Tests/Action/ActionContextTest.cs
- Libplanet.Tests/Action/ActionEvaluationExtensions.cs
- Libplanet.Tests/Action/ActionEvaluationTest.cs
- Libplanet.Tests/Action/InsufficientBalanceExceptionTest.cs
- Libplanet.Tests/Assets/CurrencyTest.cs
- Libplanet.Tests/Assets/FungibleAssetValueTest.cs
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Blocks/BlockTest.cs
- Libplanet.Tests/Common/Action/DumbAction.cs
- Libplanet.Tests/Tx/TransactionTest.cs
- Libplanet/Action/AccountBalanceGetter.cs
- Libplanet/Action/AccountStateDeltaImpl.cs
- Libplanet/Action/CurrencyPermissionException.cs
- Libplanet/Action/IAccountStateDelta.cs
- Libplanet/Action/InsufficientBalanceException.cs
- Libplanet/Assets/Currency.cs
- Libplanet/Assets/FungibleAssetValue.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Blockchain/FungibleAssetStateCompleter.cs
- Libplanet/Blockchain/FungibleAssetStateCompleters.cs
- Libplanet/Blocks/Block.cs
- Libplanet/Tx/Transaction.cs
This pull request adds `Currency.DecimalPlaces` property and `FungibleAssetValue` type to address the issue #944.
From this changes, fungible asset values are no more represented as `BigInteger`, which does not hold any decimal places, but `FungibleAssetValue` instead.  The introduced `FungibleAssetValue` type is essentially a pair of `(Currency, BigInteger)`.  It cannot mix heterogeneous currencies.  `FungibleAssetValue`s can be made like below:
```csharp
var gold = new Currency(ticker: "GOLD", decimalPlaces: 2, minter: null);
FungibleAssetValue value;
value = new FungibleAssetValue(gold, majorUnit: 123, minorUnit: 0);
// Or alternatively:
value = 123 * gold;
// Or:
value = gold * 123;
```
This patch also introduces a new property named `DecimalPlaces` to `Currency`.  This defines how …
> Represent fungible asset values as a distinct type and support minor units

- CONTRIBUTING.md
- Docs/publish.sh
- Libplanet.Tools/package.json
- Libplanet/Libplanet.csproj
- README.md
Because of this, <https://docs.libplanet.io/main/> hadn't updated for several days.
> Fix the outdated branch name in the docs build script

- CHANGES.md
- Libplanet.Tests/Net/Protocols/TestTransport.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/ITransport.cs
- Libplanet/Net/NetMQTransport.cs
- Libplanet/Net/Swarm.cs
This PR adds `LastMessageTimestamp` to `Swarm<T>`  so that library users can take appropriate action. (e.g. restarting `Swarm<T>`)
Also, I didn't mention deleted `Swarm<T>.LastReceived` because it hadn't been in the previous documentation.
> Add Swarm<T>.LastMessageTimestamp

- CHANGES.md
- Libplanet.Tests/Net/FactOnlyTurnAvailableAttribute.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/NetMQTransport.cs
- Libplanet/Net/Swarm.cs
This PR fixes a bug that `Swarm<T>` hadn't started after `Swarm<T>.StopAsync()`.
> Restartable Swarm<T>

- Libplanet.Tests/Store/StateStoreTracker.cs
- Libplanet.Tests/Store/TrieStateStoreTest.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Store/BaseBlockStatesStore.cs
- Libplanet/Store/IStateStore.cs
- Libplanet/Store/TrieStateStore.cs
Before this bugfix, `TrieStateStore` couldn't store states properly because of [this line](https://github.com/planetarium/libplanet/blob/4d080b547c7c6bc4616d15de9d345c9f747f6196/Libplanet/Blockchain/BlockChain.cs#L1562).
Also, the changes in `TrieStateStore` and `IStateStore`, were introduced in this version 0.11.0. So, the changelog was skipped.
> Fix a bug that TrieStateStore.SetStates(…) couldn't get previous hash successfully

- CHANGES.md
- Libplanet.Stun/Stun/TurnClient.cs
- Libplanet.Tests/Net/SwarmTest.cs
This PR addresses #957 ~and #969~.
> Fix errors on TurnClient

- .vscode/settings.json
- CHANGES.md
- Docs/articles/overview.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Blockchain/Renderers/AnonymousActionRendererTest.cs
- Libplanet.Tests/Blockchain/Renderers/AnonymousRendererTest.cs
- Libplanet.Tests/Blockchain/Renderers/LoggedActionRendererTest.cs
- Libplanet.Tests/Common/Action/ExecuteRecord.cs
- Libplanet.Tests/Common/DumbRenderer.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet.sln.DotSettings
- Libplanet/Action/PolymorphicAction.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Blockchain/Renderers/AnonymousActionRenderer.cs
- Libplanet/Blockchain/Renderers/AnonymousRenderer.cs
- Libplanet/Blockchain/Renderers/IActionRenderer.cs
- Libplanet/Blockchain/Renderers/IRenderer.cs
- Libplanet/Blockchain/Renderers/LoggedActionRenderer.cs
- Libplanet/Blockchain/Renderers/LoggedRenderer.cs
This addresses #967.
The previous patch #963 unified two types of events into one: one is for rendering/unrendering actions, and other one is for watching new tips & reorgs.  At the same time, it also threw away the `BlockChain<T>()` constructor's Boolean option `render` because I thought it's redundant as `render: false` seemed equivalent to `renderers: null`.
However, those two changes regressed the performance of reorg, because the optimization made by the patch #883 was thrown away together.  The disappeared optimization was a short-circuit evaluation option for stale actions to be unrendered.  As the option `render: false` was removed, stale actions became evaluated even if there is no renderers, or all renderers do nothing for `UnrenderAction()`/`UnrenderActionError()` events…
In …
> Short-circuit evaluation of stale actions on reorg

- .azure-pipelines/dotnet-core.yml
- .azure-pipelines/mono.yml
- .azure-pipelines/windows-net471.yml
- .github/workflows/check-build.yaml
- CONTRIBUTING.md
- Libplanet.RocksDBStore.Tests/Libplanet.RocksDBStore.Tests.csproj
- Libplanet.RocksDBStore/Libplanet.RocksDBStore.csproj
- Libplanet.Stun.Tests/Libplanet.Stun.Tests.csproj
- Libplanet.Stun/Libplanet.Stun.csproj
- Libplanet.Tests.ruleset
- Libplanet.Tests/Libplanet.Tests.csproj
- Libplanet.Tests/Net/SwarmTest.Preload.cs
- Libplanet.Tests/Net/SwarmTest.TrustedStateCompleter.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet.Tools/Libplanet.Tools.csproj
- Libplanet.ruleset
- Libplanet/Libplanet.csproj
This is another version of #977.
This turns off Sonar Analyzer by default and checks it using in the `check-sonar` action.
In your local environment, you can skip Sonar by using `SkipSonar` option like `dotnet build -p:SkipSonar=true`.
> Make SonarAnalyzer optional

- Libplanet.Tools/download.js
- Check Node.js Minimum Version (Above v8)
- Add Error Handler in Download
- Use `util.promisify` and split promises for refactor.
> Refactor CLI Install Script

- CHANGES.md
- Libplanet.Tests/Net/Protocols/TestTransport.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/NetMQTransport.cs
- Libplanet/Net/Protocols/KademliaProtocol.cs
- Libplanet/Net/Protocols/PingTimeoutException.cs
- Libplanet/Net/Protocols/RoutingTable.cs
- Libplanet/Net/Swarm.cs
There was `Swarm<T>.FindSpecificPeerAsync()` method but it was not precise. This PR makes it to work more precisely.
> Find specific peer from network

- .vscode/settings.json
- CHANGES.md
- Libplanet.Tests/Action/ActionContextTest.cs
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Blockchain/Renderers/DelayedActionRendererTest.cs
- Libplanet.Tests/Blockchain/Renderers/DelayedRendererTest.cs
- Libplanet.Tests/Libplanet.Tests.csproj
- Libplanet.Tests/LoggerExtensions.cs
- Libplanet.sln.DotSettings
- Libplanet/Action/ActionContext.cs
- Libplanet/Action/IActionContext.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Blockchain/Renderers/DelayedActionRenderer.cs
- Libplanet/Blockchain/Renderers/DelayedRenderer.cs
- Libplanet/Blockchain/Renderers/IActionRenderer.cs
This patch adds `DelayedRenderer<T>` & `DelayedActionRenderer<T>` that decorate another `IRenderer<T>` & `IActionRenderer<T>` and delay rendering events until the certain number of descendant blocks confirm a block.  See also the unit tests and XML comments.
> DelayedRenderer<T> & DelayedActionRenderer<T> for stable app-side state transfer

- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Blockchain/Renderers/DelayedActionRendererTest.cs
- Libplanet.Tests/Net/SwarmTest.Preload.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Blockchain/Renderers/DelayedActionRenderer.cs
- Libplanet/Blockchain/Renderers/IRenderer.cs
- Libplanet/Net/Swarm.cs
As `BlockChain<T>.Swap()` method has used for several purposes besides reorg, fix `IRenderer<T>.RenderReorg()` to be invoked if and only if an actual reorg happens.  Also reorder the timing of `IActionRenderer<T>.UnrenderAction()` & `UnrenderActionError()` being invoked so that they are called before `IRenderer<T>.RenderBlock()` and after `IRenderer<T>.RenderReorg()`.
> Make BlockChain<T>.Swap() without reorg not to invoke IRenderer<T>.RenderReorg()

- Libplanet.RocksDBStore.Tests/RocksDBStoreFixture.cs
- Libplanet.Tests/Net/SwarmTest.Fixtures.cs
- Libplanet.Tests/Net/SwarmTest.Preload.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet.Tests/Store/DefaultStoreFixture.cs
- Libplanet.Tests/Store/StoreFixture.cs
- Libplanet.Tests/TestUtils.cs
- Libplanet/Net/Swarm.MessageHandlers.cs
- Libplanet/Net/Swarm.cs
Previously, nodes turned off`IBlockStateStore` had requested `RecentStates` despite these hadn't been stored.  Therefore, these requests cause unnecessary computation on seed nodes.  This pull request addresses the problem.  I skipped the changelog as `IStateStore` and `IBlockStateStore` have never released yet.
> Do not request RecentStates if IBlockStateStore is unused

- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.Preload.cs
- Libplanet/Blocks/Block.cs
- Libplanet/Net/Swarm.cs
This changes `Swarm<T>.PreloadAsync()` to execute the actions from the branch point rather than the genesis block when there is a branch point.
> Execute actions from branch point when preloading

- Libplanet.Tests/Net/Protocols/ProtocolTest.cs
- Libplanet/Net/Protocols/KademliaProtocol.cs
Since the feature that made this bug hasn't released, skip changelog.
> Fix bug where BootstrapAsync throw PingTimeoutException when some FindPeer fails

- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Blockchain/Renderers/DelayedRenderer.cs
I'm going to add more accurate unit test later.
> Even backward tip change shouldn't invoke RenderReorg

- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/Protocols/KademliaProtocol.cs
I also added a regression test for the case.
> Fix FindSpecificPeerAsync's depth parameter did not worked properly

- CHANGES.md
- Libplanet/Net/Swarm.cs
This PR addresses two bugs in `Swarm<T>` as below
1. a bug that `Swarm<T>` had not received block headers after failing to receive previous blocks.
2. a bug that  `Swarm<T>` had thrown `InvalidGenesisBlockException` when reorg chain repeatedly.
> Polishing Swarm<T>

- .gitignore
- CONTRIBUTING.md
- Libplanet.RocksDBStore.Tests/Libplanet.RocksDBStore.Tests.csproj
- Libplanet.Stun.Tests/Libplanet.Stun.Tests.csproj
- Libplanet.Tests/Blockchain/Renderers/DelayedActionRendererTest.cs
- Libplanet.Tests/Blockchain/Renderers/DelayedRendererTest.cs
- Libplanet.Tests/Libplanet.Tests.csproj
- Libplanet/Blockchain/Renderers/DelayedRenderer.cs
- Libplanet/Blockchain/Renderers/IActionRenderer.cs
This fixes `DelayedRenderer<T>`'s bug that it changes its `Tip` even if a discovered block's `TotalDifficulty` is less than the existing `Tip`'s `TotalDifficulty`.
> Make DelayedRenderer<T> to regard total difficulty 

- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Net/SwarmTest.Preload.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Net/Swarm.cs
I added `renderBlocks` parameter to `BlockChain.Append()` internal method.
Since the method is internal and `IRenderer` isn't released yet, I omitted changelog.
> Do not render genesis block during fork

- Libplanet.Tests/Net/SwarmTest.Preload.cs
Actually, it is possible not to report all of them because it reports them asynchronously. So it became to report synchronously by using `ActionProgress`.
> Report progress synchronously in test

- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.Preload.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/Messages/BlockHeaderMessage.cs
- Libplanet/Net/Messages/ChainStatus.cs
- Libplanet/Net/Messages/Message.cs
- Libplanet/Net/Swarm.MessageHandlers.cs
- Libplanet/Net/Swarm.TrustedStateCompleter.cs
- Libplanet/Net/Swarm.cs
`ChainStatus` and `BlockHeaderMessage` messages now contain `GenesisHash` parameter, so receiving peer ignores those messages if its value is different from hash of the genesis block of self.
> Ignore messages from peer with different genesis block

- Libplanet/Blockchain/BlockEvaluator.cs
- Libplanet/Blocks/Block.cs
Before this pull request, the evaluation methods used `Block<T>.Hash` as a random seed. Since `PreEvaluationHash` had introduced, it must replace the seed with it but it didn't. And it made indeterministic states. So it fixed those.
> Use PreEvaluationHash (instead of Hash) as random seed

- Libplanet.Tests/Blockchain/BlockEvaluatorTest.cs
- Libplanet.Tests/Common/Action/RandomAction.cs
- Libplanet/Blockchain/BlockEvaluator.cs
It is continued from #1005. It contains a test to check whether `BlockEvaluator` evaluates blocks idempotently.
I'm not sure it can cover all of the issues in #1005 properly. Please review this hard and leave your opinions.
> Check whether BlockEvaluator evaluates blocks idempotently

- .azure-pipelines/dotnet-core.yml
- .azure-pipelines/mono.yml
- .azure-pipelines/windows-net471.yml
- azure-pipelines.yml
In the pull request #992, I applied `-stoponfail` option to Xunit, but it's only Mono and .NET Framework, because .NET Core jobs used `dotnet test` instead.  This replaces `dotnet test` with [xunit-cli][1] which can support all options `xunit.console.exe` provides.  Meanwhile, for coverage it still uses `dotnet test` because all tests should be run anyway even if some fails.
[1]: https://github.com/natemcmaster/xunit-cli
> CI: Use -stoponfail on .NET Core tests

- CHANGES.md
- Libplanet.Tools/ConsolePasswordReader.cs
- Libplanet.Tools/Key.cs
- Libplanet.Tools/Libplanet.Tools.csproj
This PR resolves Issue #983.
Tested in WSL2 Ubuntu 18.04, Windows 10 CMD and Powershell, macOS 10.15.
Feel free to review this. Thanks. :)
> Fix Backspace not working in create new key in CLI.

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs
- Libplanet.Tests/Libplanet.Tests.csproj
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Blockchain/Policies/BlockPolicy.cs
This moves block validation code to `BlockChain<T>` from `BlockPolicy<T>` and also the methods of `BlockPolicy<T>` became to virtual so that it can be overridden.
> Move block validation code to BlockChain<T>

- Libplanet.Tests/Blocks/BlockTest.cs
- Libplanet/Blocks/Block.cs
Originally `Block<T>` shuffled transactions with `Block<T>.Hash` to restrict miner control its execution order. But now, `Block<T>.Hash` is different in the two steps so it should be fixed to `Block<T>.PreEvaluationHash`. This pull request does it.
> Fix a bug the order of transactions was different in two steps (i.e., pre-evaluation and evaluation)

- CHANGES.md
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Store/BlockSet.cs
This PR adds a cache to `BlockSet<T>` to improve its fetching performance. (it can be useful when blocks contain huge and complex actions.)
> Improve performance of `BlockSet<T>`

- Libplanet/Blockchain/BlockChain.cs
This PR omits a check for `Block<T>.StateRootHash` when `evaluateActions` is `false` to avoid unexpected evaluation.
I also skip the changelog because we didn't release 0.10.0 that introduced MPT yet(!).
> Omit state root hash check when evaluateActions is disabled

- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Common/RecordingRenderer.cs
- Libplanet.Tests/Common/RenderRecord.cs
- Libplanet.Tests/Common/ValidatingActionRenderer.cs
- Libplanet.Tests/Menees.Analyzers.Settings.xml
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet.Tests/TestUtils.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Blockchain/Renderers/DelayedActionRenderer.cs
- Libplanet/Net/Swarm.cs
This fixes the inaccurate order of rendering events that `BlockChain<T>` emits so that the order conforms to the [documented rendering automata][1], i.e.:
> See also the docs on `IRenderer<T>`:
> 
> ![IRenderer<T>](https://user-images.githubusercontent.com/12431/92929971-5c4e9f80-f47c-11ea-8c46-9bda44e34889.png)
> 
> … and `IActionRenderer<T>`:
> 
> ![IActionRenderer<T>](https://user-images.githubusercontent.com/12431/92929884-3a551d00-f47c-11ea-861b-0ec7382a2269.png)
In order to find the causes of these bugs, I also added `ValidatingActionRenderer<T>` which is a profiler-guided analyzer.
[1]: https://github.com/planetarium/libplanet/pull/1000
> Fix inaccurate render events order according to documented automata

- Libplanet/Store/BlockSet.cs
This changes `Add` method to `AddOrUpdate` method to prevent exceptions that occur when multiple threads are writing the cache at the same time.
> Change Add to AddOrUpdate

- CHANGES.md
- Libplanet.RocksDBStore.Tests/Libplanet.RocksDBStore.Tests.csproj
- Libplanet.RocksDBStore/Libplanet.RocksDBStore.csproj
- Libplanet.Stun.Tests/Libplanet.Stun.Tests.csproj
- Libplanet.Stun/Libplanet.Stun.csproj
- Libplanet.Stun/Stun/Messages/StunMessage.cs
- Libplanet.Tests.ruleset
- Libplanet.Tests/Action/ActionContextTest.cs
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Libplanet.Tests.csproj
- Libplanet.ruleset
- Libplanet/Address.cs
- Libplanet/AddressExtensions.cs
- Libplanet/ByteArrayExtensions.cs
- Libplanet/ByteUtil.cs
- Libplanet/FixedSizedQueue.cs
- Libplanet/HashDigest.cs
- Libplanet/Hashcash.cs
- Libplanet/KeyStore/Kdfs/Pbkdf2.cs
- Libplanet/KeyStore/ProtectedPrivateKey.cs
- Libplanet/Libplanet.csproj
- Libplanet/Nonce.cs
This enables null checker on Libplanet project's top-level files to contribute to #458.
Also upgraded StyleCop.Analyzers to 1.2.0-beta.205 in order to avoid <https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/2927>.
Total files:
```console
$ find Libplanet/ -name '*.cs' | wc -l
187
```
Files that enable null checker (43%):
```console
$ git grep '#nullable enable' Libplanet/ | wc -l
81
```
Note that it was before (39%):
```console
$ git grep '#nullable enable' Libplanet/ | wc -l
73
```
> Enable null checker on Libplanet project's top-level files

- Libplanet.Tests/Store/Trie/TrieTest.cs
- Libplanet/Store/Trie/ITrie.cs
- Libplanet/Store/Trie/MerkleTrie.cs
There is no reason to store `null`.
> Do not store null state

- Libplanet/Net/Protocols/KademliaProtocol.cs
- Libplanet/Net/Protocols/RoutingTable.cs
Now many methods and properties were added to examine `Swarm`'s state, logging for periodic method in protocol need not to be logged. I changed some logging levels in periodic methods from `Level.Debug` to `LogLevel.Verbose`.
> Change verbosity of periodic logging in protocol

- Libplanet.Tests/Store/TrieStateStoreTest.cs
- Libplanet/Store/TrieStateStore.cs
Actually, `MerkleTrie` has supported *secure mode* with the constructor parameter since it was introduced. But users couldn't use it by any method because `MerkleTrie` has been `internal` class and `TrieStateStore` hasn't provided any method to set up the mode. So this pull request makes it provide the method to set up the mode with the constructor parameter.
> Introduce `secure` option into `TrieStateStore` constructor

- CHANGES.md
- Libplanet.Tests/ImmutableArrayEqualityComparer.cs
- Libplanet.Tests/Store/Trie/MerkleTrieExtensionsTest.cs
- Libplanet.Tools/Mpt.cs
- Libplanet/Store/Trie/MerkleTrieExtensions.cs
Before this pull request, #1023 MUST proceed.
This pull request introduced a new feature to export all states corresponded to the state root hash as JSON.
```powershell
> dotnet run -- mpt export "C:\Users\moreal\AppData\Local\planetarium\9c-beta-8-rc1\states" "09dc793242a7f0932656654e01d92e5e84b58b3f52738cf0d67960e9d32951de" -t rocksdb > states.json
> cat states.json
{"39666566633833366331343965336664383436333932366232623434626431616633363734663034":"ZHU3OmFkZHJlc3MyMDqf78g2wUnj/YRjkmsrRL0a82dPBHU1Om5vbmNlM ....
....
```
It will be exported as not pretty JSON like the below type:
```JSON
{
"<state_key>": "<bencodexed_hexdecimal_string>"
}
```
> Export all states as JSON

- Libplanet.Tests/TestUtils.cs
Originally, it was possible that `TestUtils.GetRandomBytes()` returns the same value if it was called in the same timestamp. This pull request prevents it.
> test: fix TestUtils.GetRandomBytes

- CHANGES.md
- Libplanet.Tests/Action/ActionContextTest.cs
- Libplanet.Tests/Blockchain/BlockEvaluatorTest.cs
- Libplanet.Tests/Store/Trie/MerkleTrieExtensionsTest.cs
- Libplanet.Tests/Store/Trie/MerkleTrieTest.cs
- Libplanet.Tests/Store/Trie/TrieTest.cs
- Libplanet.Tests/TestUtils.cs
- Libplanet.Tests/Tx/TransactionTest.cs
- Libplanet/Action/ActionContext.cs
- Libplanet/Action/ActionEvaluation.cs
- Libplanet/Action/IAccountStateDeltaExtensions.cs
- Libplanet/Action/IActionContext.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Blockchain/BlockEvaluator.cs
- Libplanet/Blockchain/KeyConverters.cs
- Libplanet/Store/Trie/ITrie.cs
- Libplanet/Store/Trie/ITrieExtensions.cs
- Libplanet/Store/Trie/MerkleTrie.cs
- Libplanet/Store/TrieStateStore.cs
It was hard to debug when an error or some situations occurred during action execution because there was no API to know the state root hash. This pull request resolves it by providing the API.
There is one which I want to ask for your advice. The pattern which passes the getter function through the constructor is a good pattern? It can make difference between the real code and the test code and I'm not sure that the real code is testing well because of the difference. So is there another pattern to resolve it? or does it seem like wrong to worry?
> feat(mpt): provide API to calculate state root hash in the action execution

- Libplanet.Analyzers.Tests/ActionAnalyzerTest.cs
- Libplanet.Analyzers.Tests/Verifiers/DiagnosticVerifier.Helper.cs
- Libplanet.Analyzers.Tests/Verifiers/DiagnosticVerifier.cs
- Libplanet.Analyzers/ActionAnalyzer.cs
- Libplanet.Analyzers/README.md
- Libplanet.Analyzers/rules/LAA1002.md
Added a new rule to ensure if dictionaries or sets are ordered before they are enumerated.  See also the docs in *LAA1002.md* file.
FYI, with this rule, Lib9c has the below warnings (though there are quite many false alarms yet):
```
Action/SellCancellation.cs(50,87): error LAA1002: Enumerating an instance of System.Collections.Generic.Dictionary<string, Bencodex.Types.IValue> is indeterministic since the order of System.Collections.Generic.Dictionary<string, Bencodex.Types.IValue> is unspecified; explicitly sort them before enumerating.
Action/AttachmentActionResult.cs(47,43): error LAA1002: Enumerating an instance of System.Collections.Generic.Dictionary<Bencodex.Types.IKey, Bencodex.Types.IValue> is indeterministic since the order of …
```
> LAA1002: DictionariesOrSetsShouldBeOrderedToEnumerate

- Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
- Libplanet/Blockchain/BlockChain.cs
This PR fixes a bug where `Swarm<T>.PreloadAsync()` hadn't caught illegal state root properly.
Also, I omitted `CHANGES.md` because we didn't release 0.10 introducing `Block<T>.StateRootHash` yet. 👀
> Fix preloading bug

- Libplanet/Net/Swarm.cs
This fixes a bug where the `BlockChain` was reorged into a chain with lower total difficulty. I skipped the changelog because the total difficulty is introduced in 0.10.0.
> Don't Swap to a chain of lower total difficulty

- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/Swarm.cs
This PR adjusts the order of re-broadcast tx from the network to avoid sending invalid transactions.
> Skip broadcasting invalid txs

- CHANGES.md
- Libplanet.Tests/Action/UnexpectedlyTerminatedActionExceptionTest.cs
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet/Action/ActionEvaluation.cs
- Libplanet/Action/UnexpectedlyTerminatedActionException.cs
- Libplanet/Blockchain/BlockEvaluator.cs
- Libplanet/Blocks/Block.cs
- Libplanet/Tx/Transaction.cs
This must be merged after #1030 merged.
This fixed an issue that it throws an exception with a message like rehearsal mode though it was not on rehearsal mode. Also the message became to provide the state root hash also.
> feat(mpt): log state root hash also when an action throws exception

- Libplanet.Tools/Configuration/MptConfiguration.cs
- Libplanet.Tools/JsonConfigurationService.cs
Fix these error:
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
at Libplanet.Tools.Mpt.Add(String alias, String uri, IConfigurationService`1 configurationService) in C:\Users\riema\Documents\Workspaces\libplanet\Libplanet.Tools\Mpt.cs:line 172
```
> fix(tools): Do not return default when type is struct

- .azure-pipelines/dotnet-core.yml
- .azure-pipelines/mono.yml
- .azure-pipelines/windows-net471.yml
- Libplanet.Tests/Net/SwarmTest.AppProtocolVersion.cs
- Libplanet.Tests/Net/SwarmTest.Fixtures.cs
- Libplanet.Tests/Net/SwarmTest.Preload.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet.Tests/Store/DefaultStoreFixture.cs
- Libplanet.Tests/Store/DefaultStoreTest.cs
- Libplanet/Net/Swarm.cs
- azure-pipelines.yml
To improve tests:
- Use in memory `DefaultStoreFixture` by default.
- Reduce the default test timeout in `SwarmTest` to 30 seconds.
- Use helper methods instead of fixtures in `SwarmTest`.
- Parallelize tests.
> Fix swarm test

- Libplanet/Blockchain/BlockChain.cs
~Instead `IStore.ForkBlockIndexes()` became to iterate from 0 (was 1).~
Instead just append its index only.
> Do not append genesis during fork

- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Blockchain/Policies/BlockPolicy.cs
- Libplanet/Blocks/BlockHeader.cs
Enriched messages of exceptions which inherits `InvalidBlockException`. Now it typically has `#index [hash]` form.
> Log block's hash in block exceptions

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.Internals.cs
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet/Blockchain/BlockChain.cs
This ports the hotfix #1057 to the 0.10-maintenance branch.  Also applied reviews from #1057.  Read the changelog too.
> Multiplex the order of staged transactions (port)

- Libplanet/Net/NetMQTransport.cs
- Libplanet/Net/Protocols/KademliaProtocol.cs
- Libplanet/Net/Swarm.cs
Patch contains followings:
- Fix bug in `KademliaProtocol.CheckReplacementCacheAsync()`
- Catch and logs error occurred in `NetMQTransport.DoBroadcast()`
- Fix `NullReferenceException` in `Swarm<T>.GetPeerChainStateAsync()`
> Enrich protocol debug loggings

- Libplanet.RocksDBStore/RocksDBStore.cs
It provides a new feature to configure some options of RocksDB options.
With `maxTotalWalSize`, you can limit the size of [WAL].
With `keepLogFileNum`, you can limit the number of log files.
[WAL]: https://github.com/facebook/rocksdb/wiki/Write-Ahead-Log
> feat(rocksdb): configure rocksdb options

- Libplanet.Tests/Blocks/BlockTest.cs
- Libplanet/Blocks/Block.cs
- Libplanet/Net/Swarm.cs
Renamed internal method `Block<T>.GetBlockHeader()` to public property `Block<T>.Header`.
> Introduce Block<T>.Header

- Libplanet/Blockchain/BlockChain.cs
> fix(blockchain): rwlock when call `SetStates()` on `MineBlock()`

- CHANGES.md
- Libplanet.Tests/ByteArrayExtensionsTest.cs
- Libplanet.Tests/Tx/TransactionTest.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Blocks/Block.cs
- Libplanet/ByteArrayExtensions.cs
- Libplanet/Tx/Transaction.cs
Applied several optimizations on action evaluation.  With this patch, evaluating actions in 50,000 blocks on Nine Chronicles' mainnet takes less than about 50 seconds now (and it was about 1 minute before; MacBook Pro 2018; 2.2GHz Intel Core i7; 16 GB 2400 MHz DDR4).
This should be ported to 0.10-maintenance as well.
> Optimize action evaluation

- Libplanet.Stun/Stun/TurnClient.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/IceServer.cs
- Libplanet/Net/NetMQTransport.cs
This PR moves TURN related features from `NetMQTransport` to `TurnClient` and enables restarting in `TurnClient` when relayed connection and TURN control session had disconnected. (see also #909 )
> Move initializing code to TurnClient

- Libplanet/Blockchain/BlockChain.cs
This patch makes appending genesis faster if genesis state already in the storage.
> Do not re-append genesis block when it already have state

- CHANGES.md
- Libplanet.Tests/ByteArrayExtensionsTest.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Blocks/Block.cs
- Libplanet/ByteArrayExtensions.cs
- Libplanet/Tx/Transaction.cs
*This must be merged after #1067 is merged first.*
This ports #1079 into the 0.10-maintenance branch.  Changelogs were added too.
> Applied several optimizations on action evaluation. With this patch, evaluating actions in 50,000 blocks on Nine Chronicles' mainnet takes less than about 50 seconds now (and it was about 1 minute before; MacBook Pro 2018; 2.2GHz Intel Core i7; 16 GB 2400 MHz DDR4).
> 
> This should be ported to 0.10-maintenance as well.
> Optimize action evaluation (port)

- Libplanet.Tests/Action/PolymorphicActionTest.cs
- Libplanet/Action/ActionEvaluation.cs
- Libplanet/Action/PolymorphicAction.cs
Also, it helps the problem that it was hard to know what `IAction` implementation the exception threw, with only exception message without debug tool. But it should be rejected or optimized if it became the part to make your application slow.
> feat(benchmark): add log for action execution benchmark

- Libplanet.Tests/Store/Trie/MerkleTrieTest.cs
- Libplanet/Store/Trie/MerkleTrie.cs
It fixes a bug where it couldn't store any states after genesis block if genesis block doesn't initialize any states.
> fix(mpt): treat as null if EmptyRootHash came as root

- Libplanet.Benchmarks/Libplanet.Benchmarks.csproj
It resolves #1059 by bumping `BenchmarkDotNet`'s version into [0.12.1](https://benchmarkdotnet.org/changelog/v0.12.1.html).
Compare [failed benchmark action](https://github.com/moreal/libplanet/runs/1422688330?check_suite_focus=true) and [succeeded benchmark action](https://github.com/moreal/libplanet/runs/1424958760?check_suite_focus=true).
> fix(benchmarks): bump BenchmarkDotNet

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Blocks/BlockExceedingTransactionsExceptionTest.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Blocks/BlockExceedingTransactionsException.cs
- Libplanet/Blocks/InvalidBlockBytesLengthException.cs
In the commit 1d357776a640839e34d4195299fc09238e4ce5d8, we added `IBlockPolicy<T>.MaxTransactionsPerBlock` property, but it had only functioned as a default value for `BlockChain<T>.MineBlock()` method's `maxTransactions` option.  This had misled and been unintended, because `BlockChain<T>.Append()` still had accept blocks violating its policy (`Block<T>` having more `Transactions` than the number a policy allows still can be made with `Block<T>.Mine()` method).
Although this adds `BlockExceedingTransactionsException` class, since it would be released as a patch release, it's not `public` yet.  We should make it `public` when it's ported to the upstream main (next major/minor release).
> Fix BlockChain<T>.Append() to disallow block with too many txs

- .github/bin/dist-npm.sh
- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Blocks/BlockExceedingTransactionsExceptionTest.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Blocks/BlockExceedingTransactionsException.cs
- Libplanet/Blocks/InvalidBlockBytesLengthException.cs
- Port updates from 0.10.2.
- Make `BlockExceedingTransactionsException` class public (as mentioned in #1104).
> Port updates from 0.10.2 & make BlockExceedingTransactionsException public

- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/BlockDemand.cs
- Libplanet/Net/Swarm.MessageHandlers.cs
- Libplanet/Net/Swarm.cs
- Libplanet/Net/SwarmOptions.cs
I skipped changelog for `BlockDemand.Timestamp` because BlockDemand struct is first introduced in 0.11.
> Ignore stale block demand

- CHANGES.md
- Libplanet/Net/Swarm.cs
If getting blocks size in `Swarm<T>.FillBlocksAsync()` is less then `Swarm<T>.FindNextHashesChunkSize`, it means getting all of blocks in this try. So, do not processing next step for check.
> Break when getting blocks count is less then hash chunk size

- Libplanet/Blockchain/BlockChain.cs
Skip changelog because `BlockChain<T>.Fork()` is internal.
> Do not append genesis block during fork

- CHANGES.md
- Libplanet.Tests/Net/Protocols/TestTransport.cs
- Libplanet/Net/ITransport.cs
- Libplanet/Net/Messages/Message.cs
- Libplanet/Net/NetMQTransport.cs
- Libplanet/Net/Protocols/IProtocol.cs
- Libplanet/Net/Protocols/KademliaProtocol.cs
- Libplanet/Net/Swarm.MessageHandlers.cs
- Libplanet/Net/Swarm.cs
In order to make client, `Message` class also became public.
For easier use, message handling method is changed to subscription model.
> Make ITransport public

- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Blockchain/Renderers/DelayedActionRendererTest.cs
- Libplanet.Tests/Common/ValidatingActionRenderer.cs
- Libplanet.Tests/TestUtils.cs
@limebell made some improvements on [lib9c](https://github.com/planetarium/lib9c)'s copy of `ValidationActionRenderer`:
- https://github.com/planetarium/lib9c/pull/118
- https://github.com/planetarium/lib9c/pull/121
- https://github.com/planetarium/lib9c/pull/124
This ports them back to the *Libplanet.Tests* project, with more improvements and some subtle bugs fixed:
- Mismatched action renders/unrenders became easier to figure out.
- Fixed the incorrect order of expected action unrenders on reorg.
- Fixed the false error on reorg where a branchpoint is genesis.
> Port changes from lib9c's ValidatingActionRenderer

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Blocks/BlockTest.cs
- Libplanet.Tests/Blocks/InvalidBlocckTxHashExceptionTest.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Blocks/Block.cs
- Libplanet/Blocks/InvalidBlockTxHashException.cs
This PR increases the performance of `BlockChain<T>.MineBlock()` and `Block<T>.Deserialize()`.
- `BlockChain<T>.MineBlock()` became to reuse action evaluations while `.Append()`.
- `Block<T>.Deserielize()` became to accept all serialized values(e.g. `.Hash`, `.TxHash`) instead of re-calculating them.
and it also changes the behavior of `Block<T>.Validate()` to only checks its `.TxHash`, not all `.Transactions`. for it, I created `InvalidBlockTxHashException` as a new exception.
> Reuse action evaluations from mining

- Libplanet.Tests/Net/SwarmTest.cs
- azure-pipelines.yml
- Fixes the `ReconnectToTurn` test that fails intermittently.
- Removes the Windows_NETCore test from the CI, which can be replaced by Windows_NETCore_coverage. I think removing the test can alleviate the test timeout problem.
> Fix broken tests

- Libplanet/Blockchain/Policies/BlockPolicy.cs
`BlockPolicy.ValidateNextBlock` has been become not to throw `InvalidBlockStateRootHashException` since https://github.com/planetarium/libplanet/pull/1010
> docs: correct document

- CHANGES.md
- Libplanet/Blockchain/BlockChain.cs
This PR improves tx selecting performance in `BlockChain<T>.MineBlock()` by storing and reusing tx's nonce instead of calculating them per each txs.
> Improve tx selecting performance

- CHANGES.md
- Libplanet.Tools/Mpt.cs
It resolves the problem which it was unavailable to compare two root hashes from each different key-value store.
It makes `planet mpt diff` more usable. 🧰
> feat(cli): support multiple kv-store in diff

- Libplanet/Net/Protocols/KademliaProtocol.cs
The change should have been included in #1120, but omitted by mistake.
> Make KademliaProtocol public

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Blockchain/Policies/StagePolicyTest.cs
- Libplanet.Tests/Blockchain/Policies/VolatileStagePolicyTest.cs
- Libplanet.Tests/Store/StoreFixture.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Blockchain/Policies/VolatileStagePolicy.cs
This patch introduces the `lifetime` parameter (which is 3 hours<sup>1</sup> by default) to the `VolatileStagePolicy<T>()` constructor, and the corresponding `VolatileStagePolicy<T>.Lifetime` property.  Staged transactions that have reached their lifetime are evicted from the stage, and never can be staged again.
Closes #1130.
----
1. Note that this default value is burrowed from [Go Ethereum's `--txpool.lifetime` option's][1].
[1]: https://github.com/ethereum/go-ethereum/blob/v1.9.25/core/tx_pool.go#L167
> Give staged transactions lifetime on VolatileStagePolicy<T>

- CHANGES.md
- Libplanet/Blockchain/BlockChain.cs
Mining hadn't been cancelled if the tip of the chain is changed in specific situation. This patch register event handler at the very beginning of `MineBlock()` to cover the case where tip is changed before event registration.
> Register WatchTip at beggining of MineBlock

- CHANGES.md
- Libplanet.Tools/Mpt.cs
It provides:
- `mpt list`: List all aliases stored.
- `mpt query KV-STORE STATE-ROOT-HASH STATE-KEY`: query a state of the state key at the state root hash in kv-store.
> feat(cli): provide useful commands

- .azure-pipelines/mono.yml
- .azure-pipelines/windows-net471.yml
- CONTRIBUTING.md
- Libplanet.Analyzers.Tests/Libplanet.Analyzers.Tests.csproj
- Libplanet.Benchmarks/Libplanet.Benchmarks.csproj
- Libplanet.RocksDBStore.Tests/Libplanet.RocksDBStore.Tests.csproj
- Libplanet.Stun.Tests/Libplanet.Stun.Tests.csproj
- Libplanet.Tests/Libplanet.Tests.csproj
- global.json
As .NET Core 2.2 is quite outdated, let's drop .NET Core 2.2 support for unit tests and require 3.1 instead.
This also removes the old workaround for Rider (note that older versions of Rider cannot run MSBuild on .NET Core) which is unnecessary nowadays.  It fixes test discovery on JetBrains Rider.  /cc @riemannulus
> Drop .NET Core 2.2 support for unit tests and require 3.1 instead

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet/Action/ActionContext.cs
- Libplanet/Action/ActionEvaluation.cs
- Libplanet/Action/IActionContext.cs
- Libplanet/Blockchain/BlockEvaluator.cs
Previously, there was no way in the action itself to check whether it was a block action or not. You can use the IActionContext.IsBlockAction property to know if the action itself is a block action or not.
> Add property `IActionContext.IsBlockAction`

- CHANGES.md
- Libplanet.Tests/Action/AccountStateDeltaImplTest.cs
- Libplanet.Tests/Action/AccountStateDeltaImplV0Test.cs
- Libplanet.Tests/Action/AccountStateDeltaTest.cs
- Libplanet/Action/AccountStateDeltaImpl.cs
- Libplanet/Action/AccountStateDeltaImplV0.cs
- Libplanet/Blockchain/BlockEvaluator.cs
- Libplanet/Blocks/Block.cs
I rebased #1134 on the current main, and made it to maintain backward compatibility with [protocol version] 0.
Please review this instead of #1134. The commit I added besides #1134 is: 506ae01d5b6d29d93acdbcca0a7a10c79065cb16.
Closes #1134.
[protocol version]: https://github.com/planetarium/libplanet/issues/1142
> Fix TransferAsset vulnerability (take 2)

- Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
I claimed `BlockChain<T>.Append()` does not validate block indices in the issue #947, but it turns out false.  However, I added a more test case if it invalidates a block with index after nonexistent.
Close #947.
> Test a block with index after nonexistent

- CHANGES.md
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet/Store/BaseStore.cs
> fix: use protocol version of existing block

- CHANGES.md
- Libplanet.Tests/Blockchain/Renderers/DelayedActionRendererTest.cs
- Libplanet/Blockchain/Renderers/DelayedActionRenderer.cs
Add `clearBufferInterval` parameter into `DelayedActionRenderer<T>()` constructor for clear `DelayedActionRenderer<T>._bufferedActionRender` and `DelayedActionRenderer<T>._bufferedActionUnrender` each block interval.
> Add `clearBufferInterval` parameter into `DelayedActionRenderer<T>()` constructor

- Libplanet.Tests/Menees.Analyzers.Settings.xml
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/Swarm.cs
This fixes an issue where it can reset block demand at an incorrect time. For instance:
- Received `BlockHeader` 100 and `BlockDemand` 100 block.
- `ProcessFillBlocks()` starts to download the 100 blocks.
- Received `BlockHeader` 101 and `BlockDemand` 101 block.
- `ProcessFillBlocks()` finished to download the 100 blocks and reset `Swarm<T>.BlockDemand` as `null`.
- Though `BlockHeader` 101 was received, it was ignored.
I tried to fix the problem by resetting the block demand as `null` when starting `SyncPreviousBlocksAsync()` after moving the block demand as the local variable, but it makes many code changes and I felt hard to build the situation. So I fixed the problem with the current changes simply. Also, I skipped the changelog because `Swarm<T>.BlockDemand` was not released yet. If …
> fix(net): reset block demand when not changed

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
- Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Store/TrieStateStore.cs
Previously, before verifying the state, the evaluated state was first saved and then verified, but now the state root hash verified first and saved.
> Check StateRootHash first when BlockChain<T>.ExecuteAction

- CHANGES.md
- Libplanet.Tests/Net/Messages/BlockHashesTest.cs
- Libplanet.Tests/Net/Messages/MessageTest.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/InvalidTimestampException.cs
- Libplanet/Net/Messages/Message.cs
- Libplanet/Net/NetMQTransport.cs
- Libplanet/Net/Protocols/KademliaProtocol.cs
- Libplanet/Net/Swarm.cs
- Libplanet/Net/SwarmOptions.cs
Added timestamp to messages. Network transport used in swarm will now ignore messages created in certain time before current time, or after current moment. The amount of lifespan of a message is configured in `SwarmOptions.MessageLifespan`, if `null` is given then timestamp will not being used in message validation.
There are API changes in `Message`, but I omitted it in the changelog because the abstract class `Message` haven't released yet.
Please refer to #1160.
> Add lifespan to messages

- CHANGES.md
- Libplanet.Stun/Stun/TurnClient.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/NetMQTransport.cs
This PR fixes a bug where `TurnClient` hadn't reset its relays after resetting.
> Reset all relays after reconnecting TURN

- .vscode/settings.json
- CHANGES.md
- Libplanet.RocksDBStore/RocksDBStore.cs
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Blockchain/NullPolicy.cs
- Libplanet.Tests/Blockchain/Renderers/DelayedRendererTest.cs
- Libplanet.Tests/Blockchain/TotalDifficultyComparerTest.cs
- Libplanet.Tests/Blocks/SimpleBlockExcerpt.cs
- Libplanet.Tests/Menees.Analyzers.Settings.xml
- Libplanet.Tests/Net/SwarmTest.Consensus.cs
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet.Tests/Store/StoreTracker.cs
- Libplanet.sln.DotSettings
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Blockchain/BlockPerception.cs
- Libplanet/Blockchain/Policies/BlockPolicy.cs
- Libplanet/Blockchain/Policies/IBlockPolicy.cs
- Libplanet/Blockchain/Renderers/DelayedActionRenderer.cs
- Libplanet/Blockchain/Renderers/DelayedRenderer.cs
- Libplanet/Blockchain/TotalDifficultyComparer.cs
- Libplanet/Blocks/BlockExcerpt.cs
- Libplanet/Net/Swarm.cs
- Libplanet/Store/BaseStore.cs
- Libplanet/Store/DefaultStore.cs
- Libplanet/Store/IStore.cs
This completely fixes #1155, in particular:
> Also: we may need to consider time a node received blocks.
I also added a new struct to represent the concept of local node's perception of blocks: `BlockPerception`.
See also the changelog.
> Stale outdated chains

- CHANGES.md
- Libplanet.RocksDBStore/MonoRocksDBStore.cs
- The `RocksDBStore` that was previously used has been separated into a class called `MonoRocksDBStore`.
> MonoRocksDBStore: for backward compablity migration

- CHANGES.md
This pull request fixes an invalid links in *CHANGES.md*. Originally, @dahlia was noticed it in #1169 as review comment and I updated it. But it was back to before applying while rebasing as mistake.
> docs: correct invalid links

- CHANGES.md
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Net/BlockCompletion.cs
- Libplanet/Net/NetMQSocketExtensions.cs
- Libplanet/Net/NetMQTransport.cs
- Libplanet/Net/Swarm.cs
This PR adds handling for `CancellationTokenSource.Dispose()` to prevent memory leakages.
> More reduce undisposed CancellationTokenSource

- CONTRIBUTING.md
- Libplanet.Extensions.Cocona/Commands/ApvCommand.cs
- Libplanet.Extensions.Cocona/Commands/KeyCommand.cs
- Libplanet.Extensions.Cocona/Commands/MptCommand.cs
- Libplanet.Extensions.Cocona/Configuration/MptConfiguration.cs
- Libplanet.Extensions.Cocona/Configuration/ToolConfiguration.cs
- Libplanet.Extensions.Cocona/ConsolePasswordReader.cs
- Libplanet.Extensions.Cocona/Extensions/ICoconaLiteServiceCollectionExtensions.cs
- Libplanet.Extensions.Cocona/Libplanet.Extensions.Cocona.csproj
- Libplanet.Extensions.Cocona/Services/IConfigurationService.cs
- Libplanet.Extensions.Cocona/Services/JsonConfigurationService.cs
- Libplanet.Extensions.Cocona/Utils.cs
- Libplanet.Tools/Program.cs
- Libplanet.sln
This pull request resolves #1206.
It separates `Libplanet.Tools` into `Libplanet.Tools` and `Libplanet.Extensions.Cocona`.
- The `Libplanet.Extensions.Cocona` package provides commands to handle `Libplanet` structures in command line (e.g. `IKeyStore`, `AppProtocolVersion`, `TrieStateStore`). 
- The `Libplanet.Tools` package is a tool, command set made up with commands `Libplanet.Extensions.Cocona`, which acts like before it does (i.e. `planet`).
Also, in code lines, there are the lines like below:
```csharp
#pragma warning disable SA1200
using Cocona;
#pragma warning restore SA1200
```
I used this preprocessor to ignore `SA1200` in temporally because there is conflict between `Libplanet.Extensions.Cocona` and `Cocona`. So I had thought what the best namespace is, like …
> feat(cli): move reusable commands into Libplanet.Extensions.Cocona

- CHANGES.md
- Libplanet.Tests/Net/Protocols/TestTransport.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/ITransport.cs
- Libplanet/Net/NetMQTransport.cs
- Libplanet/Net/PeerState.cs
- Libplanet/Net/Protocols/IProtocol.cs
- Libplanet/Net/Protocols/KademliaProtocol.cs
- Libplanet/Net/Swarm.cs
- Libplanet/Net/SwarmOptions.cs
This PR contains two changes:
- Added `SwarmOptions.RefreshPeriod` and `SwarmOptions.RefreshLifespan` which configures refresh of routing table. It have 10 seconds and 60 seconds as its default value.
- Removed `PeerState.Address`, added `PeerState.Peer` instead which has more information.
This contains one backward incompatible change and one behavioral change, please feel free two tell me if it will be better to separate two patches into two pull requests.
> Make `Swarm<T>.RefreshTableAsync` config constants configurable and change structure of `PeerState`

- CHANGES.md
- Libplanet.Stun.Tests/Stun/Messages/AllocateErrorResponseTest.cs
- Libplanet.Stun.Tests/Stun/Messages/AllocateSuccessResponseTest.cs
- Libplanet.Stun.Tests/Stun/Messages/BindingRequestSucessTest.cs
- Libplanet.Stun.Tests/Stun/Messages/ConnectionAttemptTest.cs
- Libplanet.Stun.Tests/Stun/Messages/ConnectionBindSuccessResponseTest.cs
- Libplanet.Stun.Tests/Stun/Messages/CreatePermissionSuccessResponseTest.cs
- Libplanet.Stun.Tests/Stun/Messages/RefreshErrorResponseTest.cs
- Libplanet.Stun.Tests/Stun/Messages/RefreshSuccessResponseTest.cs
- Libplanet.Stun/Stun/Messages/StunMessage.cs
- Libplanet.Stun/Stun/TurnClient.cs
- Libplanet/Net/BlockCompletion.cs
- Libplanet/Net/NetMQTransport.cs
- Libplanet/Net/Swarm.cs
Undiposed `CancellationTokenRegistration` were causing memory leak. This patch fixes the bug and made `TurnClient.ReceiveMessageAsync` cancellable.
Additionally this provides `CancellationToken` support for `StunMessage.ParseAsync()` (which was `SturnMessage.Parse()`).
> Dispose `CancellationTokenRegistration`s

- CHANGES.md
- Libplanet/Net/Protocols/KademliaProtocol.cs
This patch fixes a bug where protocol has been pinged to peers that were already pinged. Additionally, fixes duplicated cache updates.
> Enhance `KademliaProtocol.BootstrapAsync()`

- CHANGES.md
- Libplanet/Net/Swarm.cs
This patch refactors `Swarm<T>.AddPeersAsync()` to public which was internal before.
> Introduce `Swarm<T>.AddPeersAsync()`

- CHANGES.md
- Libplanet.Tests/Net/Protocols/TestTransport.cs
- Libplanet.Tests/Net/SwarmTest.Broadcast.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet.Tests/Net/Transports/BoundPeerExtensionsTest.cs
- Libplanet/Net/Messages/Message.cs
- Libplanet/Net/Protocols/KademliaProtocol.cs
- Libplanet/Net/Swarm.cs
- Libplanet/Net/Transports/BoundPeerExtensions.cs
- Libplanet/Net/Transports/ITransport.cs
- Libplanet/Net/Transports/NetMQTransport.cs
~This PR introduces `NetMQTransport.QueryAppProtocolVersion()` to get current APV of specific node via `Ping` message.~
This PR contains two changes
1. it moves `ITransport` and `NetMQTransport` to a new `Libplanet.Net.Transports` namespace.
2. it introduces `Libplanet.Net.Transports.BoundPeerExtensions` and `.QueryAppProtocolVersion()`  to get current APV of specific node via `Ping` message.
> Introduce BoundPeerExtensions and .QueryAppProtocolVersion()

- CHANGES.md
- Libplanet.Extensions.Cocona/Commands/ApvCommand.cs
- Libplanet.Extensions.Cocona/Libplanet.Extensions.Cocona.csproj
- Libplanet.Tests/Net/BoundPeerTest.cs
- Libplanet/Net/BoundPeer.cs
This PR adds two features as below. it addresses #1237 and #1238 
- Added `--json` flag to `planet apv analyze` to format the result as JSON.
- Added `planet apv query` subcommand.
And, it also adds `BoundPeer.Parse(string)` for convenience.
> Enrich `planet apv` command

- .azure-pipelines/dotnet-core.yml
- .azure-pipelines/mono.yml
- .azure-pipelines/windows-net471.yml
- .idea/.idea.Libplanet/.idea/indexLayout.xml
- CONTRIBUTING.md
- Libplanet.Tests/Net/FactOnlyTurnAvailableAttribute.cs
- Libplanet.Tests/Net/IceServerTest.cs
- Libplanet.Tests/Net/SwarmTest.cs
- azure-pipelines.yml
This patch makes the test suite to take multiple `TURN_SERVER_URLS` instead of a single `TURN_SERVER_URL` so that these loads that TURN/ICE servers receive become balanced.  I already configured `turnServerUrls` on Azure Pipelines too.
Read the changes in _CONTRIBUTING.md_ for details.
> Utilize multiple TURN/ICE servers to balance loads

- CHANGES.md
- Libplanet.Extensions.Cocona/Commands/KeyCommand.cs
It resolves #1213. See also https://github.com/planetarium/NineChronicles.Headless/pull/365
Also, it needs to write a unittest. The #1233 PR contains addition of the unittest project and I will open new pull request to complement unittests of commands. If the reviewers agree it, I will do it after the pull request merged.
> feat(cli): add `--no-passphrase` option into `key` command

- Libplanet.Tests/Blocks/InvalidBlockTxHashExceptionTest.cs
Typos in class name `InvalidBlocckTxHashExceptionTest` and file name `InvalidBlocckTxHashExceptionTest.cs` in `Libplanet.Tests` respectively changed to `InvalidBlockTxHashExceptionTest` and `InvalidBlockTxHashExceptionTest.cs`.
> Class and filename typo fixed

- CHANGES.md
- Libplanet.Extensions.Cocona/Commands/Key/ConversionCommand.cs
- Libplanet.Extensions.Cocona/Commands/Key/DerivationCommand.cs
- Libplanet.Extensions.Cocona/Commands/KeyCommand.cs
This pull request introdcues `planet key convert private-key` subcommand to provide conversion *private key → public key* and *private key → address*.
> feat(cli): introduce `planet key derive`

- CHANGES.md
- Libplanet/Net/Swarm.cs
- Libplanet/Net/Transports/NetMQTransport.cs
This PR enforces AsyncIO in `NetMQTransport`, instead of `Swarm<T>` to fix a bug where `NetMQTransport` had hung in Mono runtime without `Swarm<T>`.
> Enforce AsyncIO in NetMQTransport instead of Swarm<T>

- CHANGES.md
- Libplanet.Tests/Action/ActionContextTest.cs
- Libplanet.Tests/Action/ActionEvaluationTest.cs
- Libplanet.Tests/Blockchain/Renderers/AnonymousActionRendererTest.cs
- Libplanet.Tests/Blockchain/Renderers/AtomicActionRendererTest.cs
- Libplanet.Tests/Blockchain/Renderers/DelayedActionRendererTest.cs
- Libplanet.Tests/Blockchain/Renderers/LoggedActionRendererTest.cs
- Libplanet.Tests/Fixtures/Arithmetic.cs
- Libplanet.Tests/Fixtures/IntegerSet.cs
- Libplanet.Tests/Fixtures/OperatorType.cs
- Libplanet.Tests/Fixtures/OperatorTypeExtensions.cs
- Libplanet.Tests/RandomExtensions.cs
- Libplanet.Tests/Tx/TransactionTest.cs
- Libplanet/Action/ActionContext.cs
- Libplanet/Action/ActionEvaluation.cs
- Libplanet/Action/IActionContext.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Blockchain/Renderers/AtomicActionRenderer.cs
- Libplanet/Blockchain/Renderers/DelayedActionRenderer.cs
- Libplanet/Blockchain/Renderers/IActionRenderer.cs
- Libplanet/Tx/Transaction.cs
This addresses fixes <https://github.com/planetarium/libplanet/issues/1267>.
Previously, `Transaction<T>.Actions` had been executed and affected states whether the actions throw an exception or not.  However, as the term “transaction” in computer science in general imply it's atomic (i.e., executed all or nothing), this behavior had been quite misleading.
This patch regards such previous behavior as a bug, and fixes it so that if any action in a `Transaction<T>` throws an exception all actions in the transaction do not commit any state changes to the current `IStore`.
However, there is still a quirk for it: `IActionRenderer<T>` receives render events caused by unsuccessful transactions too, as it has done.  In other words, transactions' atomicity still is not guaranteed for action …
> Execute `Transaction<T>.Actions` all or nothing at all

- Libplanet/Libplanet.csproj
This PR bumps Planetatrium.NetMQ version to [4.0.0.261-planetarium](https://www.nuget.org/packages/Planetarium.NetMQ/4.0.0.261-planetarium).
I omitted the changelog since it doesn't have any interface/behavioral changes.
> Bump Planetarium.NetMQ

- .idea/.idea.Libplanet/.idea/indexLayout.xml
- Libplanet.Explorer/Queries/Query.cs
This pull request makes `Libplanet.Explorer.Queries.Query` to use chain & store directly from the source `IBlockChainContext<T>`. And it can be a bug in somewhere like [planetarium/NineChronicles.Headless](https://github.com/planetarium/NineChronicles.Headless), when the dependency injection order is not determined.
Though I thought the best way is to use `IStore` and `BlockChain<T>` through dependency injection pattern and to remove `Libplanet.Explorer.Query`'s static members, but I opened this pull request which fixed the bug simply because I have other my own other task 😢
> feat(explorer): use directly chain & store, from context

- .github/bin/bundle.sh
'Executeable' projects are don't include when bundle. (e.g Libplanet.Tools)
> Don't include executable project when bundle

- Libplanet/Blocks/Block.cs
> Fix typo `Block<T>.CalcualteTxHashes()` to `Block<T>.CalculateTxHashes()`

- .vscode/settings.json
- CHANGES.md
- Libplanet.Tests/Action/ActionContextTest.cs
- Libplanet.Tests/Action/ActionEvaluationTest.cs
- Libplanet.Tests/Blockchain/Renderers/AnonymousActionRendererTest.cs
- Libplanet.Tests/Blockchain/Renderers/DelayedActionRendererTest.cs
- Libplanet.Tests/Blockchain/Renderers/LoggedActionRendererTest.cs
- Libplanet.sln.DotSettings
- Libplanet/Action/ActionContext.cs
- Libplanet/Action/ActionEvaluation.cs
- Libplanet/Action/IActionContext.cs
Context: <https://github.com/planetarium/libplanet/issues/1295#issuecomment-842764538>
This reverts the PR #1296, and renames several misleading names.
> Remove `IActionContext.BlockHash` property

- CHANGES.md
- Libplanet.RocksDBStore/RocksDBStore.cs
- Libplanet.Tests/Store/StoreTest.cs
This PR address https://github.com/planetarium/libplanet/issues/1280. 
Basic idea is, re-use the previous chain instead of eliminating the full index copy when `RocksDBStore.ForkBlockIndexes()`. to accomplish this, it also changes `IterateIndexes()` and `IndexBlockHash()` to address the previous chain if needed.
~~Furthermore, all chains can be referenced by other chains, so `RocksDBStore.DeleteChainId()` needs to be modified as well. IMO, it can be possible if we have the reference for the source chain side too. but it may be too complicated to maintain... cc @planetarium/libplanet~~
Updated: I modified `RocksDBStore.DeleteChainId()` and related APIs (`.IterateIndexes()` and `.IndexBlockHash()`) to hide from public API when a chain with the fork is deleted.
These changes are compatible …
> Copy-less RocksDBStore.ForkBlockIndexes()

- Docs/build.ps1
Closes #1327 
From what I have checked, simply running `build.ps1` under Windows 10 with PowerShell 5.1, which is the current default version, seems to fail. This is due to variable scoping in the script.
Invoking
```
Remove-Item Alias:curl
```
once only removes the script scoped alias. However, globally scoped alias for `curl` persists, resulting in failure to run "actual" `curl` instead of `Invoke-WebRequest` cmdlet.
There are three ways to mitigate the issue:
- Invoke `Remove-Item Alias:curl` twice.
- Run the script with `. .\build.ps1` instead of `.\build.ps1` for the script to have the same environment as the invoking shell.
- Use "`wget`" instead of `curl`.
Of the three, the first two have the undesirable side-effect of having the alias removed from the invoking shell environment. …
> [skip changelog] Use wget over curl if possible

- CHANGES.md
- Libplanet.RocksDBStore/RocksDBStore.cs
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet/Store/DefaultStore.cs
This PR fixes a bug where `RocksDBStore.IterateIndexes()` had followed the previous branch even if has been forked.
And it also fixes a bug where `DefaultStore.ForkBlockIndexes()` hadn't copied the genesis block index.
* I skipped changelog because we didn't release the new version contains #1287
> Fix IterateIndexes() bug 

- Libplanet.Tests/Libplanet.Tests.csproj
- Libplanet.Tests/Net/FactOnlyTurnAvailableAttribute.cs
- Libplanet.Tests/Net/SwarmTest.Broadcast.cs
- Libplanet.Tests/Net/SwarmTest.Preload.cs
- Libplanet.Tests/Net/SwarmTest.cs
We have some flaky tests, and it seems these won't be fixed in the near future.  Instead of manually rerunning the whole CI/CD job to retry one or two failed tests among about 700 succeeded tests.  And these tend to fail even after several retries.
As the team @planetarium/libplanet became more members, there are more pending pull requests, and rebasing barely succeeded pull requests becomes more painful today.
Instead of bearing such pain, this pull request introduces [xRetry] which provides `[RetryFact]` and `[RetryTheory]` attributes.  I attributed some flaky tests as `[RetryFact]`/`[RetryTheory]` in this patch.  FYI I found the list of flaky tests from [Azure Pipelines' test failure report][1].
[xRetry]: https://github.com/JoshKeegan/xRetry
[1]: …
> Retry flaky tests using xRetry

- CHANGES.md
- Libplanet.Explorer/Store/LiteDBRichStore.cs
- Libplanet.Explorer/Store/MySQLRichStore.cs
- Libplanet.RocksDBStore/MonoRocksDBStore.cs
- Libplanet.RocksDBStore/RocksDBStore.cs
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet.Tests/Store/StoreTracker.cs
- Libplanet/Store/BaseStore.cs
- Libplanet/Store/DefaultStore.cs
- Libplanet/Store/IStore.cs
- codecov.yml
closes #1294 
Following APIs are added to `IStore`
```csharp
void PutTxIdBlockHashIndex(TxId txId, BlockHash blockHash);
BlockHash? GetFirstTxIdBlockHashIndex(TxId txId);
IEnumerable<BlockHash> IterateTxIdBlockHashIndex(TxId txId);
void DeleteTxIdBlockHashIndex(TxId txId, BlockHash blockHash);
```
* There exists only one record for a pair <TxId, BlockHash>.
* There are multiple BlockHash paired with the same TxId (consider `reorg` situation.)
> feat: introduce txid->blockhash index on IStore

- CHANGES.md
- Libplanet.Tests/Action/ActionEvaluatorTest.cs
- Libplanet.Tests/Common/Action/ThrowException.cs
- Libplanet/Action/ActionEvaluator.cs
Closes #1320.
Pretty lousy implementation at the moment. 😶 
There are two main concerns.
I thought about repackaging a caught exception to something like `CriticallyTerminatedActionException`, but for a critical exception such as `OutOfMemoryException`, decided it would be better not to try and instantiate any new exception.
Testing is flimsy. It would be much better to see if thrown exception gets caught on a higher level, such as `BlockChain<T>.Mine()` or `BlockChain<T>.Append()`, but this is made rather hard to test as actions are run with `rehearsal` set to `true` for creation of transactions and run with `rehearsal` set to `false` for creation of blocks through these methods. The best I could do was to observe a thrown exception from `ActionEvaluator<T>.Evaluate()`.
> Patch: Throw an unmanaged exception for critical failure during evaluation

- CHANGES.md
- Libplanet/Net/Transports/NetMQTransport.cs
This PR parallelizes message broadcasting in `Swarm<T>`.
> Parallelize broadcast

- CHANGES.md
- Libplanet/Net/Swarm.BlockSync.cs
- Libplanet/Net/Swarm.cs
- Libplanet/Net/SwarmOptions.cs
This PR adds `SwarmOptions.BranchpointThreshold` to enables API users to set a threshold value for branchpoint detecting.
> Add `SwarmOptions.BranchpointThreshold`

- Libplanet/Libplanet.csproj
- Libplanet/Net/BoundPeer.cs
- Libplanet/Net/Messages/BlockHashes.cs
- Libplanet/Net/Messages/ChainStatus.cs
- Libplanet/Net/Messages/Message.cs
- Libplanet/Net/Messages/Neighbors.cs
- Libplanet/Net/Peer.cs
This PR addresses #1309 by using `LogAsScalar` in [Destructurama.Attributed](https://github.com/destructurama/attributed).
I skipped the changelog since couldn't find the previous changelog about log restructuring. (if there is, please let me know).
> Scalarize fields in log

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
- Libplanet/Blockchain/BlockChain.cs
closes #1315 
`BlockChain<T>.Append()` cumulates indexes for pairs (TxId and BlockHash).
A transaction inclusion for a block is retrievable by using this index.
> feat: indexing TxId->BlockHash when appending block

- CHANGES.md
- Libplanet.Benchmarks/SwarmBenchmark.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/Swarm.cs
This PR adds the worker task to broadcast chain tip repeatedly.
> Introduce block broadcaster

- CHANGES.md
- Libplanet.Extensions.Cocona.Tests/Commands/StoreCommandTest.cs
- Libplanet.Extensions.Cocona/Commands/StoreCommand.cs
closes #1316 
add commands for indexing TxId->BlockHash
* planet store build-index-tx-block [STORE] [OFFSET] [LIMIT]
* planet store blocks-by-tx-id [STORE] [TX-ID]
* planet store block-hashes-by-tx-id [STORE] [TX-ID]
> CLI for `TxId` → `BlockHash` index

- CHANGES.md
- Libplanet/Net/Transports/NetMQTransport.cs
This PR remove `while` loop in `ProcessMessage()` to release `NetMQPoller` for `_router`. it's [common technique for poller performance](https://netmq.readthedocs.io/en/latest/poller/#performance), but in our case, it also can block other callbacks (i.e. `DoReply()`) that use poller.
> Fix replying delay

- Libplanet/Net/Swarm.cs
As `BlockLocator()` constructor already is ready for `indexBlockHash()` callback returning `null` (but is not ready for it throwing exceptions), make it to catch unexpected `ArgumentOutOfRangeException` and return `null` instead of throwing exceptions.
On the other hand, to investigate enough when such exception is thrown, I left a log with local variable values too.
Closes <https://github.com/planetarium/libplanet/issues/1346>.
> Catch `ArgumentOutOfRangeException` & return `null` instead during block sync

- CHANGES.md
- Libplanet/Net/Swarm.BlockSync.cs
This PR removes null check before chain swapping when block synchronization. it's to fail quickly instead of malfunctioning when a problem situation such as #1349
> Fail-fast when block sync

- CHANGES.md
- Libplanet.Extensions.Cocona.Tests/Commands/StatsCommandTest.cs
- Libplanet.Extensions.Cocona/AssemblyInfo.cs
- Libplanet.Extensions.Cocona/Commands/StatsCommand.cs
- Libplanet.Tools/Program.cs
A rudimentary implementation of extracting stored blockchain information. See the provided help text for usage.
```
Usage: Libplanet.Tools stats [--path <String>] [--header] [--offset <Int64>] [--limit <Nullable`1>] [--help]
Outputs a summary of a stored chain in a CSV format.
Options:
-p, --path <String>         The URI denoting the type and the path of a concrete class for IStore; given as <store-type>://<store-path> (Required)
-r, --header                Whether to include header row
-o, --offset <Int64>        Starting index offset; supports negative indexing (Default: 0)
-l, --limit <Nullable`1>    Maximum number of results to return; no limit by default
-h, --help                  Show help message
```
Outputs to a terminal, so pipe accordingly. Output is in a CSV format with the …
> New stats command added to planet cli

- CHANGES.md
- Libplanet.Tests/Tx/TransactionTest.cs
- Libplanet/Tx/Transaction.cs
This pull request introduces `Transaction.CreateUnsigned()` factory method to create *unsigned transaction* easily.
> feat: introduce factory method to create unsigned tx

- CHANGES.md
- Libplanet/Blockchain/BlockChain.cs
This PR simply exposes `BlockChain<T>.ExecuteActions()` for better benchmarking in `lib9c`.
> ExecuteActions made public for benchmarking usage

- Libplanet/Tx/Transaction.cs
Fixed a  typo in line 399 of transaction.cs. 
Closes #1376
> Fixed a typo in transaction.cs on line 399

- CHANGES.md
- Libplanet.Tests/Net/Protocols/RoutingTableTest.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/Protocols/RoutingTable.cs
- Libplanet/Net/Swarm.cs
- Libplanet/Net/SwarmOptions.cs
This patch addresses issue #1230 continue to #1271.
#1271 caused network overload to the single static peer because it selected at least one peer from the static peers when broadcasting messages. In this patch, revert changes in the routing table. Now static peers are dealt same with normal peers. Instead a task named `MaintainStaticPeersAsync()` in `Swarm<T>` checks whether the peer is existing in the table periodically, if not, send a message to add the peer to the table.
> Maintain static peers in `Swarm<T>`

- CHANGES.md
- Libplanet/Net/Swarm.cs
This PR changes the `BlockCompletion` predicate to use the `ContainsBlock` method of `IStore` instead of `BlockChain`. This way, `Swarm` won't have to download blocks again if preloading is aborted during the `Block Execution` stage.
> Find blocks in store instead of in chain

- CHANGES.md
- Libplanet/Net/Transports/NetMQTransport.cs
This occurs intermittently, but when it occur, `Swarm<T>` stops. This patch fixes the case when `ObjectDisposedException` occurs. Closes #1361 and #1362.
> Prevent ObjectDisposedException during NetMQTransport.DoBroadcast()

- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.Fixtures.cs
- Libplanet/Net/Swarm.cs
- Libplanet/Net/SwarmOptions.cs
This PR allows `SwarmOptions` to control `TableSize` and `BucketSize` of the `RoutingTable`.
> Configurable bucket size

- CHANGES.md
- Libplanet.Tests/HashAlgorithmTypeTest.cs
- Libplanet/HashAlgorithmType.cs
As `HashAlgorithm.ComputeHash()` method is not guaranteed thread-safe, this patch makes `HashAlgorithmType`'s internal `HashAlgorithm` instances thread-local.
Read also the following article: [*C# Cautionary Tale — The dangers of SHA256 reuse*](https://wanderingdeveloper.medium.com/c-cautionary-tail-the-dangers-of-sha256-reuse-2b5bb9c6fde9).
> Hotfix: Make `HashAlgorithmType.Digest()` thread-safe

- azure-pipelines.yml
Since mono and .NET Framework will not be supported, testbed for those environment removed. I've left `.azure_pipelines/windows-net471.yml` for future support for `Windows_Unity`.
Closes #1374
> Remove testbed for mono and .NET Framework

- Libplanet.Tests/Libplanet.Tests.csproj
On VSCode, the following errors persist:
```
The type 'IAsyncEnumerable<>' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. [Libplanet.Tests]
```
[AsyncEnumerator](https://www.nuget.org/packages/AsyncEnumerator/) requires [Microsoft.Bcl.AsyncInterfaces](https://www.nuget.org/packages/Microsoft.Bcl.AsyncInterfaces/) only on certain target frameworks, but dependency does not seem to resolve properly with OmniSharp on VSCode.
This might not be a proper solution, but does get rid of numerous pesky error messages on VSCode. 🙃
> Explicit package reference to Microsoft.Bcl.AsyncInterfaces

- CHANGES.md
- Libplanet.Stun/Stun/TurnClient.cs
This PR fixes reconnecting logic for TURN connections.
- Lib9c bump: https://github.com/planetarium/lib9c/pull/536
- 9c Headless bump: https://github.com/planetarium/NineChronicles.Headless/pull/602
- 9c Unity bump: https://github.com/planetarium/NineChronicles/pull/578
> Release 0.13.2 & Fix TURN reconnection

- .azure-pipelines/dotnet-core.yml
- CHANGES.md
- Libplanet.Tests/Blockchain/Renderers/NonblockActionRendererTest.cs
- Libplanet.Tests/Blockchain/Renderers/NonblockRendererTest.cs
- Libplanet/Blockchain/Renderers/DelayedActionRenderer.cs
- Libplanet/Blockchain/Renderers/NonblockActionRenderer.cs
- Libplanet/Blockchain/Renderers/NonblockRenderer.cs
- azure-pipelines.yml
This implements <https://github.com/planetarium/libplanet/issues/1402>.
> Currently `BlockChain<T>` and `Swarm<T>` wait for registered renderers to get their jobs done for every render event.  These render calls can be nonblocking if there is a renderer decorator which maintains its own background thread and a queue/channel to communicate between the main thread and the background thread.
----
Relevant pull requests on Nine Chronicles:
- <https://github.com/planetarium/lib9c/pull/532>
- <https://github.com/planetarium/NineChronicles.Headless/pull/599>
> Non-blocking renderers

- CHANGES.md
- Libplanet/Action/IRandom.cs
- Libplanet/Action/Random.cs
This PR introduces `IRandom.Seed` to enable store and send replayable random seed to other nodes. 
Basically, `System.Random` is `[Serializable]` but we're using an inheritanced version(`Libplanet.Actions.Random`) and it can't be serialized natively.
---
Lib9c: https://github.com/planetarium/lib9c/pull/556
NineChronicles: https://github.com/planetarium/NineChronicles/pull/627
NineChronicles.Headless: https://github.com/planetarium/NineChronicles.Headless/pull/625
> Add IRandom.Seed

- Libplanet/Blockchain/Renderers/LoggedRenderer.cs
- Libplanet/Net/Swarm.cs
- Libplanet/Net/Transports/NetMQTransport.cs
General QoL improvement for log parsing.
Although `SourceContext` is always provided, due to generic classes and usage of fully qualified name, directly using `SourceContext` results in something akin to:
```
[09:16:29 DBG] Libplanet.Net.BlockCompletion`2[[Libplanet.Net.BoundPeer, Libplanet, Version=0.12.0.0, Culture=neutral, PublicKeyToken=null],[Libplanet.Action.PolymorphicAction`1[[Nekoyume.Action.ActionBase, Lib9c, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]], Libplanet, Version=0.12.0.0, Culture=neutral, PublicKeyToken=null]] Downloaded a block #2122913 8af712404f75ec894b9c8474fa6f04f21933953f7bafaabaf5ddcbe0aa8a37c6 from 0xc1BF31cb992aCfb82EAe8f57Ee4fF455B18A679E.Unspecified/3.22.224.238:56104.73.111.87.115.
```
This is just an ad hoc improvement. Proper implementation …
> Shortened source tagging

- .github/bin/dist-pack.sh
- README.md
This adds Git commit hashes to version suffixes of prereleases.  See also the [diff of README.md](https://github.com/dahlia/libplanet/commit/648768c3ca1c984130cc912fe55f24bcb46e6cc3?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5).
> Append Git commit hash to version suffix

- CHANGES.md
- Libplanet.Explorer.Executable/Program.cs
- Libplanet.Tests/Blockchain/NullPolicy.cs
- Libplanet.Tests/Blockchain/Renderers/DelayedRendererTest.cs
- Libplanet.Tests/Blockchain/TotalDifficultyComparerTest.cs
- Libplanet.Tests/Net/SwarmTest.Consensus.cs
- Libplanet/Blockchain/Policies/BlockPolicy.cs
- Libplanet/Blockchain/Policies/IBlockPolicy.cs
- Libplanet/Blockchain/Renderers/DelayedActionRenderer.cs
- Libplanet/Blockchain/Renderers/DelayedRenderer.cs
- Libplanet/Blockchain/TotalDifficultyComparer.cs
- Libplanet/Net/BlockDemandTable.cs
- Libplanet/Net/Swarm.BlockSync.cs
- Libplanet/Net/Swarm.cs
Preparatory refactoring for #1435.
This prepares for #1443. Although not strictly necessary, this allows to remove unnecessary parameters from `BlockDemandTable` class. 😛 
----
- <https://github.com/planetarium/libplanet/pull/1440>
- <https://github.com/planetarium/libplanet/pull/1442>
- <https://github.com/planetarium/libplanet/pull/1443>
- <https://github.com/planetarium/lib9c/pull/589>
- <https://github.com/planetarium/NineChronicles.Headless/pull/663>
> Comparers genericized to use `IComparer<IBlockExcerpt>`

- CHANGES.md
- Libplanet/Blockchain/TotalDifficultyComparer.cs
- Libplanet/Net/BlockDemandTable.cs
- Libplanet/Net/Swarm.MessageHandlers.cs
- Libplanet/Net/Swarm.cs
Closes #1435 and #1444.
`BlockDemand` handling inside `BlockDemandTable` class is overhauled. `BlockPerception` is no longer used for comparers. Removing "stale" `BlockDemand` is handled using internally stored `blockdemandLifespan`, which can be set on runtime.
----
- <https://github.com/planetarium/libplanet/pull/1440>
- <https://github.com/planetarium/libplanet/pull/1442>
- <https://github.com/planetarium/libplanet/pull/1443>
- <https://github.com/planetarium/lib9c/pull/589>
- <https://github.com/planetarium/NineChronicles.Headless/pull/663>
> Prevent tip regression

- CHANGES.md
- Libplanet.Tests/Net/Protocols/TestTransport.cs
- Libplanet.Tests/Net/SwarmTest.Broadcast.cs
- Libplanet/Net/Swarm.cs
- Libplanet/Net/Transports/ITransport.cs
- Libplanet/Net/Transports/NetMQTransport.cs
Previously, the failure of receiving any messages leads to the failure of the whole process. This patch adds `ITransport.SendMessageWithReplyAsync(BoundPeer peer, Message message, TimeSpan? timeout, int expectedResponses, bool returnWhenTimeout, CancellationToken cancellationToken)` method to handle the case by hand over `returnWhenTimeout` argument to true.
> Dealing the timeout of the request of multiple replies & Release 0.15.2

- CHANGES.md
- Libplanet.Tests/Action/ActionEvaluatorTest.cs
- Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
- Libplanet.Tests/Blockchain/BlockChainTest.Internals.cs
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Blockchain/Renderers/DelayedActionRendererTest.cs
- Libplanet.Tests/Net/SwarmTest.Broadcast.cs
- Libplanet.Tests/Net/SwarmTest.Preload.cs
- Libplanet/Blockchain/BlockChain.MineBlock.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Net/Swarm.BlockSync.cs
Closes #1462.
Should be fine as a standalone PR as lib9c does not seem to make any `Append()` call with a timestamp.
> Unnecessary parameter removed from Append()

- .github/bin/dist-pack.sh
- CHANGES.md
- Libplanet.Tests/Blocks/BlockHeaderTest.cs
- Libplanet.Tests/Blocks/BlockTest.cs
- Libplanet.Tests/RandomExtensions.cs
- Libplanet.Tests/TestUtils.cs
- Libplanet.Tests/Tx/TxFailureTest.cs
- Libplanet.Tests/Tx/TxSuccessTest.cs
- Libplanet/Blocks/Block.cs
- Libplanet/Blocks/BlockHeader.cs
- Libplanet/Net/Swarm.BlockSync.cs
- Libplanet/Net/Swarm.MessageHandlers.cs
- Libplanet/Store/BaseStore.cs
- README.md
Instead of `string`s and `ImmutableArray<byte>`s, this patch gives `BlockHeader`'s fields richer types like `DateTimeOffset`, `BlockHash`, `Nonce`, and `HashDigest<SHA256>`.
> Represent `BlockHeader`'s fields as richer types
