- Libplanet.Explorer/Controllers/ExplorerController.cs
- Libplanet.Tests/AddressExtensionTest.cs
- Libplanet.Tests/AddressTest.cs
- Libplanet.Tests/Blocks/BlockTest.cs
- Libplanet.Tests/TestUtils.cs
- Libplanet/Action/AddressStateMap.cs
- Libplanet/Address.cs
- Libplanet/Store/FileStore.cs
It adds a constructor which takes a hexadecimal address string(#33).
> Add a constructor which takes a hexadecimal address string

- Libplanet/Libplanet.csproj
- publish.sh
A project icon image and a Markdown description were added.
> More NuGet metadata

- Libplanet.Tests/Action/ActionContextTest.cs
- Libplanet.Tests/Common/Action/Attack.cs
- Libplanet.Tests/Common/Action/BaseAction.cs
- Libplanet.Tests/Common/Action/DummyAction.cs
- Libplanet.Tests/Common/Action/Sleep.cs
- Libplanet/Action/ActionContext.cs
- Libplanet/Action/IAction.cs
- Libplanet/Action/IActionContext.cs
- Libplanet/Blockchain.cs
Side effect
- Increment random seed for each actions (was for each transactions)
> Move all parameters of IAction.Execute to IActionContext

- Libplanet/Tx/TxId.cs
This patch eliminates boilerplate code to implement `IEquatable<TxId>` by using `[Uno.GeneratedEquality]` attribute.
> Get rid of IEquatable<TxId> boilerplate for TxId

- Libplanet.Explorer/ViewModels/BlockViewModel.cs
- Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs
- Libplanet.Tests/Blocks/BlockTest.cs
- Libplanet.Tests/HashcashTest.cs
- Libplanet.Tests/TestUtils.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Blockchain/Policies/BlockPolicy.cs
- Libplanet/Blockchain/Policies/IBlockPolicy.cs
- Libplanet/Blocks/Block.cs
- Libplanet/Blocks/RawBlock.cs
- Libplanet/HashDigest.cs
- Libplanet/Hashcash.cs
- Libplanet/Store/BaseStore.cs
- Libplanet/Store/FileStore.cs
- Libplanet/Store/IStore.cs
It resolves #61.
It looks good to me for converting unsigned to signed with no additional codes.
> Convert unsigned to signed

- .editorconfig
- .travis.yml
- CONTRIBUTING.md
- Libplanet.Explorer/Controllers/ExplorerController.cs
- Libplanet.Explorer/ExplorerStartup.cs
- Libplanet.Explorer/Interfaces/IBlockchainStore.cs
- Libplanet.sln.DotSettings
- hooks/pre-commit
I wrote a small shell script to check if any text files have BOM (and trim with `--apply` option), and some guide for contributors.
> Contributor guide and BOM checker

- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Store/AddressTransactionSetTest.cs
- Libplanet.Tests/Store/BlockSetTest.cs
- Libplanet.Tests/Store/FileStoreFixture.cs
- Libplanet.Tests/Store/FileStoreTest.cs
- Libplanet.Tests/Store/TransactionSetTest.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Net/Swarm.cs
- Libplanet/Store/AddressTransactionSet.cs
- Libplanet/Store/BaseIndex.cs
- Libplanet/Store/BaseStore.cs
- Libplanet/Store/BlockSet.cs
- Libplanet/Store/FileStore.cs
- Libplanet/Store/IStore.cs
- Libplanet/Store/TransactionSet.cs
It introduces `BlockChain.Fork()` to handle branch on block receiving safely. to accomplish that, it also added namespace concept to `IStore` / `FileStore` (using subdirectory).
> Added BlockChain.Fork()

- CONTRIBUTING.md
- Docs/CONTRIBUTING.md
- Docs/toc.yml
- README.md
Wrote a short guide to set up basic development environmnt, and linked our Discord server.  Added some shiny badges too.
> Contributor guide

- Libplanet.Tests/Action/ActionContextTest.cs
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet/Action/ActionContext.cs
- Libplanet/Action/IActionContext.cs
- Libplanet/Blockchain/BlockChain.cs
Haven't tested it yet but it probably works.
> Add BlockIndex to ActionContext. Closes #102

- CHANGES.md
- README.md
If this is merged I'm going to tag the merge commit with 0.1.0.
> Release 0.1.0

- .travis.yml
- Libplanet/Libplanet.csproj
I missed this at the previous PR (#109).  I'm going to tag the merge commit with 0.1.0 again.
> Proper NuGet package version for 0.1.0

- .travis.yml
- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/Swarm.cs
This PR fixes some glitches in `Swarm` and `SwarmTest`.
> Stabilize Swarm and SwarmTest

- CHANGES.md
- Libplanet/Libplanet.csproj
> Release 0.1.1

- .travis.yml
- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/Swarm.cs
- publish.sh
As we've released 0.1.1, let's port back thoes fixes made from that branch to the master branch.
Reviewers are enough to see only the last merge commit: efc91b36f49e3e7a3e5e8ac56866318128190b70.
> Backport fixes from 0.1.1

- Libplanet.Tests/TestUtils.cs
- Libplanet/Blocks/Block.cs
- Libplanet/Blocks/RawBlock.cs
> Typo fix : Benificiary -> Beneficiary

- CHANGES.md
- Libplanet.Tests/AddressTest.cs
- Libplanet.Tests/Tx/TxIdTest.cs
- Libplanet/Address.cs
- Libplanet/Tx/TxId.cs
> Make Address and TxId serializable

- CHANGES.md
- Docs/build.ps1
- Libplanet.Tests/Common/Action/DetectRehearsal.cs
- Libplanet.Tests/Common/Action/ThrowException.cs
- Libplanet.Tests/Tx/TransactionTest.cs
- Libplanet/Tx/InvalidTxException.cs
- Libplanet/Tx/InvalidTxUpdatedAddressesException.cs
- Libplanet/Tx/Transaction.cs
- Libplanet/Tx/UnexpectedlyTerminatedTxRehearsalException.cs
> UnexpectedlyTerminatedTxRehearsalException

- Libplanet.Tests/Serialization/Bencodex/BencodexFormatterTest.cs
- Renamed BencodeFormatterTest to BencodexFormatterTest
> Rename BencodeFormatterTest to BencodexFormatterTest

- Libplanet.sln
- Fixed `Solution 'Libplanet' load failed:` due to a syntax error.
> Fix solution syntax

- Libplanet.Explorer/Controllers/ExplorerController.cs
- Libplanet.Explorer/Interfaces/IBlockchainStore.cs
- Added `ChainId` to IBlockchainStore to get a specific blockchain.
> Modify Block Explorer to get chain ID

- CHANGES.md
- Libplanet/Libplanet.csproj
> Release 0.2.0

- CHANGES.md
- Libplanet/Libplanet.csproj
Let's start to work on the next minor release!
> Version bump

- .travis.yml
- CHANGES.md
- Docs/publish.sh
- Libplanet/Libplanet.csproj
This patch fixed a release script bug (#179) that *\*.nupkg* file had not been uploaded, and also releases 0.2.2.
> Fix a release script bug (#179) and release 0.2.2

- CHANGES.md
> Release 0.3.0

- .github/bin/dist-release-note.sh
This fixes the condition of checking release date.
> Fix checking release date

- Libplanet/Action/IAction.cs
I elaborate on the relationship of `IAction` code and its property values from a perspective of security.
Preview: <https://docs.libplanet.io/action-docs/api/Libplanet.Action.IAction.html>
> A note on security of IAction objects

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet.Tests/Store/StoreTracker.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Net/Swarm.cs
- Libplanet/Store/BaseStore.cs
- Libplanet/Store/FileStore.cs
- Libplanet/Store/IStore.cs
- Libplanet/Store/LiteDBStore.cs
This makes `Swarm` broadcast transactions periodically. To do this, I make staged `Transaction`s store whether to broadcast.
> Make Swarm broadcast transactions periodically

- CONTRIBUTING.md
CONTRIBUTING.md need troubleshooting. Create a troubleshooting contents on CONTRIBUTING.md.
> Creating a troubleshooting section on CONTRIBUTING.md

- Libplanet.Stun.Tests/Libplanet.Stun.Tests.csproj
- Libplanet.Stun.Tests/Stun/Attributes/StunAddressExtensionTest.cs
- Libplanet.Stun.Tests/Stun/Attributes/UserNameTest.cs
- Libplanet.Stun.Tests/Stun/Messages/AllocateRequestTest.cs
- Libplanet.Stun.Tests/Stun/Messages/BindingRequestTest.cs
- Libplanet.Stun.Tests/Stun/Messages/ConnectionBindRequestTest.cs
- Libplanet.Stun.Tests/Stun/Messages/CreatePermissionRequestTest.cs
- Libplanet.Stun.Tests/Stun/Messages/RefreshErrorResponseTest.cs
- Libplanet.Stun.Tests/Stun/Messages/RefreshRequestTest.cs
- Libplanet.Stun/Libplanet.Stun.csproj
- Libplanet.Tests/Blocks/BlockTest.cs
- Libplanet.Tests/Crypto/SymmetricKeyTest.cs
- Libplanet.Tests/Libplanet.Tests.csproj
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet.Tests/Store/FileStoreTest.cs
- Libplanet/Libplanet.csproj
- Menees.Analyzers.Settings.xml
> Apply style lints to test projects

- CHANGES.md
This PR fixes the release date of `0.4.0` to 2019-07-08.
> Release 0.4.0

- CHANGES.md
- Libplanet/Libplanet.csproj
This PR make to ready this project to 0.5.0-dev. this also includes #335
> Feature/ready 0.5.0

- Libplanet/Blockchain/BlockChain.cs
This adds rwlock for state reference.
> Add rwlock for state reference

- Libplanet/Blocks/Block.cs
It's quick and dirty, but anyway seems to work.  We should refactor this in a proper way in the near future…
> Make stamping blocks efficient for higher hash rate

- Libplanet.Tests/Store/StoreExtensionTest.cs
- Libplanet/Net/Swarm.cs
- Libplanet/Store/StoreExtension.cs
This patch fixes two one-by-off errors I made in the previous patches, #374 & #385.
> Two one-by-off errors 🙄

- CHANGES.md
- Libplanet.Stun/Stun/TurnClient.cs
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet.Tests/Store/LiteDBStoreTest.cs
- Libplanet.Tests/Store/StoreExtensionTest.cs
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet.Tests/Store/StoreTracker.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Blocks/Block.cs
- Libplanet/Libplanet.csproj
- Libplanet/Net/BlockDownloadState.cs
- Libplanet/Net/Messages/GetRecentStates.cs
- Libplanet/Net/Swarm.cs
- Libplanet/Store/BaseIndex.cs
- Libplanet/Store/BaseStore.cs
- Libplanet/Store/BlockSet.cs
- Libplanet/Store/FileStore.cs
- Libplanet/Store/IStore.cs
- Libplanet/Store/LiteDBStore.cs
- Libplanet/Store/StoreExtension.cs
- Libplanet/Store/TransactionSet.cs
- azure-pipelines.yml
This PR apply changes in `upstream/9c-fft` to master.
> Merge 9c-fft to master

- .gitignore
- Libplanet.Benchmarks/Libplanet.Benchmarks.csproj
- Libplanet.Benchmarks/MineBlock.cs
- Libplanet.Benchmarks/Program.cs
- Libplanet.sln
- azure-pipelines.yml
This adds Libplanet.Benchmarks. Currently, it has only MineBlock benchmarks.
This closes #361.
> Add Libplanet.Benchmarks

- Libplanet/Net/Swarm.cs
This PR fixes a bug that `Swarm<T>` had deleted a store namespace unexpectedly when any exception occurred in `SyncPreviousBlocksAsync()`.
I've omitted the changelog because this bug hadn't occurred in 0.4.0.
> Fix a namespace deletion bug

- Libplanet/Net/Swarm.cs
This fixes a problem where `receivedBlockCount` is reset when an exception occurs during `FillBlocksAsync`.
> Fix receivedBlockCount to handle retries

- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Net/Messages/BlockHashes.cs
This improves `BlockHashes` performance.
> Improve BlockHashes performance

- Libplanet.Tests/Store/FileStoreFixture.cs
> Fixed a FileStoreFixture bug

- CHANGES.md
- Libplanet.Tests/Action/ActionContextTest.cs
- Libplanet/Action/ActionContext.cs
- Libplanet/Action/IActionContext.cs
> Implement deterministic Guid

- CHANGES.md
> Release 0.5.0

- CHANGES.md
- Libplanet/Net/Swarm.cs
This PR ensures resource disposing of resources in `Swarm<T>`.
> Dispose _turnClient properly

- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Net/Swarm.cs
This PR rebase #444 on the current master and adds default values.
Resolve #407
> Move BlockChain<T>.FindNextHashesChunkSize to Swarm<T>.FindNextHashesChunkSize 

- CHANGES.md
> Release 0.5.2

- .azure-pipelines/mono.yml
- .azure-pipelines/windows-net461.yml
- CHANGES.md
- Libplanet.Stun/Stun/TurnClient.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet/Store/LiteDBStore.cs
- azure-pipelines.yml
See also <https://github.com/planetarium/libplanet/releases/tag/0.5.2>.
> Port 0.5.2

- Libplanet.Tests/Net/SwarmTest.cs
This resolves #499 I guess.
This PR fixes problem concerned with file IO exception in test.
> Fix BroadcastBlockToReconnectedPeer test

- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/Protocols/KademliaProtocol.cs
- Libplanet/Net/Swarm.cs
This resolves #488, resolves #490, resolves #491, resolves #492 (maybe?)
> Prevent close using dealer

- .azure-pipelines/mono.yml
- .azure-pipelines/windows-net461.yml
- Libplanet.Tests/xunit.runner.mono.json
- Libplanet/Store/LiteDBStore.cs
This PR aids some troubles during testing on a mono environment.
> Adjust test options

- CHANGES.md
- Libplanet.Tests/Action/ActionContextTest.cs
- Libplanet/Action/RandomExtension.cs
This changes `GenerateRandomGuid` implement RFC 4122.
> Implement RFC 4122

- Libplanet/Net/Protocols/KademliaProtocol.cs
Now, `KademliaProtocol.FindPeerAsync()`  finds closest peer by recursive query.
But it can let `KademliaProtocol.BootstrapAsync()` use long time.
So, this pull-request makes it be limited with depth to prevent that situation.
> Limit to find peer depth

- .github/workflows/main.yml
I missed this in the previous patch (#532).
> Add pull request event to the GitHub Actions workflow

- Libplanet/Net/Protocols/KademliaProtocol.cs
> ProcessFoundAsync() become to ping found neighbors in parallel

- .github/workflows/rebase.yml
Adds Rebase PR Action to rebase PR automatically.
> Use Rebase PR Action

- Libplanet/Hashcash.cs
> Remove the duplicate difficulty check for 0

- Libplanet/Blockchain/BlockChain.cs
[changelog skip]
PR Should Address #523
> Avoids re-sorting transactions when appending the already sorted block to the blockchain

- .github/bin/dist-github-release.sh
This PR fixes a bug that github action runs at release fails.
> Fix github action

- CHANGES.md
- Libplanet.Stun/Stun/TurnClient.cs
- Libplanet/Net/DifferentProtocolVersionEventArgs.cs
- Libplanet/Net/Swarm.cs
Changed all occurrences of occured to occurred.
Fixes #393
> Fixed typo

- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/Swarm.cs
> Fixed a bug during sync blocks when blockchain is empty

- CHANGES.md
- Libplanet/Store/LiteDBStore.cs
This PR adds block mutex to `LiteDBStore` to guarantee atomicity.
> Add block mutex to LiteDBStore

- Libplanet/Net/Swarm.cs
This PR fixes #582. I omitted changelog because #582 had occurred after #576 isn't released yet.
> Prevent re-download genesis

- Libplanet/Blockchain/BlockChain.cs
I added some logging to `BlockChain<T>` with context of its class.
> Log blockchain

- Libplanet/Net/Protocols/KademliaProtocol.cs
- Libplanet/Net/Swarm.cs
To reduce log messages, I removed variable contents in the log.
> Do not display variable contents in log

- Libplanet/Net/Swarm.cs
This fixes `ProcessRuntime` to retry when an exception occurs while processing the request.
Because NetMQ Runtime is introduced in 0.7.0, I skipped the changelog.
> Retry request when an exception occurs in ProcessRuntime

- Libplanet.Benchmarks/Libplanet.Benchmarks.csproj
- Libplanet.Stun.Tests/Libplanet.Stun.Tests.csproj
- Libplanet.Stun/Libplanet.Stun.csproj
- Libplanet.Tests/Libplanet.Tests.csproj
- Libplanet/Libplanet.csproj
- Libplanet/Net/Swarm.cs
> Support .NET Core 3.0

- README.md
A grammar issue fixed by removing 'a' from sentence in README.md file [changelog skip]
> Grammar issue fixed

- Libplanet.Tests/Net/ProtocolTest.cs
- Libplanet/Net/Protocols/KBucket.cs
- Libplanet/Net/Protocols/KademliaProtocol.cs
- Libplanet/Net/Protocols/RoutingTable.cs
And removed unnecessary `using` phrases, added new logging.
> Prevent redundant caching

- CHANGES.md
- Libplanet.Stun/Stun/TurnClient.cs
- Libplanet.Tests/Net/IceServerTest.cs
- Libplanet/Net/IceServer.cs
This PR fixes URLs in `IceServerTest`'s fixture to avoid unexpected hanging.
> Fix IceServerTest hanging

- .github/stale.yaml
This automatically closes stale issues (and PRs).
> Add github stale bot

- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Blocks/BlockTest.cs
- Libplanet.Tests/Common/Action/Attack.cs
- Libplanet.Tests/Common/Action/DetectRehearsal.cs
- Libplanet.Tests/Common/Action/DumbAction.cs
- Libplanet.Tests/Common/Action/MinerReward.cs
- Libplanet.Tests/Common/Action/Sleep.cs
- Libplanet.Tests/Common/Action/ThrowException.cs
- Libplanet.Tests/Libplanet.Tests.csproj
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet.Tests/Tx/TransactionTest.cs
- Libplanet/Action/IAction.cs
- Libplanet/Action/PolymorphicAction.cs
- Libplanet/Libplanet.csproj
Bumped packages below.
- Bencodex: 0.1.0 -> 0.2.0
- System.Collections.Immutable: 1.5.0 -> 1.6.0 (by dependecies of bencodex)
> Bump bencodex version to 0.2.0

- CHANGES.md
Describe changes in higher level, hiding internal and private classes. (`KademliaProtocol<T>`, `IProtocol`, `KBucket`)
> Reword changelog

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Net/Swarm.cs
This fixes a bug where the chain is forked when a branch point doesn't exist in the chain.
Resolves #651 
Resolves #652
> Fix a bug where the chain is forked when a branch point doesn't exist

- .github/workflows/benchmarks.yml
- CONTRIBUTING.md
- Libplanet.Benchmarks/Store.cs
- Libplanet.Tests/TestUtils.cs
- azure-pipelines.yml
Added some benchmarks on basic `IStore` operations.  Also wrote minimal docs on how to run benchmarks.  As benchmarks take too long time on the CI, `-j short` option is also added.
> Store benchmarks

- Libplanet.Stun/Stun/TurnClient.cs
- Libplanet.ruleset
- Libplanet/Serialization/BencodexFormatterConverter.cs
- Libplanet/Store/BaseStore.cs
- Libplanet/Store/LiteDBStore.cs
> Remove Sonar Analyzer suppression S927

- CHANGES.md
- Libplanet.Tests/Store/DefaultStoreFixture.cs
- Libplanet.Tests/Store/DefaultStoreTest.cs
- Libplanet/Store/DefaultStore.cs
> Make DefaultStore constrcutor to accept relative path

- CHANGES.md
- Libplanet/Net/Messages/GetBlocks.cs
- Libplanet/Net/Swarm.cs
- hooks/check-changelog
- hooks/pre-commit
At the moment, I only decreased the hard-coded number.  I will add an option to configure this in the next patch.
Also added a small hook script to check duplicated link definitions in *CHANGES.md* docs.
> Decrease window to fetch blocks at IDL time from 500 to 100

- Libplanet.Tests/Net/Protocols/RoutingTableTest.cs
- Libplanet.Tests/Net/Protocols/TestSwarm.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/Protocols/IProtocol.cs
- Libplanet/Net/Protocols/KBucket.cs
- Libplanet/Net/Protocols/KademliaProtocol.cs
- Libplanet/Net/Protocols/RoutingTable.cs
- Libplanet/Net/Swarm.cs
> Make KBucket used in Kademlia protocol concurrent

- Libplanet/Store/DefaultStore.cs
This PR adds state cache to `DefaultStore`. I've to skip the changelog because `DefaultStore` isn't released yet.
> Add states cache to DefaultStore

- Libplanet.Benchmarks/SwarmBenchmark.cs
- Libplanet/Blockchain/BlockChain.cs
I added a benchmark for the case of block broadcasting relay through multiple swarms.
> Block relay benchmark

- Docs/articles/overview.md
- Docs/articles/toc.yml
- Docs/toc.yml
This PR adds overview docs (from [planet-clicker's](https://github.com/planetarium/planet-clicker/blob/87073d99372d602879704ea078d37a4a04d8896c/OVERVIEW.md)). I'll re-organize overview and design docs in next PR.
It resolves #659
> Add overview page

- Libplanet.Tests/Net/SwarmTest.cs
> Fix a bug that ExchangeWithIceServer hadn't used TURN relay

- Libplanet/Net/Swarm.cs
This adjusts the timeout value of `Swarm<T>`.
> Adjust timeout value of Swarm<T>

- CHANGES.md
- Libplanet/Net/Swarm.cs
Changed `TxReceived`, `BlockReceived`
> Made Swarm<T>'s Event internal [skip changelog]

- Docs/articles/overview.md
It adds some mention about consensus to overview docs.
> Add Consensus paragraph to overview

- Libplanet.Stun.Tests/Libplanet.Stun.Tests.csproj
- Libplanet.Stun/Libplanet.Stun.csproj
- Libplanet.Tests/Libplanet.Tests.csproj
- Libplanet.ruleset
- Libplanet/Action/ActionEvaluation.cs
- Libplanet/Action/IRandom.cs
- Libplanet/Action/UnexpectedlyTerminatedActionException.cs
- Libplanet/Address.cs
- Libplanet/Blockchain/IncompleteBlockStatesException.cs
- Libplanet/Blocks/Block.cs
- Libplanet/Blocks/InvalidGenesisBlockException.cs
- Libplanet/ByteUtil.cs
- Libplanet/KeyStore/Kdfs/Pbkdf2.cs
- Libplanet/KeyStore/ProtectedPrivateKey.cs
- Libplanet/Libplanet.csproj
- Libplanet/Store/DefaultStore.cs
- Libplanet/Store/StoreExtension.cs
- Libplanet/Tx/InvalidTxNonceException.cs
- Libplanet/Tx/RawTransaction.cs
> Tweaking SonarAnalyzer.CSharp

- CHANGES.md
- Libplanet/Net/Swarm.cs
Hello :wave: I am newbie for the project. 
I fixed #740.
> Fix incorrect loggin in Swarm.DoReply

- README.md
Added a link to our blog post and rewrote some sentences
> Add link to blog post on README

- Libplanet/Store/DefaultStore.cs
This PR separates states from `index.ldb` to help maintain with large states. 
also, I skipped changelog because 0.8.0 introducing `DefaultStore` wasn't released yet. 😕
> Store states as files in DefaultStore

- Libplanet.Stun/Stun/Attributes/Attribute.cs
- Libplanet.Stun/Stun/Attributes/ErrorCode.cs
- Libplanet.Stun/Stun/Attributes/MessageIntegrity.cs
- Libplanet.Stun/Stun/Attributes/StunAddressExtension.cs
- Libplanet.Stun/Stun/Messages/StunMessage.cs
- Libplanet/Crypto/SymmetricKey.cs
- Libplanet/Hashcash.cs
- Libplanet/KeyStore/ProtectedPrivateKey.cs
- Libplanet/Net/Messages/Message.cs
- Libplanet/Net/Messages/RecentStates.cs
- Libplanet/Net/NetMQFrameExtension.cs
- Libplanet/Net/NetMQTransport.cs
- Libplanet/Store/DefaultStore.cs
- Libplanet/Tx/Transaction.cs
See also the docs: <https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#using-declarations>.
@planetarium/libplanet I recommend you to review code [with the option to ignore whitespaces.][1]
[1]: https://github.com/planetarium/libplanet/pull/799/files?w=1
> Introduce C# 8's using declaration

- Libplanet.Stun/Stun/Messages/StunMessage.cs
- Libplanet/KeyStore/Kdfs/Pbkdf2.cs
- Libplanet/KeyStore/ProtectedPrivateKey.cs
See also the docs: <https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8#switch-expressions>.
> Introduce C# 8's switch expression

- .github/bin/dist-nuget.sh
- .github/bin/dist-pack.sh
- Libplanet.RocksDBStore/Libplanet.RocksDBStore.csproj
This deploys Libplanet.RocksDBStore to NuGet with the same package version as Libplanet.
> Deploy Libplanet.RocksDBStore to NuGet

- .github/workflows/rebase.yml
See also: <https://github.com/marketplace/actions/automatic-rebase>.
> Update the rebase action to the latest version

- .github/workflows/rebase.yml
So that it can rebase PRs sent from forks as well.
https://github.com/cirrus-actions/rebase/commit/347ae6fbf8d710f78b239cbf0e1c936552694dec
> Update the cirrus-actions/rebase to 1.3

- Libplanet.RocksDBStore.Tests/RocksDBStoreTest.cs
- Libplanet.RocksDBStore/RocksDBStore.cs
This opens all `ColumnFamilies` when opening DB. Please refer to https://github.com/facebook/rocksdb/wiki/Column-Families#reference.
> Open all ColumnFamilies when opening DB

- Docs/theme/styles/main.css
> Sticky footer using flexbox

- Libplanet.Tests/Net/AppProtocolVersionTest.cs
- Libplanet/Net/AppProtocolVersion.cs
> Disallow null from AppProtocolVersion.FromToken()

- Libplanet.Tools/Libplanet.Tools.csproj
- Libplanet.Tools/README.md
- Libplanet/Libplanet.csproj
See also <https://github.com/NuGet/Home/wiki/Packaging-Documentation-within-the-nupkg>.
> Apply NuGet's readme field

- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/Swarm.cs
> Fix to evaluate action only once when receiving blocks

- CHANGES.md
> Fix a missing link in the changelog

- Libplanet.Tools/Apv.cs
- Libplanet.Tools/Key.cs
Adds `planet apv verify`, a new command to verify app protocol versions' signatures.
> planet apv verify command

- .github/bin/dist-github-release.sh
- .github/bin/dist-pack.sh
> Fix the release script (GitHub Actions)

- CHANGES.md
This is revised from the PR #863.
> Release 0.9.1

- CHANGES.md
- Libplanet/Net/NetMQTransport.cs
> Add timeout create permission

- Libplanet/Net/NetMQTransport.cs
- Libplanet/Net/Swarm.cs
This PR is cherry-picked from #879 for `9c-beta` branch. it has almost the same contents with #879 except CHANGELOG changing.
> Apply #879 to 9c-beta

- CHANGES.md
- Libplanet.RocksDBStore/RocksDBStore.cs
- Libplanet.Tests/Store/StoreTest.cs
Replaced the PR #894 which was a mistake.
> Merge back 0.9.4 into 9c-beta

- CHANGES.md
- Libplanet/Libplanet.csproj
> Version bump; ready for 0.9.5

- Libplanet/Net/NetMQTransport.cs
This fixes a bug where `Swarm<T>` was terminated when a timeout occurred in `CreatePermission`.
> Ignore TaskCanceledException in CreatePermission

- Libplanet.Tests/CurrencyTest.cs
- Libplanet/Currency.cs
> Implement .Equals for Currency

- Libplanet/Net/Swarm.cs
This fixes the wrong exception message properly. 😢
> Fix exception message properly

- Libplanet.Tests/Assets/FungibleAssetValueTest.cs
- Libplanet/Assets/FungibleAssetValue.cs
As the `FungibleAssetValue` type has never released yet, I omitted changelog for this.
> FungibleAssetValue.Parse() method

- Libplanet.Tests/Action/AccountStateDeltaImplTest.cs
- Libplanet.Tests/Action/InsufficientBalanceExceptionTest.cs
- Libplanet.Tests/Assets/FungibleAssetValueTest.cs
- Libplanet.Tests/Blocks/BlockTest.cs
- Libplanet.Tests/Common/Action/DumbAction.cs
- Libplanet/Action/AccountStateDeltaImpl.cs
- Libplanet/Assets/FungibleAssetValue.cs
- Libplanet/Blockchain/BlockChain.cs
See also: <https://github.com/planetarium/lib9c/pull/19#discussion_r472835551>.
> Make FungibleAssetValue.RawValue public

- .github/workflows/delete-old-artifacts.yml
It introduces [purge-artifacts](https://github.com/kolpav/purge-artifacts-action) to cleanup old artifacts.
> Configure purge-artifacts

- .github/auto_assign.yml
You can see preview at https://github.com/planetarium/auto-assign-test/pull/2
> Set auto assign by github bot

- Libplanet.Tests/Net/SwarmTest.Preload.cs
- Libplanet.Tests/Net/SwarmTest.cs
Fixed unit tests that occasionally fails.
> Fix unit tests

- .azure-pipelines/dotnet-core.yml
- .github/workflows/rebase.yml
- azure-pipelines.yml
> Optimize CI build

- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Blockchain/Renderers/DelayedRenderer.cs
Fixed several bugs related on tip changes & reorgs.  See also the commit messages for details.
> Fixed several bugs on DelayedRenderer<T> & BlockChain<T>.Swap()

- Libplanet/Blockchain/Renderers/DelayedActionRenderer.cs
- Make temporary render/unrender buffers for reorg thread-local so that they be consistent in a thread at least.
- Use lock-free concurrent data structures for delayed render/unrender queues so that each buffer are atomically updated at least even if some are overwritten.
> Make delayed renderers more multithread-resistant

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Blockchain/NullPolicy.cs
- Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Blockchain/Policies/BlockPolicy.cs
- Libplanet/Blockchain/Policies/IBlockPolicy.cs
- Libplanet/Net/Swarm.cs
This PR adds `BlockChain<T>` parameter to `IBlockPolicy<T>.DoesTransactionFollowsPolicy()` as its context.
> Add blockChain param to IBlockPolicy<T>.DoesTransactionFollowsPolicy()

- Libplanet.Tools/Configuration/MptConfiguration.cs
- Libplanet.Tools/Configuration/ToolConfiguration.cs
- Libplanet.Tools/JsonConfigurationService.cs
There was an issue that it doesn't deserialize the configuration well. This pull request fixes it.
> fix(cli): fix an issue from deserialization

- Libplanet.Tests/Blocks/BlockTest.cs
> Fix broken unittests on ar_SA

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet/Blockchain/BlockChain.cs
> Add mining option to configure tx batch size

- Libplanet.Tools/Mpt.cs
> docs: improve arguments' description of `mpt` subcommand

- CHANGES.md
> Release 0.10.0

- Libplanet.Tests/Blockchain/BlockChainTest.Internals.cs
- Libplanet/Blockchain/BlockChain.cs
Co-authored-by: Lee Suho <riemannulus@hitagi.moe>
> 9C hotfix: Multiplex the order of staged transactions

- Libplanet/Net/Swarm.cs
> Removed retrying logic when block downloading

- Libplanet.RocksDBStore/Libplanet.RocksDBStore.csproj
SSIA
I'll prepare porting PR to 0.10-maintenance soon.
> Bump Planetarium.RocksDbSharp to avoid memory leak

- .azure-pipelines/dotnet-core.yml
- .azure-pipelines/mono.yml
- .azure-pipelines/windows-net471.yml
- Libplanet.Tests/Net/SwarmTest.AppProtocolVersion.cs
- Libplanet.Tests/Net/SwarmTest.Fixtures.cs
- Libplanet.Tests/Net/SwarmTest.Preload.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet.Tests/Store/DefaultStoreFixture.cs
- Libplanet.Tests/Store/DefaultStoreTest.cs
- Libplanet/Net/Swarm.cs
- azure-pipelines.yml
cherry picked from commit c4106230df6af8ac61c77278485a16a6264f473f
> Cherry pick test fix PR from main

- Libplanet/Net/Swarm.MessageHandlers.cs
- Libplanet/Net/Swarm.cs
> Initialize BlockDemand when stopping swarm

- Libplanet/Libplanet.csproj
https://github.com/planetarium/bencodex.net/commit/5cdd49bcdf29d578debe0e586fc27b0c5f552133
See also:
- https://github.com/planetarium/bencodex.net/pull/28
- https://github.com/planetarium/bencodex.net/pull/29
> Upgrade Bencodex to get benefits from its recent optimizations

- Libplanet/Libplanet.csproj
https://github.com/planetarium/bencodex.net/commit/d449b419d17760428887372a23a3fce535b80927
See also:
https://github.com/planetarium/bencodex.net/pull/33
> Upgrade Bencodex to get benefits from its recent optimizations (2)

- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Libplanet.csproj
- Libplanet/Net/Swarm.cs
Please leave a comment it is enough to check its performance. @libplanet
> feat(benchmark): add log for preloading action execution benchmark

- CHANGES.md
- Libplanet/Blockchain/BlockChain.cs
> Make `BlockChain<T>.GetStagedTransactionIds()` public

- Libplanet/Blockchain/BlockChain.cs
Cherry picked from 543c7b506e9ead1c5dd1301836d23b4b6aa357b4
> Public GetStagedTransactionIds(): main → 9c-main

- CHANGES.md
- Libplanet.RocksDBStore/Libplanet.RocksDBStore.csproj
- Libplanet.Stun/Stun/TurnClient.cs
- Libplanet.Tests/Action/PolymorphicActionTest.cs
- Libplanet.Tests/Store/Trie/MerkleTrieTest.cs
- Libplanet/Action/ActionEvaluation.cs
- Libplanet/Action/PolymorphicAction.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Net/Swarm.cs
- Libplanet/Store/Trie/MerkleTrie.cs
I tried to pick commits of pull requests which were applied to 9c-main and were not added a new API.
> Port 9c-main → 0.10-maintenance

- CHANGES.md
- Libplanet/Libplanet.csproj
> Version bump; ready for 0.10.2

- .github/auto_assign.yml
> Remove @earlbread from auto-assigned reviewers

- Libplanet/Net/Swarm.cs
(cherry picked from commit 302530cc23d946378991cc29745d8355cd7a4e47)
> Cherry pick #1106 from main (Enrich logging)

- .github/bin/dist-npm.sh
- CHANGES.md
Release 0.10.2 which contains #1104, and fix #1098.
> Release 0.10.2 & fix #1098

- Libplanet/Net/Swarm.cs
> Enrich logging in `Swarm<T>.FillBlocksAsync()`

- Libplanet.Tests/Action/PolymorphicActionTest.cs
- Libplanet/Action/PolymorphicAction.cs
Though there was #1102, there was a missing commit yet.
> Cherry-pick missing commits from 9c-main

- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/Swarm.cs
> Test for break when getting blocks count is less then hash chunk size #1112

- Libplanet/Blockchain/Renderers/Debug/ValidatingActionRenderer.cs
Since virtually every `InvalidRenderException<T>` is caught and suppressed by `Swarm<T>.ProcessFillBlocks()`:
https://github.com/planetarium/libplanet/blob/9d98e8adca315e5794527e45564e4566d570c607/Libplanet/Net/Swarm.cs#L1992-L1998
… in the client code the way to programmatically handle it is impossible.  (Only its logs are left.)
In order to make it can be handled through program code in the client side, I added an option named `onError` which accepts `Action<InvalidRenderException<T>>`.
> Error event handler on ValidatingActionRenderer<T>

- CHANGES.md
- Libplanet.RocksDBStore/RocksDBStore.cs
> Add maxLogFileSize for RocksDBStore

- Docs/docfx.json
The title says it all.
FYI we started this project on the late 2018: f45d83b298c5345fbfa734be32a963d7105ba92d.
> Update the copyright year

- .github/workflows/benchmarks.yml
- .github/workflows/check-build.yaml
- .github/workflows/main.yml
- Docs/build.ps1
- Docs/docfx.json
This fixes #1122.
[Before][1]:
[![](https://user-images.githubusercontent.com/12431/104153268-43073100-5425-11eb-97f2-938633a17b01.png)][1]
[After][2]:
[![](https://user-images.githubusercontent.com/12431/104153266-41d60400-5425-11eb-8dc4-5c769b4eb44d.png)][2]
[1]: https://docs.libplanet.io/main/api/Libplanet.Net.ITransport.html#Libplanet_Net_ITransport_LastMessageTimestamp
[2]: https://dahlia.github.io/libplanet/main/api/Libplanet.Net.ITransport.html#Libplanet_Net_ITransport_LastMessageTimestamp
> Fix broken crefs to System.* on docs.libplanet.io

- CHANGES.md
- Libplanet.Tests/Blocks/BlockHeaderTest.cs
- Libplanet/Blocks/Block.cs
- Libplanet/Blocks/BlockHeader.cs
This PR adds hash validation to `BlockHeader.Validate()` (and `Block<T>`.Validate()).
> Add Hash validation to Block<T>.Validate()

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
- Libplanet.Tests/Blockchain/TotalDifficultyComparerTest.cs
- Libplanet.Tests/Blocks/BlockHeaderTest.cs
- Libplanet.Tests/Blocks/BlockTest.cs
- Libplanet/Blockchain/TotalDifficultyComparer.cs
- Libplanet/Blocks/Block.cs
- Libplanet/Blocks/BlockExcerpt.cs
- Libplanet/Blocks/BlockHeader.cs
- Libplanet/Blocks/IBlockExcerpt.cs
- Libplanet/Net/Messages/ChainStatus.cs
- Libplanet/Net/Swarm.MessageHandlers.cs
> Motivate miners to upgrade protocol version

- CHANGES.md
- Libplanet.Tests/Blocks/BlockHeaderTest.cs
- Libplanet/Blocks/Block.cs
- Libplanet/Blocks/BlockHeader.cs
> Port of #1168

- CHANGES.md
It adds missing links in changelog.
> docs: add missing links

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Menees.Analyzers.Settings.xml
- Libplanet/Blockchain/BlockChain.cs
> Unstage txs have lower nonces at BlockChain<T>.MineBlock()

- CHANGES.md
> Release 0.10.3

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet/Blockchain/BlockChain.cs
> Merge from 0.10.3

- CHANGES.md
- Libplanet/Libplanet.csproj
> Version bump to 0.10.4

- CHANGES.md
- Libplanet.Tests/Net/Messages/MessageTest.cs
- Libplanet/Net/Messages/Message.cs
> Sign all messages

- CHANGES.md
- Libplanet/Net/BlockCompletion.cs
- Libplanet/Net/NetMQTransport.cs
> Fix CancellationTokenSource dose not dispose

- Libplanet/Action/ActionEvaluation.cs
> Logging action execution failed msg

- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet/Net/Protocols/KademliaProtocol.cs
- Libplanet/Net/Swarm.cs
Additionally removed unnecessary loggings.
> Adjust RebuildConnectionAsync

- Libplanet.RocksDBStore/MonoRocksDBStore.cs
This PR applies an improvement about `.ForkBlockIndexes()` in #1198 to `MonoRocksDBStore`. 
I omitted changelogs about this because `MonoRocksDBStore` introduced in 0.11 that isn't released yet.
> Apply #1198 to MonoRocksDBStore

- CHANGES.md
- Libplanet/Blocks/Block.cs
> Ignore PreEvaluationHash for old blocks during block validation

- CHANGES.md
- Libplanet.Stun/Stun/TurnClient.cs
- Libplanet/Action/ActionEvaluation.cs
- Libplanet/Store/TrieStateStore.cs
This PR adds logging context to certain classes for filtering by the application side. (i.e. https://github.com/planetarium/NineChronicles.Headless/issues/391)
> Add logging context

- CHANGES.md
> Release 0.11.0

- CHANGES.md
- Libplanet/Libplanet.csproj
> Bump: 0.12.0

- CHANGES.md
> Prepare 0.11-maintenance

- Libplanet/Net/Swarm.cs
This PR widens try-catch guard in `Swarm<T>.ProcessFillBlocks()` to prevent abnormal termination. 
At this time, it targets `9c-maintenance-v100040` and I'll prepare regular PR for `main` and `v0.11-maintenance` after deploying it with 9c.
> Durable ProcessFillBlocks()

- CHANGES.md
> Release 0.11.1

- CHANGES.md
> Prepare 0.11.2

- CHANGES.md
- Libplanet/Net/Swarm.BlockSync.cs
This PR ports a fix of #1259 to v0.12.0. 
There are code changes from #1259 due to separating files and added logs. IMO it needs to review again 😅.
> Port 0.11.1

- Libplanet.Extensions.Cocona/Commands/ApvCommand.cs
- Libplanet.Extensions.Cocona/Commands/KeyCommand.cs
- Libplanet.Extensions.Cocona/Commands/MptCommand.cs
- Libplanet.Extensions.Cocona/Configuration/MptConfiguration.cs
- Libplanet.Extensions.Cocona/ConsolePasswordReader.cs
- Libplanet.Extensions.Cocona/Extensions/ICoconaLiteServiceCollectionExtensions.cs
- Libplanet.Extensions.Cocona/Libplanet.Extensions.Cocona.csproj
- Libplanet.Extensions.Cocona/Services/JsonConfigurationService.cs
- Libplanet.Extensions.Cocona/Utils.cs
This pull request `Libplanet.Extensions.Cocona` become to use shared rules. See also https://github.com/planetarium/libplanet/pull/1268#discussion_r621805388.
> build: share code analyzers rules

- CHANGES.md
- Libplanet.Tests/Net/Transports/NetMQTransportTest.cs
- Libplanet.Tests/Net/Transports/TransportExceptionTest.cs
- Libplanet.Tests/Net/Transports/TransportTest.cs
- Libplanet/Net/Swarm.cs
- Libplanet/Net/Transports/NetMQTransport.cs
- Libplanet/Net/Transports/TransportException.cs
Adds unit tests for `ITransport` for further extensions, and bumps C# version of `Libplanet.Tests` project to 8.0.
> Add unit tests for `ITransport`

- Libplanet.RocksDBStore/RocksDBStore.cs
This PR adds error logs to `RocksDBStore` to better assess preloading failures.
> add error log to rocksdbstore

- Libplanet.RocksDBStore/RocksDBStore.cs
> add rocksdb error log [skip changelog]

- .github/workflows/rebase.yml
This PR fixes version typo from #1281
> Fix version of actions/checkout [skip changelog]

- Libplanet.Explorer/Interfaces/IBlockChainContext.cs
- Libplanet.Explorer/Queries/BlockQuery.cs
- Libplanet.Explorer/Queries/ExplorerQuery.cs
- Libplanet.Explorer/Queries/TransactionQuery.cs
- https://github.com/planetarium/NineChronicles.Headless/issues/428
> Rename class for avoid conflict in NineChronicles.Headless

- CHANGES.md
- Libplanet.Tests/Action/ActionContextTest.cs
- Libplanet.Tests/Action/ActionEvaluationTest.cs
- Libplanet.Tests/Blockchain/Renderers/AnonymousActionRendererTest.cs
- Libplanet.Tests/Blockchain/Renderers/DelayedActionRendererTest.cs
- Libplanet.Tests/Blockchain/Renderers/LoggedActionRendererTest.cs
- Libplanet/Action/ActionContext.cs
- Libplanet/Action/ActionEvaluation.cs
- Libplanet/Action/IActionContext.cs
Closes <https://github.com/planetarium/libplanet/issues/1295>.
> `IActionContext.BlockHash` property

- Libplanet.Explorer/Queries/ExplorerQuery.cs
> Fix a typo in `Libplanet.Explorer.Queries.Query.IsValidTransacion`

- .github/auto_assign.yml
PR reviewer auto assign list updated.
> Auto assign list update

- CHANGES.md
- CONTRIBUTING.md
- Libplanet.Extensions.Cocona.Tests/Commands/MptCommandTest.cs
- Libplanet.Extensions.Cocona.Tests/Libplanet.Extensions.Cocona.Tests.csproj
- Libplanet.Extensions.Cocona.Tests/Services/TestToolConfigurationService.cs
- Libplanet.Extensions.Cocona/Commands/KeyCommand.cs
- Libplanet.Extensions.Cocona/Commands/MptCommand.cs
- Libplanet.Extensions.Cocona/Libplanet.Extensions.Cocona.csproj
- Libplanet.Extensions.Cocona/Utils.cs
- Libplanet.sln
- Libplanet/AssemblyInfo.cs
This continues #1191 closed pull request. It resolves #1138.
> feat(cli): improve `mpt diff` output

- .vscode/settings.json
Just some minor QoL improvement for anyone using VSCode for development.
> Semantic highlighting update for VSCode

- codecov.yml
- ignore *Tests, *Benchmarks directories
- added branch_detection
> [skip changelog] chore: ignore coverage for test projects

- .github/workflows/push-docker-image.yml
- azure-pipelines.yml
See also: <https://github.com/actions/virtual-environments/issues/3287>.
> Upgrade Ubuntu images on Azure Pipelines & GitHub Actions

- Libplanet/Libplanet.csproj
> Fix Version for 0.11.1 

- CHANGES.md
- Libplanet.RocksDBStore.Tests/RocksDBStoreTest.cs
- Libplanet.RocksDBStore/RocksDBStore.cs
> Thread-safe `.GetBlock<T>()` and `.GetTransaction<T>()`

- CHANGES.md
- Libplanet.Tests/Net/Transports/NetMQTransportTest.cs
- Libplanet.Tests/Net/Transports/TransportTest.cs
- Libplanet/Net/Swarm.cs
- Libplanet/Net/SwarmOptions.cs
- Libplanet/Net/Transports/NetMQTransport.cs
> Configurable minimum number of peer to broadcast

- CHANGES.md
- Libplanet.Tests/Net/Transports/NetMQTransportTest.cs
- Libplanet.Tests/Net/Transports/TransportTest.cs
- Libplanet/Net/Swarm.cs
- Libplanet/Net/SwarmOptions.cs
- Libplanet/Net/Transports/NetMQTransport.cs
This PR cherrypicks https://github.com/planetarium/libplanet/pull/1377
> Configurable broadcast target number

- CHANGES.md
> Release 0.12.0

- CHANGES.md
- Libplanet/Libplanet.csproj
> Version bump 0.13.0

- .github/bin/dist-npm.sh
Fixes <https://github.com/planetarium/libplanet/issues/1396>.
> Fix error that dist-npm.sh makes on release

- CHANGES.md
- Libplanet.Tests/Tx/TransactionTest.cs
- Libplanet/Tx/Transaction.cs
Ports patches from #1378 to the main branch.
> Port `Transaction.CreateUnsigned()` factory method (#1378)

- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.Preload.cs
- Libplanet/Net/Swarm.cs
No API change though, should rebuild project using `Libplanet` because of ABI change.
TODO:
> Add option to render while preloading

- CHANGES.md
> Release 0.14.1

- CHANGES.md
- Libplanet/Blockchain/Renderers/LoggedRenderer.cs
- Libplanet/Net/Swarm.cs
- Libplanet/Net/Transports/NetMQTransport.cs
Ports 0.14.1 into main and release 0.15.0.
> Release 0.15.0 (with 0.14.1 port)

- CHANGES.md
- Libplanet.Explorer/Queries/ExplorerQuery.cs
- Libplanet/Blockchain/BlockChain.Swap.cs
- Libplanet/Blockchain/BlockChain.cs
Closes #1409.
----
- <https://github.com/planetarium/libplanet/pull/1430>
- <https://github.com/planetarium/lib9c/pull/575>
- <https://github.com/planetarium/NineChronicles.Headless/pull/644>
> `BlockChain<T>.Tip` made non-nullable

- CHANGES.md
This release includes https://github.com/planetarium/libplanet/pull/1425
> Release 0.16.0

- CHANGES.md
- Libplanet/Libplanet.csproj
> Prepare 0.17.0

- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.Broadcast.cs
- Libplanet/Net/Swarm.BlockSync.cs
- Libplanet/Net/Swarm.cs
Block sync using `BlockDemand` became not to use `BlockCompletion`.
> Restore block push logic

- CHANGES.md
- Libplanet.Tests/Net/Protocols/TestTransport.cs
- Libplanet.Tests/Net/SwarmTest.Broadcast.cs
- Libplanet/Net/Swarm.cs
- Libplanet/Net/Transports/ITransport.cs
- Libplanet/Net/Transports/NetMQTransport.cs
> Merge 0.15.2 to main

- CHANGES.md
- Libplanet/Libplanet.csproj
> Prepare 0.15.3

- CHANGES.md
- Libplanet.Tests/Net/Protocols/TestTransport.cs
- Libplanet.Tests/Net/SwarmTest.Broadcast.cs
- Libplanet/Net/Swarm.cs
- Libplanet/Net/Transports/ITransport.cs
- Libplanet/Net/Transports/NetMQTransport.cs
> Merge 0.15.2 to 0.16-maintenance

- Docs/build.ps1
Still haven't figured out as to why documentation isn't updating properly on local builds, but this seems to work. 🙃
> Docfx version bump

- .github/auto_assign.yml
- CHANGES.md
- Libplanet.Tests/HashAlgorithmTypeTest.cs
- Libplanet/HashAlgorithmType.cs
I added more overloads to `HashAlgorithmType.Digest()` method group.  This will be useful for lower latent PoW in the future.
> Streamed hashing

- CHANGES.md
- Libplanet/Net/Swarm.MessageHandlers.cs
> Prevent `KeyNotFoundException` during `TransferTxs()`

- CHANGES.md
- Libplanet/Net/Swarm.MessageHandlers.cs
> Merge 0.15.3 into 0.16-maintenance

- CHANGES.md
- Libplanet/Net/Swarm.MessageHandlers.cs
> Merge 0.15.3 into main

- CHANGES.md
- Libplanet.Tests/Crypto/PrivateKeyTest.cs
- Libplanet/Crypto/PrivateKey.cs
- Libplanet/KeyStore/ProtectedPrivateKey.cs
See also <https://github.com/planetarium/libplanet/pull/1571>.
> Merge 0.18.4 into 0.19-maintenance (to be 0.19.2)

- CHANGES.md
- Libplanet.Explorer.Executable/Program.cs
- Libplanet.Extensions.Cocona.Tests/Commands/StatsCommandTest.cs
- Libplanet.Extensions.Cocona.Tests/Commands/StoreCommandTest.cs
- Libplanet.Extensions.Cocona/Commands/StatsCommand.cs
- Libplanet.Extensions.Cocona/Commands/StoreCommand.cs
- Libplanet.RocksDBStore.Tests/MonoRocksDBStoreFixture.cs
- Libplanet.RocksDBStore.Tests/MonoRocksDBStoreTest.cs
- Libplanet.RocksDBStore/MonoRocksDBStore.cs
Closes <https://github.com/planetarium/libplanet/issues/1513>.
> Deprecate `MonoRocksDBStore`

- CHANGES.md
- Libplanet/Libplanet.csproj
> Prepare 0.21

- Libplanet/Blockchain/BlockChain.MineBlock.cs
A small fix for a mistake found.
> Bad log fix

- CHANGES.md
- Libplanet.RocksDBStore/RocksDBStore.cs
- Libplanet.Tests/Store/StoreTest.cs
This PR addresses #1591. Please check `CHANGES.md` and the added test case.
> Fix RockDBStore.ForkIndexes() bug

- CHANGES.md
- Libplanet.Tests/Blocks/BlockExceedingTransactionsExceptionTest.cs
- Libplanet.Tests/Blocks/InvalidBlockBytesLengthExceptionTest.cs
- Libplanet/Blocks/BlockExceedingTransactionsException.cs
- Libplanet/Blocks/InvalidBlockBytesLengthException.cs
~Merging into main for now as I plan on further refactoring these exceptions shortly.~
> Broken serializations for exceptions fixed

- CHANGES.md
Close <https://github.com/planetarium/libplanet/issues/1601>.
> Release 0.21.0

- Libplanet/Action/ActionEvaluator.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Net/Swarm.MessageHandlers.cs
- Libplanet/Net/Swarm.cs
- Scrubbed missed txid listing.
- Updated pre-evaluation hash hex logging.
> [Skip Changelog] Updated logging

- Libplanet.Extensions.Cocona/Commands/ApvCommand.cs
- use netmq query instead of tcp
> Fix apv query command

- CHANGES.md
- Libplanet/Libplanet.csproj
Closes <https://github.com/planetarium/libplanet/issues/813>.
> Distribute Libplanet.Stun as a separate NuGet package

- CHANGES.md
- Libplanet/Net/BlockCompletion.cs
- Libplanet/Net/Swarm.cs
- Libplanet/Net/Transports/NetMQTransport.cs
Taking care of some missing spots in #1607 and a minor QoL improvement.
> More compact logging

- Libplanet.Tests/Net/Protocols/KBucketTest.cs
> Hotfix for namespace

- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.Broadcast.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet.Tests/Net/Transports/NetMQTransportTest.cs
- Libplanet/Net/Transports/ITransport.cs
- Libplanet/Net/Transports/NetMQTransport.cs
- Libplanet/Net/Transports/TcpTransport.cs
> Remove message history & release 0.22.1

- .github/auto_assign.yml
> Restore limebell

- CHANGES.md
- Libplanet.Tests/Net/SwarmTest.Broadcast.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet.Tests/Net/Transports/NetMQTransportTest.cs
- Libplanet/Net/BlockCompletion.cs
- Libplanet/Net/Swarm.cs
- Libplanet/Net/Transports/ITransport.cs
- Libplanet/Net/Transports/NetMQTransport.cs
- Libplanet/Net/Transports/TcpTransport.cs
This PR ports [0.22.1](https://github.com/planetarium/libplanet/releases/tag/0.22.1) to main.
> Port 0.22.1

- Libplanet/Blockchain/BlockChain.cs
Just some additional metric for future analysis.
> Added metric logs

- CHANGES.md
- Libplanet/Libplanet.csproj
> Prepare 0.23.3

- CHANGES.md
- Libplanet.RocksDBStore/RocksDBStore.cs
- Libplanet/Blockchain/BlockChain.Swap.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Net/Swarm.BlockSync.cs
- Libplanet/Net/Transports/NetMQTransport.cs
> Port 0.23.2 to main

- CHANGES.md
> Release 0.24.0

- CHANGES.md
- Libplanet.Tests/Net/PeerTest.cs
- Libplanet/Net/BoundPeer.cs
- Libplanet/Net/Peer.cs
> Nullable context for `Peer` and `BoundPeer`

- CHANGES.md
- Libplanet/Net/Swarm.BlockSync.cs
This reverts commit 2eb1e95b99e1ef94e955613ab9b40a750be8c8d0, reversing
changes made to c8c056acdc3f2e52cd4973be93e2fb993bfed81d.
> Revert "Merge pull request #1606 from moreal/refactor/core/remove-lock"

- CHANGES.md
> Release 0.25.1

- CHANGES.md
> Prepare 0.25.2

- Libplanet/Libplanet.csproj
Patching up a mistake in #1698. 😭
> [Changelog] Hotfix

- CHANGES.md
- Libplanet/Net/TxCompletion.cs
> Port 0.25.2 to main

- CHANGES.md
- Libplanet.Tests/Blockchain/Policies/VolatileStagePolicyTest.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Blockchain/Policies/IStagePolicy.cs
- Libplanet/Blockchain/Policies/VolatileStagePolicy.cs
- Libplanet/Net/TxCompletion.cs
> `BlockChain<T>.StageTransaction()` returns `bool`

- CHANGES.md
- Libplanet/Libplanet.csproj
> Prepare 0.25.4

- CHANGES.md
- Libplanet/Net/Transports/NetMQTransport.cs
> Port 0.25.3 into main

- CHANGES.md
- Libplanet/Net/TxCompletion.cs
> Error logging

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .vscode/extensions.json
- .vscode/settings.json
- .vscode/tasks.json
This configures GitHub Codespaces so that any first-time contributors can get started to code without hassle.
> Configure GitHub Codespaces

- CHANGES.md
- Libplanet/Net/DifferentAppProtocolVersionException.cs
- Libplanet/Net/Messages/Message.cs
- Libplanet/Net/Transports/ITransport.cs
- Libplanet/Net/Transports/NetMQTransport.cs
Trying to break up #1702. No noticeable change other than rephrased logging for QoL.
> Chore - documentation clarification and internal type change

- Libplanet/Net/Transports/NetMQTransport.cs
Was part of now abandoned #1702. In general, `ConcurrentDictionary` should not be updated with an external check. This PR changes the update to be more atomic making the handling of `DealerSocket`s more thread safe. In general, mutating a value retrieved from `TryGetValue()` is not thread safe.
> More atomic `DealerSocket` handling

- CHANGES.md
> Release 0.26.1

- CHANGES.md
- Libplanet/Libplanet.csproj
> Prepare 0.26.2

- CHANGES.md
- Libplanet/Net/DifferentAppProtocolVersionException.cs
- Libplanet/Net/Messages/Message.cs
- Libplanet/Net/Transports/ITransport.cs
- Libplanet/Net/Transports/NetMQTransport.cs
> Port 0.26.1 to main

- CHANGES.md
- Libplanet.Benchmarks/BlockChain.cs
- Libplanet.Benchmarks/MineBlock.cs
- Libplanet.Benchmarks/SwarmBenchmark.cs
- Libplanet.RocksDBStore.Tests/RocksDBStoreTest.cs
- Libplanet.Tests/Action/AccountStateDeltaTest.cs
- Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
- Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Fixtures/IntegerSet.cs
- Libplanet.Tests/Net/SwarmTest.Broadcast.cs
- Libplanet.Tests/Net/SwarmTest.cs
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet/Blockchain/Policies/NullBlockPolicy.cs
> Expose `NullPolicy` as a public class

- CHANGES.md
- Libplanet.Tests/Net/Protocols/TestTransport.cs
- Libplanet.Tests/Net/Transports/NetMQTransportTest.cs
- Libplanet.Tests/Net/Transports/TcpTransportTest.cs
- Libplanet.Tests/Net/Transports/TransportTest.cs
- Libplanet/Net/Swarm.MessageHandlers.cs
- Libplanet/Net/Swarm.cs
- Libplanet/Net/Transports/ITransport.cs
- Libplanet/Net/Transports/NetMQTransport.cs
- Libplanet/Net/Transports/TcpTransport.cs
Inner behavior for disposing unused dealer socket has been changed. This closes #1741 .
> Remove `RoutingTable` dependency from `ITransport`

- Libplanet.Tests/Net/Messages/MessageTest.cs
- Libplanet/Net/Messages/IMessageCodec.cs
- Libplanet/Net/Messages/NetMQMessageCodec.cs
- Libplanet/Net/Messages/TcpMessageCodec.cs
Non-nullability is enforced by nullable context already. 🙃
> Unnecessary clutter removed.

- Libplanet/Action/ActionEvaluator.cs
Log output from #1758 seemed bit too simple.
> More info on transaction evaluation log

- CHANGES.md
- Libplanet.Net.Tests/SwarmTest.Broadcast.cs
- Libplanet.Net/Swarm.BlockCandidate.cs
- Libplanet.Net/Swarm.BlockSync.cs
- Libplanet.Net/Swarm.cs
close #1731 
Now use `BlockCandidateTable<T>` on polling blocks too.
> Use `BlockCandidateTable<T>` on `PollBlocksAsync`

- Libplanet/Net/Swarm.MessageHandlers.cs
> Measure time spend during `IsBlockNeeded` when receiving new `BlockHeaderMessage`

- CHANGES.md
- Libplanet.Net.Tests/InvalidMessageTimestampExceptionTest.cs
- Libplanet.Net.Tests/Messages/MessageTest.cs
- Libplanet.Net/InvalidMessageSignatureException.cs
- Libplanet.Net/InvalidMessageTimestampException.cs
- Libplanet.Net/Messages/IMessageCodec.cs
- Libplanet.Net/Messages/NetMQMessageCodec.cs
- Libplanet.Net/Messages/TcpMessageCodec.cs
- Libplanet.Net/Protocols/KademliaProtocol.cs
- Libplanet.Net/Transports/NetMQTransport.cs
More fine grained `Exception`s for clarity.
> Finer `Exception`s

- CHANGES.md
- Libplanet.Net/Swarm.MessageHandlers.cs
- Libplanet.Net/Swarm.cs
- Libplanet/EnumerableExtensions.cs
See also:
- <https://github.com/planetarium/libplanet/pull/1774>
- <https://github.com/planetarium/libplanet/pull/1775>
> Port 0.26.3 & release 0.27.1

- CHANGES.md
- Libplanet.Net/Swarm.MessageHandlers.cs
- Libplanet.Net/Swarm.cs
- Libplanet/EnumerableExtensions.cs
This ports #1775 to 0.28.x, and adds `tipDeltaThreshold` option to `Swarm<T>.PreloadAsync()` method.
> Port 0.26.3/0.27.1 to main (0.28.x) & add `tipDeltaThreshold` to `Swarm<T>.PreloadAsync()`

- CHANGES.md
- Libplanet/Libplanet.csproj
> Release 0.27.2

- CHANGES.md
- Libplanet.Net/Transports/NetMQTransport.cs
- Libplanet/Blockchain/BlockChain.Swap.cs
> Port to 0.27.2 main

- CHANGES.md
- Libplanet/Libplanet.csproj
> Prepare 0.27.3

- CHANGES.md
- Libplanet.Net.Tests/Transports/MessageSendFailedExceptionTest.cs
- Libplanet.Net/Transports/MessageSendFailedException.cs
- Libplanet.Net/Transports/NetMQTransport.cs
Closes #1781. Follow up to #1778.
> Add `MessageSendFailedException`

- CHANGES.md
- Libplanet.Net.Tests/SwarmTest.Broadcast.cs
- Libplanet.Net/Swarm.BlockCandidate.cs
- Libplanet.Net/Swarm.BlockSync.cs
- Libplanet.Net/Swarm.cs
Because #1759 has preload problem, we revert #1759
> Revert #1759

- CHANGES.md
- Libplanet/Libplanet.csproj
> Prepare 0.27.4

- CHANGES.md
- Libplanet.Net.Tests/SwarmTest.Broadcast.cs
- Libplanet.Net/Swarm.BlockCandidate.cs
- Libplanet.Net/Swarm.BlockSync.cs
- Libplanet.Net/Swarm.cs
> Port to 0.27.3 main 

- .devcontainer/devcontainer.json
- .vscode/extensions.json
- CHANGES.md
Also fixed few typos in the changelog.
> Release 0.27.4

- CHANGES.md
- Libplanet/Net/Transports/NetMQTransport.cs
Adds logs for counting sockets in use and request process duration.
> Additional network related metric logs

- CHANGES.md
> Release 0.26.4

- CHANGES.md
- Libplanet/Libplanet.csproj
> Prepare 0.26.5

- Libplanet.Net/Transports/NetMQTransport.cs
> Bad tabbing introduced in `0.26.x`

- CHANGES.md
- Libplanet.Net/Transports/NetMQTransport.cs
> Fix socket leak

- CHANGES.md
> Release 0.28.0

- CHANGES.md
- Libplanet/Libplanet.csproj
> Prepare 0.29.0

- CHANGES.md
- Libplanet.Net/Transports/NetMQTransport.cs
> Unused parameter removed from `NetMQTransport()`

- Libplanet/Action/ActionEvaluator.cs
> Logging format update for consistency

- CHANGES.md
> Release 0.28.1

- CHANGES.md
- Libplanet.Net/Transports/NetMQTransport.cs
- Libplanet/Action/ActionEvaluator.cs
> Port 0.28.1 to main

- CHANGES.md
- Libplanet.Extensions.Cocona/Commands/StoreCommand.cs
- Libplanet.RocksDBStore.Tests/RocksDBStoreTest.cs
- Libplanet.RocksDBStore/RocksDBStore.cs
> Replace ColumnFamilies to key prefix for index db

- Libplanet.RocksDBStore/RocksDBStore.cs
Prevent using key with duplicated prefixes.
> Fix bug in migration indexes

- Libplanet.Net/Transports/NetMQTransport.cs
> Combined logging for `NetMQTransport.SendMessageWithReplyAsync()`

- Libplanet.Net/Transports/NetMQTransport.cs
- Libplanet/Action/ActionEvaluator.cs
- Libplanet/Blockchain/BlockChain.Swap.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Blockchain/Policies/VolatileStagePolicy.cs
Just a small QoL improvement for [9c-metric-dash].
[9c-metric-dash]: https://github.com/planetarium/9c-metric-dash
> Subtags added to metric logs for easy parsing

- Libplanet.Net/Transports/NetMQTransport.cs
More logging for [9c-metric-dash].
[9c-metric-dash]: https://github.com/planetarium/9c-metric-dash
> Inbound message tracking metric log added

- Libplanet.Net/Transports/NetMQTransport.cs
In retrospect, this probably should've been part of #1849. 😶
Calling `BroadcastMessage()` to enqueue to `NetMQQueue` just to have it consumed by `DoBroadcast()` would make more sense for a pub/sub model, but as it stands, where all `DoBroadcast()` does is to call `SendMessageAsync()`, doesn't seem necessary. There is a slim possibility that `NetMQQueue` might be useful to control network IO in case of traffic congestion, but it is more likely that either this can be done in `BroadcastMessage()` or in `SendMessageAsync()`.
> [skip changelog] Unnecessary broadcast poller removed

- CHANGES.md
- Libplanet.Extensions.Cocona/Commands/StoreCommand.cs
- Libplanet.RocksDBStore.Tests/RocksDBStoreTest.cs
- Libplanet.RocksDBStore/RocksDBStore.cs
This is reupload of https://github.com/planetarium/libplanet/pull/1838.
> Remove column family from index db and add support for migration

- CHANGES.md
- Libplanet.Net.Tests/Protocols/ProtocolTest.cs
- Libplanet.Net/Protocols/Kademlia.cs
- Libplanet.Net/Protocols/KademliaProtocol.cs
Just some preparatory work for interfacing other classes such as `IRoutingTable`, `IMessageHandler`, etc. 😗
> Some name changes in `Kademlia` for clarity

- CHANGES.md
- Libplanet.Net.Tests/Protocols/ProtocolTest.cs
- Libplanet.Net/Protocols/Kademlia.cs
- Libplanet.Net/Protocols/KademliaProtocol.cs
This reverts commit 94151f803694e6c12408a895f31d51ec69f8641f, reversing
changes made to fa3695cab0854a963eb3289064b54f4f51dc3ceb.
> Revert #1871

- CHANGES.md
- Libplanet.Net.Tests/Protocols/ProtocolTest.cs
- Libplanet.Net/Protocols/Kademlia.cs
- Libplanet.Net/Protocols/KademliaProtocol.cs
Reintroducing #1871 due to git mistake. 😐
> Some name changes in Kademlia for clarity

- CHANGES.md
> Release 0.31.0

- CHANGES.md
- Libplanet/Libplanet.csproj
> Prepare 0.32.0

- CHANGES.md
- Libplanet/Libplanet.csproj
> Prepare 0.31.1

- CHANGES.md
- Libplanet.Net.Tests/DifferentAppProtocolVersionExceptionTest.cs
- Libplanet.Net.Tests/InvalidMessageSignatureExceptionTest.cs
- Libplanet.Net.Tests/InvalidMessageTimestampExceptionTest.cs
- Libplanet.Net.Tests/Messages/MessageTest.cs
- Libplanet.Net/DifferentAppProtocolVersionException.cs
- Libplanet.Net/InvalidMessageSignatureException.cs
- Libplanet.Net/InvalidMessageTimestampException.cs
- Libplanet.Net/Messages/NetMQMessageCodec.cs
- Libplanet.Net/Messages/TcpMessageCodec.cs
- Libplanet.Net/Protocols/KademliaProtocol.cs
- Libplanet.Net/Transports/NetMQTransport.cs
- Libplanet.Net/Transports/TcpTransport.cs
This is mostly to reduce noise on a larger refactoring task as part of #1885 that I am working on. 😶
> Decoding related exceptions refactored

- CHANGES.md
> Release 0.32.0

- CHANGES.md
- Libplanet/Libplanet.csproj
> Prepare 0.32.1

- CHANGES.md
- Libplanet/Libplanet.csproj
> Prepare 0.33.0

- CHANGES.md
> Release 0.32.1

- CHANGES.md
- Libplanet/Libplanet.csproj
> Prepare 0.32.2

- CHANGES.md
- Libplanet.Net.Tests/InvalidCredentialExceptionTest.cs
- Libplanet.Net.Tests/Messages/BlockHashesTest.cs
- Libplanet.Net.Tests/Messages/MessageTest.cs
- Libplanet.Net.Tests/Transports/BoundPeerExtensionsTest.cs
- Libplanet.Net.Tests/Transports/TcpTransportTest.cs
- Libplanet.Net/InvalidCredentialException.cs
- Libplanet.Net/Messages/IMessageCodec.cs
- Libplanet.Net/Messages/NetMQMessageCodec.cs
- Libplanet.Net/Messages/TcpMessageCodec.cs
- Libplanet.Net/Transports/BoundPeerExtensions.cs
> Sanity check added to IMessageCodec.Encode()

- CHANGES.md
> Release 0.33.0

- CHANGES.md
- Libplanet/Libplanet.csproj
> Prepare 0.33.1

- CHANGES.md
- Libplanet/Libplanet.csproj
> Prepare 0.34.0

- Libplanet.Net/Messages/ConsensusCommit.cs
- Libplanet.Net/Messages/ConsensusCommit23.cs
- Libplanet.Net/Messages/Message.cs
There are more messages for PBFT.
> New message for PBFT

- CHANGES.md
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Tx/InvalidTxException.cs
- Libplanet/Tx/TxPolicyViolationException.cs
This is squashed PR of #1912, and resolves #1830.
> `TxPolicyViolationException` should contain `InnerException`

- CHANGES.md
- Libplanet/Blockchain/BlockChain.MineBlock.cs
> Defer `Transaction<T>` policy validation to after nonce check

- CHANGES.md
> Release 0.33.1

- CHANGES.md
- Libplanet/Libplanet.csproj
> Prepare 0.33.2

- CHANGES.md
- Libplanet/Blockchain/BlockChain.MineBlock.cs
> Port 0.33.1 to main

- Libplanet.Net/Messages/ConsensusCommit.cs
- Libplanet.Net/Messages/ConsensusMessage.cs
- Libplanet.Net/Messages/ConsensusPropose.cs
- Libplanet.Net/Messages/ConsensusVote.cs
Add new Height field in message
> Add Height to ConsensusMessages

- Libplanet.Net/Swarm.BlockSync.cs
- Libplanet.Net/Swarm.MessageHandlers.cs
- Libplanet.Net/Swarm.cs
> Remove unused/unnecessary stuff

- Libplanet.Tests/Store/DataModelTest.cs
- Libplanet/Store/DataModel.cs
> [skip changelog] Fix broken tests

- CHANGES.md
> Release 0.34.0

- CHANGES.md
- Libplanet.Net.Tests/Messages/MessageValidatorTest.cs
- Libplanet.Tests/TimeSpanExtensionsTest.cs
- Libplanet/TimeSpanExtensions.cs
Implemented out of necessity while working on #1957.
> `TimeSpanExtensions.Multiply()` added

- CHANGES.md
- Libplanet.Tests/Store/DataModelTest.cs
- Libplanet/Store/DataModel.Decode.cs
- Libplanet/Store/DataModel.Encode.cs
- Libplanet/Store/DataModel.cs
> Add `Guid` support for `DataModel`

- Libplanet.Net.Tests/Consensus/ConsensusContextTest.cs
- Libplanet.Net.Tests/Consensus/ConsensusReactorTest.cs
- Libplanet.Net.Tests/Consensus/ReactorTest.cs
- Libplanet.Net.Tests/Consensus/RoundContextTest.cs
- Libplanet.Net.Tests/Consensus/States/DefaultStateTest.cs
- Libplanet.Net.Tests/Consensus/States/PreCommitStateTest.cs
- Libplanet.Net.Tests/Consensus/States/PreVoteStateTest.cs
- Libplanet.Net.Tests/TestUtils.cs
- Libplanet.Net/Consensus/ConsensusContext.cs
- Libplanet.Net/Consensus/ConsensusReactor.cs
- Libplanet.Net/Consensus/DefaultState.cs
- Libplanet.Net/Consensus/IReactor.cs
- Libplanet.Net/Consensus/IState.cs
- Libplanet.Net/Consensus/PreCommitState.cs
- Libplanet.Net/Consensus/PreVoteState.cs
- Libplanet.Net/Consensus/RoundContext.cs
- Libplanet.Net/Consensus/UnexpectedBlockHashException.cs
- Libplanet.Net/Messages/ConsensusCommit.cs
- Libplanet.Net/Messages/ConsensusMessage.cs
- Libplanet.Net/Messages/ConsensusPropose.cs
- Libplanet.Net/Messages/ConsensusVote.cs
This patch adds block handling logic to consensus, thus `T` (action type) is added to almost all classes.
> [PBFT] Feature/consensus use block

- Libplanet.Net.Tests/Consensus/ConsensusContextTest.cs
- Libplanet.Net.Tests/Consensus/ConsensusReactorTest.cs
- Libplanet.Net/Consensus/ConsensusContext.cs
- Libplanet.Net/Consensus/PreCommitState.cs
- Libplanet.Net/Consensus/RoundContext.cs
Fixed problem when processing multiple messages before state transition.
> Prevent duplicated commit

- CHANGES.md
- Libplanet.Benchmarks/SwarmBenchmark.cs
- Libplanet.Explorer.Executable/Program.cs
- Libplanet.Net.Tests/SwarmTest.Preload.cs
- Libplanet.Net.Tests/SwarmTest.cs
- Libplanet.Net/Swarm.cs
- Libplanet.Net/SwarmOptions.cs
- Libplanet.Net/TimeoutOptions.cs
Closes #1957.
Had to update certain parts of `Swarm<T>` API to make it less non-sensical. 🙄
There's still a long way to go to mitigate #1933.
> Added `TimeoutOptions` to `SwarmOptions`

- CHANGES.md
> Release 0.35.0

- CHANGES.md
- Libplanet/Libplanet.csproj
> Prepare 0.36.0

- CHANGES.md
- Libplanet/Libplanet.csproj
> Prepare 0.35.1

- CHANGES.md
> :rocket: Release 0.35.1

- CHANGES.md
- Libplanet/Libplanet.csproj
> :hammer: prepare 0.35.2

- CHANGES.md
- Libplanet.Net/TimeoutOptions.cs
> :twisted_rightwards_arrows: Port/0.35.1 to main

- Libplanet.Unity.Tests/Libplanet.Unity.Tests.csproj
- Libplanet.Unity/Libplanet.Unity.csproj
- Libplanet.sln
Wasn't sure about how to set up a separate project properly so I just copy pasted `*.csproj` files from `Libplanet.Net`. 😶
> [skip changelog] Setup Libplanet.Unity

- CHANGES.md
- Libplanet.Net.Tests/SwarmTest.Preload.cs
- Libplanet.Net/Swarm.BlockSync.cs
- Libplanet.Net/SwarmOptions.cs
Closes #1981.
If I have missed a context where this option might be useful, please give me a feedback. 😶
> Unused SwarmOptions.BlockDownloadTimeout property removed

- CHANGES.md
> Changelog hotfix

- CHANGES.md
- Libplanet.Net.Tests/SwarmTest.Preload.cs
- Libplanet.Net/Swarm.BlockSync.cs
- Libplanet.Net/SwarmOptions.cs
> Merge `main` branch

- CHANGES.md
- Libplanet.Explorer.Executable/Program.cs
- Libplanet.Net.Tests/Protocols/ProtocolTest.cs
- Libplanet.Net.Tests/Protocols/TestTransport.cs
- Libplanet.Net.Tests/SwarmTest.cs
- Libplanet.Net/Protocols/IProtocol.cs
- Libplanet.Net/Protocols/KademliaProtocol.cs
- Libplanet.Net/Swarm.cs
> Removed `findNeighborsTimeout` from `BootstrapAsync()`

- CHANGES.md
> :rocket: Release 0.36.0

- CHANGES.md
> :rocket: Release 0.36.1

- CHANGES.md
- Libplanet.Tests/Tx/TransactionTest.cs
- Libplanet/Tx/Transaction.cs
> :twisted_rightwards_arrows: Port 0.36.1 to main

- CHANGES.md
- Libplanet/Libplanet.csproj
> :wrench: Prepare 0.36.2

- .circleci/config.yml
- Libplanet.Net/Swarm.cs
These commits are separated from #2000.  See also <https://github.com/planetarium/libplanet/pull/2000#issuecomment-1138212530>.
> Small updates on `Swarm<T>` docs

- .circleci/config.yml
- Libplanet.Net/Swarm.cs
> :twisted_rightwards_arrows: Merge `main` to `libplanet-node`

- Libplanet.Node.Tests/Libplanet.Node.Tests.csproj
> [skip changelog] Bad project reference removed

- CHANGES.md
- Libplanet.Node/BootstrapConfig.cs
- Libplanet.Node/InitConfig.cs
- Libplanet.Node/PreloadConfig.cs
- Libplanet.Node/SwarmConfig.cs
- Libplanet.Node/SyncConfig.cs
This still more of a stub. I know it's bad practice, but tests will be added later once the interface gets tidied up. 😥
> Various config classes added

- CHANGES.md
- Libplanet.Explorer.Executable/Program.cs
- Libplanet.Net.Tests/SwarmTest.Preload.cs
- Libplanet.Net/PreloadOptions.cs
- Libplanet.Net/Swarm.cs
- Libplanet.Net/SwarmOptions.cs
- Libplanet.Net/TimeoutOptions.cs
Just a continuation of #2024.
Arg, `SwarmOptions` is still in pretty lousy shape, but we are getting closer to having
```csharp
swarm.BootstrapAsync();
swarm.PreloadAsync();
swarm.StartAsync();
```
for running nodes. 😗
> `PreloadOptions` added to `SwarmOptions`

- CHANGES.md
> 🚀 Release 0.37.0

- CHANGES.md
- Libplanet/Libplanet.csproj
> 🔧 Prepare 0.38.0

- CHANGES.md
- Libplanet/Libplanet.csproj
> 🔧 Prepare 0.37.1

- CHANGES.md
- Libplanet.Explorer.Executable/Options.cs
- Libplanet.Explorer.Executable/Program.cs
- Libplanet.Net.Tests/FactOnlyTurnAvailableAttribute.cs
- Libplanet.Net.Tests/IceServerTest.cs
- Libplanet.Net.Tests/SwarmTest.Preload.cs
- Libplanet.Net.Tests/SwarmTest.cs
- Libplanet.Net/BootstrapOptions.cs
- Libplanet.Net/IceServer.cs
- Libplanet.Net/PreloadOptions.cs
- Libplanet.Net/Swarm.cs
- Libplanet.Net/SwarmOptions.cs
- Libplanet.Net/TimeoutOptions.cs
- Libplanet.Node/SwarmConfig.cs
- Libplanet/Libplanet.csproj
> 🔀 Merge `main` into `libplanet-node`

- Libplanet.Node/InitConfig.cs
I really wanted to frontload config validation, but couldn't come up with a clean *and* consistent way. 😥
> Default host changed to localhost

- Docs/theme/styles/main.css
I'm pretty sure yall like this!
- Widen sidebar (270px -> 285px)
- Changed fonts (Pretendard, Roboto Mono)
- Planetarium BI Colored!
- New Code Highlight scheme!
> Newly styled up docs page.

- Libplanet.Net/Consensus/ConsensusContext.cs
Fixed a bug where current height of initial consensus state was set to 0.
> Fix bug in consensus initial height

- CHANGES.md
- Libplanet.Tests/AddressTest.cs
- Libplanet/Address.cs
> Allow 0x prefix for Address class

- CHANGES.md
- Libplanet.Net.Tests/Protocols/ProtocolTest.cs
- Libplanet.Net.Tests/Protocols/TestTransport.cs
- Libplanet.Net.Tests/SwarmTest.Broadcast.cs
- Libplanet.Net.Tests/SwarmTest.cs
- Libplanet.Net/Protocols/KademliaProtocol.cs
- Libplanet.Net/Swarm.cs
- Libplanet.Stun/Stun/Messages/StunMessage.cs
- Libplanet.Stun/Stun/TurnClient.cs
- Libplanet/Blockchain/BlockChain.MineBlock.cs
> Minor cleanup for consistency

- CHANGES.md
> 🚀 Release 0.38.0

- CHANGES.md
- Libplanet/Libplanet.csproj
> 🔧 Prepare libplanet 0.39.0

- Libplanet.Unity/Paths.cs
- Libplanet.Unity/Utils.cs
Ported from [planet-clicker](https://github.com/planetarium/planet-clicker).
> `Paths` and `Utils` for Unity

- Libplanet.Unity/Utils.cs
Making too many mistakes here and there. 😥
Perhaps trying to go fast is a bad idea. 😕
> Rename method for `Utils`

- Libplanet.Unity/Paths.cs
> [skip changelog] TempPrivateKeysPath added to Paths

- Libplanet.Net/Consensus/ConsensusReactor.cs
- Libplanet.Net/Consensus/IReactor.cs
Fixes a problem failure in unit tests `SwarmTest.Cancel()` in linux environment.
> chore: fix tests in linux

- .github/bin/constants.sh
- Libplanet.Unity/Editor/BlockChainMenu.cs
- Libplanet.Unity/Editor/GenesisBlockMenu.cs
- Libplanet.Unity/Editor/PrivateKeyMenu.cs
- Libplanet.Unity/Editor/SwarmConfigMenu.cs
- Libplanet.Unity/Editor/UtilsMenu.cs
- Libplanet.Unity/Libplanet.Unity.csproj
- Libplanet.sln
Removed `Libplanet.Unity` from build.
> Editor menu items ported

- Libplanet.Extensions.Cocona/Commands/KeyCommand.cs
this resolves #1807.
- key create --json outputs newly created key as json
- key import --json import Web3 formatted json. (path optional.)
- key export --json exports Web3 formatted json. (default path provided)
> Libplanet.Tools key command now Import/Exports Web3 Formatted json.

- Libplanet.Net/Consensus/Context.cs
Adding Votes block the condition when a node has received +2/3 Vote in Propose step.
> Create VoteSet when `VoteSet()` is called

- Libplanet.Net.Tests/Consensus/ConsensusContextTest.cs
- Libplanet.Net.Tests/Consensus/ContextTest.cs
- Libplanet.Net.Tests/TestUtils.cs
- Libplanet.Net/Consensus/ConsensusContext.cs
- Libplanet.Net/Consensus/Context.cs
- Libplanet.Net/Consensus/InvalidHeightIncreasingException.cs
- Libplanet.Net/Consensus/InvalidRoundMessageException.cs
WIP, Round-Skip and Timeout, NIL vote +2/3 need to be tested.
> Unit Tests for new PBFT algorithm

- Libplanet.Net/Consensus/Context.cs
- Add block hash cache
- Resolves https://github.com/planetarium/libplanet/issues/2105
> feat: add block hash cache

- .circleci/config.yml
> Fix typo in the CI script

- Libplanet.Node.Tests/SwarmConfigTest.cs
- Libplanet.Node/NodeConfig.cs
- Libplanet.Node/SwarmConfig.cs
- Libplanet.Node/SyncConfig.cs
> Fix API mismatch

- Libplanet/Consensus/VoteSet.cs
- Libplanet/Store/BlockDigest.cs
> BlockDigest / VoteSet comment

- CHANGES.md
- Libplanet.Explorer.Executable/Program.cs
- Libplanet.Net/Swarm.cs
> Default number of workers raised to 100

- CHANGES.md
> docs: add missing link in changelog

- CHANGES.md
- Libplanet.Node/SwarmConfig.cs
> Add changelog for PBFT -> main

- CHANGES.md
- Libplanet/Action/PolymorphicAction.cs
> Let `PolymorphicAction<T>` allow `T` to be inherited from the entry assembly

- CHANGES.md
- Libplanet.Tests/Action/DuplicateActionTypeIdentifierExceptionTest.cs
- Libplanet.Tests/Action/PolymorphicActionTest.cs
- Libplanet/Action/ActionTypeAttribute.cs
- Libplanet/Action/DuplicateActionTypeIdentifierException.cs
- Libplanet/Action/PolymorphicAction.cs
> Make `PolymorphicAction<T>` more robust

- CHANGES.md
> 🚀 Release 0.39.0

- CHANGES.md
- Libplanet/Libplanet.csproj
> 🔧 Prepare 0.39.1

- CHANGES.md
- Libplanet/Libplanet.csproj
> 🔧 Prepare 0.40.0

- CHANGES.md
- Libplanet.Benchmarks/Store.cs
- Libplanet.Explorer/Store/LiteDBRichStore.cs
- Libplanet.Explorer/Store/MySQLRichStore.cs
- Libplanet.Tests/Store/ProxyStore.cs
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet.Tests/Store/StoreTracker.cs
- Libplanet/Store/BaseStore.cs
- Libplanet/Store/IStore.cs
- Libplanet/Store/MemoryStore.cs
> Introduce `IStore.GetCanonicalGenesisBlock<T>()` method

- CHANGES.md
- Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
- Libplanet.Net/Consensus/Context.cs
- Libplanet.Net/Consensus/InvalidValidatorVoteMessageException.cs
This PR is a partial revert of PR #2177.
> Restore rejecting invalid vote

- Dockerfile.explorer
Fix Github Actions failure introduced in 8017027905fc70ec286e09b8096a6b78f80ab4ee.
> Hotfix Dockerfile.explorer

- Libplanet.Net/Consensus/Context.Async.cs
- Libplanet.Net/Consensus/Context.Mutate.cs
- Libplanet.Net/Consensus/Context.cs
- Libplanet.Net/Consensus/MessageLog.cs
Closes #2194.
Code is pretty self explanatory. Skipping changelog since it is purely `internal`.
> `MessageLog` added

- Libplanet.Net.Tests/Consensus/Context/ContextNonProposerTest.cs
Just an additional test with a quick and dirty setup. Open to suggestions for other scenarios. 😗
> `Context` edge case test added

- CHANGES.md
> 🧹 Changelog formatting

- CHANGES.md
> 🚀 Release 0.40.0

- CHANGES.md
- Libplanet/Libplanet.csproj
> 🔧 Prepare 0.41.0

- CHANGES.md
- Libplanet/Libplanet.csproj
> 🔧 Prepare 0.40.1

- CHANGES.md
- Libplanet.Explorer/Store/LiteDBRichStore.cs
- Libplanet.Explorer/Store/MySQLRichStore.cs
- Libplanet.RocksDBStore/RocksDBStore.cs
- Libplanet.Tests/Store/ProxyStore.cs
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet.Tests/Store/StoreTracker.cs
- Libplanet/Store/BaseStore.cs
- Libplanet/Store/DefaultStore.cs
- Libplanet/Store/IStore.cs
- Libplanet/Store/MemoryStore.cs
> Remove unused tx related methods from IStore (#1538)

- CHANGES.md
- Libplanet.Net.Tests/Messages/BlockHashesTest.cs
- Libplanet.Net.Tests/Messages/MessageTest.cs
- Libplanet.Net.Tests/Messages/MessageValidatorTest.cs
- Libplanet.Net.Tests/Messages/NetMQMessageCodecTest.cs
- Libplanet.Net.Tests/Transports/InvalidMessageSignatureExceptionTest.cs
- Libplanet.Net/DifferentAppProtocolVersionEncountered.cs
- Libplanet.Net/Messages/IMessageCodec.cs
- Libplanet.Net/Messages/Message.cs
- Libplanet.Net/Messages/MessageValidator.cs
- Libplanet.Net/Messages/NetMQMessageCodec.cs
- Libplanet.Net/Transports/BoundPeerExtensions.cs
- Libplanet.Net/Transports/InvalidMessageSignatureException.cs
Preparatory work to get rid of `Peer` class entirely.
> More `BoundPeer` type enforcement

- CHANGES.md
> 🧹 Some old typo fix

- CHANGES.md
> 🚀 Release 0.41.0

- CHANGES.md
- Libplanet/Libplanet.csproj
> 🔧 Prepare 0.41.1

- CHANGES.md
- Libplanet/Libplanet.csproj
> 🔧 Prepare 0.42.0

- CHANGES.md
- Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
- Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet/Blockchain/Policies/BlockPolicy.cs
- Libplanet/Blockchain/Policies/IBlockPolicy.cs
- Libplanet/Blockchain/Policies/NullBlockPolicy.cs
Follows #2254.
Preparatory work to remove `Difficulty` and `TotalDifficulty`.
> Remove difficulty policy

- CHANGES.md
- Libplanet.Explorer.Tests/GraphTypes/BlockTypeTest.cs
- Libplanet.Net.Tests/Consensus/Context/ContextTestBase.cs
- Libplanet.Net.Tests/SwarmTest.Broadcast.cs
- Libplanet.Node/NodeUtils.cs
- Libplanet.Tests/Action/ActionEvaluatorTest.cs
- Libplanet.Tests/Blockchain/BlockChainTest.MineBlock.cs
- Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Blockchain/Renderers/DelayedActionRendererTest.cs
- Libplanet.Tests/Blocks/BlockContentTest.cs
- Libplanet.Tests/Blocks/BlockTest.cs
- Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
- Libplanet.Tests/Blocks/PreEvaluationBlockTest.cs
- Libplanet.Tests/Fixtures/IntegerSet.cs
- Libplanet/Blockchain/BlockChain.MineBlock.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Blocks/PreEvaluationBlock.cs
Follows #2263.
Left `BlockContent.Mine()` just in case for now. 🙄
> Remove mining

- CHANGES.md
- Libplanet.Tests/Tx/TransactionTest.cs
- Libplanet/Tx/Transaction.cs
> Port 0.40.1 to 0.41-maintenance & release 0.41.1

- .github/auto_assign.yml
See also: <https://github.com/planetarium/libplanet/discussions/2266#discussioncomment-3514591>
> No more automatically assign every maintainer

- Libplanet.Net.Tests/SwarmTest.cs
Just adding back in some missing tests just in case.
> Reinstate missing tests

- CHANGES.md
> Fix typo on the CHANGES.md

- .github/auto_assign.yml
- CHANGES.md
- Libplanet.Net.Tests/SwarmTest.Broadcast.cs
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Libplanet.csproj
> 🔀 Merge main to pbft

- CHANGES.md
- Libplanet.Tests/Action/PolymorphicActionTest.cs
- Libplanet.Tests/Assets/CurrencyTest.cs
- Libplanet.Tests/Blocks/BlockMarshalerTest.cs
- Libplanet.Tests/Common/Action/DumbAction.cs
- Libplanet.Tests/Fixtures/Arithmetic.cs
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet.Tests/Tx/TransactionTest.cs
- Libplanet/Action/PolymorphicAction.cs
- Libplanet/Action/Sys/Mint.cs
- Libplanet/Action/Sys/Registry.cs
- Libplanet/Action/Sys/Transfer.cs
- Libplanet/Assets/Currency.cs
- Libplanet/Blocks/BlockMarshaler.cs
- Libplanet/Blocks/BlockMetadata.cs
- Libplanet/Libplanet.csproj
- Libplanet/Store/BaseStore.cs
Seems like there is lot more work to do with [Bencodex] API than I've originally expected. Also even with more type support, some old working usage have become ambiguous, so had to be fixed. 🙄
[Bencodex]: https://www.nuget.org/packages/Bencodex
> ⬆️ Bump becodex to 0.5.0

- Libplanet.Net/Transports/NetMQTransport.cs
> 🧹 Clean up unnecessary log

- CHANGES.md
- Libplanet.Net.Tests/SwarmTest.Preload.cs
- Libplanet.Tests/Blocks/BlockMetadataTest.cs
- Libplanet.Tests/TestUtils.cs
- Libplanet/Blocks/BlockContent.cs
- Libplanet/Blocks/BlockMetadata.cs
- Libplanet/Blocks/PreEvaluationBlock.cs
- Libplanet/Blocks/PreEvaluationBlockHeader.cs
Skipped changelog for mining related methods.
The PR title is a bit of a misnomer as this refactoring was cut short to work on #2291. 🙄
> Minor `BlockContent` refactor

- Libplanet.Tests/PoS/BondedValidatorSetCtrlTest.cs
- Libplanet.Tests/PoS/DelegateCtrlTest.cs
- Libplanet.Tests/PoS/RedelegateCtrlTest.cs
- Libplanet.Tests/PoS/UndelegateCtrlTest.cs
- Libplanet.Tests/PoS/ValidatorCtrlTest.cs
- Libplanet.Tests/PoS/ValidatorPowerIndexCtrlTest.cs
- Libplanet.Tests/PoS/ValidatorPowerSetCtrlTest.cs
- Libplanet.Tests/PoS/ValidatorTest.cs
- Libplanet/PoS/Action/Sys/CancelUndelegation.cs
- Libplanet/PoS/Action/Sys/Delegate.cs
- Libplanet/PoS/Action/Sys/PromoteValidator.cs
- Libplanet/PoS/Action/Sys/Redelegate.cs
- Libplanet/PoS/Action/Sys/Undelegate.cs
- Libplanet/PoS/Control/Bond.cs
- Libplanet/PoS/Control/BondedValidatorSetCtrl.cs
- Libplanet/PoS/Control/DelegateCtrl.cs
- Libplanet/PoS/Control/RedelegateCtrl.cs
- Libplanet/PoS/Control/UnbondingSetCtrl.cs
- Libplanet/PoS/Control/UndelegateCtrl.cs
- Libplanet/PoS/Control/ValidatorCtrl.cs
- Libplanet/PoS/Control/ValidatorPowerIndexCtrl.cs
- Libplanet/PoS/Control/ValidatorPowerSetCtrl.cs
- Libplanet/PoS/Model/Validator.cs
> Make namespaces correct

- Libplanet.Tests/Blocks/BlockContentExtensionsTest.cs
- Libplanet.Tests/Blocks/BlockContentTest.cs
- Libplanet.Tests/Blocks/BlockMarshalerTest.cs
- Libplanet.Tests/Blocks/BlockMetadataExtensionsTest.cs
- Libplanet.Tests/Blocks/BlockMetadataTest.cs
- Libplanet.Tests/Blocks/BlockTest.cs
- Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
- Libplanet.Tests/Blocks/PreEvaluationBlockTest.cs
- Libplanet.Tests/Fixtures/BlockContentFixture.cs
> 🧹 General renaming and reordering of fixture construction

- CHANGES.md
Move changelog items on `PBFT` to `PoS`, due to change on target branch
> document: fix changelog due to change on target branch

- CHANGES.md
> 🚀 Release 0.42.0

- CHANGES.md
- Libplanet.Net/Swarm.cs
- Libplanet.Net/Transports/NetMQTransport.cs
- Libplanet/Address.cs
- Libplanet/Tx/TxId.cs
> 🔀 Merge main 0.42.0 to pbft

- CHANGES.md
- Libplanet/Libplanet.csproj
> 🔧 Prepare 0.43.0

- Libplanet/PoS/Misc/ReservedAddress.cs
change access modifier for reserved addresses, to read on application level, especially `RewardPool`.
> Change access modifier for reserved addresses

- Libplanet/PoS/Action/Sys/WithdrawValidator.cs
Change access modifier of WithdrawValidator constructor to pulic to call action correctly
> Change access modifier of WithdrawValidator constructor to pulic

- CHANGES.md
- Libplanet/Libplanet.csproj
> 🔧 Prepare 0.42.1

- CHANGES.md
- Libplanet.Net/Protocols/IRoutingTable.cs
- Libplanet.Net/Protocols/RoutingTable.cs
> Make interface for routing table (#2046)

- Libplanet.Net.Tests/Consensus/ConsensusReactorTestBase.cs
- Libplanet.Net.Tests/Consensus/GossipTest.cs
- Libplanet.Net.Tests/SwarmTest.Fixtures.cs
- Libplanet.Net/Consensus/ConsensusReactor.cs
- Libplanet.Net/Consensus/ConsensusReactorOption.cs
- Libplanet.Net/Consensus/Gossip.cs
- Libplanet.Net/Swarm.cs
Synchronize with the gossip table of the seed node.
> Update gossip table from seed node

- Libplanet.Net.Tests/Consensus/ConsensusReactorTestBase.cs
- Libplanet.Net.Tests/Consensus/GossipTest.cs
- Libplanet.Net.Tests/SwarmTest.Fixtures.cs
- Libplanet.Net/Consensus/ConsensusReactor.cs
- Libplanet.Net/Consensus/ConsensusReactorOption.cs
- Libplanet.Net/Consensus/Gossip.cs
- Libplanet.Net/Swarm.cs
It is cherry-picking of https://github.com/planetarium/libplanet/pull/2336
> Update consensus' routing table from seed node

- Libplanet.Explorer.Executable/Program.cs
- Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs
- Libplanet/Blockchain/Policies/BlockPolicy.cs
- Libplanet/Blockchain/Policies/IBlockPolicy.cs
- Libplanet/Blockchain/Policies/NullBlockPolicy.cs
Aside from #2349, this is preparatory work for #2350. Once tested, this should be properly implemented in the main branch when we are ready.
> PBFT migration preparatory PoW BPV policy

- Libplanet/Blocks/BlockCommit.cs
> `BlockCommit.Votes` no longer nullable or default

- CHANGES.md
- Libplanet.Explorer.Tests/TransactionQueryTest.cs
- Libplanet.Explorer/Queries/TransactionQuery.cs
> Port 0.40.3 & release 0.41.4

- CHANGES.md
- Libplanet.Explorer.Tests/TransactionQueryTest.cs
- Libplanet.Explorer/Queries/TransactionQuery.cs
> Port 0.40.3 & 0.41.4, and release 0.42.2

- CHANGES.md
- Libplanet.Explorer.Tests/TransactionQueryTest.cs
- Libplanet.Explorer/Queries/TransactionQuery.cs
See also:
- #2358
- #2359
- #2360
> Port 0.40.3, 0.41.4, & 0.42.2 to main (0.43.x)

- CHANGES.md
- Libplanet.Explorer.Tests/Queries/TransactionQueryTest.cs
- Libplanet.Explorer/Queries/TransactionQuery.cs
> Implement nextNonce query in Libplanet.Explorer

- Libplanet.Tests/Blocks/BlockCommitTest.cs
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet/Blocks/BlockCommit.cs
Working towards a spec where `LastCommit` to be `null` for no vote for now. 😗
> Disallow empty set of votes for `BlockCommit`

- Libplanet.Tests/Blocks/BlockCommitExtensionsTest.cs
- Libplanet.Tests/Blocks/BlockCommitTest.cs
- Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
- Libplanet/Blocks/BlockCommit.cs
More preemptive validation for `BlockCommit`.
> Vote height and round consistency for `BlockCommit`

- CHANGES.md
This pull request release `0.43.1` version.
After this pull request:
If it needs other reviewers, please request to more reviewers 🙏🏻
> Release 0.43.1

- CHANGES.md
- Libplanet.Explorer/GraphTypes/TxResultType.cs
> Merge 0.43.1

- CHANGES.md
- Libplanet.Explorer/GraphTypes/TxResultType.cs
- Libplanet.Net.Tests/Messages/MessageValidatorTest.cs
- Libplanet.Net/Messages/MessageValidator.cs
- Libplanet/Libplanet.csproj
> 🔀 Merge main 0.43.1 to pbft

- Libplanet.Net/Consensus/ConsensusContext.cs
The access collision was observed in linux-unity-test from `ConsensusContext<T>._contexts` dictionary after https://github.com/planetarium/libplanet/pull/2390 patch.
> Access collision in `Context` dictionary

- Libplanet.Explorer.Tests/Queries/TransactionQueryTest.cs
- Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
- Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextProposerTest.cs
- Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
- Libplanet.Net.Tests/Consensus/Context/ContextNonProposerTest.cs
- Libplanet.Net.Tests/Consensus/Context/ContextProposerTest.cs
- Libplanet.Net.Tests/Consensus/Context/ContextProposerValidRoundTest.cs
- Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
- Libplanet.Net.Tests/TestUtils.cs
- Libplanet.Net/Consensus/Context.Mutate.cs
- Libplanet.Net/Consensus/Context.cs
- Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
- Libplanet.Tests/Blocks/BlockCommitExtensionsTest.cs
- Libplanet.Tests/Blocks/BlockCommitTest.cs
- Libplanet.Tests/Blocks/BlockFixture.cs
- Libplanet.Tests/Blocks/BlockMetadataTest.cs
- Libplanet.Tests/Consensus/VoteSetTest.cs
- Libplanet.Tests/Consensus/VoteTest.cs
- Libplanet.Tests/TestUtils.cs
- Libplanet/Blocks/BlockCommitExtensions.cs
- Libplanet/Consensus/VoteFlag.cs
- Libplanet/Consensus/VoteSet.cs
> ♻️ Renamed vote flags

- Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
- Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextProposerTest.cs
- Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
- Libplanet.Net.Tests/Consensus/Context/ContextNonProposerTest.cs
- Libplanet.Net.Tests/Consensus/Context/ContextProposerTest.cs
- Libplanet.Net.Tests/Consensus/Context/ContextProposerValidRoundTest.cs
- Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
- Libplanet.Net.Tests/Consensus/GossipTest.cs
- Libplanet.Net.Tests/Consensus/MessageCacheTest.cs
- Libplanet.Net.Tests/Messages/MessageTest.cs
- Libplanet.Net.Tests/TestUtils.cs
- Libplanet.Net/Consensus/ConsensusContext.Event.cs
- Libplanet.Net/Consensus/ConsensusContext.cs
- Libplanet.Net/Consensus/ConsensusReactor.cs
- Libplanet.Net/Consensus/ConsensusReactorOption.cs
- Libplanet.Net/Consensus/Context.Async.cs
- Libplanet.Net/Consensus/Context.Event.cs
- Libplanet.Net/Consensus/Context.Mutate.cs
- Libplanet.Net/Consensus/Context.cs
- Libplanet.Net/Consensus/InvalidBlockProposeMessageException.cs
- Libplanet.Net/Consensus/InvalidHeightMessageException.cs
- Libplanet.Net/Consensus/InvalidProposerProposeMessageException.cs
- Libplanet.Net/Consensus/InvalidValidatorVoteMessageException.cs
- Libplanet.Net/Consensus/MessageLog.cs
- Libplanet.Net/Messages/ConsensusMsg.cs
- Libplanet.Net/Messages/ConsensusPreCommitMsg.cs
- Libplanet.Net/Messages/ConsensusPreVoteMsg.cs
- Libplanet.Net/Messages/ConsensusProposeMsg.cs
- Libplanet.Net/Messages/NetMQMessageCodec.cs
Changes made to make them more in line with other messages. See #2185.
> Rename consensus messages

- Libplanet.Tests/Blockchain/BlockChainTest.ValidateNextBlock.cs
- Libplanet.Tests/Blocks/BlockCommitExtensionsTest.cs
- Libplanet.Tests/Blocks/BlockCommitTest.cs
- Libplanet.Tests/Blocks/BlockMetadataTest.cs
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Blocks/BlockCommit.cs
- Libplanet/Blocks/BlockCommitExtensions.cs
Just some more constraints on `BlockCommit`. 🙄
> Added voting power requirement to `BlockCommit`

- Libplanet.Tools/Libplanet.Tools.csproj
This PR (temporarily) fixes Mono testing by ad-hoc solution. (we may need to discuss testing environments in near future.)
> Fix Mono CI

- Libplanet.Net.Tests/Consensus/Context/ContextNonProposerTest.cs
- Libplanet.Net.Tests/Consensus/Context/ContextProposerTest.cs
- Libplanet.Net/Consensus/Context.Mutate.cs
- Libplanet.Net/Consensus/Context.cs
> 🔨 Prevent invalid block proposal

- Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
- Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
- Libplanet.Net.Tests/Consensus/Context/ContextProposerTest.cs
- Libplanet.Net.Tests/Consensus/Context/ContextProposerValidRoundTest.cs
- Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
- Libplanet.Net.Tests/Consensus/GossipTest.cs
- Libplanet.Net.Tests/Messages/MessageTest.cs
- Libplanet.Net.Tests/TestUtils.cs
- Libplanet.Net/Consensus/Context.Mutate.cs
- Libplanet.Net/Consensus/Context.cs
- Libplanet.Net/Consensus/InvalidBlockProposeMessageException.cs
- Libplanet.Net/Consensus/InvalidProposerProposeMessageException.cs
- Libplanet.Net/Consensus/MessageLog.cs
- Libplanet.Net/Messages/ConsensusProposalMsg.cs
- Libplanet.Net/Messages/NetMQMessageCodec.cs
- Libplanet/Consensus/Proposal.cs
> ♻️ Rename `ConsensusProposeMsg` to `ConsensusProposalMsg`

- Libplanet.Net/Consensus/Context.Mutate.cs
To be more defensive just in case.
Seems like `ProcessHeightOrRoundUponRules()` could've had an undesirable effect on `Context` under the right circumstances.
> 🔨 Added stricter constraint for steps

- Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
- Libplanet.Net.Tests/Messages/MessageTest.cs
- Libplanet.Net.Tests/TestUtils.cs
- Libplanet.Net/Consensus/Context.Mutate.cs
- Libplanet.Net/Messages/ConsensusMsg.cs
- Libplanet.Net/Messages/ConsensusPreCommitMsg.cs
- Libplanet.Net/Messages/ConsensusPreVoteMsg.cs
- Libplanet.Net/Messages/ConsensusProposalMsg.cs
- Libplanet/Consensus/Proposal.cs
- Libplanet/Consensus/ProposalMetaData.cs
- Libplanet/Consensus/VoteMetadata.cs
> Add `BlockHash` to `Proposal`

- Libplanet.Net.Tests/Consensus/Context/MessageLogTest.cs
- Libplanet.Net/Consensus/Context.Mutate.cs
- Libplanet.Net/Consensus/Context.cs
- Libplanet.Net/Consensus/MessageLog.cs
> Refactor `MessageLog`

- CHANGES.md
- Libplanet.Net.Tests/Consensus/Context/MessageLogTest.cs
- Libplanet.Net.Tests/TestUtils.cs
- Libplanet.Net/Consensus/Context.Mutate.cs
- Libplanet.Net/Consensus/Context.cs
- Libplanet.Tests/Consensus/ProposalMetadataTest.cs
- Libplanet.Tests/Consensus/ProposalTest.cs
- Libplanet/Consensus/Proposal.cs
- Libplanet/Consensus/ProposalMetadata.cs
> 🧹 Renaming for consistency

- Libplanet.Net/Consensus/Context.cs
- Libplanet.Net/Consensus/Gossip.cs
- Libplanet.Net/Messages/MessageId.cs
- Libplanet/Consensus/Proposal.cs
- Libplanet/Consensus/Vote.cs
> 🧹 Use `langword` tags

- Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
- Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextProposerTest.cs
- Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
- Libplanet.Net.Tests/Consensus/Context/ContextNonProposerTest.cs
- Libplanet.Net.Tests/Consensus/Context/ContextProposerTest.cs
- Libplanet.Net.Tests/Consensus/Context/ContextProposerValidRoundTest.cs
- Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
- Libplanet.Net.Tests/TestUtils.cs
- Libplanet.Net/Consensus/ConsensusContext.Event.cs
- Libplanet.Net/Consensus/Context.Async.cs
- Libplanet.Net/Consensus/Context.Event.cs
- Libplanet.Net/Consensus/Context.Mutate.cs
- Libplanet.Net/Consensus/Context.cs
> ♻️ Refactor `Context` events

- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Store/BaseStore.cs
> Improve some log messages

- Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
- Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextProposerTest.cs
- Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
- Libplanet.Net.Tests/TestUtils.cs
> ♻️ Use `MessageBroadcasted` event handler for `ConsensusContext` tests

- CHANGES.md
> 🚀 Release 0.44.0

- CHANGES.md
- Libplanet/Libplanet.csproj
> 🔧 Prepare 0.45.0

- CHANGES.md
- Libplanet/Libplanet.csproj
> 🔧 Prepare 0.44.1

- Libplanet.Net/Consensus/ConsensusContext.cs
- Libplanet.Net/Consensus/Context.Async.cs
- Libplanet.Net/Consensus/Context.cs
- Libplanet.Net/Consensus/Gossip.cs
- Libplanet/Blockchain/BlockChain.cs
It matters at the edge of PoW based block and PBFT based block.
> Validate lastcommit only when lastblock is PBFT based block

- CHANGES.md
- Libplanet.Net.Tests/Transports/TransportTest.cs
- Libplanet.Net/Transports/NetMQTransport.cs
> 🔀 🚀 Port 0.43.3 to 0.44-maintenance and release 0.44.1

- CHANGES.md
- Libplanet/Libplanet.csproj
> 🔧 Prepare 0.44.2

- CHANGES.md
- Docs/theme/styles/main.css
- Libplanet.Explorer/GraphTypes/TransactionType.cs
- Libplanet.Explorer/Queries/ExplorerQuery.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Store/BaseStore.cs
> 🔀 Merge main 0.44.0 to pbft

- CHANGES.md
- Libplanet.Net.Tests/Transports/TransportTest.cs
- Libplanet.Net/Transports/NetMQTransport.cs
> 🔀 Port 0.44.1 to main

- Libplanet.Net.Tests/Consensus/GossipTest.cs
- Libplanet.Net.Tests/SwarmTest.cs
- Libplanet.Net/Consensus/ConsensusReactor.cs
- Libplanet.Net/Consensus/Gossip.cs
Use `KademliaProtocol` to control nodes.
TODO:
> Enhance gossip

- CHANGES.md
- Libplanet.Explorer/Store/LiteDBRichStore.cs
- Libplanet.Explorer/Store/MySQLRichStore.cs
- Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
- Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
- Libplanet.Net.Tests/Consensus/Context/ContextTest.cs
- Libplanet.Net.Tests/Consensus/Context/MessageLogTest.cs
- Libplanet.Net.Tests/TestUtils.cs
- Libplanet.Net/Consensus/ConsensusContext.cs
- Libplanet.Net/Consensus/ConsensusReactor.cs
- Libplanet.Net/Consensus/ConsensusReactorOption.cs
- Libplanet.Net/Swarm.cs
- Libplanet.RocksDBStore/RocksDBStore.cs
- Libplanet.Tests/Store/ProxyStore.cs
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet.Tests/Store/StoreTracker.cs
- Libplanet/Store/BaseStore.cs
- Libplanet/Store/DefaultStore.cs
- Libplanet/Store/IStore.cs
- Libplanet/Store/MemoryStore.cs
♻️ Just to clarify things as we will be dealing with a `BlockCommit` that is not yet a `LastCommit`. 😗
> ♻️ Renamed last commits to block commits where appropriate

- Libplanet.Net/Consensus/ConsensusContext.cs
- Libplanet.Net/Consensus/Context.Async.cs
- Libplanet.Net/Consensus/Context.cs
- Libplanet/Blocks/BlockCommit.cs
- Libplanet/Consensus/Vote.cs
> Add `.ToString()` method to `BlockCommit` and `Vote`

- CHANGES.md
- Libplanet.Net/Messages/ConsensusProposalMsg.cs
- Libplanet.Net/Messages/Message.cs
- Libplanet.Net/Messages/NetMQMessageCodec.cs
Tries to standardize `MessageType` numbering.
> Refactor `MessageType`

- CHANGES.md
- Libplanet.Tools/README.md
Now `planet` can be installed using Homebrew on macOS.
> Homebrew Cask packaging

- Libplanet.Net.Tests/BlockCompletionTest.cs
- Libplanet.Net.Tests/SwarmTest.Broadcast.cs
- Libplanet.Net.Tests/SwarmTest.cs
- Libplanet.Net/BlockCandidateTable.cs
- Libplanet.Net/BlockCompletion.cs
- Libplanet.Net/Messages/ConsensusPreCommitMsg.cs
- Libplanet.Net/Messages/ConsensusPreVoteMsg.cs
- Libplanet.Net/Messages/ConsensusProposalMsg.cs
- Libplanet.Net/Swarm.BlockCandidate.cs
- Libplanet.Net/Swarm.BlockSync.cs
- Libplanet.Net/Swarm.MessageHandlers.cs
- Libplanet.Net/Swarm.cs
- Libplanet.RocksDBStore/RocksDBStore.cs
- Libplanet.Tests/Blocks/BlockCommitTest.cs
- Libplanet.Tests/Consensus/ProposalTest.cs
- Libplanet.Tests/Consensus/VoteMetadataTest.cs
- Libplanet.Tests/Consensus/VoteTest.cs
- Libplanet/Blocks/BlockCommit.cs
- Libplanet/Consensus/Proposal.cs
- Libplanet/Consensus/ProposalMetadata.cs
- Libplanet/Consensus/Vote.cs
- Libplanet/Consensus/VoteMetadata.cs
- Libplanet/Store/DefaultStore.cs
> Send `BlockCommit` in `BlocksMsg`

- Libplanet.Explorer/Store/LiteDBRichStore.cs
- Libplanet.Explorer/Store/MySQLRichStore.cs
- Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextTest.cs
- Libplanet.Net.Tests/SwarmTest.Preload.cs
- Libplanet.Net/Swarm.BlockCandidate.cs
- Libplanet.Net/Swarm.BlockSync.cs
- Libplanet.Net/Swarm.cs
- Libplanet.RocksDBStore/RocksDBStore.cs
- Libplanet.Tests/Blockchain/BlockChainTest.Append.cs
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Store/ProxyStore.cs
- Libplanet.Tests/Store/StoreTest.cs
- Libplanet.Tests/Store/StoreTracker.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Store/BaseStore.cs
- Libplanet/Store/DefaultStore.cs
- Libplanet/Store/IStore.cs
- Libplanet/Store/MemoryStore.cs
Now uses `BlockHash` based caching. There may be some performance implications.
> Refactor `BlockCommit` caching

- CHANGES.md
> 🧹 Changelog

- CHANGES.md
- Libplanet/Libplanet.csproj
> Prepare 0.44.3

- CHANGES.md
- Libplanet.Explorer.Executable/Program.cs
- Libplanet.Tests/Blockchain/Policies/BlockPolicyTest.cs
- Libplanet/Blockchain/Policies/BlockPolicy.cs
- Libplanet/Blockchain/Policies/IBlockPolicy.cs
- Libplanet/Blockchain/Policies/NullBlockPolicy.cs
This is in preparation for PBFT migration.
> Introduce `IBlockPolicy.GetMinBlockProtocolVersion()`

- CHANGES.md
- Libplanet.Tests/Blocks/BlockContentTest.cs
- Libplanet.Tests/Fixtures/BlockContentFixture.cs
- Libplanet.Tests/Tx/TxMetadataTest.cs
- Libplanet/Tx/TxMetadata.cs
> Port 0.44.3 to main (0.45.x)

- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet/Blockchain/BlockChain.cs
> Add `IAction systemAction` parameter to `BlockChain.ProposeGenesisBlock()`

- Libplanet/Blockchain/BlockChain.cs
> Fixed logging context for `BlockChain<T>`

- Libplanet/Store/IStore.cs
> 🧹 Fixed `IStore` interface method description

- Libplanet.Net/TxCompletion.cs
- Buffered `TxCompletion<T>`
- Parallelize req/res
> Increase performance of NetMQTransport and related features

- .github/workflows/benchmarks-main.yml
> Remove exclusive option

- CHANGES.md
- Libplanet.Explorer.Executable/Program.cs
- Libplanet.Explorer.Tests/Queries/TransactionQueryTest.cs
- Libplanet.Explorer/GraphTypes/BoundPeerType.cs
- Libplanet.Explorer/GraphTypes/NodeStateType.cs
- Libplanet.Explorer/Interfaces/IBlockChainContext.cs
- Libplanet.Explorer/Libplanet.Explorer.csproj
- Libplanet.Net/Consensus/ConsensusReactor.cs
- Libplanet.Net/Swarm.cs
Query peers that swarm has, and validators that consensus has.
> Introduce peers and validators query

- Libplanet.Net/Swarm.BlockSync.cs
> Fix bug on ActionExecutionState

- CHANGES.md
- Libplanet.Explorer/Queries/ExplorerQuery.cs
> Fix stateQuery

- CHANGES.md
> Release 0.44.5

- CHANGES.md
- Libplanet.Net/Protocols/KBucketDictionary.cs
- Libplanet.Net/Protocols/KademliaProtocol.cs
- Libplanet.Net/Swarm.MessageHandlers.cs
- Libplanet.Net/Swarm.cs
- Libplanet.Net/Transports/NetMQTransport.cs
> Port 0.44.5 to 0.45-maintenance

- .github/workflows/benchmarks-main.yml
- .github/workflows/benchmarks-pr.yml
Giving a bit more leeway until we gather more benchmark data.
> 🔧 Benchmark CI fix

- Libplanet.Net/Protocols/KBucketDictionary.cs
> 🧹 Minor refactor for `KBucketDictionary`

- Libplanet.Net.Tests/Consensus/ConsensusContext/ConsensusContextNonProposerTest.cs
- Libplanet.Net.Tests/SwarmTest.Broadcast.cs
- Libplanet.Net.Tests/SwarmTest.cs
> 🔧 Reduce test flakiness

- Libplanet.Tests/Action/AccountStateDeltaTest.cs
- Libplanet.Tests/Action/Sys/SetValidatorTest.cs
- Libplanet/Action/AccountStateDeltaImpl.cs
- Libplanet/Action/IAccountStateDelta.cs
This test just including tests that checks the action actually modified the state.
> Add unit tests related to `SetValidator` system action

- CHANGES.md
- Libplanet.Net.Tests/SwarmTest.Broadcast.cs
- Libplanet.Net/AsyncDelegate.cs
- Libplanet.Net/Libplanet.Net.csproj
- Libplanet.Net/Protocols/KademliaProtocol.cs
- Libplanet.Net/Transports/NetMQTransport.cs
- Libplanet.Net/TxCompletion.cs
This PR adds changes from 0.44.7 release.
> Port 0.44.7

- CHANGES.md
- Libplanet/Libplanet.csproj
But I hope we never have to release 0.44.x evermore. 😇
> Prepare 0.44.8

- CHANGES.md
- Libplanet.Net.Tests/SwarmTest.Broadcast.cs
- Libplanet.Net/AsyncDelegate.cs
- Libplanet.Net/Libplanet.Net.csproj
- Libplanet.Net/Protocols/KBucketDictionary.cs
- Libplanet.Net/Protocols/KademliaProtocol.cs
- Libplanet.Net/Swarm.MessageHandlers.cs
- Libplanet.Net/Swarm.cs
- Libplanet.Net/Transports/NetMQTransport.cs
- Libplanet.Net/TxCompletion.cs
- Libplanet.Tests/Blocks/BlockContentTest.cs
- Libplanet.Tests/Fixtures/BlockContentFixture.cs
- Libplanet.Tests/Tx/TxMetadataTest.cs
- Libplanet/Blockchain/BlockChain.cs
- Libplanet/Blockchain/BlockLocator.cs
- Libplanet/Blockchain/Policies/VolatileStagePolicy.cs
- Libplanet/Tx/TxMetadata.cs
This PR ports the changes between 0.44.2 and 0.44.7 releases, to pbft branch.
> Bump 0.44.7 to pbft

- Libplanet.Explorer.Tests/Queries/StateQueryTest.cs
- Libplanet.Explorer/GraphTypes/ValidatorType.cs
- Libplanet.Explorer/Queries/StateQuery.cs
> Fix explorer's validators query

- Libplanet/Action/ActionEvaluationsExtensions.cs
> fix: empty validator set not impact state root hash

- CHANGES.md
- Libplanet.Extensions.Cocona/Commands/StoreCommand.cs
- Libplanet.Tools/Program.cs
```console
$ planet store chain-ids rocksdb+file://$HOME/Desktop/9c-main
Chain ID                             Height  Canon?
------------------------------------ ------- ------
ed3823a5-996b-407a-93d4-4ad5c24c4553 5816989 *     
```
> New subcommand: `planet store chain-ids`

- Libplanet.Extensions.Cocona/Commands/StoreCommand.cs
- Libplanet.Extensions.Cocona/Utils.cs
Added functionality to show hash of tip for chain ids.
> Show tip hash for Libplanet.Explorer.Cocona.Commands.StoreCommand.ChainIds

- Libplanet/Blockchain/BlockChain.Swap.cs
This is mainly optimized for memory usage. Could be slower on tx restaging as `Transaction<T>`s are loaded again when traversing. Also possibly slightly less safe as instead of directly traversing a `BlockChain<T>` object, this assumes some business logic and directly accesses the `IStore`. 🙄
Shouldn't be much of a problem:
- Rewinding should be relatively small. Aside from trying to move to PBFT, if we have a long rewind path, we have a larger issue.
- Takes relatively smaller amount of time compared to block append and execution.
> ♻️ Optimize preload

- Libplanet.RocksDBStore/RocksDBStore.cs
Like #2379, This PR turns a recursion to iteration on `RocksDBStore.IndexBlockHash()` for stack depth managing.
> Turn recursion to iteration on `RocksDBStore.IndexBlockHash()`

- Libplanet.Net/Swarm.BlockSync.cs
Still a confusing mess. There shouldn't be any observable behavioral changes. 🙄
Note to reviewer: Probably easier to review each commit. Each commit is supposed to behave exactly the same as prior commit. 🙃
> 🧹 Cleanup preload

- Libplanet/Action/AccountStateDeltaImpl.cs
- Libplanet/Consensus/Validator.cs
- Libplanet/Consensus/ValidatorSet.cs
> Modify Equals methods on Validator, ValidatorSet

- CHANGES.md
- Libplanet.Tests/Action/AccountStateDeltaTest.cs
- Libplanet.Tests/Action/ActionContextTest.cs
- Libplanet.Tests/Action/Sys/SetValidatorTest.cs
- Libplanet.Tests/Common/Action/DumbAction.cs
- Libplanet.Tests/Consensus/ValidatorSetTest.cs
- Libplanet.Tests/Consensus/ValidatorTest.cs
- Libplanet/Action/AccountStateDeltaImpl.cs
- Libplanet/Action/IAccountStateDelta.cs
- Libplanet/Action/Sys/SetValidator.cs
- Libplanet/Consensus/Validator.cs
- Libplanet/Consensus/ValidatorSet.cs
> 🧹 Refactor `Validator`

- CHANGES.md
> 🚀 Release 0.46.0

- CHANGES.md
- Libplanet/Libplanet.csproj
> release: prepare 0.46.1

- CHANGES.md
- Libplanet/Libplanet.csproj
> release: prepare 0.47

- Libplanet.Net.Tests/Messages/MessageTest.cs
- Libplanet.Net/Consensus/Context.Mutate.cs
- Libplanet.Tests/Action/AccountStateDeltaTest.cs
- Libplanet.Tests/Action/ActionContextTest.cs
- Libplanet.Tests/Action/ActionEvaluatorTest.cs
- Libplanet.Tests/Action/Sys/SetValidatorTest.cs
- Libplanet.Tests/Blockchain/BlockChainTest.cs
- Libplanet.Tests/Blocks/BlockMetadataTest.cs
- Libplanet.Tests/Blocks/PreEvaluationBlockHeaderTest.cs
- Libplanet.Tests/Common/Action/DumbAction.cs
- Libplanet.Tests/Consensus/ValidatorSetTest.cs
- Libplanet.Tests/Consensus/ValidatorTest.cs
- Libplanet.Tests/TestUtils.cs
- Libplanet/Action/AccountStateDeltaExtensions.cs
- Libplanet/Action/AccountStateDeltaImpl.cs
- Libplanet/Action/ActionEvaluationsExtensions.cs
- Libplanet/Action/IAccountStateDelta.cs
- Libplanet/Action/Sys/SetValidator.cs
- Libplanet/Consensus/Validator.cs
- Libplanet/Consensus/ValidatorSet.cs
Cherry-pick of 195248ee2005474f747838ea6cdaf709c309df6b^..77bb3ff27ac8f81bc0f817f0e701f2a645dd355a from main branch.
- https://github.com/planetarium/libplanet/pull/2720
> Update `Validator`, `ValidatorSet` specs

- CHANGES.md
- Libplanet.Net.Tests/BoundPeerTest.cs
- Libplanet.Net.Tests/Transports/NetMQTransportTest.cs
- Libplanet.Net.Tests/Transports/TransportTest.cs
- Libplanet.Net/BoundPeer.cs
- Libplanet.Net/Transports/NetMQTransport.cs
This PR ports the below fixes from 0.46.0 to 0.45-maintenance.
- #2708 
- it's a minor log fix but I think it helps debug significantly. 
- #2719 
- #2721
> Backports the transport-related fixes from 0.46.0 to 0.45-maintenance
